Error when requested package doesn't exist in ROS 2 workspace
RobotLocomotion/drake-ros pull request #109
Opened 2022-08-08 19:10 UTC by sloretz

Fixes #100

Here's what it looks like with a non-existent package

```
bazel build //...
INFO: Repository ros2 instantiated at:
  /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/WORKSPACE:34:13: in <toplevel>
Repository rule ros2_archive defined at:
  /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl:307:31: in <toplevel>
INFO: Repository 'ros2' used the following cache hits instead of downloading the corresponding file.
 * Hash '87ba25ac7f97a220cfaeb7ac577c3bb7e3c36040f41e16309d55b8847a895682' for http://repo.ros2.org/ci_archives/drake-ros-underlay/ros2-humble-linux-focal-amd64-ci.tar.bz2
If the definition of 'ros2' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'ros2':
   Traceback (most recent call last):
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 300, column 25, in _ros2_archive_impl
		base_ros2_repository(repo_ctx, workspaces_in_sandbox)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 107, column 29, in base_ros2_repository
		result = execute_or_fail(repo_ctx, cmd, quiet=True, environment=env)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/tools/execute.bzl", line 16, column 13, in execute_or_fail
		fail("Failed to setup @{} repository: {}".format(
Error in fail: Failed to setup @ros2 repository: './run.bash /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py -i action_msgs -i builtin_interfaces -i rosidl_default_generators -i rclcpp_action -i rclcpp -i rclpy -i ros2cli -i ros2cli_common_extensions -i rmw_cyclonedds_cpp -i does_not_exist -o distro_metadata.json' exited with 1
--- captured stderr ---
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 54, in <module>
    main()
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 46, in main
    distro = scrape_distribution(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 85, in scrape_distribution
    packages, dependency_graph = build_dependency_graph(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 45, in build_dependency_graph
    raise RuntimeError(f'Cannot find packages {unknown_packages}')
RuntimeError: Cannot find packages {'does_not_exist'}
ERROR: /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/WORKSPACE:34:13: fetching ros2_archive rule //external:ros2: Traceback (most recent call last):
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 300, column 25, in _ros2_archive_impl
		base_ros2_repository(repo_ctx, workspaces_in_sandbox)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 107, column 29, in base_ros2_repository
		result = execute_or_fail(repo_ctx, cmd, quiet=True, environment=env)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/tools/execute.bzl", line 16, column 13, in execute_or_fail
		fail("Failed to setup @{} repository: {}".format(
Error in fail: Failed to setup @ros2 repository: './run.bash /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py -i action_msgs -i builtin_interfaces -i rosidl_default_generators -i rclcpp_action -i rclcpp -i rclpy -i ros2cli -i ros2cli_common_extensions -i rmw_cyclonedds_cpp -i does_not_exist -o distro_metadata.json' exited with 1
--- captured stderr ---
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 54, in <module>
    main()
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 46, in main
    distro = scrape_distribution(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 85, in scrape_distribution
    packages, dependency_graph = build_dependency_graph(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 45, in build_dependency_graph
    raise RuntimeError(f'Cannot find packages {unknown_packages}')
RuntimeError: Cannot find packages {'does_not_exist'}
ERROR: no such package '@ros2//': Failed to setup @ros2 repository: './run.bash /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py -i action_msgs -i builtin_interfaces -i rosidl_default_generators -i rclcpp_action -i rclcpp -i rclpy -i ros2cli -i ros2cli_common_extensions -i rmw_cyclonedds_cpp -i does_not_exist -o distro_metadata.json' exited with 1
--- captured stderr ---
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 54, in <module>
    main()
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 46, in main
    distro = scrape_distribution(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 85, in scrape_distribution
    packages, dependency_graph = build_dependency_graph(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 45, in build_dependency_graph
    raise RuntimeError(f'Cannot find packages {unknown_packages}')
RuntimeError: Cannot find packages {'does_not_exist'}
INFO: Elapsed time: 3.886s
INFO: 0 processes.
```

2022-08-08 20:40 UTC, IanTheEngineer requested changes
Thanks for tackling this. The update looks good overall. Just a few small comments below.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/109#-:-N8zAt8a9UZyCl6WH5TG:b3n8avd)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @IanTheEngineer and @sloretz)

___
*[`bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py` line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/109#-N8zAR8aCyK1THbfKC-v:-N8zAR8aCyK1THbfKC-w:b-d1pvv3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/443c2d38cf96fe29ef999244347591b7817c2adc/bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py#L45)):*
> ```Python
>         if not package_set.issuperset(include):
>             unknown_packages = include.difference(package_set)
>             raise RuntimeError(f'Cannot find packages {unknown_packages}')
> ```

Nit: The most likely scenario is one package, so perhaps message it as an optional plural?
```
f'Cannot find package(s) {unknown_packages}'
```
___
*[`ros2_example_bazel_installed/WORKSPACE` line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/109#-N8zA0u-3nDzvWYGoYt9:-N8zA0u-3nDzvWYGoYtA:b67tbc4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/443c2d38cf96fe29ef999244347591b7817c2adc/ros2_example_bazel_installed/WORKSPACE#L31)):*
> ```Starlark
>     # RMW implementations
>     "rmw_cyclonedds_cpp",
>     # "rmw_fastrtps_cpp",
> ```

Is there a reason this `fastrtps` is now commented out?


<!-- Sent from Reviewable.io -->

2022-08-08 21:32 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/109)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer)

___
*[`bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py` line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/109#-N8zAR8aCyK1THbfKC-v:-N8zLzWrAi38XUZRH91h:blgitmy) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/443c2d38cf96fe29ef999244347591b7817c2adc/bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py#L45)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Nit: The most likely scenario is one package, so perhaps message it as an optional plural?
```
f'Cannot find package(s) {unknown_packages}'
```
</blockquote></details>

Done in 9fe2149

<details><summary>Plural output</summary>

```
focal:osrf> bazel build //...
INFO: Repository ros2 instantiated at:
  /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/WORKSPACE:35:13: in <toplevel>
Repository rule ros2_archive defined at:
  /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl:307:31: in <toplevel>
INFO: Repository 'ros2' used the following cache hits instead of downloading the corresponding file.
 * Hash '87ba25ac7f97a220cfaeb7ac577c3bb7e3c36040f41e16309d55b8847a895682' for http://repo.ros2.org/ci_archives/drake-ros-underlay/ros2-humble-linux-focal-amd64-ci.tar.bz2
If the definition of 'ros2' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'ros2':
   Traceback (most recent call last):
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 300, column 25, in _ros2_archive_impl
		base_ros2_repository(repo_ctx, workspaces_in_sandbox)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 107, column 29, in base_ros2_repository
		result = execute_or_fail(repo_ctx, cmd, quiet=True, environment=env)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/tools/execute.bzl", line 16, column 13, in execute_or_fail
		fail("Failed to setup @{} repository: {}".format(
Error in fail: Failed to setup @ros2 repository: './run.bash /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py -i action_msgs -i builtin_interfaces -i rosidl_default_generators -i rclcpp_action -i rclcpp -i rclpy -i ros2cli -i ros2cli_common_extensions -i rmw_cyclonedds_cpp -i rmw_fastrtps_cpp -i dne -o distro_metadata.json' exited with 1
--- captured stderr ---
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 54, in <module>
    main()
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 46, in main
    distro = scrape_distribution(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 90, in scrape_distribution
    packages, dependency_graph = build_dependency_graph(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 50, in build_dependency_graph
    raise RuntimeError(msg)
RuntimeError: Cannont find packages ('dne', 'rmw_fastrtps_cpp')
ERROR: /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/WORKSPACE:35:13: fetching ros2_archive rule //external:ros2: Traceback (most recent call last):
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 300, column 25, in _ros2_archive_impl
		base_ros2_repository(repo_ctx, workspaces_in_sandbox)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 107, column 29, in base_ros2_repository
		result = execute_or_fail(repo_ctx, cmd, quiet=True, environment=env)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/tools/execute.bzl", line 16, column 13, in execute_or_fail
		fail("Failed to setup @{} repository: {}".format(
Error in fail: Failed to setup @ros2 repository: './run.bash /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py -i action_msgs -i builtin_interfaces -i rosidl_default_generators -i rclcpp_action -i rclcpp -i rclpy -i ros2cli -i ros2cli_common_extensions -i rmw_cyclonedds_cpp -i rmw_fastrtps_cpp -i dne -o distro_metadata.json' exited with 1
--- captured stderr ---
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 54, in <module>
    main()
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 46, in main
    distro = scrape_distribution(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 90, in scrape_distribution
    packages, dependency_graph = build_dependency_graph(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 50, in build_dependency_graph
    raise RuntimeError(msg)
RuntimeError: Cannont find packages ('dne', 'rmw_fastrtps_cpp')
ERROR: no such package '@ros2//': Failed to setup @ros2 repository: './run.bash /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py -i action_msgs -i builtin_interfaces -i rosidl_default_generators -i rclcpp_action -i rclcpp -i rclpy -i ros2cli -i ros2cli_common_extensions -i rmw_cyclonedds_cpp -i rmw_fastrtps_cpp -i dne -o distro_metadata.json' exited with 1
--- captured stderr ---
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 54, in <module>
    main()
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 46, in main
    distro = scrape_distribution(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 90, in scrape_distribution
    packages, dependency_graph = build_dependency_graph(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 50, in build_dependency_graph
    raise RuntimeError(msg)
RuntimeError: Cannont find packages ('dne', 'rmw_fastrtps_cpp')
INFO: Elapsed time: 3.792s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: ros2_example_apps ... (3 packages)
```
</details>

<details><summary>Singular output</summary>

```
focal:osrf> bazel build //...
INFO: Repository ros2 instantiated at:
  /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/WORKSPACE:34:13: in <toplevel>
Repository rule ros2_archive defined at:
  /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl:307:31: in <toplevel>
INFO: Repository 'ros2' used the following cache hits instead of downloading the corresponding file.
 * Hash '87ba25ac7f97a220cfaeb7ac577c3bb7e3c36040f41e16309d55b8847a895682' for http://repo.ros2.org/ci_archives/drake-ros-underlay/ros2-humble-linux-focal-amd64-ci.tar.bz2
If the definition of 'ros2' was updated, verify that the hashes were also update [...]

2022-08-08 23:00 UTC, IanTheEngineer requested changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks for the update!

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/109#-:-N8zfoJl7UcJcMqDSwpe:b-ljurkm)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py` line 45 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/109#-N8zAR8aCyK1THbfKC-v:-N8zexIQ9DePC_bAFTy3:bqf4i46) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/443c2d38cf96fe29ef999244347591b7817c2adc/bazel_ros2_rules/ros2/resources/ros2bzl/scraping/__init__.py#L45)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Done in 9fe2149

<details><summary>Plural output</summary>

```
focal:osrf> bazel build //...
INFO: Repository ros2 instantiated at:
  /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/WORKSPACE:35:13: in <toplevel>
Repository rule ros2_archive defined at:
  /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl:307:31: in <toplevel>
INFO: Repository 'ros2' used the following cache hits instead of downloading the corresponding file.
 * Hash '87ba25ac7f97a220cfaeb7ac577c3bb7e3c36040f41e16309d55b8847a895682' for http://repo.ros2.org/ci_archives/drake-ros-underlay/ros2-humble-linux-focal-amd64-ci.tar.bz2
If the definition of 'ros2' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'ros2':
   Traceback (most recent call last):
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 300, column 25, in _ros2_archive_impl
		base_ros2_repository(repo_ctx, workspaces_in_sandbox)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 107, column 29, in base_ros2_repository
		result = execute_or_fail(repo_ctx, cmd, quiet=True, environment=env)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/tools/execute.bzl", line 16, column 13, in execute_or_fail
		fail("Failed to setup @{} repository: {}".format(
Error in fail: Failed to setup @ros2 repository: './run.bash /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py -i action_msgs -i builtin_interfaces -i rosidl_default_generators -i rclcpp_action -i rclcpp -i rclpy -i ros2cli -i ros2cli_common_extensions -i rmw_cyclonedds_cpp -i rmw_fastrtps_cpp -i dne -o distro_metadata.json' exited with 1
--- captured stderr ---
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 54, in <module>
    main()
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 46, in main
    distro = scrape_distribution(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 90, in scrape_distribution
    packages, dependency_graph = build_dependency_graph(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 50, in build_dependency_graph
    raise RuntimeError(msg)
RuntimeError: Cannont find packages ('dne', 'rmw_fastrtps_cpp')
ERROR: /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/WORKSPACE:35:13: fetching ros2_archive rule //external:ros2: Traceback (most recent call last):
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 300, column 25, in _ros2_archive_impl
		base_ros2_repository(repo_ctx, workspaces_in_sandbox)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl", line 107, column 29, in base_ros2_repository
		result = execute_or_fail(repo_ctx, cmd, quiet=True, environment=env)
	File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/tools/execute.bzl", line 16, column 13, in execute_or_fail
		fail("Failed to setup @{} repository: {}".format(
Error in fail: Failed to setup @ros2 repository: './run.bash /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py -i action_msgs -i builtin_interfaces -i rosidl_default_generators -i rclcpp_action -i rclcpp -i rclpy -i ros2cli -i ros2cli_common_extensions -i rmw_cyclonedds_cpp -i rmw_fastrtps_cpp -i dne -o distro_metadata.json' exited with 1
--- captured stderr ---
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 54, in <module>
    main()
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 46, in main
    distro = scrape_distribution(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 90, in scrape_distribution
    packages, dependency_graph = build_dependency_graph(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 50, in build_dependency_graph
    raise RuntimeError(msg)
RuntimeError: Cannont find packages ('dne', 'rmw_fastrtps_cpp')
ERROR: no such package '@ros2//': Failed to setup @ros2 repository: './run.bash /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py -i action_msgs -i builtin_interfaces -i rosidl_default_generators -i rclcpp_action -i rclcpp -i rclpy -i ros2cli -i ros2cli_common_extensions -i rmw_cyclonedds_cpp -i rmw_fastrtps_cpp -i dne -o distro_metadata.json' exited with 1
--- captured stderr ---
Traceback (most recent call last):
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 54, in <module>
    main()
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/scrape_distribution.py", line 46, in main
    distro = scrape_distribution(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 90, in scrape_distribution
    packages, dependency_graph = build_dependency_graph(
  File "/home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/ros2/resources/ros2bzl/scraping/__init__.py", line 50, in build_dependency_graph
    raise RuntimeError(msg)
RuntimeError: Cannont find packages ('dne', 'rmw_fastrtps_cpp')
INFO: Elapsed time: 3.792s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: ros2_example_apps ... (3 packages)
```
</details>

<details><summary>Singular output</summary>

```
focal:osrf> bazel build //...
INFO: Repository ros2 instantiated at:
  /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/WORKSPACE:34:13: in <toplevel>
Repository rule ros2_archive defined at:
  /home/osrf/.cache/bazel/_bazel_osrf/383f079a2635d21e3b905b3ffc908f7b/external/bazel_ros2_rules/ros2/defs.bzl:307:31: in <toplevel>
INFO: Repository 'ros2' used the following cache hits instead of downloading the corresponding file.
 * Hash '87ba25ac7f97a220cfaeb7ac577c3bb7e3c36040f41e16309d55b8847a895682' for http://repo.ros2.org/ci_archives/drake-ros-underlay/ros2-humble-linux-focal-amd64-ci.tar.bz2
If the def [...]

2022-08-09 00:12 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/109)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer)

___
*[`ros2_example_bazel_installed/WORKSPACE` line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/109#-N8zA0u-3nDzvWYGoYt9:-N8zwX7s8XpPVw2uj0fd:bsj4mou) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/443c2d38cf96fe29ef999244347591b7817c2adc/ros2_example_bazel_installed/WORKSPACE#L31)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Nit: Ok, I had a feeling that was the case. I'm fine with it remaining commented out, but perhaps add a single short description in an additional comment. Something like
```
    # RMW implementations
    # Uncomment one and only one to use a change implementations
    "rmw_cyclonedds_cpp",
    # "rmw_fastrtps_cpp",

```
</blockquote></details>

Added comment in 7d3600c8328682e766319f8a201245296db33b4f


<!-- Sent from Reviewable.io -->

2022-08-09 02:32 UTC, IanTheEngineer reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/109)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @IanTheEngineer)

___
*[`ros2_example_bazel_installed/WORKSPACE` line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/109#-N8zA0u-3nDzvWYGoYt9:-N9-RZwU88E-zEBDkx3r:bcg1pu2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/443c2d38cf96fe29ef999244347591b7817c2adc/ros2_example_bazel_installed/WORKSPACE#L31)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Added comment in 7d3600c8328682e766319f8a201245296db33b4f
</blockquote></details>

Looks great. Thanks!


<!-- Sent from Reviewable.io -->

2022-08-09 02:33 UTC, IanTheEngineer reviewed
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> again!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/109#-:-N9-Rg796Hzam-wZCvkh:b-etoe8g)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2022-08-09 16:09 UTC, sloretz reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (seeing if this makes the reveiwable test line become a check instead of a yellow circle)

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/109#-:-N92MGm-CBjG7ZiIMz2I:b-y4tydi)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2022-08-09 16:09 UTC, merged