Add reproduction of RobotLocomotion/drake-ros#113
RobotLocomotion/drake-ros pull request #114
Opened 2022-08-10 23:12 UTC by sloretz

RobotLocomotion/drake-ros#113

`bazel run //:bin_unaware_of_ros`

It looks like binaries can run ROS 2 without the shim.

```console
$ ldd bazel-bin/bin_unaware_of_ros
	linux-vdso.so.1 (0x00007ffd42de2000)
	librclcpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crclcpp_Ucc___Uarchive_Slib/librclcpp.so (0x00007f6bd1ccc000)
	liblibstatistics_collector.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Clibstatistics_Ucollector_Ucc___Uarchive_Slib/liblibstatistics_collector.so (0x00007f6bd1cc5000)
	libstd_msgs__rosidl_typesupport_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Cstd_Umsgs_Ucc___Uarchive_Slib/libstd_msgs__rosidl_typesupport_cpp.so (0x00007f6bd1cbd000)
	libstd_msgs__rosidl_typesupport_introspection_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Cstd_Umsgs_Ucc___Uarchive_Slib/libstd_msgs__rosidl_typesupport_introspection_cpp.so (0x00007f6bd1ca6000)
	libstd_msgs__rosidl_generator_py.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Cstd_Umsgs_Ucc___Uarchive_Slib/libstd_msgs__rosidl_generator_py.so (0x00007f6bd1c96000)
	libstd_msgs__rosidl_generator_c.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Cstd_Umsgs_Ucc___Uarchive_Slib/libstd_msgs__rosidl_generator_c.so (0x00007f6bd1c78000)
	libstd_msgs__rosidl_typesupport_c.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Cstd_Umsgs_Ucc___Uarchive_Slib/libstd_msgs__rosidl_typesupport_c.so (0x00007f6bd1c71000)
	libstd_msgs__rosidl_typesupport_introspection_c.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Cstd_Umsgs_Ucc___Uarchive_Slib/libstd_msgs__rosidl_typesupport_introspection_c.so (0x00007f6bd1c5e000)
	librcl.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crcl_Ucc___Uarchive_Slib/librcl.so (0x00007f6bd1c1f000)
	librcl_interfaces__rosidl_typesupport_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crcl_Uinterfaces_Ucc___Uarchive_Slib/librcl_interfaces__rosidl_typesupport_cpp.so (0x00007f6bd1c17000)
	librcl_interfaces__rosidl_typesupport_introspection_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crcl_Uinterfaces_Ucc___Uarchive_Slib/librcl_interfaces__rosidl_typesupport_introspection_cpp.so (0x00007f6bd1bf4000)
	librcl_interfaces__rosidl_generator_py.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crcl_Uinterfaces_Ucc___Uarchive_Slib/librcl_interfaces__rosidl_generator_py.so (0x00007f6bd1be3000)
	librcl_interfaces__rosidl_generator_c.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crcl_Uinterfaces_Ucc___Uarchive_Slib/librcl_interfaces__rosidl_generator_c.so (0x00007f6bd1bca000)
	librcl_interfaces__rosidl_typesupport_c.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crcl_Uinterfaces_Ucc___Uarchive_Slib/librcl_interfaces__rosidl_typesupport_c.so (0x00007f6bd1bc1000)
	librcl_interfaces__rosidl_typesupport_introspection_c.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crcl_Uinterfaces_Ucc___Uarchive_Slib/librcl_interfaces__rosidl_typesupport_introspection_c.so (0x00007f6bd1ba8000)
	libtracetools.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Ctracetools_Ucc___Uarchive_Slib/libtracetools.so (0x00007f6bd1ba3000)
	librmw_cyclonedds_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/librmw_cyclonedds_cpp.so (0x00007f6bd1b19000)
	libddsc.so.0 => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/libddsc.so.0 (0x00007f6bd19de000)
	librmw_dds_common.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/librmw_dds_common.so (0x00007f6bd19c1000)
	librmw.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/librmw.so (0x00007f6bd19b5000)
	librmw_dds_common__rosidl_typesupport_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/librmw_dds_common__rosidl_typesupport_cpp.so (0x00007f6bd19b0000)
	librosidl_typesupport_introspection_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/librosidl_typesupport_introspection_cpp.so (0x00007f6bd19ab000)
	librosidl_typesupport_introspection_c.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/librosidl_typesupport_introspection_c.so (0x00007f6bd19a6000)
	librosidl_runtime_c.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/librosidl_runtime_c.so (0x00007f6bd1999000)
	libiceoryx_binding_c.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/libiceoryx_binding_c.so (0x00007f6bd1962000)
	librmw_dds_common__rosidl_typesupport_introspection_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/librmw_dds_common__rosidl_typesupport_introspection_cpp.so (0x00007f6bd195a000)
	libiceoryx_posh.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/libiceoryx_posh.so (0x00007f6bd185b000)
	libiceoryx_hoofs.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/libiceoryx_hoofs.so (0x00007f6bd17e1000)
	libiceoryx_platform.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crmw_Uimplementation_Ucc___Uarchive_Slib/libiceoryx_platform.so (0x00007f6bd17da000)
	libament_index_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Cament_Uindex_Ucpp_Ucc___Uarchive_Slib/libament_index_cpp.so (0x00007f6bd17cf000)
	librcl_logging_spdlog.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crcl_Ulogging_Uspdlog_Ucc___Uarchive_Slib/librcl_logging_spdlog.so (0x00007f6bd17c5000)
	librcl_logging_interface.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Crcl_Ulogging_Uinterface_Ucc___Uarchive_Slib/librcl_logging_interface.so (0x00007f6bd17c0000)
	libstatistics_msgs__rosidl_typesupport_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Cstatistics_Umsgs_Ucc___Uarchive_Slib/libstatistics_msgs__rosidl_typesupport_cpp.so (0x00007f6bd17bb000)
	libstatistics_msgs__rosidl_typesupport_introspection_cpp.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/_U@ros2_S_S_Cstatistics_Umsgs_Ucc___Uarchive_Slib/libstatistics_msgs__rosidl_typesupport_introspection_cpp.so (0x00007f6bd17b3000)
	libstatistics_msgs__rosidl_generator_py.so => /home/osrf/ws/drake/src/drake-ros/ros2_example_bazel_installed/bazel-bin/_solib_k8/ [...]

2022-08-10 23:29 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/114)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/114#-N994_LUB2ZjCSPHg0Ca:-N994_LUB2ZjCSPHg0Cb:b-wcdkv) (no related file):*
Thanks! Can I ask what your plan is w.r.t. this PR? I assume land it, but then show failure once we have proper checks in place?

If so, then we could actually do the above `ldd` inside a `bazel test` and verify current behavior.

___


<!-- Sent from Reviewable.io -->

2022-08-10 23:41 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/114)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/114#-N994_LUB2ZjCSPHg0Ca:-N9970ja9MNUUWBdzQKl:b24dxmc) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Thanks! Can I ask what your plan is w.r.t. this PR? I assume land it, but then show failure once we have proper checks in place?

If so, then we could actually do the above `ldd` inside a `bazel test` and verify current behavior.
</blockquote></details>

My plan for the PR was just to share what I learned. I don't yet know know to implement a check making sure the right binary rule is used when `@ros2` is depended upon indirectly.

___


<!-- Sent from Reviewable.io -->

2022-08-11 13:26 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/114)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/114#-N994_LUB2ZjCSPHg0Ca:-N9C4Ea7Bfrqz8JW3jL-:b-eawxhm) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

My plan for the PR was just to share what I learned. I don't yet know know to implement a check making sure the right binary rule is used when `@ros2` is depended upon indirectly.
</blockquote></details>

Gotcha; in that case, mentioning as much in PR overview, marking it as draft, etc. would help in the future!

And yeah, just using this as repro anchor point makes sense.

___


<!-- Sent from Reviewable.io -->

2022-08-11 15:55 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/114)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/114#-N994_LUB2ZjCSPHg0Ca:-N9CbWyJ1wy12H5Vg7k3:b-vshhn4) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha; in that case, mentioning as much in PR overview, marking it as draft, etc. would help in the future!

And yeah, just using this as repro anchor point makes sense.
</blockquote></details>

Converted to a draft

___


<!-- Sent from Reviewable.io -->

2022-09-16 19:54 UTC, EricCousineau-TRI commented
I believe we've more-or-less resolved this within Anzu by using Starlark macros instrumented both in this repo and in Anzu.

We can open-source an example of the Anzu macros in the future, if so desired
Thanks!

2022-09-16 19:54 UTC, closed without merging