Stop including entire ament index for each package
RobotLocomotion/drake-ros pull request #123
Opened 2022-08-22 15:03 UTC by cottsay

The ament index design specs state that marker files in the resource index should share the name of the package installing them. We can leverage this to select which marker files belong to each package.

The existing approach worked for isolated workspace layouts, but broke down when inspecting a merged workspace.

2022-08-24 19:26 UTC, sloretz requested changes
> The ament index design specs state that marker files in the resource index should share the name of the package installing them. We can leverage this to select which marker files belong to each package.

With this change it seems like packages can only see ament index entries for their dependencies. Consider `bazel run @ros2//:ros2 pkg list`. The intent is to show all packages in a workspace, but with this PR it only shows the packages the CLI tool itself depends on. 

<details><summary>ros2 pkg list with this PR</summary>

```
action_msgs
ament_cmake
ament_cmake_core
ament_cmake_export_definitions
ament_cmake_export_dependencies
ament_cmake_export_include_directories
ament_cmake_export_interfaces
ament_cmake_export_libraries
ament_cmake_export_link_flags
ament_cmake_export_targets
ament_cmake_gen_version_h
ament_cmake_libraries
ament_cmake_python
ament_cmake_target_dependencies
ament_cmake_test
ament_cmake_version
ament_copyright
ament_index_cpp
ament_index_python
ament_lint
builtin_interfaces
class_loader
composition_interfaces
console_bridge_vendor
launch
launch_ros
launch_xml
launch_yaml
libstatistics_collector
libyaml_vendor
lifecycle_msgs
osrf_pycommon
rcl
rcl_action
rcl_interfaces
rcl_lifecycle
rcl_logging_interface
rcl_logging_spdlog
rcl_yaml_param_parser
rclcpp
rclcpp_action
rclcpp_components
rclpy
rcpputils
rcutils
rmw
rmw_cyclonedds_cpp
rmw_dds_common
rmw_implementation
rmw_implementation_cmake
ros2action
ros2cli
ros2cli_common_extensions
ros2component
ros2doctor
ros2interface
ros2launch
ros2lifecycle
ros2multicast
ros2node
ros2param
ros2pkg
ros2run
ros2service
ros2topic
ros_environment
rosgraph_msgs
rosidl_adapter
rosidl_cli
rosidl_cmake
rosidl_default_generators
rosidl_default_runtime
rosidl_generator_c
rosidl_generator_cpp
rosidl_generator_py
rosidl_parser
rosidl_runtime_c
rosidl_runtime_cpp
rosidl_runtime_py
rosidl_typesupport_c
rosidl_typesupport_cpp
rosidl_typesupport_interface
rosidl_typesupport_introspection_c
rosidl_typesupport_introspection_cpp
rpyutils
spdlog_vendor
sros2
statistics_msgs
std_msgs
tracetools
unique_identifier_msgs
```
</details>

<details><summary>ros2 pkg list with develop</summary>

```
action_msgs
actionlib_msgs
ament_clang_format
ament_cmake
ament_cmake_auto
ament_cmake_clang_format
ament_cmake_copyright
ament_cmake_core
ament_cmake_cppcheck
ament_cmake_cpplint
ament_cmake_export_definitions
ament_cmake_export_dependencies
ament_cmake_export_include_directories
ament_cmake_export_interfaces
ament_cmake_export_libraries
ament_cmake_export_link_flags
ament_cmake_export_targets
ament_cmake_flake8
ament_cmake_gen_version_h
ament_cmake_gmock
ament_cmake_google_benchmark
ament_cmake_gtest
ament_cmake_include_directories
ament_cmake_libraries
ament_cmake_lint_cmake
ament_cmake_pep257
ament_cmake_pycodestyle
ament_cmake_pytest
ament_cmake_python
ament_cmake_ros
ament_cmake_target_dependencies
ament_cmake_test
ament_cmake_uncrustify
ament_cmake_version
ament_cmake_xmllint
ament_copyright
ament_cppcheck
ament_cpplint
ament_flake8
ament_index_cpp
ament_index_python
ament_lint
ament_lint_auto
ament_lint_cmake
ament_lint_common
ament_mypy
ament_package
ament_pep257
ament_pycodestyle
ament_uncrustify
ament_xmllint
builtin_interfaces
class_loader
common_interfaces
composition_interfaces
console_bridge_vendor
cv_bridge
diagnostic_msgs
domain_coordinator
eigen3_cmake_module
geometry2
geometry_msgs
image_transport
interactive_markers
kdl_parser
keyboard_handler
laser_geometry
launch
launch_ros
launch_testing
launch_testing_ament_cmake
launch_testing_ros
launch_xml
launch_yaml
libcurl_vendor
libstatistics_collector
libyaml_vendor
lifecycle_msgs
map_msgs
message_filters
mimick_vendor
nav_msgs
orocos_kdl_vendor
osrf_pycommon
performance_test_fixture
pluginlib
pybind11_vendor
python_cmake_module
rcl
rcl_action
rcl_interfaces
rcl_lifecycle
rcl_logging_interface
rcl_logging_spdlog
rcl_yaml_param_parser
rclcpp
rclcpp_action
rclcpp_components
rclcpp_lifecycle
rclpy
rcpputils
rcutils
resource_retriever
rmw
rmw_cyclonedds_cpp
rmw_dds_common
rmw_implementation
rmw_implementation_cmake
robot_state_publisher
ros2action
ros2bag
ros2cli
ros2cli_common_extensions
ros2cli_test_interfaces
ros2component
ros2doctor
ros2interface
ros2launch
ros2lifecycle
ros2lifecycle_test_fixtures
ros2multicast
ros2node
ros2param
ros2pkg
ros2run
ros2service
ros2test
ros2topic
ros_base
ros_core
ros_environment
ros_testing
rosbag2
rosbag2_compression
rosbag2_compression_zstd
rosbag2_cpp
rosbag2_interfaces
rosbag2_py
rosbag2_storage
rosbag2_storage_default_plugins
rosbag2_test_common
rosbag2_tests
rosbag2_transport
rosgraph_msgs
rosidl_adapter
rosidl_cli
rosidl_cmake
rosidl_default_generators
rosidl_default_runtime
rosidl_generator_c
rosidl_generator_cpp
rosidl_generator_py
rosidl_parser
rosidl_runtime_c
rosidl_runtime_cpp
rosidl_runtime_py
rosidl_typesupport_c
rosidl_typesupport_cpp
rosidl_typesupport_interface
rosidl_typesupport_introspection_c
rosidl_typesupport_introspection_cpp
rpyutils
rviz2
rviz_assimp_vendor
rviz_common
rviz_default_plugins
rviz_ogre_vendor
rviz_rendering
rviz_rendering_tests
rviz_visual_testing_framework
sensor_msgs
sensor_msgs_py
shape_msgs
shared_queues_vendor
spdlog_vendor
sqlite3_vendor
sros2
sros2_cmake
statistics_msgs
std_msgs
std_srvs
stereo_msgs
test_interface_files
test_msgs
tf2
tf2_bullet
tf2_eigen
tf2_eigen_kdl
tf2_geometry_msgs
tf2_kdl
tf2_msgs
tf2_py
tf2_ros
tf2_ros_py
tf2_sensor_msgs
tf2_tools
tinyxml2_vendor
tinyxml_vendor
tracetools
trajectory_msgs
uncrustify_vendor
unique_identifier_msgs
urdf
urdf_parser_plugin
visualization_msgs
xacro
yaml_cpp_vendor
zstd_vendor
```
</details>


I think the same issue would come up with pluginlib plugins `bazel run @ros2//:ros2 component types` shows composable nodes on the `develop` branch, but it shows no composable nodes with this PR.

I'm not sure how to fix this. We'd have to know what ament index resource types a package was going to use, and then populate all packages for that type, but I'm not sure there's a way to discover what resource types a package is going to use without looking at it's source code.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/123#-:-NAGG5re2GPjTL7bPNcW:bo5m6bx)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @cottsay)



<!-- Sent from Reviewable.io -->

2022-08-26 03:04 UTC, EricCousineau-TRI commented
Can I ask which issue this is addressing? I believe we discussed it on Monday, but upon review:
- #95 - I don't believe this removes hard-coded paths
- #96 - I assume `share_filegroup()` comes in via `data` dependencies. `data` should not affect *compilation* of C++ programs, only binary execution.
- #116 - same as for #96 - I don't believe this should cause recompilation.

(in the future, can you be sure to reference the intended issue?)

In conjunction w/ Shane's comment, I am also not sure if I'd know how to acutely  and if my above assumptions are correct, it may be good to focus on what is causing recompilation of C++ programs. I can explain more if you like.

2022-08-26 17:40 UTC, cottsay commented
Clearly my understanding of what's happening here is incomplete.

I believed that this was part of #96 because adding a package to the underlay caused ~71 of the ~516 processes to be re-evaluated on subsequent builds of `ros2_example_bazel_installed`, but I see now that none of those processes were actually compile commands, which #96 references specifically. This change eliminated those extra action runs, so I thought it added value. Clearly not.

2022-08-26 17:40 UTC, closed without merging

2022-08-26 22:18 UTC, EricCousineau-TRI commented
Sorry for not catching that earlier; do you have candidate path(s) forward for the recompilation issues?

2022-08-26 23:17 UTC, cottsay commented
> do you have candidate path(s) forward for the recompilation issues?

Continued discussion in #128.