Create ament index for custom messages and make dload shims aware of it
RobotLocomotion/drake-ros pull request #124
Opened 2022-08-22 22:20 UTC by sloretz

Fixes #118 
Contains #120

This creates an ament resource index describing the existence of custom messages created with `rosidl_interfaces_group()`. The index is made available as runfiles to any target that depends on `{group name}_ament_index`. The dload shim uses a bazel aspect to accumulate declared ament index prefixes, and prepends `AMENT_PREFIX_PATH` with them.

Note that the `ros2 interface list` test in `custom_message_echo_test` now passes because it depends on `:ros2_example_apps_msgs_ament_index`

2022-08-22 22:20 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6d5_v0-pmBgpbN0dV:-NA6d5_v0-pmBgpbN0dW:btxkahr) (no related file):*
+@ericcousineau-tri for review please!

___


<!-- Sent from Reviewable.io -->

2022-08-22 23:09 UTC, EricCousineau-TRI requested changes
Looks good thus far! Made some comments for both user experience and implementation.

> Reviewed 4 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-:-NA6nSAQE4QbV2Tb8roq:bg8cz17)* status: 4 of 10 files reviewed, 12 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6jb9F3utii1M50nTR:-NA6jb9F3utii1M50nTS:b9319qb) (no related file):*
nit Indentation inconsistent among some files; can you run `buildifier` from Anzu or Drake on these files once this PR is good?

___
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 170 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6ieXp2bU2MjtBaEoO:-NA6ieXq0Iutk8hjo6UZ:bp6bok3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L170)):*
> ```Starlark
>     # Declare interface files in a file under the rosidl_interfaces resource.
>     # Directory names are important.
>     # https://github.com/ament/ament_cmake/blob/master/ament_cmake_core/
> ```

nit Can you pin this to a release (or commit, if one does not exist)?
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 181 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6mr0FB1ioomM9o7OE:-NA6mr0FB1ioomM9o7OF:bpw3ctv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L181)):*
> ```Starlark
>     # Gather interface files from arguments which may be rules or files.
>     interface_files = []
>     for input_file_or_rule in ctx.attr.interfaces:
> ```

Per below, a bit confusing as to why we need this `rule_or_file` construct; 
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 216 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6mcAJ5DJcwN-wzOcH:-NA6mcAKA3eJ4tXM6NtF:brpdvua) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L216)):*
> ```Starlark
> 
>     return [
>         AmentIndex(prefix = ctx.attr.prefix),
> ```

Per below, is it possible to only have `AmentIndexes`, and have this rule do the recursion / composition, perhaps with something like `depset`?

It should simplify this a bit.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6j4on6t-omvESR03_:-NA6j4on6t-omvESR03a:b-2narqc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1140)):*
> ```Starlark
>     )
> 
>     rosidl_generate_ament_index_entry(
> ```

Rather than require users to depend on this data separately, should we incorporate the data into each of the language targets?

Pro: Any dependency on the generated language bindings includes the index.
Con: If the generated ament index does not have a stable hash, or is easily changed, then it could quickly invalidate any tests.

My assumption for the "Con" is that this should be more stable once we resolve things like #123, maybe other stuff like #95, etc. (\cc @cottsay)

WDYT?
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1143 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6jvQb06VhIu70tw09:-NA6jvQb06VhIu70tw0A:b-48vjgk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1143)):*
> ```Starlark
>         name = name + "_ament_index",
>         group = group or name,
>         interfaces = [name + "_defs"] + interfaces,
> ```

nit `name + "_defs"` repeated from (what looks like) above.

Can you use assign this to temporary, and use `_make_public_name()`?
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1143 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6kGEu40aUTubjCWqV:-NA6kGEu40aUTubjCWqW:b-an0vnw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1143)):*
> ```Starlark
>         name = name + "_ament_index",
>         group = group or name,
>         interfaces = [name + "_defs"] + interfaces,
> ```

I'm confused by this logic; why are you specifying both the filegroup and generated files?
___
*[`bazel_ros2_rules/ros2/tools/ament_index.bzl` line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6kl72EAcIwAmLztsn:-NA6kl72EAcIwAmLztso:b-iqmql4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/tools/ament_index.bzl#L7)):*
> ```Starlark
> )
> 
> AmentIndexes = provider(
> ```

Why not have just one provider, `AmentIndexes`?

Is there any way to rejigger above logic to admit recursive dependency among `AmentIndexes`?
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 136 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6i4313PsqEQe5Ohx9:-NA6i4320XlaUdybN66f:b-2olyg8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L136)):*
> ```Starlark
> # messages (#118). See note below.
> ros_py_test(
>     name = "custom_message_echo_test",
> ```

nit This test now does more; can you rename this to something like `ros2cli_custom_interface_test`?
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6iFlO0FlXDp-MtGzt:-NA6iFlO0FlXDp-MtGzu:b3nm68n) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L140)):*
> ```Starlark
>     srcs = ["test/custom_message_echo_test.py"],
>     deps = [
>         # This is the main key - you must provide the generated messages as a
> ```

This comment is now stale; from reading this, it looks like we need two things: the Python dependency and the data dependency on the ament index.
___
*[`ros2_example_bazel_installed/ros2_example_apps/simple_talker.py` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6l-qFE32K9CiqvxRk:-NA6l-qFE32K9CiqvxRl:b-7c5t8d) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/ros2_example_bazel_installed/ros2_example_apps/simple_talker.py#L1)):*
> ```Python
> import rclpy
> ```

nit Purpose of file unclear; can you add something like "Simple code-based publisher for custom message type" ?

That, or consider using something like `ros2 topic pub -r 10 ros2_example_apps/msg/Status '{}'` in the test, and remove this test?
(I had done this just to get one part working)


<!-- Sent from Reviewable.io -->

2022-08-23 00:17 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124)* status: 4 of 10 files reviewed, 12 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @sloretz)

___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6j4on6t-omvESR03_:-NA71hV66faoj1QRcuIs:bvzsfvg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1140)):*
> Rather than require users to depend on this data separately, should we incorporate the data into each of the language targets?

I think that would be a good idea (making the language targets depend on the `name + "_ament_index"` target). It seems likely to me that we'll discover other tools that assume they can lookup interfaces in the ament index, and making the language targets depend on these files would satisfy them without extra work in the future.

> If the generated ament index does not have a stable hash, or is easily changed, then it could quickly invalidate any tests.

Reading `depset` documentation, I wonder if the traversal order of the `ament_index_prefixes` aspect is stable. Any change there could re-order lines in the manifest. That might be another reason to look into how to use `depset`.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1143 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6kGEu40aUTubjCWqV:-NA6z-Te1in0dBjIZR7K:b-6k2m8o) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1143)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm confused by this logic; why are you specifying both the filegroup and generated files?
</blockquote></details>

The `interfaces` variable has all the files in the ROS interface description (`.msg`, `.srv`, `.action` extensions). The `name + "_defs"` target runs an executable that translates those files to OMG IDL (`.idl` extension), and returns the generated files in a `RosInterfaces` provider. They're both given to `rosidl_generate_ament_index_entry()` because when ROS interface descriptions are used, the rosidl pipeline puts both the original file and the generated OMG IDL file into the manifest in `rosidl_interfaces`.
___
*[`bazel_ros2_rules/ros2/tools/ament_index.bzl` line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6kl72EAcIwAmLztsn:-NA70xE_AIVrYqGz2U2l:b-y1mt2o) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/tools/ament_index.bzl#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Why not have just one provider, `AmentIndexes`?

Is there any way to rejigger above logic to admit recursive dependency among `AmentIndexes`?
</blockquote></details>

I tried this at first, but Bazel complained that two rules provided the same provider. I think it's because both the `ament_index_prefixes` aspect and the `rosidl_generate_ament_index_entry` returned a provider with the same type when the aspect looked at the `name + "_ament_index"` rule. I'm not familiar with depsets, but I can look for examples to see if they could solve that issue.


<!-- Sent from Reviewable.io -->

2022-08-23 00:57 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124)* status: 3 of 10 files reviewed, 12 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @sloretz)

___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 170 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6ieXp2bU2MjtBaEoO:-NA73xxL73RDRT2VJzqg:bosyoua) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L170)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you pin this to a release (or commit, if one does not exist)?
</blockquote></details>

`master` -> `1.5.0` in 9721a6c
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1143 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6jvQb06VhIu70tw09:-NA7BunC3wWzg42bcAgQ:buyincu) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1143)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `name + "_defs"` repeated from (what looks like) above.

Can you use assign this to temporary, and use `_make_public_name()`?
</blockquote></details>

Used `_make_public_label()` in 8ad75b8, but didn't use a temporary because it's no longer repeated.


<!-- Sent from Reviewable.io -->

2022-08-23 01:29 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124)* status: 3 of 10 files reviewed, 12 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @sloretz)

___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 216 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6mcAJ5DJcwN-wzOcH:-NA7I2Jq5m2K-_keAGT1:b-iktjk2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L216)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per below, is it possible to only have `AmentIndexes`, and have this rule do the recursion / composition, perhaps with something like `depset`?

It should simplify this a bit.
</blockquote></details>

It looks like having the rule doe the recursion with a depset breaks down when a rule doesn't provide `AmentIndexes`. Say we we have a target `:foobar` depending on `:geometry_msgs_py` which itself depends on `:geometry_msgs_ament_index`. It looks like `:foobar` can't accumulate `AmentIndexes` from the dependency `:geometry_msgs_py` because the `_py` rule doesn't provide it.

https://gist.github.com/sloretz/c9a80738e8aac4500d4015d1405714a8


<!-- Sent from Reviewable.io -->

2022-08-25 21:38 UTC, EricCousineau-TRI requested changes
> Reviewed 1 of 3 files at r1, 4 of 9 files at r2, 2 of 2 files at r3, all commit messages.
> Dismissed @sloretz from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124)* status: all files reviewed, 13 unresolved discussions (waiting on @cottsay and @sloretz)

___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 181 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6mr0FB1ioomM9o7OE:-NALtvku6ztREv5MYN0E:br93n5t) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L181)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per below, a bit confusing as to why we need this `rule_or_file` construct; 
</blockquote></details>

Per above, I think this can be simplified by having `RosInterfaces` provider include both ROS and OMG interfaces.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 216 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6mcAJ5DJcwN-wzOcH:-NALuEfGDizRYBS26crE:buy8eei) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L216)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

It looks like having the rule doe the recursion with a depset breaks down when a rule doesn't provide `AmentIndexes`. Say we we have a target `:foobar` depending on `:geometry_msgs_py` which itself depends on `:geometry_msgs_ament_index`. It looks like `:foobar` can't accumulate `AmentIndexes` from the dependency `:geometry_msgs_py` because the `_py` rule doesn't provide it.

https://gist.github.com/sloretz/c9a80738e8aac4500d4015d1405714a8


</blockquote></details>

OK Gotcha, makes sense, and thanks for repro!
Moved my clarifying requests to `ament_index.bzl`.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6j4on6t-omvESR03_:-NALuwk1C_OeZ4a8BsSY:bf0y7du) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1140)):*
> I think that would be a good idea [...]

Cool, then yeah, let's go ahead and include the ament index info in each then.

> Reading depset documentation, [...]

I would assume (hope) it's deterministic for the same inputs, but perhaps chaotic (insertion order may make things less intuitive).
Given that Bazel is all about asynchrony, we may just want to apply naive sorting here, perhaps making the total ordering something like `(party_level, name)`, where `party_level` is 2 if from ROS2 workspace, 1 if third-party, and then 0 if first-party (proper repository)?
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1143 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6kGEu40aUTubjCWqV:-NALsuHZAx3S2zb9tBVG:b-jz8rbt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1143)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

The `interfaces` variable has all the files in the ROS interface description (`.msg`, `.srv`, `.action` extensions). The `name + "_defs"` target runs an executable that translates those files to OMG IDL (`.idl` extension), and returns the generated files in a `RosInterfaces` provider. They're both given to `rosidl_generate_ament_index_entry()` because when ROS interface descriptions are used, the rosidl pipeline puts both the original file and the generated OMG IDL file into the manifest in `rosidl_interfaces`.
</blockquote></details>

Gotcha; I have made comments to this effect regarding `RosInterfaces` and delineating more (with additional bookkeeping) for both OMG and ROS interface files.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NALtWkd8ZA6PE20aIpU:-NALtWkd8ZA6PE20aIpV:bnmbqp0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8ad75b86af0a158f67bd7dd60fcf2b339a0dc899/bazel_ros2_rules/ros2/rosidl.bzl#L16)):*
> ```Starlark
> )
> 
> RosInterfaces = provider(
> ```

nit Missing docstring.

What does interfaces entail? Purely OMG IDL interfaces as well, or also ROS interface files as well?
(I assume the former)
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NALtgrB4mgXOSKMoefb:-NALtgrB4mgXOSKMoefc:b-82i1n0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8ad75b86af0a158f67bd7dd60fcf2b339a0dc899/bazel_ros2_rules/ros2/rosidl.bzl#L16)):*
> ```Starlark
> )
> 
> RosInterfaces = provider(
> ```

nit Name is now confusing; per below, I think this is really `OmgInterfaces`, not `RosInterfaces`.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 17 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NALu1vX5PnyyBBeJTZ1:-NALu1vYD3TTfIcYHUCO:bz0v600) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8ad75b86af0a158f67bd7dd60fcf2b339a0dc899/bazel_ros2_rules/ros2/rosidl.bzl#L17)):*
> ```Starlark
> 
> RosInterfaces = provider(
>     fields = ["interfaces"],
> ```

Perhaps logic can be cleared up here by specifying both interface types:
```
fields = ["omg_interfaces", "ros_interfaces"]
```
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 233 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NALuMd336roAcV1MaOT:-NALuMd336roAcV1MaOU:bm4thl7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8ad75b86af0a158f67bd7dd60fcf2b339a0dc899/bazel_ros2_rules/ros2/rosidl.bzl#L233)):*
> ```Starlark
>     provides = [AmentIndex],
> )
> ```

nit Missing docstring.

Also, be sure to include reference to docstring in `ament_index.bzl`
___
*[`bazel_ros2_rules/ros2/tools/ament_index.bzl` line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6kl72EAcIwAmLztsn:-NALqTWv-hLhDnAhqNQ9:b-fbal9t) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/tools/ament_index.bzl#L7)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I tried this at first, but Bazel complained that two rules provided the same provider. I think it's because both the `ament_index_prefixes` aspect and the `rosidl_generate_ament_index_entry` returned a provider with the same type when the aspect looked at the `name + "_ament_index"` rule. I'm not familiar with depsets, but I can look for examples to see if they could solve that issue.
</blockquote></details>

Gotcha; I think see the issues you've pointed out here and above:

(a) You define two providers so one rule can define the minimal data, while the aspect can transitively gather the information.
(b) Per your above point, you can use `aspect()` to transtively crawl through `deps`, but you cannot use `rule()` to do so.

In this case, can you comment / rename the variables as something along these lines?
```
# We have two constraints for this setup:
# (a) aspect() can directly analyze dependencies transitively (`data` and
# `deps`), but `rule()` cannot (it relies on rule implementation aggregating
# information to implicitly gather transitive information).
# Therefore we define the two providers below:

# This defines the index path, but does not aggregate them due to possible indirection
# (e.g. a dep in `py_binary` provides `AmentIndex`, but the `rule()` cannot access as mentioned above).
# Defined by `rosidl_generate_ament_index_entry`.
# Consumed by `ament_index_prefixes`.
AmentIndex = ...

# This aggregates transitive ament indexes information using an `aspect()` (as mentioned above).
# Defined by `ament_index_prefixes`.
# Consumed by `do_dload_shim`.
TransitiveAmentIndexes = ...
```
___
*[`ros2_example_bazel_installed/ros2_example_apps/test/custom_message_echo_test.py` line 1 at r3](ht [...]

2022-08-25 23:48 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @cottsay and @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6jb9F3utii1M50nTR:-NAMOVTf60eEwPEN5tQH:bwz0868) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Indentation inconsistent among some files; can you run `buildifier` from Anzu or Drake on these files once this PR is good?
</blockquote></details>

I ran drake's buildifier on the new file `ament_index.bzl`. I can run it on the rest when this looks ok so that there aren't a lot of unrelated changes while you're reviewing.

___
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 181 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6mr0FB1ioomM9o7OE:-NAM9u3S2WtWoxIkGNua:bks5xtq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L181)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per above, I think this can be simplified by having `RosInterfaces` provider include both ROS and OMG interfaces.
</blockquote></details>

I made the `_defs` rule provide all ROS interfaces and simplified this to just look for RosInterface providers on rules.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6j4on6t-omvESR03_:-NAMMAgdAG07ez2Aa9tr:b-llil5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1140)):*
> Cool, then yeah, let's go ahead and include the ament index info in each then.

Done. I implemented this making `name + _defs` a `filegroup` target that depends both on the target translating the files to IDL and to the target creating the ament index.

> (party_level, name), where party_level is 2 if from ROS2 workspace, 1 if third-party, and then 0 if first-party (proper repository)?

I'm not sure how to get that information. I updated the PR to sort the manifest alphabetically.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1143 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6kGEu40aUTubjCWqV:-NAMA9YWDdLUxG-yqnJ8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1143)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha; I have made comments to this effect regarding `RosInterfaces` and delineating more (with additional bookkeeping) for both OMG and ROS interface files.
</blockquote></details>

Done.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NALtWkd8ZA6PE20aIpU:-NAM9X0KB4sEtq-FD0Ke:b-7dmmzc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8ad75b86af0a158f67bd7dd60fcf2b339a0dc899/bazel_ros2_rules/ros2/rosidl.bzl#L16)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Missing docstring.

What does interfaces entail? Purely OMG IDL interfaces as well, or also ROS interface files as well?
(I assume the former)
</blockquote></details>

In the version you reviewed it was only interfaces written in OMG IDL. It's now any ROS interface regardless of of the description format used.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NALtgrB4mgXOSKMoefb:-NAM9mUg8Ew06fNwZt-f:b-33mb9y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8ad75b86af0a158f67bd7dd60fcf2b339a0dc899/bazel_ros2_rules/ros2/rosidl.bzl#L16)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Name is now confusing; per below, I think this is really `OmgInterfaces`, not `RosInterfaces`.
</blockquote></details>

I combined all ROS interfaces regardless of format into `interfaces` and documented it.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 17 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NALu1vX5PnyyBBeJTZ1:-NAM9ssi7YAs7Oq3MGLI:b-33mb9y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8ad75b86af0a158f67bd7dd60fcf2b339a0dc899/bazel_ros2_rules/ros2/rosidl.bzl#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Perhaps logic can be cleared up here by specifying both interface types:
```
fields = ["omg_interfaces", "ros_interfaces"]
```
</blockquote></details>

I combined all ROS interfaces regardless of format into `interfaces` and documented it.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 233 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NALuMd336roAcV1MaOT:-NAMA4ml7vJVnEUyABLK:b98eez1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8ad75b86af0a158f67bd7dd60fcf2b339a0dc899/bazel_ros2_rules/ros2/rosidl.bzl#L233)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Missing docstring.

Also, be sure to include reference to docstring in `ament_index.bzl`
</blockquote></details>

Added docstrings to the requested places.
___
*[`bazel_ros2_rules/ros2/tools/ament_index.bzl` line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6kl72EAcIwAmLztsn:-NAMAozDC14hWYUSAwHF:bvjgjw9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/tools/ament_index.bzl#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha; I think see the issues you've pointed out here and above:

(a) You define two providers so one rule can define the minimal data, while the aspect can transitively gather the information.
(b) Per your above point, you can use `aspect()` to transtively crawl through `deps`, but you cannot use `rule()` to do so.

In this case, can you comment / rename the variables as something along these lines?
```
# We have two constraints for this setup:
# (a) aspect() can directly analyze dependencies transitively (`data` and
# `deps`), but `rule()` cannot (it relies on rule implementation aggregating
# information to implicitly gather transitive information).
# Therefore we define the two providers below:

# This defines the index path, but does not aggregate them due to possible indirection
# (e.g. a dep in `py_binary` provides `AmentIndex`, but the `rule()` cannot access as mentioned above).
# Defined by `rosidl_generate_ament_index_entry`.
# Consumed by `ament_index_prefixes`.
AmentIndex = ...

# This aggregates transitive ament indexes information using an `aspect()` (as mentioned above).
# Defined by `ament_index_prefixes`.
# Consumed by `do_dload_shim`.
TransitiveAmentIndexes = ...
```
</blockquote></details>

Documented and renamed the plural provider to `AggregatedAmentIndexes`
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 136 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6i4313PsqEQe5Ohx9:-NAML5mp2earqzCQGSIo:b23pqd4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L136)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This test now does more; can you rename this to something like `ros2cli_custom_interface_test`?
</blockquote></details>

I moved the `ros2 interface list` check to a new test `custom_message_list_test`.
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6iFlO0FlXDp [...]

2022-08-26 04:00 UTC, EricCousineau-TRI approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 10 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-:-NANIl__6DmekFxb4wht:b-uwkowd)* status: all files reviewed, 2 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6jb9F3utii1M50nTR:-NANInLq26nfSGRHyhno:b-ldfcuf) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I ran drake's buildifier on the new file `ament_index.bzl`. I can run it on the rest when this looks ok so that there aren't a lot of unrelated changes while you're reviewing.
</blockquote></details>

I think this is good to go!

___
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 1140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6j4on6t-omvESR03_:-NANGyJL3F_BSxq3CcnL:bqkh08o) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/rosidl.bzl#L1140)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

> Cool, then yeah, let's go ahead and include the ament index info in each then.

Done. I implemented this making `name + _defs` a `filegroup` target that depends both on the target translating the files to IDL and to the target creating the ament index.

> (party_level, name), where party_level is 2 if from ROS2 workspace, 1 if third-party, and then 0 if first-party (proper repository)?

I'm not sure how to get that information. I updated the PR to sort the manifest alphabetically.
</blockquote></details>

OK I think that's good for now; it most likely will hurt us if/when there's shadowing, but we can cross that bridge when we get to it.
___
*[`bazel_ros2_rules/ros2/rosidl.bzl` line 16 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NALtWkd8ZA6PE20aIpU:-NANIWH1Cs1U-_yxt2z7:b68r7ml) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8ad75b86af0a158f67bd7dd60fcf2b339a0dc899/bazel_ros2_rules/ros2/rosidl.bzl#L16)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

In the version you reviewed it was only interfaces written in OMG IDL. It's now any ROS interface regardless of of the description format used.
</blockquote></details>

OK Much better!
___
*[`bazel_ros2_rules/ros2/tools/ament_index.bzl` line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6kl72EAcIwAmLztsn:-NANIBiR44Apkkgr5ZRl:bn8cdfm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/bazel_ros2_rules/ros2/tools/ament_index.bzl#L7)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Documented and renamed the plural provider to `AggregatedAmentIndexes`
</blockquote></details>

OK Thanks! I think it may help to still mention the reason why `rule()` can't do this, but we still have this PR as a point of discussion if all else.
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 136 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6i4313PsqEQe5Ohx9:-NANHcCa-nblyKCGOyCT:b5uiqt9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/48451b113da123c9efe9cd50bd021c54cb1f5a01/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L136)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I moved the `ros2 interface list` check to a new test `custom_message_list_test`.
</blockquote></details>

OK Hm... I think it might've been clearer being joined. However, I can file that as a follow-up PR (if I do indeed think it's that important :sweat_smile:)
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 164 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NANHS9j0FnxJdtG0x_B:-NANHS9j0FnxJdtG0x_C:brjcyk6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a9611284d5bc089c27059e52bd9db87ae9d0562/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L164)):*
> ```Starlark
>     ],
>     data = [
>         # This is the main key. You must provide the generated definitions as
> ```

nit Per your above work, any transitive usage should make it work - be it through (in)direct `data`  or indirect `deps`.

Can you relax this comment, or mention something like:
```
This can come through data as is done here, or via any dependency, such as depending on the Python messages types (which allows `ros2 topic echo` to work).
```


<!-- Sent from Reviewable.io -->

2022-08-26 16:57 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NA6jb9F3utii1M50nTR:-NAQ4PnS385AcLmiUCx-:b-2vnmnt) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I think this is good to go!
</blockquote></details>

In 6e7cf3a I ran Drake's buildifier on the files changed by this PR

___
___
*[`ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel` line 164 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/124#-NANHS9j0FnxJdtG0x_B:-NAQ3RTXA3HQwiYbarOS:b36dhih) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a9611284d5bc089c27059e52bd9db87ae9d0562/ros2_example_bazel_installed/ros2_example_apps/BUILD.bazel#L164)):*
> This can come through data as is done here, or via any dependency, such as depending on the Python messages types (which allows `ros2 topic echo` to work).

Relaxed the comment in 97d0b8c


<!-- Sent from Reviewable.io -->

2022-08-26 22:27 UTC, EricCousineau-TRI reviewed
> Reviewed 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2022-08-26 22:27 UTC, EricCousineau-TRI approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2022-08-26 22:28 UTC, merged