Sloretz  gbalke  drake ros viz hydroelastic
RobotLocomotion/drake-ros pull request #133
Opened 2022-09-13 19:08 UTC by sloretz

This brings @gbalke's PR #25 up to date with both the latest changes in Drake and Drake-ROS.

I confirmed the demo runs and collisions are visualized.

```
./install/drake_ros_viz/lib/drake_ros_viz/hydroelastic_collisions
```

```
rviz2 -d src/drake-ros/drake_ros_viz/examples/hydroelastic_collisions/hydroelastic_collisions.rviz
```

![Screenshot from 2022-09-13 12-01-53](https://user-images.githubusercontent.com/4175662/189987912-987ca050-9d16-4945-8639-bace2858b910.png)

scratchpad
 * need to move into `drake_ros_examples`
 * There's a bunch of code for populating LCM messages. What does it do? Can I replace it [with a function in Drake?](https://github.com/RobotLocomotion/drake/blob/c246c0d4480a5b4cc2cdc07cfda9aabe6b25b9a1/multibody/plant/contact_results_to_lcm.cc#L163)
 * Review the code for any other issues
 * Lodepng is vendored - what license is it? Is there value in using a system dependency like libpng instead?

2022-09-16 21:44 UTC, sloretz reviewed
+@ericcousineau-tri for review. I think this is ready for feedback.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-:-NC7FWWgD-172vLZnZaQ:b6245he)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2022-09-16 23:02 UTC, EricCousineau-TRI commented
Which OS / ROS distro should I use for this? Focal+Galactic, Jammy+Humble, or Jammy+Rolling?

2022-09-16 23:06 UTC, sloretz reviewed
I'd recommend Humble and the latest version of Drake. Either Focal with drake-ros-underlay (It's a Humble tarbal)  or Jammy with Humble from debs.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-:-NC7XuqI-WK6pMpd1Hh2:bj93m6s)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2022-09-16 23:58 UTC, EricCousineau-TRI requested changes
> Reviewed 5 of 9 files at r1, 4 of 13 files at r2, 6 of 11 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 13 of 17 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7hNAh0aSm-RbFbjhX:-NC7hNAh0aSm-RbFbjhY:b14rywu) (no related file):*
When running using Drake install in `/opt/drake`, I had to do this:
```
export LD_LIBRARY_PATH=/opt/drake/lib:${LD_LIBRARY_PATH}
```
Otherwise, I got the following error:
```
... libdrake.so: cannot open shared object file: No such file or directory
```

Is that expected?

___
___
*[`drake_ros_examples/package.xml` line 15 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7hLye2OWwb48ioIHT:-NC7hLye2OWwb48ioIHU:b-kimxt4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5e90c688363e0f7876ed137756018006fd66c485/drake_ros_examples/package.xml#L15)):*
> ```XML
>   <depend>drake_ros_core</depend>
>   <depend>drake_ros_viz</depend>
>   <depend>libgflags-dev</depend>
> ```

BTW Thanks!
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 22 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7iTGo2lO9hfE3lSpF:-NC7iTGo2lO9hfE3lSpG:b-6v9o2l) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5e90c688363e0f7876ed137756018006fd66c485/drake_ros_examples/examples/collisions/collisions.cc#L22)):*
> ```cpp
> #include <utility>
> 
> #include "drake/multibody/plant/multibody_plant.h"
> ```

BTW At some point, we should start using better header file sorting order.


<!-- Sent from Reviewable.io -->

2022-09-17 00:15 UTC, EricCousineau-TRI commented
Noted the following on 90a770b (slightly older rev)
- The rate of update between sphere and contact patch is different - why?
- On restart, the spheres don't move?
- Ignore comment about only centroids moving, didn't observe that correctly :facepalm: 

https://user-images.githubusercontent.com/26719449/190832508-ca9a9ab9-1572-4f09-a0e8-ce232c7ebd79.mp4

2022-09-17 00:16 UTC, EricCousineau-TRI requested changes
and woot on running! thanks for the help!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-:-NC7nMXC97EbMzJYFq-s:b-6m1oiz)* status: 13 of 17 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7nFW654HNARBsFriO:-NC7nFW654HNARBsFriP:b-4urj6x) (no related file):*
Why do spheres update at rate different than contact patch?

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7nIml6CoGgYTsGDbx:-NC7nIml6CoGgYTsGDby:b-sn9n4o) (no related file):*
Why does restarting sim only reset contact patch, but not spheres?

___


<!-- Sent from Reviewable.io -->

2022-09-17 00:25 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7hNAh0aSm-RbFbjhX:-NC7pG7s-nYTY715haEk:b-tsmcc0) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

When running using Drake install in `/opt/drake`, I had to do this:
```
export LD_LIBRARY_PATH=/opt/drake/lib:${LD_LIBRARY_PATH}
```
Otherwise, I got the following error:
```
... libdrake.so: cannot open shared object file: No such file or directory
```

Is that expected?
</blockquote></details>

It sounds like this might be related to the first bullet point in https://github.com/RobotLocomotion/drake-ros/pull/135#issue-1375254180 

___


<!-- Sent from Reviewable.io -->

2022-09-17 01:57 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7hNAh0aSm-RbFbjhX:-NC88yXR0_XfWaa__bc7:bb4vnxw) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

It sounds like this might be related to the first bullet point in https://github.com/RobotLocomotion/drake-ros/pull/135#issue-1375254180 
</blockquote></details>

Ah yeah; was fuzzily remembering something along those lines :facepalm: 

Is there any way we can add this to `LD_LIBRARY_PATH` via `drake_ros_core`?

I remember in catkin you could generate / install `*.sh` files to be incorporated into the `setup.sh`
Yeah, it was `catkin_add_env_hooks`:
https://github.com/eacousineau/amber_developer_stack/blob/068acd416b2929ffd4fa561cc100be3eef90ad44/common_scripts/CMakeLists.txt#L7

I think we could use the drake find results, configure a file, and then have that put Drake on LD_LIBRARY_PATH for CMake env?

\cc @cottsay

___


<!-- Sent from Reviewable.io -->

2022-09-17 01:58 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7hNAh0aSm-RbFbjhX:-NC89fo7BJUS9TprFsop:br6uy2m) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah yeah; was fuzzily remembering something along those lines :facepalm: 

Is there any way we can add this to `LD_LIBRARY_PATH` via `drake_ros_core`?

I remember in catkin you could generate / install `*.sh` files to be incorporated into the `setup.sh`
Yeah, it was `catkin_add_env_hooks`:
https://github.com/eacousineau/amber_developer_stack/blob/068acd416b2929ffd4fa561cc100be3eef90ad44/common_scripts/CMakeLists.txt#L7

I think we could use the drake find results, configure a file, and then have that put Drake on LD_LIBRARY_PATH for CMake env?

\cc @cottsay
</blockquote></details>

(the test in this case would be to then remove the `LD_LIBRARY_PATH` changes that were added into the GitHub workflows)

___


<!-- Sent from Reviewable.io -->

2022-09-17 02:00 UTC, cottsay commented
> I think we could use the drake find results, configure a file, and then have that put Drake on LD_LIBRARY_PATH for CMake env?

We should be able to make an ament hook for this.

2022-09-17 02:09 UTC, EricCousineau-TRI reviewed
sweet! will make a quick issue and assign it to ya

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-:-NC8C9yf97B-66UUXg4f:b-am75d3)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @sloretz)



<!-- Sent from Reviewable.io -->

2022-09-17 02:10 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7hNAh0aSm-RbFbjhX:-NC8C_pyBufCvQzfSZsZ:b28i47) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(the test in this case would be to then remove the `LD_LIBRARY_PATH` changes that were added into the GitHub workflows)
</blockquote></details>

OK Deferred to #139.

___


<!-- Sent from Reviewable.io -->

2022-09-20 22:11 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 12 of 19 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7nFW654HNARBsFriO:-NCLtU944stbhtxiP0gk:b9s9mhl) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Why do spheres update at rate different than contact patch?
</blockquote></details>

The trigger types were different between the `ContactMarkersSystem` and the `SceneMarkersSystem`. The former was publishing at an unlimited rate. I was seeing contacts markers published at 200-300Hz, while the visual markers were published at around 6Hz. I updated how parameters are passed to `ConnectContactResultsToRviz` and make the default trigger types `Forced` and `Periodic` with a default rate of 32Hz.

The system seems to run slower than realtime on my machine while the two balls are touching. I see 18Hz now for both until the top ball rolls off the compliant ball.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7nIml6CoGgYTsGDbx:-NCRfnrBE04CQ-I0lyYq:b-yehxc2) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Why does restarting sim only reset contact patch, but not spheres?
</blockquote></details>

This appears to be a mix of time, transforms, and "frame_locked" markers.

First the fixed frame in the RViz config is "world", meaning everything we display has to be transformed to that frame. All of the markers are set to "frame locked", which means they are expected to move with the frame they're declared in. When a marker is "frame locked" RViz will recompute the pose of the marker in the fixed frame [using the "latest" transform](https://github.com/ros2/rviz/blob/efa6b89b16ce6581d9d749da4fa70d1b17566670/rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/marker_base.cpp#L107-L109). "Latest" here means [timestamp with the highest value](https://github.com/ros2/geometry2/blob/d6559f955c3f9de3360d35e10373d7c44185db4a/tf2/src/cache.cpp#L238).

The contact patch and points are already declared to be in "world" frame, so no transform is needed. The spheres are declared to be in [their own tf frames](https://github.com/RobotLocomotion/drake-ros/blob/67151b88dfeb357ba8297549e9a4a04a8cb5b40d/drake_ros_viz/src/scene_markers_system.cc#L78-L79), so their transform will be calculated from the "latest" TF data.

The [marker systems get the current time from `Drake`](https://github.com/RobotLocomotion/drake-ros/blob/67151b88dfeb357ba8297549e9a4a04a8cb5b40d/drake_ros_viz/src/scene_markers_system.cc#L318-L319). Since this is a simulated system, Drake [sets time to zero](https://github.com/RobotLocomotion/drake/blob/35e6290f1b126a7bd19f406a2ac674745e12360c/systems/framework/context.h#L861) every time the simulation is restarted. RViz would normally [reset itself when time jumps backwards](https://github.com/ros2/rviz/blob/4e976dc444e7e59ec9cdef30f1f04e0beafcafc8/rviz_common/src/rviz_common/visualization_manager.cpp#L462-L463), but it doesn't know simulated time is being used. Instead it transforms the spheres using the tf data with the latest timestamp, and the latest time stamp comes from the longest previous run of the simulation. The spheres are frozen in place until time advances farther than that, at which point they move as expected.

There are a few ways we could fix this. One option would be to make the Drake-ROS systems ignore Drake's time and always use the system time. New runs would always have greater timestamp values as long as the system clock didn't jump backwards. A problem with this option occurs when a simulation is running at slower than real time. Say one uses `ros2 bag` to record the simulation, and they want to play it back at "real time". That becomes impossible because the timestamps were set to their slower-than-realtime values.

Another option would be to make a `ROSClockSystem` that published Drake's time on a `/clock` topic so RViz could use it. This seems like the most "correct" option, but it requires remembering to launch RViz with the "use_sim_time" option. We had this before [in a past prototype](https://github.com/sloretz/drake_ros2_demos/blob/3a6bd2cf526379999293ec3b517d3a6e22d142ba/drake_ros/drake_ros/systems/simulator_clock.py), but it looks like we haven't added it drake_ros_core here.

A third option might be to specify the initial time to be something other than 0. That would make new runs have newer time stamps than old runs. Unfortunately this doesn't seem to work in Drake at the moment.

I tried setting the time before the simulator's `Initialize()` call in the `collisions` example.

```
simulator_context.SetTime(time(nullptr));
```

The first step fails with this error.

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error control wants to select step smaller than minimum allowed (1.66371e-05)
[ros2run]: Aborted
```

___
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 22 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7iTGo2lO9hfE3lSpF:-NCRwPG56JmTe21Jk5pW:bwjse2q) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/88b51510b59d552ae3130a7bc9103b47310fa29a/drake_ros_examples/examples/collisions/collisions.cc#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW At some point, we should start using better header file sorting order.
</blockquote></details>

I think we copied this order from drake

https://github.com/RobotLocomotion/drake-ros/blob/67151b88dfeb357ba8297549e9a4a04a8cb5b40d/drake_ros_viz/.clang-format#L21

https://github.com/RobotLocomotion/drake/blob/35e6290f1b126a7bd19f406a2ac674745e12360c/.clang-format#L20


<!-- Sent from Reviewable.io -->

2022-09-22 12:03 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 12 of 19 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7nIml6CoGgYTsGDbx:-NC_3uiN9M459RD1ypdE:bc9r51t) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

This appears to be a mix of time, transforms, and "frame_locked" markers.

First the fixed frame in the RViz config is "world", meaning everything we display has to be transformed to that frame. All of the markers are set to "frame locked", which means they are expected to move with the frame they're declared in. When a marker is "frame locked" RViz will recompute the pose of the marker in the fixed frame [using the "latest" transform](https://github.com/ros2/rviz/blob/efa6b89b16ce6581d9d749da4fa70d1b17566670/rviz_default_plugins/src/rviz_default_plugins/displays/marker/markers/marker_base.cpp#L107-L109). "Latest" here means [timestamp with the highest value](https://github.com/ros2/geometry2/blob/d6559f955c3f9de3360d35e10373d7c44185db4a/tf2/src/cache.cpp#L238).

The contact patch and points are already declared to be in "world" frame, so no transform is needed. The spheres are declared to be in [their own tf frames](https://github.com/RobotLocomotion/drake-ros/blob/67151b88dfeb357ba8297549e9a4a04a8cb5b40d/drake_ros_viz/src/scene_markers_system.cc#L78-L79), so their transform will be calculated from the "latest" TF data.

The [marker systems get the current time from `Drake`](https://github.com/RobotLocomotion/drake-ros/blob/67151b88dfeb357ba8297549e9a4a04a8cb5b40d/drake_ros_viz/src/scene_markers_system.cc#L318-L319). Since this is a simulated system, Drake [sets time to zero](https://github.com/RobotLocomotion/drake/blob/35e6290f1b126a7bd19f406a2ac674745e12360c/systems/framework/context.h#L861) every time the simulation is restarted. RViz would normally [reset itself when time jumps backwards](https://github.com/ros2/rviz/blob/4e976dc444e7e59ec9cdef30f1f04e0beafcafc8/rviz_common/src/rviz_common/visualization_manager.cpp#L462-L463), but it doesn't know simulated time is being used. Instead it transforms the spheres using the tf data with the latest timestamp, and the latest time stamp comes from the longest previous run of the simulation. The spheres are frozen in place until time advances farther than that, at which point they move as expected.

There are a few ways we could fix this. One option would be to make the Drake-ROS systems ignore Drake's time and always use the system time. New runs would always have greater timestamp values as long as the system clock didn't jump backwards. A problem with this option occurs when a simulation is running at slower than real time. Say one uses `ros2 bag` to record the simulation, and they want to play it back at "real time". That becomes impossible because the timestamps were set to their slower-than-realtime values.

Another option would be to make a `ROSClockSystem` that published Drake's time on a `/clock` topic so RViz could use it. This seems like the most "correct" option, but it requires remembering to launch RViz with the "use_sim_time" option. We had this before [in a past prototype](https://github.com/sloretz/drake_ros2_demos/blob/3a6bd2cf526379999293ec3b517d3a6e22d142ba/drake_ros/drake_ros/systems/simulator_clock.py), but it looks like we haven't added it drake_ros_core here.

A third option might be to specify the initial time to be something other than 0. That would make new runs have newer time stamps than old runs. Unfortunately this doesn't seem to work in Drake at the moment.

I tried setting the time before the simulator's `Initialize()` call in the `collisions` example.

```
simulator_context.SetTime(time(nullptr));
```

The first step fails with this error.

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error control wants to select step smaller than minimum allowed (1.66371e-05)
[ros2run]: Aborted
```
</blockquote></details>

Ah, this sounds like a systemic issue that may require some more thinking outside scope of this PR.

Can you make an issue for this, perhaps copying+pasting your above investigation + pointer to this PR + perhaps subset of video that shows restart behavior?

___


<!-- Sent from Reviewable.io -->

2022-09-22 12:11 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 12 of 19 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros_viz/src/contact_markers_system.cc` line 237 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_4fOI3uNYDD8szjjU:-NC_4fOI3uNYDD8szjjV:bl7sn34) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/42db2a13cb264254cfb79a1b97fa50af801d5aa1/drake_ros_viz/src/contact_markers_system.cc#L237)):*
> ```cpp
> 
>     const auto& color = impl_->params.default_color;
>     ball_msg.color.r = color.r();
> ```

nit Can you move color conversion to separate function?

We can then eventually incorporate this into public converters like @gbiggs's PR.
___
*[`drake_ros_viz/src/contact_markers_system.cc` line 272 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_4vci-Tbmw0tLZoP2:-NC_4vci-Tbmw0tLZoP3:b-a08wop) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/42db2a13cb264254cfb79a1b97fa50af801d5aa1/drake_ros_viz/src/contact_markers_system.cc#L272)):*
> ```cpp
> 
>     const auto& nhat_BA_W = contact_info.point_pair().nhat_BA_W;
>     // C = Center of contact, l = one of the end points of the normal
> ```

I'm having trouble figuring out what this physically means, as well as how it relates to below math.

Concretely:
- I can't tell if `l` is qualifying `C` or a distinct entitty
- I don't know what "end point of normal" means (physically)
___
*[`drake_ros_viz/src/contact_markers_system.cc` line 275 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_5Eii-JVp1LCFjpmE:-NC_5Eii-JVp1LCFjpmF:bul3pqc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/42db2a13cb264254cfb79a1b97fa50af801d5aa1/drake_ros_viz/src/contact_markers_system.cc#L275)):*
> ```cpp
>     const auto p_Cl_W = kPointNormalLength / 2.0 * nhat_BA_W;
> 
>     normal_msg.points.resize(2);
> ```

nit `resize(2)` + `front(), back()` feels too "cute".

Can you instead make a free function for converting (w/ TODO to leverage #141), just do `.push_back(Vector3dToRosPoint(p_CStart_W
___
*[`drake_ros_viz/src/contact_markers_system.cc` line 276 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_4nIqE4WUrGllkyE-:-NC_4nIqE4WUrGllkyE0:b-d1nyei) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/42db2a13cb264254cfb79a1b97fa50af801d5aa1/drake_ros_viz/src/contact_markers_system.cc#L276)):*
> ```cpp
> 
>     normal_msg.points.resize(2);
>     normal_msg.points.front().x = p_Cl_W.x() + contact_info.contact_point().x();
> ```

We should not mix the role of conversion and math transform.

Can you make a separate var for math, e.g. `, then relegate this to purely conversion?
My guess is something like:
```
p_WC = contact_info.contact_point()
p_WStart = p_WC + p_CL_W
p_WEnd = p_WC - p_CL_W
```


<!-- Sent from Reviewable.io -->

2022-09-22 13:00 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 12 of 19 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7nFW654HNARBsFriO:-NC_GsN4AKjioINyIyD2:bmjtwlj) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

The trigger types were different between the `ContactMarkersSystem` and the `SceneMarkersSystem`. The former was publishing at an unlimited rate. I was seeing contacts markers published at 200-300Hz, while the visual markers were published at around 6Hz. I updated how parameters are passed to `ConnectContactResultsToRviz` and make the default trigger types `Forced` and `Periodic` with a default rate of 32Hz.

The system seems to run slower than realtime on my machine while the two balls are touching. I see 18Hz now for both until the top ball rolls off the compliant ball.
</blockquote></details>

Cool, same rate now, excellent!

Regarding update rate itself, yeah, that does seem a bit slow. Making separate discussion item, resolving this one!

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_H1OY65fCBtHPc5-U:-NC_H1OZC7k4sc6WWIn3:b5578k9) (no related file):*
> The system seems to run slower than realtime on my machine while the two balls are touching. I see 18Hz now for both until the top ball rolls off the compliant ball.

It'd be nice to know if that's intrinsic to our simulation, or the converters.
Can you add a command-line options to enable/disable both DrakeVisualizer and the ROS-specific visualization?

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_HBki2HQ_4Y4uzQSU:-NC_HBki2HQ_4Y4uzQSV:bf45vdt) (no related file):*
> I see 18Hz now for both until the top ball rolls off the compliant ball.

Can I ask how you observed this? `ros2 topic hz`?

___


<!-- Sent from Reviewable.io -->

2022-09-22 18:02 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 12 of 19 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_HBki2HQ_4Y4uzQSU:-NCaFmXECDdI2guEOgKW:by70p30) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> I see 18Hz now for both until the top ball rolls off the compliant ball.

Can I ask how you observed this? `ros2 topic hz`?
</blockquote></details>

Correct. I compared `ros2 topic hz /contacts` and `ros2 topic hz /scene_markers/visual`

___
___
*[`drake_ros_viz/src/contact_markers_system.cc` line 272 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_4vci-Tbmw0tLZoP2:-NCaJ2LZ8JVhRq6tRWVS:b-mtnzwf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/42db2a13cb264254cfb79a1b97fa50af801d5aa1/drake_ros_viz/src/contact_markers_system.cc#L272)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm having trouble figuring out what this physically means, as well as how it relates to below math.

Concretely:
- I can't tell if `l` is qualifying `C` or a distinct entitty
- I don't know what "end point of normal" means (physically)
</blockquote></details>

I'm not 100% sure `normal` is the right thing to call it because the visualization goes both directions from the contact point rather than one direction from a surface. It's visualizing `nhat_BA_W` and `nhat_AB_W` as a line segment with length `kPointNormalLength` centered at point `C` (I think drake calls this `p_WC`). `l` is one of the points of that line segment. I see you're using `p_CL_W` below.


<!-- Sent from Reviewable.io -->

2022-09-22 22:26 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 12 of 20 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_H1OY65fCBtHPc5-U:-NCbI5jm5D8wqVma1mcL:bhwlmlx) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> The system seems to run slower than realtime on my machine while the two balls are touching. I see 18Hz now for both until the top ball rolls off the compliant ball.

It'd be nice to know if that's intrinsic to our simulation, or the converters.
Can you add a command-line options to enable/disable both DrakeVisualizer and the ROS-specific visualization?
</blockquote></details>

It looks like it's the simulation. I added a command line option `ros2 run drake_ros_examples collisions --use_drake_visualizer` that uses DrakeVisualizer instead of RViz. Drake visualizer reports a real time factor of 0.55ish which is very close to to 18 out of 32 Hz I see with Rviz.

___


<!-- Sent from Reviewable.io -->

2022-09-22 22:28 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 12 of 20 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_H1OY65fCBtHPc5-U:-NCbJ7uP8a3vYYGvlOB3:b-2jldbq) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

It looks like it's the simulation. I added a command line option `ros2 run drake_ros_examples collisions --use_drake_visualizer` that uses DrakeVisualizer instead of RViz. Drake visualizer reports a real time factor of 0.55ish which is very close to to 18 out of 32 Hz I see with Rviz.
</blockquote></details>

Note that DrakeVisualizer only works on Focal. It seems to have been removed upstream in Jammy.

___
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 22 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_4P0q2ibqoA6YuY-R:-NCbJENGDZs-CaoaECYB:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/42db2a13cb264254cfb79a1b97fa50af801d5aa1/drake_ros_examples/examples/collisions/collisions.cc#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Inconsistent usage of quotes vs. `<>` includes.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-22 23:36 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 12 of 20 files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC7nIml6CoGgYTsGDbx:-NCbYnow11Ymo-XFGbX2:b54z10q) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(at which point, we can resolve this discussion item and move this PR forward)
</blockquote></details>

Opened issue with video in https://github.com/RobotLocomotion/drake-ros/issues/144

___
___
*[`drake_ros_viz/src/contact_markers_system.cc` line 237 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_4fOI3uNYDD8szjjU:-NCbOO3J4TZwH6oFAk6h:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/42db2a13cb264254cfb79a1b97fa50af801d5aa1/drake_ros_viz/src/contact_markers_system.cc#L237)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you move color conversion to separate function?

We can then eventually incorporate this into public converters like @gbiggs's PR.
</blockquote></details>

Done.
___
*[`drake_ros_viz/src/contact_markers_system.cc` line 272 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_4vci-Tbmw0tLZoP2:-NCbUAjjBzxfkAokY1IZ:bs8u6qe) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/42db2a13cb264254cfb79a1b97fa50af801d5aa1/drake_ros_viz/src/contact_markers_system.cc#L272)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I'm not 100% sure `normal` is the right thing to call it because the visualization goes both directions from the contact point rather than one direction from a surface. It's visualizing `nhat_BA_W` and `nhat_AB_W` as a line segment with length `kPointNormalLength` centered at point `C` (I think drake calls this `p_WC`). `l` is one of the points of that line segment. I see you're using `p_CL_W` below.
</blockquote></details>

Updated comments and code.
___
*[`drake_ros_viz/src/contact_markers_system.cc` line 276 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_4nIqE4WUrGllkyE-:-NCbUA9j3TISS4z2dBuK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/42db2a13cb264254cfb79a1b97fa50af801d5aa1/drake_ros_viz/src/contact_markers_system.cc#L276)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

We should not mix the role of conversion and math transform.

Can you make a separate var for math, e.g. `, then relegate this to purely conversion?
My guess is something like:
```
p_WC = contact_info.contact_point()
p_WStart = p_WC + p_CL_W
p_WEnd = p_WC - p_CL_W
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-11 23:43 UTC, EricCousineau-TRI requested changes
> Reviewed 1 of 5 files at r5, 2 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 15 of 20 files reviewed, 5 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_H1OY65fCBtHPc5-U:-NCbJ_FECqKzzfbvM1Qk:b9yyd64) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Note that DrakeVisualizer only works on Focal. It seems to have been removed upstream in Jammy.
</blockquote></details>

Ah, sorry, forgot to mention: While `drake-visualizer` itself is removed, the `DrakeVisualizer` system (transcribing visualization to LCM messages) is still there, and you can then visualize using `meldis`:
https://drake.mit.edu/pydrake/pydrake.visualization.meldis.html

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_HBki2HQ_4Y4uzQSU:-NE8Ps_LAgFDTQJ2OWcC:b-gy8kbz) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Correct. I compared `ros2 topic hz /contacts` and `ros2 topic hz /scene_markers/visual`
</blockquote></details>

OK Thanks! I've also filed #142

___
___
*[`drake_ros_viz/src/contact_markers_system.cc` line 258 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NE8QTQH0puZS1Xc8FEt:-NE8QTQH0puZS1Xc8FEu:b-aa66qv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0515a4e95c6d9db14f64d08d7fe3143e3c427faf/drake_ros_viz/src/contact_markers_system.cc#L258)):*
> ```cpp
>     ball_msg.scale.z = kPointBallDiameter;
> 
>     ball_msg.pose.position.x = contact_info.contact_point()[0];
> ```

nit Can you add TODO to use @gbigg's conversion PR?


<!-- Sent from Reviewable.io -->

2022-10-11 23:43 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 15 of 20 files reviewed, 5 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros_viz/src/contact_markers_system.cc` line 272 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_4vci-Tbmw0tLZoP2:-NE8Qawx2DYyBT45Wnml:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/42db2a13cb264254cfb79a1b97fa50af801d5aa1/drake_ros_viz/src/contact_markers_system.cc#L272)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Updated comments and code.
</blockquote></details>

OK Thanks!


<!-- Sent from Reviewable.io -->

2023-01-03 18:46 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 0 of 27 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_ros_viz/src/contact_markers_system.cc` line 258 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NE8QTQH0puZS1Xc8FEt:-NKswyPU8PYEvJSk_7wM:b-h4mhhi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0515a4e95c6d9db14f64d08d7fe3143e3c427faf/drake_ros_viz/src/contact_markers_system.cc#L258)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you add TODO to use @gbigg's conversion PR?
</blockquote></details>

It now uses the conversions.


<!-- Sent from Reviewable.io -->

2023-01-09 14:59 UTC, EricCousineau-TRI reviewed
> Reviewed 7 of 27 files at r9.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 7 of 27 files reviewed, 4 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros_viz/BUILD.bazel` line 34 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLM0a0U9PIem-mo-K2s:-NLM0a0V-jJfAFkYxcCu:b-yibpev) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_viz/BUILD.bazel#L34)):*
> ```Starlark
>             "src/*.cc",
>             "src/*.h",
>             "src/lodepng/lodepng.cpp",
> ```

nit I don't love merging `lodepng` source files into this target, as it doesn't show great separation.

Can you  make `lodepng` a separate target?
___
*[`drake_ros_viz/BUILD.bazel` line 34 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLM1JCB8Ow6VSkrbDDz:-NLM1JCB8Ow6VSkrbDE-:b-3m91pl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_viz/BUILD.bazel#L34)):*
> ```Starlark
>             "src/*.cc",
>             "src/*.h",
>             "src/lodepng/lodepng.cpp",
> ```

FYI At some point, we may want to consider: https://github.com/nothings/stb
___
*[`drake_ros_viz/src/contact_markers_system.cc` line 52 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLM1_Fy8jW0bKGi1jbn:-NLM1_Fz7752SAlcC88S:boaysxv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_viz/src/contact_markers_system.cc#L52)):*
> ```cpp
> 
> namespace {
> // Copied from:
> ```

nit These seem like they'd eventually be great public API for conversions.

Can you add TODO to that effect?


<!-- Sent from Reviewable.io -->

2023-01-10 00:56 UTC, EricCousineau-TRI requested changes
> Reviewed 20 of 27 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: all files reviewed, 15 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_H1OY65fCBtHPc5-U:-NLO5kg30eEpP4-MxgSr:b-com33v) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, sorry, forgot to mention: While `drake-visualizer` itself is removed, the `DrakeVisualizer` system (transcribing visualization to LCM messages) is still there, and you can then visualize using `meldis`:
https://drake.mit.edu/pydrake/pydrake.visualization.meldis.html
</blockquote></details>

Per VC, should either use `meldis` (if it supports transcribing from `drake-visualizer` LCM to MeshCat) or `MeshcatVisualizer`. Made comment below to that effect.

Leaving this discussion open to ensure we don't have a performance regression or timing mismatch as indicated above (18Hz).

___
___
*[`drake_ros_examples/examples/collisions/README.md` line 1 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO8dsuDD_6OOBpU0Td:-NLO8dsuDD_6OOBpU0Te:b-uvoif2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/README.md#L1)):*
> ```Markdown
> # Collisions
> ```

I don't love the name `collisions`, as it's not very indicative of what it's showcasing (hydroelastic and visualization).

Can you rename this to folder to `hydroelastic` or `visualization` or something else?
___
*[`drake_ros_viz/include/drake_ros_viz/contact_markers_system.h` line 43 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO8x6P1_2vOLUYGAMJ:-NLO8x6P1_2vOLUYGAMK:bhahc9n) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_viz/include/drake_ros_viz/contact_markers_system.h#L43)):*
> ```objc
> /// System for visualizing contacts as a ROS markers array.
> ///
> /// This system outputs a `visualization_msgs/msg/MarkerArray` populated with
> ```

nit We should use Russ's Doxygen setup for systems, e.g.
https://github.com/RobotLocomotion/drake/blob/v1.11.0/systems/controllers/joint_stiffness_controller.h#L44-L51
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 1 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO62CP8OTK3YKgSlMQ:-NLO62CP8OTK3YKgSlMR:b-1k4c3i) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L1)):*
> ```cpp
> // Copyright 2021 Open Source Robotics Foundation, Inc.
> ```

Per VC and email chain, can you strip out these copyright notices?
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 90 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO6LvkCwCs-PYJTBOT:-NLO6LvkCwCs-PYJTBOU:bm97ye7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L90)):*
> ```cpp
>             "Use drake-visualizer instead of RViz.");
> 
> int do_main() {
> ```

Per https://drake.mit.edu/styleguide/cppguide.html#Namespaces, we should avoid writing code in global namespace level when possible.

Can you place main definition in a namespace? For example, see:
https://github.com/RobotLocomotion/drake/blob/da02da36edbb053cad8e039427ca006e63a4f3c3/examples/acrobot/run_plant_w_lcm.cc#L39-L44
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 103 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO7b4FAopN5LyetJPw:-NLO7b4G7lnisOEo7Gwj:bamabvn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L103)):*
> ```cpp
>   const double friction_coefficient = 0.3;
> 
>   const CoulombFriction<double> surface_friction(
> ```

While constructing a scene programmatically is a great exercise and good for decoupling in Drake itself, I'm not sure if it's the best route for showcasing `drake-ros` usage to users.

Can you have this leverage a SDFormat file to create the scene? (similar to comment on UFO example)
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 109 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO6r14EdfdvnQXemdM:-NLO6r14EdfdvnQXemdN:b-pb1s7d) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L109)):*
> ```cpp
>   // Hydroelastic Ball and Plane example taken from
>   // https://github.com/RobotLocomotion/drake/blob/
>   // 940b63716161c7206d494378701be11852c53d75/
> ```

nit While commit is precise, it's unclear why we don't use a version tag.

Could you change this to `v1.11.0`?
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 153 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO7C5FAlUSIFSOspzA:-NLO7C5FAlUSIFSOspzB:b-axo34w) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L153)):*
> ```cpp
>   const RigidTransformd X_BS = RigidTransformd::Identity();
>   // Set material properties for hydroelastics.
>   {
> ```

nit (Readability) A bit hard to parse these separate blocks; took me a minute to figure out it was for compliant vs. rigid.

Can you remove scoping, and just qualify `ball_props` to `compliant_ball_props` and `rigid_ball_props`, and add a one-liner? e.g.
```
// Set complaint hydroelastic materials.
ProximityProperties compliant_ball_props;

// Set rigid hydroelastic materials.
ProximityProperties compliant_ball_props;
```

Alternative is to construct using SDFormat file.
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 178 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO7XgZ0ctLUt8vugEO:-NLO7Xg_0_0tVHNoW62W:b-izqghn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L178)):*
> ```cpp
> 
>   // Gravity acting in the -z direction.
>   plant.mutable_gravity_field().set_gravity_vector(-g * Vector3d::UnitZ());
> ```

I'm not sure if I understand why this is here.

Can we remove this?
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 185 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO7zwVCfGNlFrDO3Qj:-NLO7zwVCfGNlFrDO3Qk:b-40ez1e) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L185)):*
> ```cpp
>   if (FLAGS_use_drake_visualizer) {
>     // Visualize with drake-visualizer
>     drake::geometry::DrakeVisualizerd::AddToBuilder(&builder, scene_graph);
> ```

Per above, should either ensure `DrakeVisualizer` + `meldis` can visualize this, or use `MeshcatVisualizer` (and update flag name).
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 216 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO87R4Dv9WL57mFa1D:-NLO87R58Owq2jMo2UKy:btjjlfc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L216)):*
> ```cpp
>   // Set the initial poses for the balls.
>   {
>     RotationMatrixd R_WB(RollPitchYawd(M_PI / 180.0 * Vector3d(0.0, 0.0, 0.0)));
> ```

nit (Readability) Same as above.

Consider renaming monograms to something like `C` for Compliant and `R` for Rigid, e.g. `X_WC`, `X_WR`
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 217 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO8MpC-nMFXxnxJ66d:-NLO8MpC-nMFXxnxJ66e:b-yq24 [...]

2023-01-10 00:56 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> pending open discussion items, thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-:-NLOAPnVDUgavx3Grpyk:b-rd0bsy)* status: all files reviewed, 15 unresolved discussions (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2023-03-10 02:12 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 8 of 42 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_H1OY65fCBtHPc5-U:-NQ8C_6P2rq-R4TCwjjk:bnwvfp5) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per VC, should either use `meldis` (if it supports transcribing from `drake-visualizer` LCM to MeshCat) or `MeshcatVisualizer`. Made comment below to that effect.

Leaving this discussion open to ensure we don't have a performance regression or timing mismatch as indicated above (18Hz).
</blockquote></details>

Done. Now uses `meshcat` with the `--use_meshcat` option.

___
___
*[`drake_ros_examples/examples/collisions/README.md` line 1 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO8dsuDD_6OOBpU0Td:-NQ2lm6qCpbr54Zgt1nK:b-czxfmn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/README.md#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I don't love the name `collisions`, as it's not very indicative of what it's showcasing (hydroelastic and visualization).

Can you rename this to folder to `hydroelastic` or `visualization` or something else?
</blockquote></details>

Done. Renamed to `hydroelastic`.
___
*[`drake_ros_viz/BUILD.bazel` line 34 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLM0a0U9PIem-mo-K2s:-NQ2YMPY-a1GCHDAaip3:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_viz/BUILD.bazel#L34)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I don't love merging `lodepng` source files into this target, as it doesn't show great separation.

Can you  make `lodepng` a separate target?
</blockquote></details>

Done.
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 1 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO62CP8OTK3YKgSlMQ:-NQ2m7e65soDOD4SwzD4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per VC and email chain, can you strip out these copyright notices?
</blockquote></details>

Done.
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 90 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO6LvkCwCs-PYJTBOT:-NQ870UY5mi443zThaIt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L90)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per https://drake.mit.edu/styleguide/cppguide.html#Namespaces, we should avoid writing code in global namespace level when possible.

Can you place main definition in a namespace? For example, see:
https://github.com/RobotLocomotion/drake/blob/da02da36edbb053cad8e039427ca006e63a4f3c3/examples/acrobot/run_plant_w_lcm.cc#L39-L44
</blockquote></details>

Done.
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 103 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO7b4FAopN5LyetJPw:-NQ2mQTaDm7oXkbX7aJT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L103)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

While constructing a scene programmatically is a great exercise and good for decoupling in Drake itself, I'm not sure if it's the best route for showcasing `drake-ros` usage to users.

Can you have this leverage a SDFormat file to create the scene? (similar to comment on UFO example)
</blockquote></details>

Done.
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 109 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO6r14EdfdvnQXemdM:-NQ2_SAU3b0KndDwTVDK:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L109)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit While commit is precise, it's unclear why we don't use a version tag.

Could you change this to `v1.11.0`?
</blockquote></details>

Done.
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 153 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO7C5FAlUSIFSOspzA:-NQ7llaA37RA9n7pU2kL:b9li1pm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L153)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (Readability) A bit hard to parse these separate blocks; took me a minute to figure out it was for compliant vs. rigid.

Can you remove scoping, and just qualify `ball_props` to `compliant_ball_props` and `rigid_ball_props`, and add a one-liner? e.g.
```
// Set complaint hydroelastic materials.
ProximityProperties compliant_ball_props;

// Set rigid hydroelastic materials.
ProximityProperties compliant_ball_props;
```

Alternative is to construct using SDFormat file.
</blockquote></details>

Done. Replaced with sdf file
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 178 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO7XgZ0ctLUt8vugEO:-NQ7lnXh1-KGVMfKMjgr:b9li1pm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L178)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm not sure if I understand why this is here.

Can we remove this?
</blockquote></details>

Done. Replaced with sdf file
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 185 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO7zwVCfGNlFrDO3Qj:-NQ8CzEK0TobA7kA5S4o:b-ecdc4y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L185)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per above, should either ensure `DrakeVisualizer` + `meldis` can visualize this, or use `MeshcatVisualizer` (and update flag name).
</blockquote></details>

Done. The flag is now called `--use_meshcat`.
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 216 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO87R4Dv9WL57mFa1D:-NQ7lc5t9vNWjDIZHNBO:b-3isy5y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/examples/collisions/collisions.cc#L216)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (Readability) Same as above.

Consider renaming monograms to something like `C` for Compliant and `R` for Rigid, e.g. `X_WC`, `X_WR`
</blockquote></details>

Done. replaced with sdf file
___
*[`drake_ros_examples/examples/collisions/collisions.cc` line 217 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NLO8MpC-nMFXxnxJ66d:-NQ7lftrA4yGTJShJnKO:b9li1pm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/71d33cbf1892354fce177a241469bd3702bb4937/drake_ros_examples/exampl [...]

2023-03-10 14:22 UTC, EricCousineau-TRI requested changes
Added some blocking discussion points regarding vendoring and path munging

Sorry for the long-of-toothness, but I think we turn this from "great example" to "awesome example" with some (hopefully not too burdensome) improvements.

WDYT?

> Reviewed 33 of 34 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-:-NQAos_A0MVLZuAKFrzV:by5mzg8)* status: all files reviewed, 17 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NC_H1OY65fCBtHPc5-U:-NQAsf122U83dgOqBcIj:b-w196av) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Done. Now uses `meshcat` with the `--use_meshcat` option.
</blockquote></details>

OK Thanks!

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAoWpO3Ntj_lyhYG4t:-NQAoWpO3Ntj_lyhYG4u:b-cj56zu) (no related file):*
Upon reinspection, I think we can just use `vtkPNGReader`, e.g.:

https://github.com/RobotLocomotion/drake/blob/v1.13.0/geometry/render_gltf_client/internal_render_client.cc#L89-L100

Rather than vendoring `lodepng` and spending some our creativity tokens there, can we just use VTK?
I think it could collapse 10k LOC of vendored code down to just a view changes to CMake / Bazel, and perhaps slightly more compact loading?

Since we're on Jammy or greater, Drake can (and does?) depends on the system-installed version:
https://github.com/RobotLocomotion/drake/pull/18340

___
___
*[`drake_ros_examples/examples/hydroelastic/BUILD.bazel` line 15 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQApvGMDNkF45LuThzU:-NQApvGMDNkF45LuThzV:boh9lf0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/BUILD.bazel#L15)):*
> ```Starlark
>     ],
>     local_defines = ["BAZEL"],
>     visibility = ["//visibility:public"],
> ```

Why public?

Can we remove visibility hoisting here?

I understand that for CMake / ament, we install the examples package, but I see that as "critical to run anything useful".
However, without a concrete story for usage in Bazel, I'd prefer we avoid over-exposing ourselves.
___
*[`drake_ros_examples/examples/hydroelastic/BUILD.bazel` line 32 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAqDAE-hL7NrMK0puW:-NQAqDAE-hL7NrMK0puX:b-lkego6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/BUILD.bazel#L32)):*
> ```Starlark
>         "@gflags",
>     ],
> )
> ```

nit Can you add a TODO to add a Python variant?
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 98 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAsEeE6Y22EB58iGVU:-NQAsEeF5Ib-rS3cg6YQ:b-ft28mb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L98)):*
> ```cpp
>   parser.package_map().Add("drake_ros_examples", package_path);
> 
>   std::filesystem::path fs_path{
> ```

Mixing both `package_path` and ament index and Bazel paths is a bit confusing.

Per below, can we try to make an affordance for this?

First pass can be just inlining it into `drake-ros`.
But we should eventually, we should make it core to Drake, as @jwnimmer-tri suggested here:
Relates https://github.com/RobotLocomotion/drake-ros/pull/1#issuecomment-1433967675
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 109 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQApQZbA-a3l-66Uh2B:-NQApQZbA-a3l-66Uh2C:bsce4ld) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L109)):*
> ```cpp
>   auto [plant, scene_graph] = AddMultibodyPlantSceneGraph(&builder, 0.0);
> 
> #ifdef BAZEL
> ```

This branching should ideally not pollute example code.

Can we carve this out into `rmw_isolation`, or at least encapsulate it somewhere else so users don't get hung up on this detail?

My main suggestion is, let's show ament index and Bazel playing well together.

Can we add functionality in `drake_ros` to update the ament index appropriately?
Maybe you can leverage your Bazel ament index logic used in scraping, or we can do it in code.
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 137 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAro9E9h3d7sjgPWm4:-NQAro9F5KwJiHqJR4hB:b-8nxqj7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L137)):*
> ```cpp
>   std::shared_ptr<Meshcat> meshcat;
>   if (FLAGS_use_meshcat) {
>     meshcat = std::make_shared<Meshcat>();
> ```

nit I believe you can use `VisualizerConfig` to compactify this:

https://github.com/RobotLocomotion/drake/blob/v1.13.0/visualization/test/visualization_config_functions_test.cc#L144-L145

You could probably use most of the defaults.
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 140 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAs2q_5jtGEaNyDT0A:-NQAs2q_5jtGEaNyDT0B:b-ed9vvg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L140)):*
> ```cpp
>     // Visualize with meshcat
>     MeshcatVisualizerParams params;
>     params.delete_on_initialization_event = false;
> ```

nit Why no initialization?
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 145 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAs4vL4KMD-rFA0agM:-NQAs4vL4KMD-rFA0agN:b1y6pty) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L145)):*
> ```cpp
> 
>     ContactVisualizerParams cparams;
>     cparams.newtons_per_meter = 60.0;
> ```

nit Rationale missing - can you add comment? (or possibly remove?)
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 176 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAqmxm6cNdwAAjrzQA:-NQAqmxm6cNdwAAjrzQB:b57giov) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L176)):*
> ```cpp
>   auto& simulator_context = simulator.get_mutable_context();
> 
>   simulator.get_mutable_integrator().set_maximum_step_size(1.0 / 50.0);
> ```

nit Rather than mutating these properties, can you instead use `SimulatorConfig`?
(sorry to picky, but as an example, I'd like us to use niceties where possible)

https://github.com/RobotLocomotion/drake/blob/v1.13.0/systems/analysis/test/simulator_config_functions_test.cc#L101-L102
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 176 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAt31rE4k5-OHrjV3G:-NQAt31s1vuV55vT78ZZ:bw4pc8o) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L176)):*
> ```cpp
>   auto& simulator_context = simulator.get_mutable_context();
> 
>   simulator.get_mutable_integrator().set_maximum_step_size(1.0 / 50.0);
> ```

nit Rationale for 50 Hz unclear. Additionally, should prefer values divisible by 2 to avoid time step dithering. e.g. `1 / 64.0`
https://github.com/RobotLocomotion/drake/pull/15850
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 194 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAr7TB61g9ToEZd0Lk:-NQAr7TB61g9ToEZd0Ll:b-8waqrd) ([raw fil [...]

2023-03-10 14:31 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: all files reviewed, 17 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAoWpO3Ntj_lyhYG4t:-NQAvPuA01hKNLv_aWMj:bcq6t9y) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Upon reinspection, I think we can just use `vtkPNGReader`, e.g.:

https://github.com/RobotLocomotion/drake/blob/v1.13.0/geometry/render_gltf_client/internal_render_client.cc#L89-L100

Rather than vendoring `lodepng` and spending some our creativity tokens there, can we just use VTK?
I think it could collapse 10k LOC of vendored code down to just a view changes to CMake / Bazel, and perhaps slightly more compact loading?

Since we're on Jammy or greater, Drake can (and does?) depends on the system-installed version:
https://github.com/RobotLocomotion/drake/pull/18340
</blockquote></details>

Sorry, I see that it's meant for *encoding* our own heatmap texture.

In that case, I think we can use `vtkImageWriter`, and just change the logic from this example to write to a stream?
https://github.com/RobotLocomotion/drake/blob/v1.13.0/systems/sensors/image_writer.cc#L22-L75

___


<!-- Sent from Reviewable.io -->

2023-03-10 19:36 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133)* status: 38 of 42 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQAoWpO3Ntj_lyhYG4t:-NQBxppkCm_K6rfzxMow:b-x6jyri) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry, I see that it's meant for *encoding* our own heatmap texture.

In that case, I think we can use `vtkImageWriter`, and just change the logic from this example to write to a stream?
https://github.com/RobotLocomotion/drake/blob/v1.13.0/systems/sensors/image_writer.cc#L22-L75
</blockquote></details>

Working.

___
___
*[`drake_ros_examples/examples/hydroelastic/BUILD.bazel` line 15 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQApvGMDNkF45LuThzU:-NQBtptD56Ylu896Uc-c:b-n4b7jj) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/BUILD.bazel#L15)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Why public?

Can we remove visibility hoisting here?

I understand that for CMake / ament, we install the examples package, but I see that as "critical to run anything useful".
However, without a concrete story for usage in Bazel, I'd prefer we avoid over-exposing ourselves.
</blockquote></details>

Probably copy/paste again. Removed.
___
*[`drake_ros_examples/examples/hydroelastic/BUILD.bazel` line 32 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQAqDAE-hL7NrMK0puW:-NQBuCnzDwbjZPOtUZ8h:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/BUILD.bazel#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you add a TODO to add a Python variant?
</blockquote></details>

Done.
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 98 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQAsEeE6Y22EB58iGVU:-NQBxtJN8wurzEbwKrF6:b-k6nlf1) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L98)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Mixing both `package_path` and ament index and Bazel paths is a bit confusing.

Per below, can we try to make an affordance for this?

First pass can be just inlining it into `drake-ros`.
But we should eventually, we should make it core to Drake, as @jwnimmer-tri suggested here:
Relates https://github.com/RobotLocomotion/drake-ros/pull/1#issuecomment-1433967675
</blockquote></details>

One thought I had before going down the path you see here was to make a bazel rule that created both an ament index package marker and a share directory. It might have looked something like.

```bazel
ament_index_share_directory(
    name = "drake_ros_examples_share",
    package_name = "drake_ros_examples",   # Maybe assert package_name == name + _share
    files = ["hydroelastic.sdf"],
    prefix = "hydroelastic",
)

# ...
ros_cc_binary(
    name = "hydroelastic",
    # ...
    data = [":drake_ros_examples_share"],
)
```

The hesitation I had was from uncertainty about how bazel will put the runfiles directory together if we also generate custom messages. The rosidl macros already create an ament index with a package marker:

https://github.com/RobotLocomotion/drake-ros/blob/967231957371377653b6803ddfde4cec98789eeb/bazel_ros2_rules/ros2/rosidl.bzl#L195-L206

 A package marker indicates a package is in a specific ament prefix. If bazel builds the runfiles by putting the rosidl rules and the `ament_index_share_directory()` rules into different  directories, then the usual pattern in ROS of "get package share directory and join this other path" could fail because the first part might return the path in the runfiles folder generated by the rosidl rule, which wouldn't have the files from the `ament_index_share_directory()` rule.

Maybe we could make the `AmentIndex` provider contain all the files that should be added to the ament index (rather than just the prefix), and then make the dload shim merge all the ament index providers into one and create all the symlinks in a single folder?
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 140 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQAs2q_5jtGEaNyDT0A:-NQBuVfrBaiah8jpyN_j:b9kjkzx) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L140)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why no initialization?
</blockquote></details>

Copy/paste from a test in Drake. Removed.
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 145 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQAs4vL4KMD-rFA0agM:-NQBun7b9Y-S7vhEBvJz:b9kjkzx) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L145)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Rationale missing - can you add comment? (or possibly remove?)
</blockquote></details>

Copy/paste from a test in Drake. Removed.
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 176 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQAt31rE4k5-OHrjV3G:-NQBurS28kFilX9RgmIR:b-dmlohu) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L176)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Rationale for 50 Hz unclear. Additionally, should prefer values divisible by 2 to avoid time step dithering. e.g. `1 / 64.0`
https://github.com/RobotLocomotion/drake/pull/15850
</blockquote></details>

The example seems to work fine with the default maximum step size, so I removed the code setting it.
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 194 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQAr7TB61g9ToEZd0Lk:-NQBwHmn17y3e4zai1j5:bss4a2b) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L194)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Extra newline?
</blockquote></details>

Removed.
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.sdf` line 1 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQArACO3wYBnj_BK564:-NQBx82hC0UrRyxk-woK:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.sdf#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Uneven indentation; some places have 2 spaces, other have 4.

Can you run through `xmllint` to make all indents be 2 spaces?
</blockquote></details>

Done.
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.sdf` line 100 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQArHT9BNItE9RHMPGd:-NQBxkUl3XCLiYEFvYSA:b-iow1j2) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.sdf#L100)):*
<details><summary><i>P [...]

2023-03-10 19:59 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133)* status: 38 of 42 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 176 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQAqmxm6cNdwAAjrzQA:-NQC5gUW1pUNJ_8GN0gA:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L176)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Rather than mutating these properties, can you instead use `SimulatorConfig`?
(sorry to picky, but as an example, I'd like us to use niceties where possible)

https://github.com/RobotLocomotion/drake/blob/v1.13.0/systems/analysis/test/simulator_config_functions_test.cc#L101-L102
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-10 22:00 UTC, EricCousineau-TRI requested changes
> Reviewed 2 of 4 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @jwnimmer-tri and @sloretz)

___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 98 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQAsEeE6Y22EB58iGVU:-NQCV1L-37-izS5avQmZ:b-96jn5q) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L98)):*
Ooh, meep!

> [...] and then make the dload shim merge [...]

I would like us to avoid runtime behavior that mutates / generates directories.
I'm fine with `ament` generating an install tree, and I'm fine with Bazel during crazy runfiles merging, but I'm fine b/c those are at build time.

(Yes, we generate temporary files for rmw isolation, but I can't say that's a model example that we should always follow!)

> [...] If bazel builds the runfiles by putting the rosidl rules [...]

Gotcha, to summarize, `ament` doesn't allow for shadowing? (that does seem like a good thing!)
And yeah, it may be hard to have Bazel automatically consolidate the files *from different packages*.

Options:

(a) A producer of `AmentIndex` must declare its package name. Any consumption of a given `AmentIndex` *can not* consume another `AmentIndex` with the same name that is in a *separate package*. By construction, all files accessible to the ament index will be collocated, thus accessible via one path, even if via multiple targets.

(b) *bottleneck* access to the ament index. e.g. rather than allow for custom IDL targets to declare their own ament index and allowing direct dependence there, consumers have to depend on a `ament_index_share_thing`. I don't love that option, though.

I think option (a) could be viable.
WDYT?


<!-- Sent from Reviewable.io -->

2023-03-11 00:39 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 35 of 42 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAoWpO3Ntj_lyhYG4t:-NQD5cmL-Z8y9-9XozZq:bnhvary) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Working.
</blockquote></details>

Done. Now using VTK

___
___
*[`drake_ros/viz/lodepng/lodepng.h` line 1 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAmITp43IDdlaSiP4n:-NQD5mce5b1rBXPOOn63:bnhvary) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros/viz/lodepng/lodepng.h#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can we make sure this has internal / private linkage?

If it helps, may you should promote `DRAKE_ROS_NO_EXPORT` to its own header, `drake_ros_export.h`?Can we make sure this has internal / private linkage?

If it helps, may you should promote `DRAKE_ROS_NO_EXPORT` to its own header, `drake_ros_export.h`?
</blockquote></details>

Done. Now using VTK
___
*[`drake_ros/viz/lodepng/lodepng.h` line 1 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAmLcUDAUT9E-L6vWV:-NQD5oHB9ebzsN87eRaw:bnhvary) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros/viz/lodepng/lodepng.h#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's unclear to me the exact source of this code.

Can you provide a permalink to the exact commit that this code was adapted from?
</blockquote></details>

Done. Now using VTK
___
*[`drake_ros/viz/lodepng/lodepng.h` line 1 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAmVkd2h90vuuVTNLY:-NQD5oju3o_ExWPrY5dw:bnhvary) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros/viz/lodepng/lodepng.h#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can we move this to an explicit third-party directory, `drake_ros/third/lodepng`?

More ideal for the Bazel world is that we use `tools/workspace/lodepng`.
However, I assume that will smell a tad odd in the context of CMake / ament.

However, maybe we can make `tools/workspace/lodepng` work for CMake, either with `ExternalProject_Add` or another mechanism.
https://cmake.org/cmake/help/latest/module/ExternalProject.html

It can either be in-tree vendoring (maybe useful for private linkage), or we can have both Bazel and CMake fetch the GitHub repository.
(For now, let's keep w/ in-tree vendoring?)

WDYT?
</blockquote></details>

Done. Now using VTK


<!-- Sent from Reviewable.io -->

2023-03-11 00:48 UTC, EricCousineau-TRI reviewed
> Reviewed 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: all files reviewed, 4 unresolved discussions (waiting on @jwnimmer-tri and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAoWpO3Ntj_lyhYG4t:-NQD7Zo-Az5B-Adr2hnr:b-fab8bo) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Done. Now using VTK
</blockquote></details>

OK Thanks!

At some point, we may want to consider writing a small Python script to write the PNG and just refer to that resource via a filepath - sorry for just now realizing we could have done that :facepalm: 

___
___
*[`drake_ros/viz/contact_markers_system.cc` line 142 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQD7B2V18_AcOT-qXej:-NQD7B2V18_AcOT-qXek:bh91g17) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/219c34aec17bb72e8be9a5f656baad3b5f2b28af/drake_ros/viz/contact_markers_system.cc#L142)):*
> ```cpp
> 
>   // Make a heatmap texture
>   size_t kWidth = 1024;
> ```

nit A bit of inline logic. Can you split this out into a separate routine? e.g.

````
impl_->texture = GenerateHeatMapPng(...)
```
````



<!-- Sent from Reviewable.io -->

2023-03-11 01:00 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: all files reviewed, 4 unresolved discussions (waiting on @jwnimmer-tri)

___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 98 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAsEeE6Y22EB58iGVU:-NQD5vAf9fO6cHpuDmW3:bbcdjfg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L98)):*
> I'm fine with ament generating an install tree, and I'm fine with Bazel during crazy runfiles merging, but I'm fine b/c those are at build time.

I was thinking maybe it was possible at build time. I was thinking `do_dload_shim` would look at all the AmentIndex providers from the `:data` dependencies of the target it was given, and it would construct the ament index. [Currently it sets AMENT_PREFIX_PATH but expects those paths already exist](https://github.com/RobotLocomotion/drake-ros/blob/967231957371377653b6803ddfde4cec98789eeb/bazel_ros2_rules/ros2/tools/dload.bzl#L100). Does that change your thoughts on what path we should take?

I think that would mean declaring package names like `(a)`, but multiple ament indexes with different resources could be merged into the same path.

> Gotcha, to summarize, ament doesn't allow for shadowing? (that does seem like a good thing!)

Shadowing meaning, a package can't exist in two ament indexes? I think in the ROS world we call this overriding. We allow it. The location of an installed package is a type of resource you can query from the ament index. When you query a for "where is the package drake_ros_examples installed", the ament index code picks the first matching resource it finds. Workspaces are prepend to`AMENT_PREFIX_PATH` so that resources in a workspace sourced after an earlier one can override resources in an earlier sourced workspace. If we have two rules that each create an ament index with a package marker for `drake_ros_examples`, then there are two `AMENT_PREFIX_PATH`s to check, and the ament index code will say "drake_ros_examples" is installed only to the first one. I think the limitation is the ament index doesn't allow a package to be split across multiple indexes.


<!-- Sent from Reviewable.io -->

2023-03-11 01:19 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133)* status: 39 of 42 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 137 at r11](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQAro9E9h3d7sjgPWm4:-NQDF6MMCYK74MzunLI2:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L137)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I believe you can use `VisualizerConfig` to compactify this:

https://github.com/RobotLocomotion/drake/blob/v1.13.0/visualization/test/visualization_config_functions_test.cc#L144-L145

You could probably use most of the defaults.
</blockquote></details>

Done.
___
*[`drake_ros/viz/contact_markers_system.cc` line 142 at r14](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQD7B2V18_AcOT-qXej:-NQDDBMd9D__eTWy_heV:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/219c34aec17bb72e8be9a5f656baad3b5f2b28af/drake_ros/viz/contact_markers_system.cc#L142)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit A bit of inline logic. Can you split this out into a separate routine? e.g.

````
impl_->texture = GenerateHeatMapPng(...)
```
````

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-14 23:06 UTC, sloretz reviewed
Requires https://github.com/ros/rosdistro/pull/36474

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-:-NQXN-LUDChjQ45s1MA2:b-v4z100)* status: 38 of 42 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @jwnimmer-tri)



<!-- Sent from Reviewable.io -->

2023-03-14 23:11 UTC, jwnimmer-tri commented
Sorry :(.  We haven't finished vendoring VTK yet in Drake (https://github.com/RobotLocomotion/drake/issues/16502).  Hopefully it'll land within a month or two.

2023-03-17 16:35 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 33 of 46 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 109 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQApQZbA-a3l-66Uh2B:-NQkNZYnBSSm3itBhJ1o:buz71k6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L109)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This branching should ideally not pollute example code.

Can we carve this out into `rmw_isolation`, or at least encapsulate it somewhere else so users don't get hung up on this detail?

My main suggestion is, let's show ament index and Bazel playing well together.

Can we add functionality in `drake_ros` to update the ament index appropriately?
Maybe you can leverage your Bazel ament index logic used in scraping, or we can do it in code.
</blockquote></details>

There's now no more branching for bazel :tada: . I added `ament_index_share_files` which creates an ament index with a package resource marker, and the given files symlinked into a share directory ([matching ament_index's expectation of a FHS folder structure](https://github.com/ament/ament_cmake/blob/master/ament_cmake_core/doc/resource_index.md#locating-resources)). We no longer need to use bazel's runfiles API ([as long as we're not on Windows](https://docs.google.com/document/d/e/2PACX-1vSDIrFnFvEYhKsCMdGdD40wZRBX3m3aZ5HhVj4CtHPmiXKDCxioTUbYsDydjKtFDAzER5eg7OjJWs3V/pub)). 


<!-- Sent from Reviewable.io -->

2023-03-20 13:59 UTC, EricCousineau-TRI approved these changes
> Reviewed 13 of 13 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: all files reviewed, 5 unresolved discussions (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/ament_index.bzl` line 69 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQzInN95c9E9DE8MEW5:-NQzInN95c9E9DE8MEW6:b97qib6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/bazel_ros2_rules/ros2/ament_index.bzl#L69)):*
> ```Starlark
>     output_to_genfiles = True,
>     provides = [AmentIndex],
> )
> ```

nit There's a chance we didn't resolve the "first one isn't the one I intended in Bazel".

What happens if a user declares an ament index for two different packages in Bazel? Should we fail fast, warn, or do nothing?
Consider adding a TODO to that effect.
___
*[`bazel_ros2_rules/ros2/ament_index.bzl` line 83 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQzHS2b7RmNqNzNkh5T:-NQzHS2b7RmNqNzNkh5U:b-o5h0b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/bazel_ros2_rules/ros2/ament_index.bzl#L83)):*
> ```Starlark
>     file = join(d, "short_path of file")
> 
> Note that this works only when bazel is able to create a real runfiles
> ```

nit I'm confused on this, specifically "able to create a real runfiles folder [...] where bazel creates a runfiles manifest, the ament index won't be accessible"

Can you clarify wording here?
___
*[`bazel_ros2_rules/ros2/tools/dload_shim.cc` line 83 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQzHhof4kFq0M1ePFB6:-NQzHhog1VnJTM19EpFu:b-5eku42) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/bazel_ros2_rules/ros2/tools/dload_shim.cc#L83)):*
> ```cpp
>           // Rlocation returns an empty string if the path cannot be found,
>           // or contains "./", "../", etc.
>           value_stream << runfiles->Rlocation(actions[i][j]) << ":";
> ```

nit Why not wrap this in a function, and fail fast if the key returns empty?
___
*[`drake_ros_examples/examples/hydroelastic/BUILD.bazel` line 10 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQzHyT05j83tZAmqoR3:-NQzHyT05j83tZAmqoR4:btpso5v) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/drake_ros_examples/examples/hydroelastic/BUILD.bazel#L10)):*
> ```Starlark
> 
> ament_index_share_files(
>     name = "hydroelastic_share",
> ```

nit Can you add a comment to clarify motivation for this mechanism? e.g.

```
# We use `ament_index_share_files` so we can easily write code that can run in both CMake / ament and Bazel.
```
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 98 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQAsEeE6Y22EB58iGVU:-NQzISa1-Bk4oplvCrVn:b-lhiii1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L98)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

> I'm fine with ament generating an install tree, and I'm fine with Bazel during crazy runfiles merging, but I'm fine b/c those are at build time.

I was thinking maybe it was possible at build time. I was thinking `do_dload_shim` would look at all the AmentIndex providers from the `:data` dependencies of the target it was given, and it would construct the ament index. [Currently it sets AMENT_PREFIX_PATH but expects those paths already exist](https://github.com/RobotLocomotion/drake-ros/blob/967231957371377653b6803ddfde4cec98789eeb/bazel_ros2_rules/ros2/tools/dload.bzl#L100). Does that change your thoughts on what path we should take?

I think that would mean declaring package names like `(a)`, but multiple ament indexes with different resources could be merged into the same path.

> Gotcha, to summarize, ament doesn't allow for shadowing? (that does seem like a good thing!)

Shadowing meaning, a package can't exist in two ament indexes? I think in the ROS world we call this overriding. We allow it. The location of an installed package is a type of resource you can query from the ament index. When you query a for "where is the package drake_ros_examples installed", the ament index code picks the first matching resource it finds. Workspaces are prepend to`AMENT_PREFIX_PATH` so that resources in a workspace sourced after an earlier one can override resources in an earlier sourced workspace. If we have two rules that each create an ament index with a package marker for `drake_ros_examples`, then there are two `AMENT_PREFIX_PATH`s to check, and the ament index code will say "drake_ros_examples" is installed only to the first one. I think the limitation is the ament index doesn't allow a package to be split across multiple indexes.



</blockquote></details>

OK Yeah, that explanation helps!
I think there's still a chance we didn't resolve the "first one isn't the one I intended in Bazel", but will comment above to that effect.
___
*[`drake_ros_examples/examples/hydroelastic/hydroelastic.cc` line 109 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQApQZbA-a3l-66Uh2B:-NQzI9tl1uTMlFbhMTSX:bcgzp9s) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/503f276e3e3cb6c608fdc605f2b773dab62aff4b/drake_ros_examples/examples/hydroelastic/hydroelastic.cc#L109)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

There's now no more branching for bazel :tada: . I added `ament_index_share_files` which creates an ament index with a package resource marker, and the given files symlinked into a share directory ([matching ament_index's expectation of a FHS folder structure](https://github.com/ament/ament_cmake/blob/master/ament_cmake_core/doc/resource_index.md#locating-resources)). We no longer need to use bazel's runfiles API ([as long as we're not on Windows](https://docs.google.com/document/d/e/2PACX-1vSDIrFnFvEYhKsCMdGdD40wZRBX3m3aZ5HhVj4CtHPmiXKDCxioTUbYsDydjKtFDAzER5eg7OjJWs3V/pub)). 
</blockquote></details>

OK Sweet!
___
*[`drake_ros/viz/contact_markers_system.cc` line 106 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQzHslX1B7fRqI3PpD6:-NQzHslX1B7fRqI3PpD7:b-xc643u) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/drake_ros/viz/contact_markers_system.cc#L106)):*
> ```cpp
> }
> 
> std::vector<uint8_t> GenerateHeatmapPng() {
> ```

BTW Yeah, given this setup, I think we should eventually just specify an image on disk rather than generate it... Or we should make this more dynamic if we care about that.


<!-- Sent from Reviewable.io -->

2023-03-23 22:20 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133)* status: 44 of 46 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

___
*[`bazel_ros2_rules/ros2/ament_index.bzl` line 69 at r17](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQzInN95c9E9DE8MEW5:-NREYs4K1Dq6vj79oKua:b-sn94q6) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/bazel_ros2_rules/ros2/ament_index.bzl#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit There's a chance we didn't resolve the "first one isn't the one I intended in Bazel".

What happens if a user declares an ament index for two different packages in Bazel? Should we fail fast, warn, or do nothing?
Consider adding a TODO to that effect.
</blockquote></details>

I think two different packages is a valid use case. For example, a target might need an arm model from `ur_description` and an end-effector model from `robotiq_description`. Two ament indexes specifying the same package could be problematic.

I tried it out here: https://github.com/sloretz/drake-ros/commit/b373cf4907e2e1ca6b893512b2457ce478d0d80d

* Two different packages works fine, as expected
* The same package twice surprised me. If they have the same prefix, then the runfiles are merged. I would have thought bazel would notice and error about two different rules creating the same file (the package marker for the foo package).
* The same package twice with a different prefix is the problematic case. Changing the order of the `deps` doesn't seem to change which prefix is listed first, meaning I'm not sure we have any control of what prefix is used when "overriding" or "shadowing". This would be a good case to raise an error, though it would require the dload shim to look at the files that are going to be generated in an `AmentIndex`, and I'm not sure how to do that. For now I left a note and a TODO in the `ament_index_share_files` comment about avoiding overriding in 44f8be5.
___
*[`bazel_ros2_rules/ros2/ament_index.bzl` line 83 at r17](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQzHS2b7RmNqNzNkh5T:-NREWFrIDDIeNEOL2sMf:b-188wva) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/bazel_ros2_rules/ros2/ament_index.bzl#L83)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I'm confused on this, specifically "able to create a real runfiles folder [...] where bazel creates a runfiles manifest, the ament index won't be accessible"

Can you clarify wording here?
</blockquote></details>

I think this might apply only to Windows (where it's not always possible to create symlinks as a non-admin user), but I'm not 100% sure that's the only place it applies. When bazel can't create a runfiles directory it creates a `*.runfiles_manifest` file instead. This file says what runfiles folder structure bazel would create if it could. If bazel were to do that, then`AMENT_PREFIX_PATH` we set won't exist, and so `ament_index_cpp` calls aren't going to find anything.

I added a little more wording to that effect in 2f7a3f9.
___
*[`bazel_ros2_rules/ros2/tools/dload_shim.cc` line 83 at r17](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQzHhof4kFq0M1ePFB6:-NREYDfS1iKTZYCNE88t:bjuw9wp) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/bazel_ros2_rules/ros2/tools/dload_shim.cc#L83)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why not wrap this in a function, and fail fast if the key returns empty?
</blockquote></details>

I'd be concerned about existing packages declaring environment variable paths that don't actually exist (like a package says it needs LD_LIBRARY_PATH set, but doesn't install any libraries) . I'll try this in a separate PR.
___
*[`drake_ros_examples/examples/hydroelastic/BUILD.bazel` line 10 at r17](https://reviewable.io/reviews/RobotLocomotion/drake-ros/133#-NQzHyT05j83tZAmqoR3:-NRFTwwT4_kdcJqqdbqp:bn8fdl4) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/drake_ros_examples/examples/hydroelastic/BUILD.bazel#L10)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you add a comment to clarify motivation for this mechanism? e.g.

```
# We use `ament_index_share_files` so we can easily write code that can run in both CMake / ament and Bazel.
```
</blockquote></details>

Added comment in e41e15d


<!-- Sent from Reviewable.io -->

2023-03-23 22:51 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: 44 of 46 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`bazel_ros2_rules/ros2/tools/dload_shim.cc` line 83 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQzHhof4kFq0M1ePFB6:-NRFelKh0qepZgpVPgP2:b-vwwu63) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/bazel_ros2_rules/ros2/tools/dload_shim.cc#L83)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I'd be concerned about existing packages declaring environment variable paths that don't actually exist (like a package says it needs LD_LIBRARY_PATH set, but doesn't install any libraries) . I'll try this in a separate PR.
</blockquote></details>

https://github.com/RobotLocomotion/drake-ros/pull/265


<!-- Sent from Reviewable.io -->

2023-03-27 16:28 UTC, EricCousineau-TRI approved these changes
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/ament_index.bzl` line 69 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQzInN95c9E9DE8MEW5:-NRYsTIL3-nBhEZbnBe9:b-wjqf9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/bazel_ros2_rules/ros2/ament_index.bzl#L69)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I think two different packages is a valid use case. For example, a target might need an arm model from `ur_description` and an end-effector model from `robotiq_description`. Two ament indexes specifying the same package could be problematic.

I tried it out here: https://github.com/sloretz/drake-ros/commit/b373cf4907e2e1ca6b893512b2457ce478d0d80d

* Two different packages works fine, as expected
* The same package twice surprised me. If they have the same prefix, then the runfiles are merged. I would have thought bazel would notice and error about two different rules creating the same file (the package marker for the foo package).
* The same package twice with a different prefix is the problematic case. Changing the order of the `deps` doesn't seem to change which prefix is listed first, meaning I'm not sure we have any control of what prefix is used when "overriding" or "shadowing". This would be a good case to raise an error, though it would require the dload shim to look at the files that are going to be generated in an `AmentIndex`, and I'm not sure how to do that. For now I left a note and a TODO in the `ament_index_share_files` comment about avoiding overriding in 44f8be5.
</blockquote></details>

Sorry, I meant "two different instances of the same package in different Bazel packages"

I'm not surprised that Bazel allows the merging when you're in the same folder - in fact, I think that's A-OK, as they should ultimately be the same folder -- unless there's some ament manifest that conflicts -- however, Bazel *should* fail if you try to combine two runfiles that have the same path for unique instances of said file.

However, if you have the same package name for ament spread across two *different Bazel packages*, that might cause an issue.
Resolving this, but added a nit to clarify.
___
*[`bazel_ros2_rules/ros2/ament_index.bzl` line 83 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NQzHS2b7RmNqNzNkh5T:-NRYsP6ZDs41KT3ca8mj:b-ieyay5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b226b00aa84829d497cd96bbe3427b8e93d0c668/bazel_ros2_rules/ros2/ament_index.bzl#L83)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I think this might apply only to Windows (where it's not always possible to create symlinks as a non-admin user), but I'm not 100% sure that's the only place it applies. When bazel can't create a runfiles directory it creates a `*.runfiles_manifest` file instead. This file says what runfiles folder structure bazel would create if it could. If bazel were to do that, then`AMENT_PREFIX_PATH` we set won't exist, and so `ament_index_cpp` calls aren't going to find anything.

I added a little more wording to that effect in 2f7a3f9.
</blockquote></details>

OK Sweet, thanks!
___
*[`bazel_ros2_rules/ros2/ament_index.bzl` line 87 at r18](https://reviewable.io/reviews/robotlocomotion/drake-ros/133#-NRYslz81nghN1LbdGWW:-NRYslz81nghN1LbdGWX:b-ph8evi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/44f8be531bb88554361aa27834171a037c170f00/bazel_ros2_rules/ros2/ament_index.bzl#L87)):*
> ```Starlark
> platform like Windows, or with `--nobuild_runfile_links`).
> 
> Note that the same package_name should never be used in two different
> ```

nit Per above, I recommend qualifying this:

```
Note that the same `package_name` for ROS 2 packages should not be used
in multiple different rules spread across multiple Bazel packages. ...
```


<!-- Sent from Reviewable.io -->

2023-03-30 21:39 UTC, EricCousineau-TRI commented
@sloretz Is this something we could land soon? (tomorrow, if possible?)

2023-04-12 22:30 UTC, EricCousineau-TRI approved these changes
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2023-04-12 22:30 UTC, EricCousineau-TRI commented
Thanks!

2023-04-12 22:31 UTC, merged