Add conversion functions for common types
RobotLocomotion/drake-ros pull request #141
Opened 2022-09-22 00:55 UTC by gbiggs

Implements #117.

2022-09-22 11:45 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @gbiggs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_-h_oAp7b-9M_sfz9:-NC_-h_oAp7b-9M_sfzA:bj2qwe0) (no related file):*
From Slack:
> It all compiles now, but two of the tests are failing because I don't understand how to use Eigen::Isometry3d.

This is a finicky type. For now, I recommend using `RigidTransformd` as intermediate.
(This does mean we're not encompassing skew transforms / mirror SO(3), but that's fine IMO)

Alternatively, if you use the constructor approach, then it should work better.
(I believe `Eigen::Isometry3d` is default uninitialized for speed, hence why testing may be failing)

___
___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NCZzejADCXZ2KpiYnS-:-NCZzejADCXZ2KpiYnS0:bxwz8tw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L30)):*
> ```objc
> 
> namespace drake_ros_core {
> namespace conversions {
> ```

Unclear why we need to qualify this namespace; other code on `develop` does not appear to have extra qualifier, and I believe this makes things too verbose.

Can you remove?
___
*[`drake_ros_core/src/conversions.cc` line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NCZzxmnCsXKYQGTLj3O:-NCZzxmo9eCS9TP1Ja4g:braerit) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/src/conversions.cc#L59)):*
> ```cpp
> }
> 
> Eigen::Isometry3d ros_pose_to_eigen_isometry3d(
> ```

For all conversions, can you prefer constructing the type from values directly, if possible, rather than using construct-then-mutate?
___
*[`drake_ros_core/src/conversions.cc` line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_-4FeBh-EVhJIKtsP:-NC_-4FeBh-EVhJIKtsQ:bnpfzfh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/src/conversions.cc#L60)):*
> ```cpp
> 
> Eigen::Isometry3d ros_pose_to_eigen_isometry3d(
>     const geometry_msgs::msg::Pose& pose)
> ```

This conversions are composable, but you seem to have reimplemented the logic.

Can you instead resuse conversions?
e.g. "transform -> point + rotation"
e.g. "rigid transform -> using isometry3d"
___
*[`drake_ros_core/test/test_conversions.cc` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_-NUe6m3bdnFzbeOQ:-NC_-NUe6m3bdnFzbeOR:b-b8tkvr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/test/test_conversions.cc#L19)):*
> ```cpp
> #include "drake_ros_core/conversions.h"
> 
> TEST(DrakeRosConversions, point) {
> ```

Testing code should ideally live in same namespace as components being tested, perhaps w/ additional anonymous namespace.

Can you wrap this test code in `namespace drake_ros_core { namespace { ... } }`?
___
*[`drake_ros_core/test/test_conversions.cc` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_-Z9T9ExQrY2MR0Yj:-NC_-Z9T9ExQrY2MR0Yk:bvtlxk8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/test/test_conversions.cc#L19)):*
> ```cpp
> #include "drake_ros_core/conversions.h"
> 
> TEST(DrakeRosConversions, point) {
> ```

FYI Testing round-trip here seems perfectly valid to me!


<!-- Sent from Reviewable.io -->

2022-09-22 11:46 UTC, EricCousineau-TRI reviewed
+@ericcousineau-tri for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-:-NC_0Bwv3eYzQ_MTUI5s:b7dr7wo)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @gbiggs)



<!-- Sent from Reviewable.io -->

2022-09-22 12:00 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @gbiggs)

___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_2rNY2hgal6-i-ndN:-NC_2rNY2hgal6-i-ndO:b-bxsjxh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L1)):*
> ```objc
> // Copyright 2022 Open Source Robotics Foundation, Inc.
> ```

The general term "conversions" seems too broad; I would like us to narrow it down a bit more.

I prefer `geometry_conversions`; in my mind, I'm not sure if forces are part of geometry; however, `geometry_msgs` contains this, so I think it's appropriate.
___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_33bM0h1bSXvhVZvE:-NC_33bNDk9DCR5iB4Mn:b-4xepah) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L32)):*
> ```objc
> namespace conversions {
> 
> Eigen::Vector3d ros_point_to_eigen_vector3d(
> ```

Per Drake GSG, perhaps these could be `lower_snake_case`; however, there's a nagging feeling that we shouldn't prescribe the `O(1)` vs. `> O(1)` convention here.

Can you rename all of these to `CamelCase`?
___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_3JBt546BoIHBD413:-NC_3JBt546BoIHBD414:b-bfl0y0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L32)):*
> ```objc
> namespace conversions {
> 
> Eigen::Vector3d ros_point_to_eigen_vector3d(
> ```

I'm not sure if we need `Eigen` or `Drake` qualifiers here.

Can you remove?
___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_3Noq1_xHsp6rqpu5:-NC_3Noq1_xHsp6rqpu6:bfifodq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L65)):*
> ```objc
>     const geometry_msgs::msg::Transform& transform);
> 
> geometry_msgs::msg::Transform drake_transform_to_ros_transform(
> ```

For `RigidTransform`, I believe we should qualify the term as `rigid_transform`, not just `transform`.


<!-- Sent from Reviewable.io -->

2022-09-26 06:11 UTC, gbiggs reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @gbiggs)

___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_2rNY2hgal6-i-ndN:-NCrZ8n_4ZaLVH0_a8S3:b-ia6an6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

The general term "conversions" seems too broad; I would like us to narrow it down a bit more.

I prefer `geometry_conversions`; in my mind, I'm not sure if forces are part of geometry; however, `geometry_msgs` contains this, so I think it's appropriate.
</blockquote></details>

Changed to `geometry_conversions` in ff92f02.
___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 30 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NCZzejADCXZ2KpiYnS-:-NCr_60BClDYjAndObfK:bgxjojo) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unclear why we need to qualify this namespace; other code on `develop` does not appear to have extra qualifier, and I believe this makes things too verbose.

Can you remove?
</blockquote></details>

Removed in 464d200.
___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_33bM0h1bSXvhVZvE:-NCrce_8DRetu0vnq879:b-olpmei) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per Drake GSG, perhaps these could be `lower_snake_case`; however, there's a nagging feeling that we shouldn't prescribe the `O(1)` vs. `> O(1)` convention here.

Can you rename all of these to `CamelCase`?
</blockquote></details>

Done in 7022ef4.
___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_3JBt546BoIHBD413:-NCsE4BL4IyP-66sG-az:b-npgecn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm not sure if we need `Eigen` or `Drake` qualifiers here.

Can you remove?
</blockquote></details>

Removed in 5d6e03f. Do you want the `Ros` qualifier removed as well?
___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 65 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_3Noq1_xHsp6rqpu5:-NCsEhcw5Hl6TYX68tai:btkracr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L65)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For `RigidTransform`, I believe we should qualify the term as `rigid_transform`, not just `transform`.
</blockquote></details>

Done in 6f2ad11.
___
*[`drake_ros_core/src/conversions.cc` line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NCZzxmnCsXKYQGTLj3O:-NCsK13mEowbNq1q4csO:b-89zlrf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/src/conversions.cc#L59)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For all conversions, can you prefer constructing the type from values directly, if possible, rather than using construct-then-mutate?
</blockquote></details>

Done in 5b73970 for those where it's possible to do so. Unfortunately ROS types don't have suitable constructors.
___
*[`drake_ros_core/test/test_conversions.cc` line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_-NUe6m3bdnFzbeOQ:-NCsFAXQ3DORsFuUIVw6:b-o84424) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/test/test_conversions.cc#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Testing code should ideally live in same namespace as components being tested, perhaps w/ additional anonymous namespace.

Can you wrap this test code in `namespace drake_ros_core { namespace { ... } }`?
</blockquote></details>

Done in 0450539.


<!-- Sent from Reviewable.io -->

2022-10-11 23:39 UTC, EricCousineau-TRI requested changes
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @gbiggs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_-h_oAp7b-9M_sfz9:-NE8P_4MD_qxuZ-_vynZ:bet2jkt) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

From Slack:
> It all compiles now, but two of the tests are failing because I don't understand how to use Eigen::Isometry3d.

This is a finicky type. For now, I recommend using `RigidTransformd` as intermediate.
(This does mean we're not encompassing skew transforms / mirror SO(3), but that's fine IMO)

Alternatively, if you use the constructor approach, then it should work better.
(I believe `Eigen::Isometry3d` is default uninitialized for speed, hence why testing may be failing)
</blockquote></details>

Can you try out removing any direction operations on Isometry, and only use RigidTransform?
(i.e., use RigidTransform as intermediate representation)

___
___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_3JBt546BoIHBD413:-NE8OskABI5ttmEDI0vb:b2itb3e) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L32)):*
<details><summary><i>Previously, gbiggs (Geoffrey Biggs) wrote…</i></summary><blockquote>

Removed in 5d6e03f. Do you want the `Ros` qualifier removed as well?
</blockquote></details>

OK Thanks! And I think the `Ros` qualifier still helps
___
*[`drake_ros_core/include/drake_ros_core/geometry_conversions.h` line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NE8P-LxBcmMG2bEjRj3:-NE8P-LxBcmMG2bEjRj4:bdar79) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/include/drake_ros_core/geometry_conversions.h#L73)):*
> ```objc
>     const drake::multibody::SpatialVelocity<double>& velocity);
> 
> drake::Vector6d RosAccelToVector6d(const geometry_msgs::msg::Accel& accel);
> ```

nit Can you use `Acceleration` in lieu of abbreviated `Accel`?
___
*[`drake_ros_core/src/conversions.cc` line 59 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NCZzxmnCsXKYQGTLj3O:-NE8PADW7gBqb27bYH3Y:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/src/conversions.cc#L59)):*
<details><summary><i>Previously, gbiggs (Geoffrey Biggs) wrote…</i></summary><blockquote>

Done in 5b73970 for those where it's possible to do so. Unfortunately ROS types don't have suitable constructors.
</blockquote></details>

OK Thanks!
___
*[`drake_ros_core/src/geometry_conversions.cc` line 43 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NE8P5zA2205DPWJCeAU:-NE8P5zBEbioL1bon3oD:b-8waqrd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/src/geometry_conversions.cc#L43)):*
> ```cpp
>   result.z = quat.z();
>   result.w = quat.w();
> ```

nit Extra newline?
___
*[`drake_ros_core/test/test_geometry_conversions.cc` line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NE8PPLoDyvzQWyILsi1:-NE8PPLoDyvzQWyILsi2:bnviizr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/test/test_geometry_conversions.cc#L22)):*
> ```cpp
> namespace {
> 
> TEST(GeometryConversions, point) {
> ```

nit Capitalization, "Point"?


<!-- Sent from Reviewable.io -->

2022-10-18 14:55 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @gbiggs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEf_owjB3VUcoRc9lN-:-NEf_owk4w2A1TJV2qQw:b-yt11ty) (no related file):*
Working: Addressing comments...

___


<!-- Sent from Reviewable.io -->

2022-10-18 14:56 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @gbiggs)

___
*[`drake_ros_core/include/drake_ros_core/geometry_conversions.h` line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NE8P-LxBcmMG2bEjRj3:-NEfa3IAB-4loO_A1YbV:b4x22ho) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/include/drake_ros_core/geometry_conversions.h#L73)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you use `Acceleration` in lieu of abbreviated `Accel`?
</blockquote></details>

Should also use `Spatial` quatlifier for Drake-specific quantities.


<!-- Sent from Reviewable.io -->

2022-10-18 14:58 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @gbiggs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEfa_E2AzaIn5tKzkiN:-NEfa_E2AzaIn5tKzkiO:b-ww3pik) (no related file):*
Should use `const` for locals when possible.

___


<!-- Sent from Reviewable.io -->

2022-10-18 15:52 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 12 unresolved discussions (waiting on @gbiggs)

___
*[`drake_ros_core/include/drake_ros_core/geometry_conversions.h` line 30 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEfmkUW7jHbaOSJrI_k:-NEfmkUW7jHbaOSJrI_l:b681m07) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/include/drake_ros_core/geometry_conversions.h#L30)):*
> ```objc
> 
> namespace drake_ros_core {
> ```

Should have conversion to `geometry_msgs::msg::Vector3`.
___
*[`drake_ros_core/src/geometry_conversions.cc` line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEfmqErAuoLpCGBG84T:-NEfmqErAuoLpCGBG84U:bh9q544) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/src/geometry_conversions.cc#L144)):*
> ```cpp
> 
> drake::Vector6d RosTwistToVector6d(const geometry_msgs::msg::Twist& twist) {
>   drake::Vector6d result;
> ```

I believe this ordering is incorrect, at least for Drake conventions. (here and below)

It should be `rotation, linear`.


<!-- Sent from Reviewable.io -->

2022-10-18 17:14 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 13 unresolved discussions (waiting on @gbiggs)

___
*[`drake_ros_core/test/test_geometry_conversions.cc` line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEg4ZsrCtKHrbZUt-tE:-NEg4ZsrCtKHrbZUt-tF:bf2bapc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/test/test_geometry_conversions.cc#L22)):*
> ```cpp
> namespace {
> 
> TEST(GeometryConversions, point) {
> ```

Should actually test values (not just round-trip), following up from Slack convo.


<!-- Sent from Reviewable.io -->

2022-10-18 17:17 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 14 unresolved discussions (waiting on @gbiggs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEg5CDkCHds8RlpW79Z:-NEg5CDl-bLI1Gn0KjcE:b-j1rkcl) (no related file):*
`Vector3d` in function names is an inconsistent qualifier on type.
 It should be renamed to `Vector3`.

___


<!-- Sent from Reviewable.io -->

2022-10-18 17:33 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 15 unresolved discussions (waiting on @gbiggs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEg8vKf4eKA7B0hYLEG:-NEg8vKf4eKA7B0hYLEH:bz6fzzi) (no related file):*
I believe most of these conversions are double, not float, e.g.
```
$ ros2 interface show geometry_msgs/msg/Vector3
...
float64 x
float64 y
float64 z
```

We should not lose data.

___


<!-- Sent from Reviewable.io -->

2022-10-18 17:34 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 15 unresolved discussions (waiting on @gbiggs)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEg8vKf4eKA7B0hYLEG:-NEg97nbAB8WIA-AcFDb:b-imim61) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I believe most of these conversions are double, not float, e.g.
```
$ ros2 interface show geometry_msgs/msg/Vector3
...
float64 x
float64 y
float64 z
```

We should not lose data.
</blockquote></details>

This may only be important for unittesting, where literals are used, e.g. `0.1f`.

___


<!-- Sent from Reviewable.io -->

2022-10-18 18:07 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 16 unresolved discussions (waiting on @gbiggs)

___
*[`drake_ros_core/CMakeLists.txt` line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEgGlOE6DedbsGtqibR:-NEgGlOE6DedbsGtqibS:b-jz9kz7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/CMakeLists.txt#L29)):*
> ```CMake
> 
> add_library(drake_ros_core
>   src/geometry_conversions.cc
> ```

Should be alpha-sorted.


<!-- Sent from Reviewable.io -->

2022-10-18 18:08 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 17 unresolved discussions (waiting on @gbiggs)

___
*[`drake_ros_core/CMakeLists.txt` line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEgGtySAMZIUJY1hu7O:-NEgGtyT9d0EwWZTOF-r:b-bxpz5k) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/CMakeLists.txt#L44)):*
> ```CMake
>     rosidl_typesupport_cpp::rosidl_typesupport_cpp
>     Eigen3::Eigen
>     ${geometry_msgs_TARGETS}
> ```

I don't understand why we need to use this.
Does this package not export a CMake target?


<!-- Sent from Reviewable.io -->

2022-10-18 18:10 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 3 of 5 files reviewed, 17 unresolved discussions (waiting on @gbiggs)

___
*[`drake_ros_core/CMakeLists.txt` line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEgGtySAMZIUJY1hu7O:-NEgHTBjCe-EGGmraqFJ:bkim2cg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/CMakeLists.txt#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I don't understand why we need to use this.
Does this package not export a CMake target?
</blockquote></details>

I think `ament_target_dependencies` is what I want.


<!-- Sent from Reviewable.io -->

2022-10-18 20:47 UTC, EricCousineau-TRI reviewed
@gbiggs and +@iantheengineer Can I ask for your (counter) review?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-:-NEgqU2z-W_MjTy7ITGK:b-7r091w)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_-h_oAp7b-9M_sfz9:-NEgqTTG7nvPYfLh-d2c:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you try out removing any direction operations on Isometry, and only use RigidTransform?
(i.e., use RigidTransform as intermediate representation)
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEf_owjB3VUcoRc9lN-:-NEgqStU03kPmS8pAwqW:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Addressing comments...
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEfa_E2AzaIn5tKzkiN:-NEgqSGbEYeCTCM2PyIr:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Should use `const` for locals when possible.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEg5CDkCHds8RlpW79Z:-NEgqRkO8xJz9GvFuQ0g:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`Vector3d` in function names is an inconsistent qualifier on type.
 It should be renamed to `Vector3`.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEg8vKf4eKA7B0hYLEG:-NEgqR3KEd9NAUw58gdU:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This may only be important for unittesting, where literals are used, e.g. `0.1f`.
</blockquote></details>

Done.

___
___
*[`drake_ros_core/CMakeLists.txt` line 29 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEgGlOE6DedbsGtqibR:-NEgqBOu1Ykk12NqhXAC:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/CMakeLists.txt#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Should be alpha-sorted.
</blockquote></details>

Done.
___
*[`drake_ros_core/CMakeLists.txt` line 44 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEgGtySAMZIUJY1hu7O:-NEgqAph3O44HPDUW8mh:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/CMakeLists.txt#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I think `ament_target_dependencies` is what I want.
</blockquote></details>

Done.
___
*[`drake_ros_core/include/drake_ros_core/conversions.h` line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_3JBt546BoIHBD413:-NEgqD9kBf3cwaXp7A3T:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/include/drake_ros_core/conversions.h#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Thanks! And I think the `Ros` qualifier still helps
</blockquote></details>

Done.
___
*[`drake_ros_core/include/drake_ros_core/geometry_conversions.h` line 30 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEfmkUW7jHbaOSJrI_k:-NEgqC_aC0OeLIR9-Uwt:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/include/drake_ros_core/geometry_conversions.h#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Should have conversion to `geometry_msgs::msg::Vector3`.
</blockquote></details>

Done.
___
*[`drake_ros_core/include/drake_ros_core/geometry_conversions.h` line 73 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NE8P-LxBcmMG2bEjRj3:-NEgqEiXAsLPoJUkTE9y:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/include/drake_ros_core/geometry_conversions.h#L73)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Should also use `Spatial` quatlifier for Drake-specific quantities.
</blockquote></details>

Done.
___
*[`drake_ros_core/src/conversions.cc` line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NC_-4FeBh-EVhJIKtsP:-NEgqHjO4jFxuOv12F4c:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/f701f17aae09897c5527964c0ae5693f44d9c820/drake_ros_core/src/conversions.cc#L60)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This conversions are composable, but you seem to have reimplemented the logic.

Can you instead resuse conversions?
e.g. "transform -> point + rotation"
e.g. "rigid transform -> using isometry3d"
</blockquote></details>

Done.
___
*[`drake_ros_core/src/geometry_conversions.cc` line 53 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEfat8B9yRHzY_yCyJl:-NEgqIObCFwbq4IfRMvn:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/src/geometry_conversions.cc#L53)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This is incorrect. We should not be rotating translation component.
</blockquote></details>

Done.
___
*[`drake_ros_core/src/geometry_conversions.cc` line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEfmqErAuoLpCGBG84T:-NEgqJLW5pqziEG8xb57:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/src/geometry_conversions.cc#L144)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I believe this ordering is incorrect, at least for Drake conventions. (here and below)

It should be `rotation, linear`.
</blockquote></details>

Done.
___
*[`drake_ros_core/test/test_geometry_conversions.cc` line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NE8PPLoDyvzQWyILsi1:-NEgqKbj864v3j7c6Dbq:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/test/test_geometry_conversions.cc#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Capitalization, "Point"?
</blockquote></details>

Done.
___
*[`drake_ros_core/test/test_geometry_conversions.cc` line 22 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEg4ZsrCtKHrbZUt-tE:-NEgqMIc3rl2ucVrSeKX:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5b739707d1d6247735d4787834fbbb032fd91310/drake_ros_core/test/test_geometry_conversions.cc#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Should actually test values (not just round-trip), following up from Slack convo.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-18 20:48 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/141)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/141#-NEgqhAs838elkqXaTX8:-NEgqhAs838elkqXaTX9:b422t8g) (no related file):*
Working: Ah, sorry. Actually, I would like to reopen this PR using fork.

___


<!-- Sent from Reviewable.io -->

2022-10-18 20:50 UTC, EricCousineau-TRI commented
Shifted to #153
Closing this and deleting branch

2022-10-18 20:50 UTC, closed without merging