ClockSystem and AddClockPublisher
RobotLocomotion/drake-ros pull request #148
Opened 2022-10-07 21:28 UTC by sloretz

Requires #147 
Resolves #144

This adds `ClockSystem` - a system that turns Drake Simulator's time into ROS Clock messages, and a convenience method `AddClockPublisher` (`add_clock_publisher` in Python) which adds the system and a publisher to a `DiagramBuilder<double>`.

I updated the iiwa_manipulator and multirobot examples to use the new system.

2022-10-07 21:33 UTC, jwnimmer-tri commented
Drake's convention[1] is to have the "Add..." kinds of functions (which create an instance an wire it up in a DiagramBuilder) be static member functions on the class itself, akin to a factory function.  In our experience, that's a lot easier for people to find, and helps make it clear exactly what's going on.  I don't know if drake-ros wants to match that particular convention, but in any case I thought I'd mention it.

[1] For example:
- https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1lcm_1_1_lcm_scope_system.html#ad6fc9bbde61e385e95afbc2ec0e80201
- https://drake.mit.edu/doxygen_cxx/classdrake_1_1geometry_1_1_meshcat_visualizer.html#a737291fe2f178eb125c8e9cb746af966

2022-10-07 23:06 UTC, sloretz reviewed
> Drake's convention[1] is to have the "Add..." kinds of functions (which create an instance an wire it up in a DiagramBuilder) be static member functions on the class itself, akin to a factory function. In our experience, that's a lot easier for people to find, and helps make it clear exactly what's going on. I don't know if drake-ros wants to match that particular convention, but in any case I thought I'd mention it

Thanks! I changed `AddClockPublisher` to `ClockSystem::AddToBuilder`mimicking `LcmScope::AddToBuilder` in f666f8c

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-:-NDogZCeERiehWp8X0qf:b-24jjct)* status: 0 of 13 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-17 22:00 UTC, IanTheEngineer requested changes
> Reviewed 1 of 13 files at r1, 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148)* status: 2 of 14 files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`drake_ros_core/src/drake_ros_core/__init__.py` line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NEbx9Au-sUQcxv1iiDl:-NEbx9AvCriE-42edBx-:b-jhwmfq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b7cbb48a0f54f3b6a0b9565893781a3794401f07/drake_ros_core/src/drake_ros_core/__init__.py#L19)):*
> ```Python
> import rclpy.qos
> 
> import rosgraph_msgs.msg
> ```

Is `rosgraph_msgs` a new package dependency that we should add to the `package.xml`, `CMakeLists.txt`, and `BUILD.bazel`?



_Code quote:_
```Python
rosgraph_msgs
```


<!-- Sent from Reviewable.io -->

2022-10-17 22:10 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer)

___
*[`drake_ros_core/src/drake_ros_core/__init__.py` line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NEbx9Au-sUQcxv1iiDl:-NEbz65y7MCcyb6svjIH:b3xfwpj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b7cbb48a0f54f3b6a0b9565893781a3794401f07/drake_ros_core/src/drake_ros_core/__init__.py#L19)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Is `rosgraph_msgs` a new package dependency that we should add to the `package.xml`, `CMakeLists.txt`, and `BUILD.bazel`?
</blockquote></details>

I made it explicitly depended upon in the latest commit  in those three files.


<!-- Sent from Reviewable.io -->

2022-10-18 02:32 UTC, IanTheEngineer requested changes
Things look quite good. I have just a few conceptual questions on how we might ensure the clock is simulated when leveraging a `ClockSystem`. The rest of the Drake and ROS2 machinery looks good to me.

We should probably document somewhere that if you're using the `ClockSystem` to control your ROS time, **all** the rest of your ROS2 nodes need to have the parameter `use_sim_time=true` set.

> Reviewed 2 of 13 files at r1, 10 of 11 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-:-NEcu1uf5MIZxh7ONB1g:b-smnzd6)* status: all files reviewed, 2 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros_core/src/clock_system.cc` line 16 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NEcuOuD4agHka19XAJp:-NEcuOuE3Kd-aIiWLaAn:bbie82b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f44193fa4e278902adf0ec85a5d962369dd2aea/drake_ros_core/src/clock_system.cc#L16)):*
> ```cpp
> void ClockSystem::CalcClock(const drake::systems::Context<double>& context,
>                             rosgraph_msgs::msg::Clock* output_value) const {
>   rclcpp::Time now;
> ```

BTW: If I recall correctly, the rclcpp::Time class is subscribed to `/clock` itself under-the-hood, as long as the parameter `use_sim_time=true` at the top level of the node. Is that understanding accurate?



_Code quote:_
```cpp
rclcpp::Time now;
```
___
*[`drake_ros_core/src/clock_system.cc` line 22 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NEcsXPY8dYW4PE6vrO4:-NEcsXPY8dYW4PE6vrO5:b2izxps) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f44193fa4e278902adf0ec85a5d962369dd2aea/drake_ros_core/src/clock_system.cc#L22)):*
> ```cpp
> 
> std::tuple<ClockSystem*, RosPublisherSystem*> ClockSystem::AddToBuilder(
>     drake::systems::DiagramBuilder<double>* builder, DrakeRos* ros,
> ```

Minor: Should we ensure the node is using ```RCL_ROS_TIME``` here? I would imagine that by using this ClockSystem, you're handing over control of your time-source to Drake (thereby forgoing the default ``` rcl_time_source_type_t = RCL_SYSTEM_TIME```). 



_Code quote:_
```cpp
DrakeRos* ros
```
___
*[`drake_ros_core/src/drake_ros_core/__init__.py` line 19 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NEbx9Au-sUQcxv1iiDl:-NEclD4L4AnA8tCc1cOZ:b-imwcxc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b7cbb48a0f54f3b6a0b9565893781a3794401f07/drake_ros_core/src/drake_ros_core/__init__.py#L19)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I made it explicitly depended upon in the latest commit  in those three files.
</blockquote></details>

Great! Thanks for adding it explicitly.


<!-- Sent from Reviewable.io -->

2022-12-29 21:45 UTC, sloretz reviewed
Documented `use_sim_time` needing to be set to True in 3f678f0

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-:-NKUq2HEA_GAliHyltl6:b-8yr4ei)* status: 4 of 17 files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer)

___
*[`drake_ros_core/src/clock_system.cc` line 16 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NEcuOuD4agHka19XAJp:-NKUlw_K0UyqkXfbrkOi:b-buzjnn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f44193fa4e278902adf0ec85a5d962369dd2aea/drake_ros_core/src/clock_system.cc#L16)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

BTW: If I recall correctly, the rclcpp::Time class is subscribed to `/clock` itself under-the-hood, as long as the parameter `use_sim_time=true` at the top level of the node. Is that understanding accurate?
</blockquote></details>

Mostly correct. It's not the `rclcpp::Time` class that's subscribed though. Instead the`rclcpp::Clock`is "attached" to an `rclcpp::TimeSource`. The default `TimeSource` subscribes to `/clock` when the `use_sim_time` parameter is set to `True`.

`clock->now()` returns the time from the `TimeSource` when ROS time is active (meaning `use_sim_time` is True).
___
*[`drake_ros_core/src/clock_system.cc` line 22 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NEcsXPY8dYW4PE6vrO4:-NKUlsRH0d0PP9E2oAY3:b-9v42ag) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2f44193fa4e278902adf0ec85a5d962369dd2aea/drake_ros_core/src/clock_system.cc#L22)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Minor: Should we ensure the node is using ```RCL_ROS_TIME``` here? I would imagine that by using this ClockSystem, you're handing over control of your time-source to Drake (thereby forgoing the default ``` rcl_time_source_type_t = RCL_SYSTEM_TIME```). 
</blockquote></details>

That makes sense. Using RCL_ROS_TIME in 2ac08c1


<!-- Sent from Reviewable.io -->

2023-02-17 01:08 UTC, EricCousineau-TRI requested changes
> Reviewed 4 of 11 files at r2, 12 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148)* status: 16 of 17 files reviewed, 8 unresolved discussions (waiting on @IanTheEngineer and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORtWrU8u39ehEO7PSv:-NORtWrU8u39ehEO7PSw:b-7yjn0u) (no related file):*
I would like us to land the following PRs before this one:
#205 - for consolidation and avoiding too many merge conflicts on that PR
#207 - to ensure this is all tested

___
___
*[`drake_ros_core/include/drake_ros_core/clock_system.h` line 1 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORrE_f-X0lPU46b8JA:-NORrE_f-X0lPU46b8JB:b-uf87ch) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_core/include/drake_ros_core/clock_system.h#L1)):*
> ```objc
> // Copyright 2022 Open Source Robotics Foundation, Inc.
> ```

Per (out of band) email thread, we should remove notices.
___
*[`drake_ros_core/include/drake_ros_core/qos_pybind.h` line 95 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORsF_6AmyxLW2Isr4q:-NORsF_6AmyxLW2Isr4r:bdhoed1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_core/include/drake_ros_core/qos_pybind.h#L95)):*
> ```objc
>   }
> 
>   // Convert from drake_ros_core::QoS to rclpy.qos.QoSProfile
> ```

This does not appear to be directly tested.

Can you add a test? (perhaps even a small acceptance test?)
___
*[`drake_ros_core/src/module_py.cc` line 110 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORrWq01Asy-TtZO5Cd:-NORrWq01Asy-TtZO5Ce:bnegag5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_core/src/module_py.cc#L110)):*
> ```cpp
>                 builder, ros, topic_name, qos, pub_triggers, publish_period);
> 
>             using py_rvp = pybind11::return_value_policy;
> ```

nit This alias should be listed at declaration scope of translation unit (i.e., inside namespace, not function)
___
*[`drake_ros_core/src/drake_ros_core/__init__.py` line 76 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORrnot7Oqq6PBVIaw-:-NORrnou-YlTRoPaoNTa:bsqydi1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_core/src/drake_ros_core/__init__.py#L76)):*
> ```Python
> 
> __all__ = [
>     'ClockSystem',
> ```

nit (pre-existing) Can you do case-sensitive alpha-sorting here?
___
*[`drake_ros_tf2/CMakeLists.txt` line 86 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORs0ET4EO_xDkRhYFr:-NORs0ET4EO_xDkRhYFs:b-7wmqje) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_tf2/CMakeLists.txt#L86)):*
> ```CMake
> # Manually register the environment hook because we didn't use an ament
> # function to install the python module
> _ament_cmake_python_register_environment_hook()
> ```

I'm very concerned about calling ament CMake macros with leading underscores.

Can this (and related change below) be split into a separate PR?
Or is it still necessary?
___
*[`drake_ros_viz/CMakeLists.txt` line 90 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORs9Mi0kY79OAV0mHs:-NORs9Mi0kY79OAV0mHt:b2nreh6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_viz/CMakeLists.txt#L90)):*
> ```CMake
> # Sets PYTHON_INSTALL_DIR
> ament_get_python_install_dir(python_install_dir)
> # Manually register the environment hook because we didn't use an ament
> ```

Same as above.


<!-- Sent from Reviewable.io -->

2023-03-20 17:20 UTC, adityapande-1995 commented
Work in progress, I'll open this for review once I've cleaned up CI and addressed the comments.

2023-03-29 22:30 UTC, adityapande-1995 commented
*[`drake_ros_core/src/module_py.cc` line 110 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORrWq01Asy-TtZO5Cd:-NRjUV1ED3afaECBABEy:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_core/src/module_py.cc#L110)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This alias should be listed at declaration scope of translation unit (i.e., inside namespace, not function)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-29 22:30 UTC, adityapande-1995 commented
*[`drake_ros_core/src/drake_ros_core/__init__.py` line 76 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORrnot7Oqq6PBVIaw-:-NRjUXcpEKd32K4haIP5:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_core/src/drake_ros_core/__init__.py#L76)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (pre-existing) Can you do case-sensitive alpha-sorting here?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-29 22:30 UTC, adityapande-1995 commented
*[`drake_ros_tf2/CMakeLists.txt` line 86 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORs0ET4EO_xDkRhYFr:-NRjU_HPB5MZsxOQP_iY:b-j3zsz6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_tf2/CMakeLists.txt#L86)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm very concerned about calling ament CMake macros with leading underscores.

Can this (and related change below) be split into a separate PR?
Or is it still necessary?
</blockquote></details>

Looks like that rule is not required anymore.


<!-- Sent from Reviewable.io -->

2023-03-29 22:30 UTC, adityapande-1995 commented
*[`drake_ros_viz/CMakeLists.txt` line 90 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORs9Mi0kY79OAV0mHs:-NRjUeB71SWJ4MZ4-uf6:b-j3zsz6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_viz/CMakeLists.txt#L90)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Looks like that rule is not required anymore.


<!-- Sent from Reviewable.io -->

2023-03-30 02:03 UTC, EricCousineau-TRI reviewed
> Reviewed 4 of 18 files at r6, 1 of 5 files at r8.
> Dismissed @IanTheEngineer from a discussion.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148)* status: 8 of 26 files reviewed, 1 unresolved discussion (waiting on @adityapande-1995, @IanTheEngineer, and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORtWrU8u39ehEO7PSv:-NRkF8EC8fk5A2DdMObS:b-896fix) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I would like us to land the following PRs before this one:
#205 - for consolidation and avoiding too many merge conflicts on that PR
#207 - to ensure this is all tested
</blockquote></details>

Done.

___
___
*[`drake_ros_viz/CMakeLists.txt` line 90 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NORs9Mi0kY79OAV0mHs:-NRkEzWO0ydNL3vEdR9M:bcgzp9s) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3f678f0111dddfcf8b003741ed28361ef357c4a6/drake_ros_viz/CMakeLists.txt#L90)):*
<details><summary><i>Previously, adityapande-1995 (Aditya Pande) wrote…</i></summary><blockquote>

Looks like that rule is not required anymore.
</blockquote></details>

OK Sweet!


<!-- Sent from Reviewable.io -->

2023-04-12 22:54 UTC, EricCousineau-TRI requested changes
Looks good, some comments at first pass!

> Reviewed 12 of 18 files at r6, 1 of 5 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-:-NSrfHD6BSNBYCPKAgG3:bk7zcr9)* status: all files reviewed, 4 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros/core/BUILD.bazel` line 69 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSrf71o7jHn_INQCh8x:-NSrf71o7jHn_INQCh8y:bspptxq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/core/BUILD.bazel#L69)):*
> ```Starlark
> )
> 
> ros_cc_test(
> ```

No testing for clock system.

Can you add focused (but small) unittest which verifies that this system functions as expected?
___
*[`drake_ros/drake_ros/core/cc_pybind.cc` line 98 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSreDbTAz5GPG7r1Sfo:-NSreDbTAz5GPG7r1Sfp:bras40e) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/drake_ros/core/cc_pybind.cc#L98)):*
> ```cpp
>   py::class_<DrakeRos>(m, "DrakeRos");
> 
>   using drake_ros::core::ClockSystem;
> ```

nit For consistency, can you move this close to the other `using` statements at top?
___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 21 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSreRIkB-rDESSRUtMI:-NSreRIkB-rDESSRUtMJ:b-jgnkha) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/drake_ros/core/qos_pybind.h#L21)):*
> ```objc
> }  // namespace drake_ros
> 
> namespace pybind11 {
> ```

nit If possible, can we pivot this to live in `drake_ros::drake_ros_py`, and then make `pybind11::detail` just use a "forwarded" version?
___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSrevrT1ofFzfjoWCPk:-NSrevrT1ofFzfjoWCPl:b-25sfti) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/drake_ros/core/qos_pybind.h#L25)):*
> ```objc
> // TODO(hidmic): rely on rclpy.qos.QoSProfile when and if a pybind11 binding
> // is introduced upstream. See https://github.com/ros2/rclpy/issues/843.
> template <>
> ```

nit No focused testing.

Can you add focused unittest on this class in Python, or perhpas add a TODO in the Bazel BUILD file?


<!-- Sent from Reviewable.io -->

2023-04-21 22:15 UTC, adityapande-1995 reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148)* status: 24 of 28 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[`drake_ros/core/BUILD.bazel` line 69 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSrf71o7jHn_INQCh8x:-NT_sIPvANEHjQ5fype7:b60w9kl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/core/BUILD.bazel#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

No testing for clock system.

Can you add focused (but small) unittest which verifies that this system functions as expected?
</blockquote></details>

Added a focused test, done
___
*[`drake_ros/drake_ros/core/cc_pybind.cc` line 98 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSreDbTAz5GPG7r1Sfo:-NT_sn-r35AtvihLqI7n:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/drake_ros/core/cc_pybind.cc#L98)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For consistency, can you move this close to the other `using` statements at top?
</blockquote></details>

Done
___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 21 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSreRIkB-rDESSRUtMI:-NT_sVeo-DyioXtUhIIY:b-h8cg01) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/drake_ros/core/qos_pybind.h#L21)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit If possible, can we pivot this to live in `drake_ros::drake_ros_py`, and then make `pybind11::detail` just use a "forwarded" version?
</blockquote></details>

Hmm, I'm not sure I understand. The typecasters are required to live in ``pybind11::detail`` namespace, right ?
___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSrevrT1ofFzfjoWCPk:-NT_sOgA0T46IztUaPoB:bhzhs3l) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/drake_ros/core/qos_pybind.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit No focused testing.

Can you add focused unittest on this class in Python, or perhpas add a TODO in the Bazel BUILD file?
</blockquote></details>

Added a todo for now. Is it okay if I implement this in a separate PR ?


<!-- Sent from Reviewable.io -->

2023-04-28 19:06 UTC, EricCousineau-TRI approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> pending remaining items

> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-:-NU8FhAZ08mvlwK5wwcP:b-mlcfr6)* status: all files reviewed, 1 unresolved discussion (waiting on @adityapande-1995)

___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 21 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSreRIkB-rDESSRUtMI:-NU8FQEEEDgL_lJDZ7Ny:btic5kh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/drake_ros/core/qos_pybind.h#L21)):*
<details><summary><i>Previously, adityapande-1995 (Aditya Pande) wrote…</i></summary><blockquote>

Hmm, I'm not sure I understand. The typecasters are required to live in ``pybind11::detail`` namespace, right ?
</blockquote></details>

They must be accessible from that namespace, but it is not requisite that the "guts" live in that namespace.
___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 25 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSrevrT1ofFzfjoWCPk:-NU8Fe033biqgyk66TbG:bnlyodo) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/drake_ros/core/qos_pybind.h#L25)):*
<details><summary><i>Previously, adityapande-1995 (Aditya Pande) wrote…</i></summary><blockquote>

Added a todo for now. Is it okay if I implement this in a separate PR ?
</blockquote></details>

OK yup!


<!-- Sent from Reviewable.io -->

2023-05-08 23:10 UTC, adityapande-1995 reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148)* status: 24 of 28 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 21 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NSreRIkB-rDESSRUtMI:-NUxcBKU3IXyPCKbRbFq:b8i1wsm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/8441a1d9423ca5aeed711b558506d3aca0d49a77/drake_ros/drake_ros/core/qos_pybind.h#L21)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

They must be accessible from that namespace, but it is not requisite that the "guts" live in that namespace.
</blockquote></details>

Done, moved to drake_ros_py, and inheriting from that struct in py::detail.


<!-- Sent from Reviewable.io -->

2023-05-11 15:02 UTC, EricCousineau-TRI approved these changes
> Reviewed 2 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148)* status: all files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer and @sloretz)

___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 23 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NVAKEhNEtdIbX5l7Uah:-NVAKEhNEtdIbX5l7Uai:bo24orn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/851abd356f3897849775762451e528ccb03190c3/drake_ros/drake_ros/core/qos_pybind.h#L23)):*
> ```objc
> namespace drake_ros {
> namespace drake_ros_py {
> using std::enable_if_t;
> ```

nit It's not great to have "incindental" `using` statements in a header file

Can you remove these using statements?


<!-- Sent from Reviewable.io -->

2023-05-11 15:42 UTC, IanTheEngineer approved these changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> I have requested a couple updates, but things look quite good overall. Thanks for iterating on this.

> Reviewed 2 of 2 files at r11, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-:-NVAST5k3clrLU6qOqWc:b-a2lteu)* status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 23 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NVAKEhNEtdIbX5l7Uah:-NVAP5KX7DWVVsdkAp3h:b-ic0dah) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/851abd356f3897849775762451e528ccb03190c3/drake_ros/drake_ros/core/qos_pybind.h#L23)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit It's not great to have "incindental" `using` statements in a header file

Can you remove these using statements?
</blockquote></details>

Agreed, these statements should be removed from this header.
___
*[`drake_ros/core/clock_system.cc` line 6 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NVARWSt3tDDqZ9vN1GB:-NVARWSt3tDDqZ9vN1GC:b-olf6vd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/851abd356f3897849775762451e528ccb03190c3/drake_ros/core/clock_system.cc#L6)):*
> ```cpp
> 
> using drake_ros_core::ClockSystem;
> using drake_ros_core::RosPublisherSystem;
> ```

Nit: Please update to the non-legacy namespace spelling of `drake_ros::core`.



_Code quote:_
```cpp
using drake_ros_core::ClockSystem;
using drake_ros_core::RosPublisherSystem;
```


<!-- Sent from Reviewable.io -->

2023-05-11 16:35 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148)* status: all files reviewed, 2 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 23 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NVAKEhNEtdIbX5l7Uah:-NVAei7zEEcnysIMoihR:b-rupdro) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/851abd356f3897849775762451e528ccb03190c3/drake_ros/drake_ros/core/qos_pybind.h#L23)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Agreed, these statements should be removed from this header.
</blockquote></details>

Working: Saw that this was b/c of macro. I have solution, will push.


<!-- Sent from Reviewable.io -->

2023-05-11 16:37 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/148)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @IanTheEngineer and @sloretz)

___
*[`drake_ros/drake_ros/core/qos_pybind.h` line 23 at r15](https://reviewable.io/reviews/RobotLocomotion/drake-ros/148#-NVAKEhNEtdIbX5l7Uah:-NVAfAhD6An2PlcRSTZq:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/851abd356f3897849775762451e528ccb03190c3/drake_ros/drake_ros/core/qos_pybind.h#L23)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Saw that this was b/c of macro. I have solution, will push.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-11 19:10 UTC, adityapande-1995 commented
> <img alt=":LGTM:" width="61" height="20" src="https://camo.githubusercontent.com/341bcbc4fc105a8a54332ced9ba9f1163b5fd81578777fffe7568934ec76d9d7/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67"> I have requested a couple updates, but things look quite good overall. Thanks for iterating on this.
> 
> > Reviewed 2 of 2 files at r11, 1 of 1 files at r15, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-:-NVAST5k3clrLU6qOqWc:b-a2lteu)_ status: all files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)
> 
> _[`drake_ros/drake_ros/core/qos_pybind.h` line 23 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NVAKEhNEtdIbX5l7Uah:-NVAP5KX7DWVVsdkAp3h:b-ic0dah) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/851abd356f3897849775762451e528ccb03190c3/drake_ros/drake_ros/core/qos_pybind.h#L23)):_
> 
> Previously, EricCousineau-TRI (Eric Cousineau) wrote…
> Agreed, these statements should be removed from this header.
> 
> _[`drake_ros/core/clock_system.cc` line 6 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/148#-NVARWSt3tDDqZ9vN1GB:-NVARWSt3tDDqZ9vN1GC:b-olf6vd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/851abd356f3897849775762451e528ccb03190c3/drake_ros/core/clock_system.cc#L6)):_
> 
> > ```c++
> > using drake_ros_core::ClockSystem;
> > using drake_ros_core::RosPublisherSystem;
> > ```
> 
> Nit: Please update to the non-legacy namespace spelling of `drake_ros::core`.
> 
> _Code quote:_
> 
> ```c++
> using drake_ros_core::ClockSystem;
> using drake_ros_core::RosPublisherSystem;
> ```

Done !

2023-05-11 20:48 UTC, EricCousineau-TRI approved these changes
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2023-05-11 21:29 UTC, merged