Add UFO Example
RobotLocomotion/drake-ros pull request #189
Opened 2022-11-04 21:33 UTC by sloretz

This adds an example of controlling a flying object using RViz, Drake-ROS, and the Drake systems framework.

Compiler warnings pointed out that the mass properties of the translucent lookout weren't being used, so I added them. Using them offsets the mass a little so that forces applied at the body's origin case the saucer to wobble.

[wobbly_ufo.webm](https://user-images.githubusercontent.com/4175662/200078122-1e88af8d-ea07-47af-8c60-8429fb01f7d7.webm)

2022-11-08 20:34 UTC, EricCousineau-TRI requested changes
Sweet, thanks!
I've made some initial comments to see if we can shrink down the size of the file and some additional nits.
Is it OK with you if we make these improvements in this PR?

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-:-NGNwlYw1h0rqCIMfc9t:b-thp9mo)* status: all files reviewed, 12 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros_examples/README.md` line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNtNVjCq9gCXYB3OLH:-NGNtNVk9yl_ZSB77slk:b-dga0eg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/README.md#L42)):*
> ```Markdown
> - [IIWA manipulator](./examples/iiwa_manipulator): an RViz visualization of a static IIWA arm.
> - [Multiple robots](./examples/multirobot): an RViz visualization of an array of Kuka LBR iiwa manipulators.
> - [UFO](./examples/multirobot): an RViz visualization of a flying object controlled with the Drake systems framework and commandedusing RViz.
> ```

nit Missing space between "command" and "using"
___
*[`drake_ros_examples/README.md` line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNtPZTCCS1Cwhzyb9Z:-NGNtPZTCCS1Cwhzyb9_:b-pydpg4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/README.md#L42)):*
> ```Markdown
> - [IIWA manipulator](./examples/iiwa_manipulator): an RViz visualization of a static IIWA arm.
> - [Multiple robots](./examples/multirobot): an RViz visualization of an array of Kuka LBR iiwa manipulators.
> - [UFO](./examples/multirobot): an RViz visualization of a flying object controlled with the Drake systems framework and commandedusing RViz.
> ```

nit Can you word-wrap this file to 80 character lines?
___
*[`drake_ros_examples/examples/ufo/README.md` line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNtb2aDM_Fk0f1DFIa:-NGNtb2aDM_Fk0f1DFIb:b-e3mm80) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/examples/ufo/README.md#L5)):*
> ```Markdown
> ## Overview
> 
> The UFO example shows how to use Drake-ROS and the Drake systems framework to
> ```

nit For consistency, should use either `Drake ROS` or `drake-ros`.
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNvyGS0oSgeS9Yjd-Y:-NGNvyGS0oSgeS9Yjd-Z:b-vyqj9f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/examples/ufo/ufo.cc#L64)):*
> ```cpp
> 
> /// Adds body named FlyingSaucer to the multibody plant.
> void AddFlyingSaucer(MultibodyPlantd* plant) {
> ```

Is it possible to move this into a SDFormat file?
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNwB2NA8K9rgn-PLgj:-NGNwB2NA8K9rgn-PLgk:bkv8e0s) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/examples/ufo/ufo.cc#L146)):*
> ```cpp
> }
> 
> class SplitRigidTransform : public LeafSystemd {
> ```

While I understand the desire for piping vectors around, I think it'd be best to instead just plumb around `SpatialForced` and `RigidTransformd` as `Value<>` instead.
I think that would then shrink the size of this file (along with porting the model to SDFormat)

See examples here, derived from Anzu:
https://github.com/EricCousineau-TRI/repro/blob/6048da3/drake_stuff/python_profiling/components_cc_py.cc
(context: https://stackoverflow.com/a/74201119/7829525 - ignore the codestyle, as it's meant to illustrate hacking / prototyping)
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 262 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNuCM3-A6KnDjHM6wV:-NGNuCM4DyIN3kcbMVsF:b1awx7x) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/examples/ufo/ufo.cc#L262)):*
> ```cpp
>   //  output: Vector3d f_S_W
>   auto* forces_pid_controller = builder.AddSystem<PidControllerd>(
>       Vector3d{100.0f, 100.0f, 2500.0f}, Vector3d{0.0f, 0.0f, 50.0f},
> ```

nit Unclear why these gains were chosen.
Can you add comment, e.g. `// Empirically chosen gains. May need tuning`?
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 262 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNuKTB7aG2V__DXEgf:-NGNuKTC5m1-w2UCwXSD:b-cp8c70) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/examples/ufo/ufo.cc#L262)):*
> ```cpp
>   //  output: Vector3d f_S_W
>   auto* forces_pid_controller = builder.AddSystem<PidControllerd>(
>       Vector3d{100.0f, 100.0f, 2500.0f}, Vector3d{0.0f, 0.0f, 50.0f},
> ```

nit Having a non-zero integrator gain implies that you're fighting gravity, i.e. not including a feedforward component in your controller.

Can you add a TODO, e.g. something like this?
```
// TODO(eric.cousineau): Add in feedforward component and remove need for integrator gains.
```
Or if you'd like to add this yourself, I can provide example (if you need it).
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 362 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNvU4N5b4Z5m9tBBM9:-NGNvU4N5b4Z5m9tBBMA:bdkh0ds) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/examples/ufo/ufo.cc#L362)):*
> ```cpp
> class RosPoseGlue : public LeafSystemd {
>  public:
>   explicit RosPoseGlue(double extra_z = 0.0) : extra_z_(extra_z) {
> ```

Hm... `extra_z` has an old smell to it.

Instead of this, can you instead make a separate, simpler `RigidTransformPremultiplier`?
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 376 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNuicVEMPOQcMQDLfK:-NGNuicW8t4VufUIWzRs:bgfiiih) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/examples/ufo/ufo.cc#L376)):*
> ```cpp
> 
>  private:
>   void CalcDrakeTransform(const Contextd& context,
> ```

These are redundant w.r.t `geometry_conversions`.

Can you use them instead?
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNuzhz-2RBEZxQKlnA:-NGNuzhz-2RBEZxQKlnB:buf137e) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/examples/ufo/ufo.cc#L427)):*
> ```cpp
>                   ufo_controller->GetInputPort("X_WS"));
> 
>   // TODO(sloretz) replace when RobotLocomotion/drake#16923 is solved
> ```

Solved by yours truly ;)
https://github.com/RobotLocomotion/drake/pull/18171

Though I'm not sure if that solves this problem? Or did you have another intent?
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 465 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNvjmi9DmKaYtoimlR:-NGNvjmj9e1If3IY9TY5:bdecet5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/examples/ufo/ufo.cc#L465)):*
> ```cpp
> }
> 
> std::unique_ptr<Contextd> SetInitialConditions(Diagramd* diagram) {
> ```

Name of function and actual execution are not the same - this also creates a context.

Can you either rename the function, or change the function to mutate an existing context?
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 474 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNvtrb-s8By8G3wrHV:-NGNvtrb-s8By8G3wrHW:b-sk6sgg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a1340784ce6d8ff4efc6be2c6f3f69dfe12f8a2a/drake_ros_examples/examples/ufo/ufo.cc#L474)):*
> ```cpp
>       diagram->Ge [...]

2022-11-10 01:33 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/189)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_ros_examples/README.md` line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNtNVjCq9gCXYB3OLH:-NGS_N4U3aN2-oF0Xzt8:b-ridjtc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/README.md#L42)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Missing space between "command" and "using"
</blockquote></details>

8e4c1e76595f2c0396ae5a7c82674eb2cf0c8ceb
___
*[`drake_ros_examples/README.md` line 42 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNtPZTCCS1Cwhzyb9Z:-NGS_NL57zaLObjN1zFz:b-ridjtc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/README.md#L42)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you word-wrap this file to 80 character lines?
</blockquote></details>

8e4c1e76595f2c0396ae5a7c82674eb2cf0c8ceb
___
*[`drake_ros_examples/examples/ufo/README.md` line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNtb2aDM_Fk0f1DFIa:-NGS_hpv0PZrtMbJWzG7:b-24kr9z) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/README.md#L5)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For consistency, should use either `Drake ROS` or `drake-ros`.
</blockquote></details>

0af4228876131909334f94cdf9d1fd6a9f34a3fb
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 64 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNvyGS0oSgeS9Yjd-Y:-NGT02Wc-SczMEfuGN9J:beq28on) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L64)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is it possible to move this into a SDFormat file?
</blockquote></details>

Moved to sdformat files in 728ef17
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNwB2NA8K9rgn-PLgj:-NGU7roVD-wjCPWGL6Ye:bhlh9nr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L146)):*
> While I understand the desire for piping vectors around, I think it'd be best to instead just plumb around SpatialForced and RigidTransformd as Value<> instead.

I would love to use those types instead of vectors! I thought I was forced to use vectors if I wanted to reuse systems like `PidController`because that's what it's input/output port types are.

I see the example you linked has fewer, but bigger LeafSystems. There seems to be more normal looking C++ logic and less plumbing through the Drake systems framework. Is that what you'd like to see instead? That is, A `SaucerController` which is just one `LeafSystem` with gravity feedforward and PID code inside instead of a `Diagram` of smaller controllers doing the individual pieces of that?
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 262 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNuCM3-A6KnDjHM6wV:-NGTsV21CD6tkyeVhf4P:bglim8f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L262)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why these gains were chosen.
Can you add comment, e.g. `// Empirically chosen gains. May need tuning`?
</blockquote></details>

74c1a20
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 262 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNuKTB7aG2V__DXEgf:-NGU7gtEAMCSXrBAvf5W:b7cm3ku) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L262)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Having a non-zero integrator gain implies that you're fighting gravity, i.e. not including a feedforward component in your controller.

Can you add a TODO, e.g. something like this?
```
// TODO(eric.cousineau): Add in feedforward component and remove need for integrator gains.
```
Or if you'd like to add this yourself, I can provide example (if you need it).
</blockquote></details>

Replaced I gain with gravity feedforward in cb1b6d1
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 465 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNvjmi9DmKaYtoimlR:-NGT0dxw2Y31WOWmKU-M:b3ewuj6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L465)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Name of function and actual execution are not the same - this also creates a context.

Can you either rename the function, or change the function to mutate an existing context?
</blockquote></details>

Renamed to `CreateInitialConditions` in d0b49e1
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 474 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNvtrb-s8By8G3wrHV:-NGT0H9O4AeIECyxAWnH:b-yw3bpr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L474)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW I think this is the default, no? If so, why not just remove?
</blockquote></details>

Removed in d0b49e1


<!-- Sent from Reviewable.io -->

2022-11-28 23:40 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/189)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNwB2NA8K9rgn-PLgj:-NHafiad5DY_mBxCoK_M:b-jvqrx5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L146)):*
> Additionally, some of the code that I linked to is complex because it's computing forces against a frame, rather than body.
You can greatly simplify that code (I can help if you like!).

Yes please. I'm not sure what it means to compute forces against a body, but I'd like to learn.

Used a single LeafSystem instead of reusing Drake's built in systems in 7f0d9fcb89c705d06704edabe8b10f5c11ef36bf  . I'm not sure about how `X_WS` from the previous step is being stored. I copied what `DiscreteDerivative` seems to be doing, but I'm not sure what would happen if the state was updated faster than the input measurement and the force from the derivative term went to zero.
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 362 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNvU4N5b4Z5m9tBBM9:-NI-TlKc0LW45BHfQG3b:bu0g8zs) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L362)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... `extra_z` has an old smell to it.

Instead of this, can you instead make a separate, simpler `RigidTransformPremultiplier`?
</blockquote></details>

Added `RigidTransformPremultiplier` in 8de9eb8
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 376 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNuicVEMPOQcMQDLfK:-NI-UrtV3vx1yOEpazUg:b-d9thrx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L376)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

These are redundant w.r.t `geometry_conversions`.

Can you use them instead?
</blockquote></details>

Using geometry_conversions in de58267
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNuzhz-2RBEZxQKlnA:-NI-_GhP2MPdlKd65z8M:bcfzisb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L427)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Solved by yours truly ;)
https://github.com/RobotLocomotion/drake/pull/18171

Though I'm not sure if that solves this problem? Or did you have another intent?
</blockquote></details>

Ah, yeah I see how that resolves that ticket. I think when I wrote that I wanted a short cut to go from the `SpatialForce` output from the controller to a  list of `ExternallyAppliedSpatialForce` to be input  into a multibody plant. IIUC `ExternallyAppliedSpatialForceMultiplexer` offers a way to concatenate vectors of `ExternallyAppliedSpatialForce`, but a system still has to construct a list of `ExternallyAppliedSpatialForce` in the first place. I replaced the `TODO` with a comment saying that's what the `AppliedSpatialForceVector` system is doing in c4799f1.
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGWaLTe4A7-WCARozxS:-NHQiKTK7s2sicXGubYi:b-8zm9ys) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb1b6d1d16e3111fd14bf83419d1f511d95e740d/drake_ros_examples/examples/ufo/ufo.cc#L60)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Apologies for dumb question, but does ROS 2 not have a resource-retriever type affordance?
(or are you using index directly because you'd like the file path, and not just content stream?)
</blockquote></details>

It does, and `resource_retriever` `package://` URLs do pretty much exactly this. I forgot about it :no_mouth:. 

In 6826486 I had to pass the package path into the `PackageMap()` anyways for the `<include>`'s to work, so I didn't make it use resource retriever.
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGWatF_9O_08WcN37n5:-NHVjzoL7CTCTWcZ8_7t:b32f687) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb1b6d1d16e3111fd14bf83419d1f511d95e740d/drake_ros_examples/examples/ufo/ufo.cc#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Rather than compose these scenes using code, can I ask that you make a `ufo_scene.sdf` that uses merge-include to compose the models?

\cc @azeey
</blockquote></details>

6826486
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 423 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGWad9bDQVbLqnN5cwC:-NHVaxR4-Xev1vIAFi0C:b-7zbygy) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb1b6d1d16e3111fd14bf83419d1f511d95e740d/drake_ros_examples/examples/ufo/ufo.cc#L423)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Hm... This is a rather small function now.

Can I ask that you inline the code?
</blockquote></details>

Inlined in 81fac61ba4325ee18e8612ef798c6281785d09c2
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 451 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGWbRO18gDs50o_Rii1:-NHVaw_Q62c1AL2Si5l3:b-7zbygy) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb1b6d1d16e3111fd14bf83419d1f511d95e740d/drake_ros_examples/examples/ufo/ufo.cc#L451)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Ownership movement here is a bit confusing; I'd like to avoid having first-time users potentially seeing this.

Can I ask that you also inline the `RunSimulation` function for now?
</blockquote></details>

Inlined in 81fac61ba4325ee18e8612ef798c6281785d09c2


<!-- Sent from Reviewable.io -->

2022-12-05 15:05 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 
Reneging from comment above, I'd say we could land this on `main` then do any further refinements off of `master`!

> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-:-NIXoMeT-SUuQerSsVaV:b-6cqthu)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 146 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNwB2NA8K9rgn-PLgj:-NIXo9886vQClVpeEAUF:b-bmop4f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L146)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

> Additionally, some of the code that I linked to is complex because it's computing forces against a frame, rather than body.
You can greatly simplify that code (I can help if you like!).

Yes please. I'm not sure what it means to compute forces against a body, but I'd like to learn.

Used a single LeafSystem instead of reusing Drake's built in systems in 7f0d9fcb89c705d06704edabe8b10f5c11ef36bf  . I'm not sure about how `X_WS` from the previous step is being stored. I copied what `DiscreteDerivative` seems to be doing, but I'm not sure what would happen if the state was updated faster than the input measurement and the force from the derivative term went to zero.
</blockquote></details>

Thanks! For now, I'd say let's get this merged in. Then I can (hopefully) file a follow-up PR!

And to be clear, this is less about "don't reuse Drake systems", but rather "don't have too much systems-level indirection if we need to curate our control spaces etc."
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 427 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGNuzhz-2RBEZxQKlnA:-NIXnmE70ACh7-_72LkS:b-vmrj4e) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ada8c10c89c811569efe691ad4d08007088b3ce/drake_ros_examples/examples/ufo/ufo.cc#L427)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Ah, yeah I see how that resolves that ticket. I think when I wrote that I wanted a short cut to go from the `SpatialForce` output from the controller to a  list of `ExternallyAppliedSpatialForce` to be input  into a multibody plant. IIUC `ExternallyAppliedSpatialForceMultiplexer` offers a way to concatenate vectors of `ExternallyAppliedSpatialForce`, but a system still has to construct a list of `ExternallyAppliedSpatialForce` in the first place. I replaced the `TODO` with a comment saying that's what the `AppliedSpatialForceVector` system is doing in c4799f1.
</blockquote></details>

SGTM, thanks!
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 60 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NGWaLTe4A7-WCARozxS:-NIXmaCMAQOY2AGRHSyF:bh0azgh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cb1b6d1d16e3111fd14bf83419d1f511d95e740d/drake_ros_examples/examples/ufo/ufo.cc#L60)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

It does, and `resource_retriever` `package://` URLs do pretty much exactly this. I forgot about it :no_mouth:. 

In 6826486 I had to pass the package path into the `PackageMap()` anyways for the `<include>`'s to work, so I didn't make it use resource retriever.
</blockquote></details>

OK Excellent! At some point, we should provide affordance to leverage ament index with Drake's package map - which I see you've mentioned below.
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 157 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NIXnHNfD3Cwa79DFRan:-NIXnHNfD3Cwa79DFRao:b-uasxfa) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c4799f18c4c72d9485faf602bc4c96c1d38ec18b/drake_ros_examples/examples/ufo/ufo.cc#L157)):*
> ```cpp
>     // Orientation PD controller - proportional
>     t_S_W +=
>         (R_error.ToRollPitchYaw().vector().array() * kp_rot_.array()).matrix();
> ```

BTW I don't love RPY for error terms, but I don't have succinct mathematical reasoning yet.
___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 312 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NIXnrIbD_RnIa8d426A:-NIXnrIcCoblmDXIU0qI:b2mto9z) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c4799f18c4c72d9485faf602bc4c96c1d38ec18b/drake_ros_examples/examples/ufo/ufo.cc#L312)):*
> ```cpp
>   auto ufo_controller = builder.AddSystem<FlyingSaucerController>(
>       saucer_mass, plant.gravity_field().gravity_vector(),
>       Vector3d{100.0, 100.0, 100.0},  // kp & kd chosen by trial and error
> ```

nit This is a bit hard to read. Can you try using param struct? e.g.,
https://github.com/EricCousineau-TRI/repro/blob/3784a154a094a59538cf6ae150f8633ef9cdfcd7/drake_stuff/python_profiling/components_cc_py.cc#L207-L216


<!-- Sent from Reviewable.io -->

2022-12-29 01:07 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/189)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[`drake_ros_examples/examples/ufo/ufo.cc` line 312 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-NIXnrIbD_RnIa8d426A:-NKQNfKv8uI-r0o6fu3F:b3ayjfz) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c4799f18c4c72d9485faf602bc4c96c1d38ec18b/drake_ros_examples/examples/ufo/ufo.cc#L312)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This is a bit hard to read. Can you try using param struct? e.g.,
https://github.com/EricCousineau-TRI/repro/blob/3784a154a094a59538cf6ae150f8633ef9cdfcd7/drake_stuff/python_profiling/components_cc_py.cc#L207-L216
</blockquote></details>

Added param struct in 9c861c6

It looks like the linked example is using designated initializes, which is a C++ 20 feature. Drake seems to be using c++ 17: https://github.com/RobotLocomotion/drake/blob/4eaa4be3e8ab7ff07b4f5cd7267e6b2bdf4f3d81/tools/cc_toolchain/bazel.rc#L5-L6 . I used a temporary variable instead.


<!-- Sent from Reviewable.io -->

2023-03-17 18:05 UTC, sloretz reviewed
Updated to `main`, but I'll hold off on bazelizing until https://github.com/RobotLocomotion/drake-ros/pull/133 merges so this can make use of `ament_index_share_files` to access the world and models.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/189#-:-NQkjqJD7XIH5EoyVAvC:b-rdse3r)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2025-01-17 17:43 UTC, jwnimmer-tri commented
Closing as stale.

2025-01-17 17:43 UTC, closed without merging