[doc] Add "Alternatives" for Bazel and ROS 2 workflows; mention ApexAI/rules_ros
RobotLocomotion/drake-ros pull request #194
Opened 2022-11-18 16:42 UTC by EricCousineau-TRI

Per internal discussion.

Will be filing an issue for RFC and possible symmetry

2022-11-18 16:49 UTC, EricCousineau-TRI reviewed
+@sloretz for review, please!
\cc @cottsay 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/194#-:-NHAd61sE6XVXV8v_AYS:bpp5bcs)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2022-11-18 22:30 UTC, mvukov commented
Here is a yet another alternative https://github.com/mvukov/rules_ros2/ ;).

2022-11-20 20:49 UTC, EricCousineau-TRI reviewed
Done, thanks! I've tried to add in a summary here. If you have a chance, could you take a look to see if it's fair / accurate?

And it cool if I file issue against your repo for similar? If you wanna link here, or add your own analysis, I'm good either way!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/194#-:-NHLmzBcBqQmJ0DTupxy:b-1vtwpa)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2022-11-20 20:55 UTC, mvukov reviewed
Very nice summary, thanks!

2022-11-20 20:55 UTC, mvukov commented on bazel_ros2_rules/ros2/README.md
> +provides scaffolding or affordances for Bazel tooling, and until pacakges
Nit: packages.

2022-11-20 20:56 UTC, mvukov commented
> And it cool if I file issue against your repo for similar? If you wanna link here, or add your own analysis, I'm good either way!

Sure, you can either open an issue or make a PR.

2022-11-20 20:58 UTC, EricCousineau-TRI reviewed
Aye, I'll make a quick PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/194#-:-NHLpL9c9cWTgL-aWcoZ:bcq6zri)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/README.md` line 144 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/194#-NHAbieMxeaUI8SqGWPI-r2-144:-NHLpJ2g0e7pRpMbaRyY:bxsser9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2ca6ff8883bb837ad958c0d0aca1b5115b01de73/bazel_ros2_rules/ros2/README.md#L144)):*
<details><summary><i>Previously, mvukov (Milan Vukov) wrote…</i></summary><blockquote>

Nit: packages.
</blockquote></details>

Done 0ef58e9, thanks!


<!-- Sent from Reviewable.io -->

2022-11-20 21:03 UTC, EricCousineau-TRI commented
--> https://github.com/mvukov/rules_ros2/pull/24

2022-11-23 12:06 UTC, kilian-funk commented
@EricCousineau-TRI This looks good to me. Thanks for referencing the ApexAI/rules_ros here.

2022-11-28 15:45 UTC, EricCousineau-TRI commented
See also discussions in https://discourse.ros.org/t/adding-bazel-as-an-official-alternative-build-system-for-ros2-iron/28476

2022-11-29 00:51 UTC, sloretz requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/194)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`bazel_ros2_rules/ros2/README.md` line 186 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/194#-NI-qgik8P3iWuQc-hVf:-NI-qgik8P3iWuQc-hVg:buz6us6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0ef58e9b1187388655f315b5c48444ab45dbc478/bazel_ros2_rules/ros2/README.md#L186)):*
> ```Markdown
> - Writing Python bindings in `pybind11` against other C++ libraries that have
>   their own bindings - e.g., [Drake](https://drake.mit.edu/).
>   - There is *some* affordance for leveraging `pybind11` against ROS 2 RMW
> ```

I don't see anything pybind11 specific in `bazel_ros2_rules`. Is this actually a feature of this approach? I know we use pybind11 in `drake_ros_*` but that seems unrelated to the generated bazel rules.

```
grep bazel_ros2_rules/ -r -e "pybind"
```


<!-- Sent from Reviewable.io -->

2022-11-29 13:47 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/194)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/README.md` line 186 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/194#-NI-qgik8P3iWuQc-hVf:-NI2cxJhCUYJSgZX7kQj:b-qo0wcf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0ef58e9b1187388655f315b5c48444ab45dbc478/bazel_ros2_rules/ros2/README.md#L186)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I don't see anything pybind11 specific in `bazel_ros2_rules`. Is this actually a feature of this approach? I know we use pybind11 in `drake_ros_*` but that seems unrelated to the generated bazel rules.

```
grep bazel_ros2_rules/ -r -e "pybind"
```
</blockquote></details>

Done. You're right! But I still want to emphasize the examples portion, so I've rescoped this statement as such.


<!-- Sent from Reviewable.io -->

2022-11-29 22:43 UTC, sloretz approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2022-11-29 23:27 UTC, EricCousineau-TRI commented
Thanks!

2022-11-29 23:27 UTC, merged