Fix bazel_ros2_rules handling of console bridge
RobotLocomotion/drake-ros pull request #195
Opened 2022-11-18 20:54 UTC by sloretz

The `@ros2//:console_bridge_vendor_cc` wasn't including any libraries to link on either Focal or Jammy. 

The first problem applies to both Focal and Jammy. The `bazel_ros2_rules` package assumes any found package will have CMake targets to link against, but the `console_bridge_vendor` doesn't have any. It expects users to `find_package(console_bridge)` and use that instead. This is fixed with a special case in the `ament_cmake_CMakeLists.txt` template to use `console_bridge` when `console_bridge_vendor` is requested.

The second problem applies only to`bazel_ros2_rules` on Jammy. The vendor package [uses the system package on Jammy because the version is new enough](https://github.com/ros2/console_bridge_vendor/blob/44389a5e8205fd3040c0ef8d0c452ac671786d09/CMakeLists.txt#L100-L105). However, the `libconsole_bridge.so*` library is filtered out as it's a system dependency. The fix is to add a special case using `-L` and `-l:` as link flags instead of filtering the library out altogether.

2022-11-18 20:54 UTC, sloretz reviewed
+@ericcousineau-tri for review please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-:-NHBWPNn6PDN22IsxXea:btxkahr)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2022-11-19 21:41 UTC, EricCousineau-TRI requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with some traceability and style nits
Thanks!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-:-NHGpjx6EB-IV8NVyXRC:bp39tp6)* status: all files reviewed, 5 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGpbD-EtwPAXpRv2di:-NHGpbD-EtwPAXpRv2dj:b8ykahf) (no related file):*
We should confirm testing on Anzu.
I may get to it in some random hack time; otherwise, can I ask you to do this when we return from break?

___
___
*[`bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py` line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGoSUKAYt-lGf4YZuQ:-NHGoSUL0jCsh1mY3thQ:b-y7wuho) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d79a1fc0e51843f2f48595884dea699d6c7deb3e/bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py#L68)):*
> ```Python
>                 continue
>             if is_system_library(library):
>                 if library.startswith('/usr/local'):
> ```

BTW Ah, yuck! We should avoid `/usr/local` IMO, at least on Linux: #196
___
*[`bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py` line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGoJjRD2T9GOk60Ndv:-NHGoJjRD2T9GOk60Ndw:b-dswx9t) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d79a1fc0e51843f2f48595884dea699d6c7deb3e/bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py#L70)):*
> ```Python
>                 if library.startswith('/usr/local'):
>                     local_link_libraries.append(library)
>                 if os.path.basename(library).startswith("libconsole_bridge"):
> ```

nit I envision this will happen with more packages.

Can we start keeping a manual manifest here for now?
Alternatively, is there a way to automatically determine this?
___
*[`bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in` line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGpRsm3Fy6R1E1BjYA:-NHGpRsn8mU5il28OdjQ:b2qbpxv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d79a1fc0e51843f2f48595884dea699d6c7deb3e/bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in#L43)):*
> ```
>   # TODO(sloretz) How to get targets from externalproject_add based vendor
>   # packages?
>   find_package(console_bridge REQUIRED)
> ```

nit Why is this not a defect in upstream `console_bridge`?
___
*[`ros2_example_bazel_installed/WORKSPACE` line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGpX3sBWiZ9KpCq4Wf:-NHGpX3sBWiZ9KpCq4Wg:bjhubk3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d79a1fc0e51843f2f48595884dea699d6c7deb3e/ros2_example_bazel_installed/WORKSPACE#L50)):*
> ```Starlark
>     "ros2cli_common_extensions",
>     "tf2_py",
>     "console_bridge_vendor",
> ```

nit Can you alpha-sort this list, and add a comment to keep it as such?


<!-- Sent from Reviewable.io -->

2022-11-20 12:07 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/195)* status: all files reviewed, 4 unresolved discussions (waiting on @sloretz)

___
*[`bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in` line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGpRsm3Fy6R1E1BjYA:-NHJvwfW14BSkE6ywluI:b-keg67p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d79a1fc0e51843f2f48595884dea699d6c7deb3e/bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in#L43)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why is this not a defect in upstream `console_bridge`?
</blockquote></details>

Ah, sorry - `console_bridge_vendor`?


<!-- Sent from Reviewable.io -->

2022-11-21 17:29 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/195)* status: all files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in` line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGpRsm3Fy6R1E1BjYA:-NHQCrlA2HkLTIaUv7UE:b-z9gafe) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d79a1fc0e51843f2f48595884dea699d6c7deb3e/bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in#L43)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, sorry - `console_bridge_vendor`?
</blockquote></details>

`console_bridge_vendor`'s job is to provide `console_bridge` on platforms that don't have it (like Windows). The best vendor package wouldn't exist at all, but the next best thing is that downstream only has to refer to them in the `package.xml`. That's why it's not a defect in `console_bridge_vendor` - ideally no one would `find_package(console_bridge_vendor)` at all.


<!-- Sent from Reviewable.io -->

2022-11-21 18:10 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/195)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py` line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGoJjRD2T9GOk60Ndv:-NHQLvAKAleIz04_bl40:bnf6qp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d79a1fc0e51843f2f48595884dea699d6c7deb3e/bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py#L70)):*
Is this what you had in mind for `manifest`? efcb87a6ea9c9b5410cadc05af2892f7f1279579

>  Alternatively, is there a way to automatically determine this?

I think this requires a human in the loop. A package not-providing any targets is suspicious, but maybe it's just providing CMake macros. A package ending in `_vendor` is also suspicious, but if it is deferring to a system library we don't automatically know what that library is.
___
*[`ros2_example_bazel_installed/WORKSPACE` line 50 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGpX3sBWiZ9KpCq4Wf:-NHQNRvn1vXQwrAcVE4N:b53ajiw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d79a1fc0e51843f2f48595884dea699d6c7deb3e/ros2_example_bazel_installed/WORKSPACE#L50)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you alpha-sort this list, and add a comment to keep it as such?
</blockquote></details>

Sorted and added comment 5c794c379569925ffc2a786fa63039f6fd727fa8


<!-- Sent from Reviewable.io -->

2022-11-21 19:39 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/195)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGpbD-EtwPAXpRv2di:-NHQgoRd8p29lBglW00l:b3u3q4j) (no related file):*
> We should confirm testing on Anzu.
> I may get to it in some random hack time; otherwise, can I ask you to do this when we return from break?

Opened Anzu PR showing that this fixes the issue there

___


<!-- Sent from Reviewable.io -->

2022-11-21 21:29 UTC, EricCousineau-TRI approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGpbD-EtwPAXpRv2di:-NHR58mEA-adbtNmfNwu:bhcs7ye) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

> We should confirm testing on Anzu.
> I may get to it in some random hack time; otherwise, can I ask you to do this when we return from break?

Opened Anzu PR showing that this fixes the issue there
</blockquote></details>

Sweet, confirmed locally w/ PR as well, thanks!

___
___
*[`bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py` line 70 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGoJjRD2T9GOk60Ndv:-NHR33sY1ylaN0rGMd7N:b-lyqzcx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d79a1fc0e51843f2f48595884dea699d6c7deb3e/bazel_ros2_rules/ros2/resources/ros2bzl/scraping/ament_cmake.py#L70)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Is this what you had in mind for `manifest`? efcb87a6ea9c9b5410cadc05af2892f7f1279579

>  Alternatively, is there a way to automatically determine this?

I think this requires a human in the loop. A package not-providing any targets is suspicious, but maybe it's just providing CMake macros. A package ending in `_vendor` is also suspicious, but if it is deferring to a system library we don't automatically know what that library is.
</blockquote></details>

Yup, thanks!
(Regex may have been more than necessary, but works for now!)

And gotcha on requiring human in the loop. I guess I don't understand full intent of ROS vendor packages, but I have posted (non-blocking) question below.
___
*[`bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in` line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/195#-NHGpRsm3Fy6R1E1BjYA:-NHR3EKJ93heXvEqEZuu:b9z1470) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/d79a1fc0e51843f2f48595884dea699d6c7deb3e/bazel_ros2_rules/ros2/resources/templates/ament_cmake_CMakeLists.txt.in#L43)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

`console_bridge_vendor`'s job is to provide `console_bridge` on platforms that don't have it (like Windows). The best vendor package wouldn't exist at all, but the next best thing is that downstream only has to refer to them in the `package.xml`. That's why it's not a defect in `console_bridge_vendor` - ideally no one would `find_package(console_bridge_vendor)` at all.
</blockquote></details>

I guess I'm confused as to the purpose of `_vendor` packages. I would have thought they not only provide "provisioning traceability" (e.g. a `rosdep` key for installing the package), but also a dependency on the package itself to then be used via `target_link_libraries()`.

Can I ask if there is a playbook on what vendor packages should look like?
(non-blocking, so we can merge onwards!)


<!-- Sent from Reviewable.io -->

2022-11-21 21:30 UTC, merged