Update for Rolling PublisherBase and SubscriptionBase API change
RobotLocomotion/drake-ros pull request #210
Opened 2023-01-11 23:15 UTC by sloretz

APIs we're using changed in https://github.com/ros2/rclcpp/pull/2066 which is released in RCLCPP 18.0.0 in ROS ROlling. This PR uses the updated API.

Fixes #208

2023-01-16 14:53 UTC, EricCousineau-TRI requested changes
+@EricCousineau-TRI for review

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-:-NLv3OPG8coO3pjaST3Q:byybt48)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NLv3T8Q700-IuUrFads:-NLv3T8Q700-IuUrFadt:b-a4h378) (no related file):*
CI is still failing - might you be able to fix those errors?

___


<!-- Sent from Reviewable.io -->

2023-01-16 14:55 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NLv3c-YDoReIvLqZTfY:-NLv3c-YDoReIvLqZTfZ:babqy76) (no related file):*
I'm concerned about such a breaking change like this.
Does ROS 2 have a stability guidelines for things like this, and what to expect for rolling vs. stable release?

e.g. for Drake:
- https://drake.mit.edu/stable.html
- https://drake.mit.edu/code_review_checklist.html (see deprecation)

___


<!-- Sent from Reviewable.io -->

2023-01-17 19:08 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NLv3T8Q700-IuUrFads:-NM01jpb10sgLXWXrIdS:bh9d6cs) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

CI is still failing - might you be able to fix those errors?
</blockquote></details>

Working

___
*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NLv3c-YDoReIvLqZTfY:-NM01q332X_64mx-Kk2P:b-pygfgv) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm concerned about such a breaking change like this.
Does ROS 2 have a stability guidelines for things like this, and what to expect for rolling vs. stable release?

e.g. for Drake:
- https://drake.mit.edu/stable.html
- https://drake.mit.edu/code_review_checklist.html (see deprecation)
</blockquote></details>

ROS 2 has different guidelines for LTS, non-LTS, and Rolling. In stable releases you can expect core packages like rclcpp to be API and ABI stable for the length of the release. For Rolling there's no stability guarantee. It is the latest code and may contain API changes.

https://ros.org/reps/rep-2000.html#support
https://www.ros.org/reps/rep-2002.html#support-status

___


<!-- Sent from Reviewable.io -->

2023-02-02 22:06 UTC, sloretz commented
CI is failing because of a bug in `rosbag2_performance_benchmarking`. Fix upstream: https://github.com/ros2/rosbag2/pull/1242

2023-02-08 16:57 UTC, cottsay approved these changes

2023-02-08 18:27 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NLv3T8Q700-IuUrFads:-NNmH-Ew0fsih8pQ1WMp:b-896fix) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Working
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-02-16 14:04 UTC, EricCousineau-TRI requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, thanks!

> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-:-NOPXa195MYeBv5lZwC3:bpqxd5f)* status: all files reviewed, 4 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NLv3c-YDoReIvLqZTfY:-NOPWs1f7R-gd792IcUk:b-do4jc2) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

ROS 2 has different guidelines for LTS, non-LTS, and Rolling. In stable releases you can expect core packages like rclcpp to be API and ABI stable for the length of the release. For Rolling there's no stability guarantee. It is the latest code and may contain API changes.

https://ros.org/reps/rep-2000.html#support
https://www.ros.org/reps/rep-2002.html#support-status
</blockquote></details>

OK Gotcha, thanks for the update!

___
___
*[`.github/workflows/main.yml` line 63 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NOPXIwL4Jx_AXvjaDt9:-NOPXIwL4Jx_AXvjaDtA:bfruipi) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/f39f8fd537af024a57c7e001af8e0aa2a570a4d3/.github/workflows/main.yml#L63)):*
> ```YAML
>           # TODO(sloretz) Use bazel_ros2_rules/ros2/compute_system_rosdeps.py to de-duplicate rosdep invocation knowledge
>           SHARE_DIRS=`find /opt/ros/${{matrix.ros_distro}} -maxdepth 2 -name share -type d`
>           # TODO(sloretz) remove rosbag2_performance_benchmarking_msgs when https://github.com/ros2/rosbag2/pull/1242 lands
> ```

nit Consider qualifying statement, "remove --skip-keys entry for rosbag2_performance_benchmarking_msgs when"
___
*[`.github/workflows/main.yml` line 63 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NOPXRAV91BJs3qNplPM:-NOPXRAV91BJs3qNplPN:btj9c0i) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/f39f8fd537af024a57c7e001af8e0aa2a570a4d3/.github/workflows/main.yml#L63)):*
> ```YAML
>           # TODO(sloretz) Use bazel_ros2_rules/ros2/compute_system_rosdeps.py to de-duplicate rosdep invocation knowledge
>           SHARE_DIRS=`find /opt/ros/${{matrix.ros_distro}} -maxdepth 2 -name share -type d`
>           # TODO(sloretz) remove rosbag2_performance_benchmarking_msgs when https://github.com/ros2/rosbag2/pull/1242 lands
> ```

BTW This already landed; has it been sync'ed?
___
*[`drake_ros_core/src/subscription.cc` line 41 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NOPXX6o8YhNCAZxD-f2:-NOPXX6o8YhNCAZxD-f3:bmt0gdj) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/f39f8fd537af024a57c7e001af8e0aa2a570a4d3/drake_ros_core/src/subscription.cc#L41)):*
> ```cpp
>                                subscription_options(qos),
> #if RCLCPP_VERSION_GTE(18, 0, 0)
>                                {}, true, true),
> ```

nit Can you annotate what these values are?


<!-- Sent from Reviewable.io -->

2023-02-16 14:09 UTC, EricCousineau-TRI approved these changes
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210)* status: all files reviewed, 3 unresolved discussions (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2023-02-16 14:17 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210)* status: all files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros_core/src/publisher.cc` line 36 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NOP_Y2xB3GM2mQcp9jm:-NOP_Y2xB3GM2mQcp9jn:b73j1q1) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/f39f8fd537af024a57c7e001af8e0aa2a570a4d3/drake_ros_core/src/publisher.cc#L36)):*
> ```cpp
>                      const std::string& topic_name, const rclcpp::QoS& qos)
>     : rclcpp::PublisherBase(node_base, topic_name, type_support,
> #if RCLCPP_VERSION_GTE(18, 0, 0)
> ```

Working: Cleaning up formatting.


<!-- Sent from Reviewable.io -->

2023-02-16 14:49 UTC, EricCousineau-TRI reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`.github/workflows/main.yml` line 63 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NOPXIwL4Jx_AXvjaDt9:-NOPgkme4FhSAt_Li539:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/f39f8fd537af024a57c7e001af8e0aa2a570a4d3/.github/workflows/main.yml#L63)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider qualifying statement, "remove --skip-keys entry for rosbag2_performance_benchmarking_msgs when"
</blockquote></details>

Done.
___
*[`drake_ros_core/src/publisher.cc` line 36 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NOP_Y2xB3GM2mQcp9jm:-NOPglbT4lhPIYDNNk1H:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/f39f8fd537af024a57c7e001af8e0aa2a570a4d3/drake_ros_core/src/publisher.cc#L36)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Cleaning up formatting.
</blockquote></details>

Done.
___
*[`drake_ros_core/src/subscription.cc` line 41 at r3](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NOPXX6o8YhNCAZxD-f2:-NOPgmUM0KztBDssgJLO:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/f39f8fd537af024a57c7e001af8e0aa2a570a4d3/drake_ros_core/src/subscription.cc#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you annotate what these values are?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-16 14:58 UTC, EricCousineau-TRI approved these changes
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)

___
*[`drake_ros_core/src/publisher.cc` line 35 at r5](https://reviewable.io/reviews/RobotLocomotion/drake-ros/210#-NOPiiFO91ZesXYHiIjt:-NOPiiFO91ZesXYHiIju:b-9qf5oq) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/93afa6cf21cc561df7ec7a29773e4eb63f347171/drake_ros_core/src/publisher.cc#L35)):*
> ```cpp
>                      const rosidl_message_type_support_t& type_support,
>                      const std::string& topic_name, const rclcpp::QoS& qos)
> #if RCLCPP_VERSION_GTE(18, 0, 0)
> ```

FYI @sloretz We should try to make sure macro guards don't cut across expressions, or more ideally, statements.

TBH, this still a bit sketchy given it cuts across the ctor initializer spec, but I think it's fine-ish for now.


<!-- Sent from Reviewable.io -->

2023-02-16 15:20 UTC, EricCousineau-TRI commented
New CI failure mode: #221
Will try re-running once. Will still merge, as this regression appears unrelated to this PR.

2023-02-16 15:27 UTC, EricCousineau-TRI commented
Failure capturedb y #221 is reproducible. Merging forward.

2023-02-16 15:27 UTC, merged