Add base drake_ros_viz package.
RobotLocomotion/drake-ros pull request #22
Opened 2021-08-26 16:39 UTC by hidmic

Spin off from #2. Built on top of #21. Only the package skeleton to keep a low LOC count.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)

2022-02-23 23:26 UTC, EricCousineau-TRI requested changes
> Reviewed 17 of 32 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: 17 of 32 files reviewed, 9 unresolved discussions (waiting on @hidmic and @sloretz)

___
*[drake_ros_core/README.md, line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-Mwcqi2BBYpyYrMXV4em:-Mwcqi2BBYpyYrMXV4en:b5hdejh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_core/README.md#L28)):*
> ```Markdown
>     1. Build this package `colcon build --packages-select drake_ros_core`
>     
>     **CMake**
> ```

nit (here and in new package) Consider removing pure CMake instructions.

I think `colcon` is the most useful (for use in ROS2 ecosystem, where the tool is available.)
___
*[drake_ros_tf2/README.md, line 26 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-Mwcqvs1Cc-dgo3Pnqc9:-Mwcqvs1Cc-dgo3PnqcA:b-9gyn9g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_tf2/README.md#L26)):*
> ```Markdown
>     1. Build this package and its dependencies `colcon build --packages-up-to drake_ros_tf2`
> 
>     **CMake**
> ```

nit (Same as above)
___
*[drake_ros_tf2/src/utilities/internal_name_conventions.h, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcsgA92xI2aLYzZYjE:-MwcsgA92xI2aLYzZYjF:b-dxlt63) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_tf2/src/utilities/internal_name_conventions.h#L1)):*
> ```objc
> // Copyright 2022 Open Source Robotics Foundation, Inc.
> ```

nit Given that this is part of TRI contract work, I think the copyright should be written for TRI?
___
*[drake_ros_tf2/src/utilities/internal_name_conventions.h, line 20 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcrwBkBnkIXxwK2vh8:-MwcrwBkBnkIXxwK2vh9:bu7cid) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_tf2/src/utilities/internal_name_conventions.h#L20)):*
> ```objc
> 
> namespace drake_ros_tf2 {
> namespace utilities {
> ```

nit (here and elsewhere) The generic name `utilities` may have poor scoping, and thus grow oddly.

Consider removing this namespace, and just use the root-level package's namespace.
Alternatively, use more descriptive naming, e.g. `conversion`
___
*[drake_ros_viz/README.md, line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcsFQD6I1XjUpo1B4C:-MwcsFQD6I1XjUpo1B4D:b-9lsn15) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/README.md#L18)):*
> ```Markdown
> 1. Activate the drake virtual environment.
> 1. Build it using Colcon, or using CMake directly.
>     
> ```

nit Trailing spaces (here and elsewhere)
___
*[drake_ros_viz/README.md, line 26 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-Mwcr0Bt0AjXX4uhfzCc:-Mwcr0Bt0AjXX4uhfzCd:b-9gyn9g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/README.md#L26)):*
> ```Markdown
>     1. Build this package `colcon build --packages-up-to drake_ros_viz`
>     
>     **CMake**
> ```

nit (Same as above)
___
*[drake_ros_viz/src/utilities/internal_name_conventions.h, line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcrgqH0yg3YAj2Pl7w:-MwcrgqH0yg3YAj2Pl7x:b-jl5761) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/internal_name_conventions.h#L36)):*
> ```objc
> }
> 
> /** Formulate marker namespace given the model instance name, body name, body
> ```

nit (here and elsewhere) This is a private component, consider demoting docstring to private, `/* */`, not `/** */`
___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-MwctrhP-E7UVho__6yY:b51n8bt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
> ```cpp
>   return internal::CalcMarkerNamespace(
>       inspector.GetOwningSourceName(geometry_id),
>       inspector.GetName(geometry_id), geometry_id.get_value());
> ```

Hm... is there precedent for using `geometry_id` always for this name? (is that from @calderpg-tri's code?)
___
*[drake_ros_core/src/python_bindings/module_drake_ros_core.cpp, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcsYYm2deu_vlPeFNQ:-MwcsYYm2deu_vlPeFNR:bf6fft4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fbcffdc6c7a1de51b574693899a6955a42f07c7a/drake_ros_core/src/python_bindings/module_drake_ros_core.cpp#L1)):*
> ```cpp
> // Copyright 2020 Open Source Robotics Foundation, Inc.
> ```

My read is that Python bindings are deferred to separate PR - is that correct?


<!-- Sent from Reviewable.io -->

2022-02-25 01:54 UTC, sloretz approved these changes
> Reviewed 15 of 32 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: all files reviewed, 9 unresolved discussions (waiting on @calderpg-tri, @EricCousineau-TRI, and @hidmic)

___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-MwiV1zA2zzdgfQCjR6v:bs75t0g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... is there precedent for using `geometry_id` always for this name? (is that from @calderpg-tri's code?)
</blockquote></details>

In `drake_ros_tf2` the version of `GetTfFrameName` that accepts a `GeometryId` uses `SceneGraphInspector` to grab the `FrameId` associated with that geometry and uses that to get a name, so it's not there. This seems to be intentionally using the Geometry's name.

https://github.com/RobotLocomotion/drake-ros/blob/d10bbdc9a587554964dccf7b92f2ea5f631a32de/drake_ros_tf2/src/utilities/name_conventions.cc#L48-L53

Can multiple Geometry IDs be associated with one Frame? The GeoemtryId might be used for the name here because it there is at least one `visualization_msgs::msg::Marker` for each geometry: https://github.com/RobotLocomotion/drake-ros/blob/8d2b950b3c04733aee8b7310029081f1189b3721/drake_ros_viz/src/scene_markers_system.cpp#L340-L346

I suppose the Frame name seems like a good namespace to group the geometry markers with, but it will still need to be unique when combined with the id field. The geometry_id value itself might not work as an ID because the [Drake geometry ID value is 64 bits](https://drake.mit.edu/doxygen_cxx/classdrake_1_1_identifier.html#ad945f7a3cc39caafc0527fcf2f7d4a46), while the [Marker Message ID is 32 bits](https://github.com/ros2/common_interfaces/blob/ea761cc4be8b6cfed67a7aeb0c057400c91f90e5/visualization_msgs/msg/Marker.msg#L31). Maybe that could be done by counting the geometries associated with the frame like [you did here](https://github.com/EricCousineau-TRI/repro/blob/9aef82f12ec379ec23843a61aef38ce69dcc5ed9/ros/drake_ros1_hacks/_ros_geometry.py#L184-L187). Do geometries have a specific order that can be relied on?
___
*[drake_ros_core/src/python_bindings/module_drake_ros_core.cpp, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcsYYm2deu_vlPeFNQ:-MwiTvn08CcIRf2TBHYX:bwgfg26) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fbcffdc6c7a1de51b574693899a6955a42f07c7a/drake_ros_core/src/python_bindings/module_drake_ros_core.cpp#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

My read is that Python bindings are deferred to separate PR - is that correct?
</blockquote></details>

It looks like the Python bindings are in https://github.com/RobotLocomotion/drake-ros/pull/24


<!-- Sent from Reviewable.io -->

2022-02-28 17:17 UTC, sloretz commented
___
*[drake_ros_tf2/src/utilities/internal_name_conventions.h, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcsgA92xI2aLYzZYjE:-Mx0IVz0AG7qIvu2kN0E:b-ttjcsm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_tf2/src/utilities/internal_name_conventions.h#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Given that this is part of TRI contract work, I think the copyright should be written for TRI?
</blockquote></details>

Good question! I asked about this internally. It looks like open source code gets the copyright assigned to `Open Source Robotics Foundation, Inc.` even when it's funded by contract work. How important is it for the copyright line to say TRI in this case?


<!-- Sent from Reviewable.io -->

2022-03-01 05:22 UTC, aaronchongth reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: all files reviewed, 9 unresolved discussions (waiting on @calderpg-tri, @EricCousineau-TRI, @hidmic, and @sloretz)

___
*[drake_ros_tf2/src/utilities/internal_name_conventions.h, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcsgA92xI2aLYzZYjE:-Mx2u7Rn-dXCiRhYCta6:b62yfbs) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_tf2/src/utilities/internal_name_conventions.h#L1)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Good question! I asked about this internally. It looks like open source code gets the copyright assigned to `Open Source Robotics Foundation, Inc.` even when it's funded by contract work. How important is it for the copyright line to say TRI in this case?
</blockquote></details>

+1 on that question. I see that there is also the choice of adding another line for the copyright, for example https://github.com/RobotLocomotion/drake/blob/master/third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl#L4. Let me know what you think


<!-- Sent from Reviewable.io -->

2022-03-01 08:22 UTC, aaronchongth reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: 20 of 38 files reviewed, 9 unresolved discussions (waiting on @aaronchongth, @calderpg-tri, @EricCousineau-TRI, and @sloretz)

___
*[drake_ros_core/README.md, line 28 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-Mwcqi2BBYpyYrMXV4em:-Mx3YQxI6cLZBf7ufz74:b-jdzw19) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_core/README.md#L28)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (here and in new package) Consider removing pure CMake instructions.

I think `colcon` is the most useful (for use in ROS2 ecosystem, where the tool is available.)
</blockquote></details>

Gotcha, removed in https://github.com/RobotLocomotion/drake-ros/pull/22/commits/fbb4ad9ee535a4c026494f651087b5cb3a92fcf3
___
*[drake_ros_tf2/README.md, line 26 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-Mwcqvs1Cc-dgo3Pnqc9:-Mx3YWJqDLwGh8f2u-DK:b-uyk4q9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_tf2/README.md#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (Same as above)
</blockquote></details>

Removed in https://github.com/RobotLocomotion/drake-ros/pull/22/commits/fbb4ad9ee535a4c026494f651087b5cb3a92fcf3
___
*[drake_ros_tf2/src/utilities/internal_name_conventions.h, line 20 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcrwBkBnkIXxwK2vh8:-Mx3YaEM4FTozZdWpJWD:b-6bq7z7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_tf2/src/utilities/internal_name_conventions.h#L20)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (here and elsewhere) The generic name `utilities` may have poor scoping, and thus grow oddly.

Consider removing this namespace, and just use the root-level package's namespace.
Alternatively, use more descriptive naming, e.g. `conversion`
</blockquote></details>

I removed the `utilities` scope, as there are helper functions for creating name conventions alongside conversion functions, https://github.com/RobotLocomotion/drake-ros/pull/22/commits/fbb4ad9ee535a4c026494f651087b5cb3a92fcf3
___
*[drake_ros_viz/README.md, line 18 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcsFQD6I1XjUpo1B4C:-Mx3Z01x04IPvIYle54n:b-es62vf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/README.md#L18)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Trailing spaces (here and elsewhere)
</blockquote></details>

Thanks for catching that, removed in https://github.com/RobotLocomotion/drake-ros/pull/22/commits/fbb4ad9ee535a4c026494f651087b5cb3a92fcf3
___
*[drake_ros_viz/README.md, line 26 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-Mwcr0Bt0AjXX4uhfzCc:-Mx3Z4AT-ejNZQihPJXG:b-uyk4q9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/README.md#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (Same as above)
</blockquote></details>

Removed in https://github.com/RobotLocomotion/drake-ros/pull/22/commits/fbb4ad9ee535a4c026494f651087b5cb3a92fcf3
___
*[drake_ros_viz/src/utilities/internal_name_conventions.h, line 36 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcrgqH0yg3YAj2Pl7w:-Mx3Z9682zLd5fLbdZRC:bje8i9w) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/internal_name_conventions.h#L36)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (here and elsewhere) This is a private component, consider demoting docstring to private, `/* */`, not `/** */`
</blockquote></details>

Got it, thanks for pointing that out, https://github.com/RobotLocomotion/drake-ros/pull/22/commits/fbb4ad9ee535a4c026494f651087b5cb3a92fcf3
___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-Mx3R3z2ETSA267Tn2b_:b2qm9p1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
> the Drake geometry ID value is 64 bits, while the Marker Message ID is 32 bits. 

thanks for catching that! I like the idea of having a single source of truth (output of `GetTfFrameName`) for both the `frame_id` and `marker_namespace`, and counting up for every unique instance. `GetMarkerNamespace` is conveniently only used once in `scene_markers_system.cpp` too, so removing it will be trivial. How does that sound?


<!-- Sent from Reviewable.io -->

2022-03-01 08:34 UTC, aaronchongth reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: 20 of 38 files reviewed, 9 unresolved discussions (waiting on @aaronchongth, @calderpg-tri, @EricCousineau-TRI, and @sloretz)

___
*[drake_ros_core/src/python_bindings/module_drake_ros_core.cpp, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcsYYm2deu_vlPeFNQ:-Mx3_wI8793i5DZeQfAm:b-cdpkvq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fbcffdc6c7a1de51b574693899a6955a42f07c7a/drake_ros_core/src/python_bindings/module_drake_ros_core.cpp#L1)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

It looks like the Python bindings are in https://github.com/RobotLocomotion/drake-ros/pull/24
</blockquote></details>

yup! These files were removed as there were still `.cpp` and `hpp` file extensions and differently named source files. I must have accidentally left them in during the rebase and had to clean up afterwards, sorry for the messy commit history


<!-- Sent from Reviewable.io -->

2022-03-01 15:38 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 32 files at r3, 17 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: 37 of 38 files reviewed, 1 unresolved discussion (waiting on @calderpg-tri and @EricCousineau-TRI)

___
*[drake_ros_tf2/src/utilities/internal_name_conventions.h, line 1 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcsgA92xI2aLYzZYjE:-Mx56oaF25ieGqFIscdz:bfa9u4b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_tf2/src/utilities/internal_name_conventions.h#L1)):*
<details><summary><i>Previously, aaronchongth (Aaron Chong) wrote…</i></summary><blockquote>

+1 on that question. I see that there is also the choice of adding another line for the copyright, for example https://github.com/RobotLocomotion/drake/blob/master/third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl#L4. Let me know what you think
</blockquote></details>

OK Gotcha, that sounds good! I will request written documentation out-of-band, just so we have it if/when someone else asks this same question.
___
*[drake_ros_core/src/python_bindings/module_drake_ros_core.cpp, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwcsYYm2deu_vlPeFNQ:-Mx5685uDRxhHy50thjH:b56uezr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fbcffdc6c7a1de51b574693899a6955a42f07c7a/drake_ros_core/src/python_bindings/module_drake_ros_core.cpp#L1)):*
<details><summary><i>Previously, aaronchongth (Aaron Chong) wrote…</i></summary><blockquote>

yup! These files were removed as there were still `.cpp` and `hpp` file extensions and differently named source files. I must have accidentally left them in during the rebase and had to clean up afterwards, sorry for the messy commit history
</blockquote></details>

OK Sounds good!


<!-- Sent from Reviewable.io -->

2022-03-11 19:59 UTC, sloretz reviewed
> Reviewed 1 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: all files reviewed, 1 unresolved discussion (waiting on @calderpg-tri)

___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-MxuYM2K1rFipwZGFR0n:b-2ngt7r) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
> I like the idea of having a single source of truth (output of GetTfFrameName) for both the frame_id and marker_namespace, and counting up for every unique instance. GetMarkerNamespace is conveniently only used once in scene_markers_system.cpp too, so removing it will be trivial. How does that sound?


Sounds good to me! I see in #23 that where `GetMakerNamespace()` is called [it has access to the SceneGraphInspector](https://github.com/RobotLocomotion/drake-ros/pull/23/files#diff-323171292b532a621f0059b13b1543f9f8a5c703a0773edaa02b6dd68d15ac12R53) so passing that to the GetTfFrameName API should be fine.

>  and counting up for every unique instance.

I have a question for @ericcousineau-tri about that - do Geometries have a specific order that can be relied on? If not, maybe a map between a geometry ID and a marker ID is needed.


<!-- Sent from Reviewable.io -->

2022-03-12 22:35 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: all files reviewed, 1 unresolved discussion (waiting on @calderpg-tri)

___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-My-Fa0y6r6dC0YwNMdp:b-6mnczs) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

> I like the idea of having a single source of truth (output of GetTfFrameName) for both the frame_id and marker_namespace, and counting up for every unique instance. GetMarkerNamespace is conveniently only used once in scene_markers_system.cpp too, so removing it will be trivial. How does that sound?


Sounds good to me! I see in #23 that where `GetMakerNamespace()` is called [it has access to the SceneGraphInspector](https://github.com/RobotLocomotion/drake-ros/pull/23/files#diff-323171292b532a621f0059b13b1543f9f8a5c703a0773edaa02b6dd68d15ac12R53) so passing that to the GetTfFrameName API should be fine.

>  and counting up for every unique instance.

I have a question for @ericcousineau-tri about that - do Geometries have a specific order that can be relied on? If not, maybe a map between a geometry ID and a marker ID is needed.
</blockquote></details>

I believe that geometry ids should always increment (given the global pool you saw), and they should generally be created in the same order (e.g. from parsing or what not).
So yes, I think the ordering is stable, at least for a given revision of the code.

From looking at Calder's code in Anzu (), I see the following:
```
  const GeometryNamespaceFunction geometry_namespace_fn = [&] (
      const drake::multibody::ModelInstanceIndex,
      const drake::multibody::BodyIndex,
      const drake::geometry::GeometryId geometry_id) {
    const std::string shape_namespace = marker_namespace_prefix.value_or(
        inspector.GetOwningSourceName(geometry_id));
    const auto* illustration_properties =
        inspector.GetIllustrationProperties(geometry_id);
    const auto* proximity_properties =
        inspector.GetProximityProperties(geometry_id);
    if (illustration_properties != nullptr) {
      return shape_namespace + "_visual";
    } else if (proximity_properties != nullptr) {
      return shape_namespace + "_collision";
    } else {
      return std::string();
    }
  };
```
...
```
  for (const auto geometry_id : all_geometries) {
    ...
    // Get the ShapeDescription of the geometry
    const ShapeDescription description =
        MakeShapeDescription(plant, plant_context, geometry_id);
    ...
    // Convert to RViz markers
    try {
      const std::string marker_namespace =
          geometry_namespace_fn(model_instance_index, body_index, geometry_id);
      auto rviz_markers = MakeGeometryDisplayMarkers(
          description, (override_color) ? override_color : shape_color);
      for (auto& rviz_marker : rviz_markers.markers) {
        namespace_marker_counts[marker_namespace] += 1;
        rviz_marker.ns = marker_namespace;
        rviz_marker.id = namespace_marker_counts.at(marker_namespace);
        display_markers.markers.push_back(rviz_marker);
      }
    ...
  }
```


<!-- Sent from Reviewable.io -->

2022-03-12 22:38 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-My-GkYQEugBPiIBz5mZ:b1a4l80) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I believe that geometry ids should always increment (given the global pool you saw), and they should generally be created in the same order (e.g. from parsing or what not).
So yes, I think the ordering is stable, at least for a given revision of the code.

From looking at Calder's code in Anzu (), I see the following:
```
  const GeometryNamespaceFunction geometry_namespace_fn = [&] (
      const drake::multibody::ModelInstanceIndex,
      const drake::multibody::BodyIndex,
      const drake::geometry::GeometryId geometry_id) {
    const std::string shape_namespace = marker_namespace_prefix.value_or(
        inspector.GetOwningSourceName(geometry_id));
    const auto* illustration_properties =
        inspector.GetIllustrationProperties(geometry_id);
    const auto* proximity_properties =
        inspector.GetProximityProperties(geometry_id);
    if (illustration_properties != nullptr) {
      return shape_namespace + "_visual";
    } else if (proximity_properties != nullptr) {
      return shape_namespace + "_collision";
    } else {
      return std::string();
    }
  };
```
...
```
  for (const auto geometry_id : all_geometries) {
    ...
    // Get the ShapeDescription of the geometry
    const ShapeDescription description =
        MakeShapeDescription(plant, plant_context, geometry_id);
    ...
    // Convert to RViz markers
    try {
      const std::string marker_namespace =
          geometry_namespace_fn(model_instance_index, body_index, geometry_id);
      auto rviz_markers = MakeGeometryDisplayMarkers(
          description, (override_color) ? override_color : shape_color);
      for (auto& rviz_marker : rviz_markers.markers) {
        namespace_marker_counts[marker_namespace] += 1;
        rviz_marker.ns = marker_namespace;
        rviz_marker.id = namespace_marker_counts.at(marker_namespace);
        display_markers.markers.push_back(rviz_marker);
      }
    ...
  }
```
</blockquote></details>

Working: Still trying to figure out full mapping to see if/when geometry id might leak in.

@sloretz If you have time to inspect it, the code in Anzu is in `rviz_geometry_visualizer.cc`; I am on vacation next week, so may not be able to find it then.


<!-- Sent from Reviewable.io -->

2022-03-21 15:52 UTC, aaronchongth reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-Myh7lwb8KkFCBUntIc4:be4ec8v) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Still trying to figure out full mapping to see if/when geometry id might leak in.

@sloretz If you have time to inspect it, the code in Anzu is in `rviz_geometry_visualizer.cc`; I am on vacation next week, so may not be able to find it then.
</blockquote></details>

Thanks for sharing this, @ericcousineau-tri! Just checking, I'm assuming `marker_namespace_prefix` is user defined, since it is outside of this example's scope, is it of any significance?

We had a brief discussion during our meetings, and thought that constructing the marker namespace from just `GetOwningSourceName` and `GeometryId` might leave out a lot of information and make mapping from marker namespace back to the geometry in the multibody plant difficult. What do you think about constructing the namespace using all of model, body and geometry id? Then we can count up the marker ID for when namespaces are duplicated, like what was done in the example you provided.


<!-- Sent from Reviewable.io -->

2022-03-22 00:40 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-Myj2MiL4zOnFpZYDkGr:b-7paiah) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
Hm... Upon inspecting Calder's viz code, and running in on my side, I think we should allow marker namespace customization has he had done in Anzu - meaning the translator function should take in a function similar to his, so that way the user can customize namespacing (albeit for one geometry role).

> [...] make mapping from marker namespace back to the geometry in the multibody plant difficult [...]

I'm not sure if I understand this workflow - when might we want to map from visualization back to plant?
While that's a nice-to-have, not sure if we want to support it yet.
Additionally, b/c `geometry_id` is a *global` singleton (and thus may get affected by construction order, etc.), then that means the namespace may be *unstable*, and the RViz configuration would then get invalidated depending on when you create the MbP.

So yeah, my suggestions are:

- Ensure that there is a callback to determine the marker namespace for visualization
- Perhaps make the above `geometry_namespace_fn` a default implementation, e.g.  `MakeFlatGeometryNamespace`
- Then make a *stable* nested / hierarchical namespace (if possible), e.g. `MakeStableNestedGeometryNamespace`
- If really desired, then make an *unstable* but 1-to-1 mappable namespace, e.g. `MakeUnstableGeometryNamespace` (I would suggest deferring for now)

Does that make sense?


<!-- Sent from Reviewable.io -->

2022-03-22 06:09 UTC, aaronchongth reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-MykDGYK-oa8QmWA8_xN:b-jg7bgx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
> when might we want to map from visualization back to plant?

So far I've not come across any instances where this mapping might be useful. At a stretch, maybe something like an rviz plugin that will in turn manipulate the MbP. But I like the idea of supporting different levels of namespacing, the unstable implementation can be considered if we ever come to that.


<!-- Sent from Reviewable.io -->

2022-03-22 10:24 UTC, aaronchongth reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: 34 of 38 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-Myl8Vys4bCafxUtN2K7:bvuro1u) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
<details><summary><i>Previously, aaronchongth (Aaron Chong) wrote…</i></summary><blockquote>

> when might we want to map from visualization back to plant?

So far I've not come across any instances where this mapping might be useful. At a stretch, maybe something like an rviz plugin that will in turn manipulate the MbP. But I like the idea of supporting different levels of namespacing, the unstable implementation can be considered if we ever come to that.
</blockquote></details>

I've opted for helper functions that generate these functors. `MarkerNamespaceFunction` will be used when the rest of `drake_ros_rviz` is introduced in https://github.com/RobotLocomotion/drake-ros/pull/23. Let me know what you think @ericcousineau-tri 


<!-- Sent from Reviewable.io -->

2022-03-26 01:35 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: 34 of 38 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-Mz2ldfr0ZdiqFzDaIjC:b-4mzktr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
<details><summary><i>Previously, aaronchongth (Aaron Chong) wrote…</i></summary><blockquote>

I've opted for helper functions that generate these functors. `MarkerNamespaceFunction` will be used when the rest of `drake_ros_rviz` is introduced in https://github.com/RobotLocomotion/drake-ros/pull/23. Let me know what you think @ericcousineau-tri 
</blockquote></details>

Looks better!

However, I still see the presence of `geometry_id` in there, which is "unstable" when considering a MultibodyPlant / SceneGraph in isolation.

Per above, we should have an option to have a *uniqueness* counter, not a `geometry_id` value, help distinguish values. Otherwise, we may invalidate RViz configurations.

Conceretely, see this:
https://github.com/EricCousineau-TRI/repro/blob/6642ed8638d028891f6a250d17812ceb01604795/drake_stuff/notebooks/geometry_id_global_counter.ipynb?short_path=aa000f3#L81-L110
(sorry, would post notebook, but GitHub rendering is dropping output for some reason...)

Does that make sense?


<!-- Sent from Reviewable.io -->

2022-03-28 03:48 UTC, aaronchongth reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: 34 of 38 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @sloretz)

___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-MzDVRQwDb0IX0TpCyeq:b-lrpx5x) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Looks better!

However, I still see the presence of `geometry_id` in there, which is "unstable" when considering a MultibodyPlant / SceneGraph in isolation.

Per above, we should have an option to have a *uniqueness* counter, not a `geometry_id` value, help distinguish values. Otherwise, we may invalidate RViz configurations.

Conceretely, see this:
https://github.com/EricCousineau-TRI/repro/blob/6642ed8638d028891f6a250d17812ceb01604795/drake_stuff/notebooks/geometry_id_global_counter.ipynb?short_path=aa000f3#L81-L110
(sorry, would post notebook, but GitHub rendering is dropping output for some reason...)

Does that make sense?
</blockquote></details>

Ahh! Thanks for the example, that makes it much clearer now. I don't know if it applies to body indices as well, but I've removed the uses of all these IDs during the formulation of the namespaces. `geometry_id` is currently only used for `GetName` or `GetOwningSourceName`.

The same considerations might need to be done for `drake_ros_tf2` as well, I'll get those changes in as well once we agree on this approach.

As for the uniqueness counter, I was considering implementing that in the subsequent PR, where the namespaces are created, https://github.com/RobotLocomotion/drake-ros/pull/23/files#diff-323171292b532a621f0059b13b1543f9f8a5c703a0773edaa02b6dd68d15ac12R52-R65.

let me know what you think!


<!-- Sent from Reviewable.io -->

2022-03-29 02:32 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 2 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @hidmic)

___
*[drake_ros_viz/src/utilities/internal_name_conventions.h, line 26 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MzIP_lEAuejrTDvSUB9:-MzIP_lEAuejrTDvSUBA:b-e4uhjj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0a70c7d697649d42309ee9f92ac620dc3215ecb3/drake_ros_viz/src/utilities/internal_name_conventions.h#L26)):*
> ```objc
> 
> bool IsEmptyName(const std::string& name) {
>   if (name.empty() || name == "::" || name == "/") {
> ```

nit It's a bit disconcerting that we'd get delimiters on their own - it means we're not doing great bookkeeping elsewhere.

Can you see if you can fix this, or add a TODO to clean this up?
___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 45 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MwctrhP-E7UVho__6yX:-MzIQ8AE7Diy6mtUg3us:byg7m8s) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4da6cd15bb8aa9762c96195dee938a3d9aff07db/drake_ros_viz/src/utilities/name_conventions.cc#L45)):*
<details><summary><i>Previously, aaronchongth (Aaron Chong) wrote…</i></summary><blockquote>

Ahh! Thanks for the example, that makes it much clearer now. I don't know if it applies to body indices as well, but I've removed the uses of all these IDs during the formulation of the namespaces. `geometry_id` is currently only used for `GetName` or `GetOwningSourceName`.

The same considerations might need to be done for `drake_ros_tf2` as well, I'll get those changes in as well once we agree on this approach.

As for the uniqueness counter, I was considering implementing that in the subsequent PR, where the namespaces are created, https://github.com/RobotLocomotion/drake-ros/pull/23/files#diff-323171292b532a621f0059b13b1543f9f8a5c703a0773edaa02b6dd68d15ac12R52-R65.

let me know what you think!
</blockquote></details>

OK Looks better!

FTR, `Body` uses *indices*, not *ids*. For Drake, that's an important distinction:
https://github.com/RobotLocomotion/drake/blob/v1.1.0/common/type_safe_index.h
https://github.com/RobotLocomotion/drake/blob/v1.1.0/common/identifier.h

Indices are *local*, and thus stable (w.r.t. how we want them).
___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 58 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MzIUSh20I2kdNvR5e7I:-MzIUSh3CSDc-qTY2-qg:b-ukcf6i) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0a70c7d697649d42309ee9f92ac620dc3215ecb3/drake_ros_viz/src/utilities/name_conventions.cc#L58)):*
> ```cpp
>     return internal::CalcHierarchicalMarkerNamespace(
>         prefix, inspector.GetOwningSourceName(geometry_id),
>         inspector.GetName(geometry_id));
> ```

nit From looking at `inspector.GetName()`, it seems like this may have more components than we want.

https://github.com/EricCousineau-TRI/repro/commit/c44615ee725b9c5498cd5b1d706ccfec6c3bd203
Can you add a TODO to further refine this?
___
*[drake_ros_viz/include/drake_ros_viz/utilities/name_conventions.h, line 46 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MzIU9hf2TnjL5jnhPPq:-MzIU9hf2TnjL5jnhPPr:b9tzwdv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0a70c7d697649d42309ee9f92ac620dc3215ecb3/drake_ros_viz/include/drake_ros_viz/utilities/name_conventions.h#L46)):*
> ```objc
> 
> /** Returns a functor that generates a hierarchical namespace (if possible) in
>   the form of 'model_instance_name/body_name/geometry_id_value'. This is
> ```

nit `geometry_id_value` => `geometry_name`b
___
*[drake_ros_viz/include/drake_ros_viz/utilities/name_conventions.h, line 51 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MzIPSq91VzjWyovQUDa:-MzIPSq91VzjWyovQUDb:bsplrks) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0a70c7d697649d42309ee9f92ac620dc3215ecb3/drake_ros_viz/include/drake_ros_viz/utilities/name_conventions.h#L51)):*
> ```objc
>   @returns the functor for generating the marker namespace.
>  */
> MarkerNamespaceFunction GetHierarchicalMarkerNamspaceFunction(
> ```

nit Spelling, "Namspace" => "Namespace"


<!-- Sent from Reviewable.io -->

2022-03-29 02:34 UTC, EricCousineau-TRI approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: all files reviewed, 4 unresolved discussions (waiting on @hidmic)



<!-- Sent from Reviewable.io -->

2022-03-29 02:35 UTC, EricCousineau-TRI approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> for moving forward, with TODO's etc. for the future
Thanks!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-:-MzIWjDTA8MPVrKXmhiX:b1imqvw)* status: all files reviewed, 4 unresolved discussions (waiting on @hidmic)



<!-- Sent from Reviewable.io -->

2022-03-29 06:24 UTC, aaronchongth reviewed
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: 35 of 38 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[drake_ros_viz/src/utilities/internal_name_conventions.h, line 26 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MzIP_lEAuejrTDvSUB9:-MzJKNwc3-vQsRPQsLRm:bfl47pi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0a70c7d697649d42309ee9f92ac620dc3215ecb3/drake_ros_viz/src/utilities/internal_name_conventions.h#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit It's a bit disconcerting that we'd get delimiters on their own - it means we're not doing great bookkeeping elsewhere.

Can you see if you can fix this, or add a TODO to clean this up?
</blockquote></details>

That's a good point. I found that there is nothing stopping users from adding bodies or model instances with names like `::` and `/`, but for all intents and purposes, it could be intentional and there might be some workflow that requires it. I have removed this check, and just used a `std::string::empty()` check in it's place.
___
*[drake_ros_viz/src/utilities/name_conventions.cc, line 58 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MzIUSh20I2kdNvR5e7I:-MzJL-_QBAod8Uy5vI5N:b-ryoe2z) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0a70c7d697649d42309ee9f92ac620dc3215ecb3/drake_ros_viz/src/utilities/name_conventions.cc#L58)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit From looking at `inspector.GetName()`, it seems like this may have more components than we want.

https://github.com/EricCousineau-TRI/repro/commit/c44615ee725b9c5498cd5b1d706ccfec6c3bd203
Can you add a TODO to further refine this?
</blockquote></details>

Just added a TODO for now, thanks for testing that out!
___
*[drake_ros_viz/include/drake_ros_viz/utilities/name_conventions.h, line 46 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MzIU9hf2TnjL5jnhPPq:-MzJJyXU8U4ksnD3-15-:b-896fja) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0a70c7d697649d42309ee9f92ac620dc3215ecb3/drake_ros_viz/include/drake_ros_viz/utilities/name_conventions.h#L46)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `geometry_id_value` => `geometry_name`b
</blockquote></details>

Done!
___
*[drake_ros_viz/include/drake_ros_viz/utilities/name_conventions.h, line 51 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/22#-MzIPSq91VzjWyovQUDa:-MzJKI3Q0HhhNTL9t_ct:b7vt94u) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/0a70c7d697649d42309ee9f92ac620dc3215ecb3/drake_ros_viz/include/drake_ros_viz/utilities/name_conventions.h#L51)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Spelling, "Namspace" => "Namespace"
</blockquote></details>

thanks for catching that! Fixed


<!-- Sent from Reviewable.io -->

2022-03-29 17:37 UTC, EricCousineau-TRI approved these changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)



<!-- Sent from Reviewable.io -->

2022-03-30 00:55 UTC, merged