Docker Containerization
RobotLocomotion/drake-ros pull request #272
Opened 2023-04-16 01:05 UTC by adeeb10abbas

Targets #9

Ultimate aim is to be able to `drake-ros` be accessible to all commonly used platforms for anyone to develop and try stuff out! 

Some notes about the approach, might be useful for the reviewers -
- I use `npm` to install bazelisk as Drake's prereq installer doesn't yet support installing Bazel for non x86 platforms. 

- I allow users to be able to build from the latest drake master. I see the benefit to be two fold, obviously some users might want to try the latest and greatest features of drake asap and the second, is that M1 Mac/ARM Ubuntu users, including users of Nvidia Jetson platforms can now use `drake-ros` directly

- Building from source is currently a requirement for non x86 platforms. Hopefully once drake maintainers start hosting `aarch64` binaries, this won't be a hard requirement. I believe it would make the user experience significantly better as drake is quite heavy to build.

This was my first pass at it. There might be some spillovers from my lab's reqs that might not be relevant here hehe. Any comments, suggestions and improvements are all welcome! Thanks! 

cc: @EricCousineau-TRI

2023-07-04 14:16 UTC, adeeb10abbas reviewed
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`Dockerfile` line 7 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURvyVjDorpNg-NfEwV:-NWOLej01SIr_JKcq5gW:btm1q3y) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Is this redundant?
</blockquote></details>

I don't believe so. Please correct me if I am wrong! 

My understanding is as follows -
SHELL ["/bin/bash", "-c"] sets the default shell for RUN commands in the Dockerfile. Any RUN command that follows this line will be executed in a bash shell.

ENTRYPOINT ["/bin/bash"] sets the command that will be executed when a container is started from the image. In this case, it starts a bash shell.
___
*[`Dockerfile` line 10 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURzT5o31eg1r3cIGiR:-NWSwvDdBZnhpF5uIAw2:b-896fja) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L10)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why install desktop on top of base ROS image? Is there a desktop version of Docker images that we can use?
</blockquote></details>

Done!
___
*[`Dockerfile` line 11 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURw01O42FrEdHjBBfb:-NWSxQR67Notkw8AQXUN:b-v6s1o3) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L11)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why version constraint? 
</blockquote></details>

Removed. 
___
*[`Dockerfile` line 15 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURwAlh3L-0G7zGlqwP:-NWSxlrbDodXYfXt-7ea:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L15)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For caching, I believe it is common practice to remove any leftover cache in `/var/lib/apt/lists/*` like you had done above.
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get
https://docs.docker.com/build/cache/
</blockquote></details>

Done
___
*[`Dockerfile` line 15 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURzM-V7iPNEmq_zO_g:-NWOMYUU-Ws5zc8mK3iU:b-nzh0j4) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L15)):*
> Unclear what effect upgrading may have upon the base image.
I will remove it since I do agree this can be a cause of instability of the wider drake-ros community. 
I just thought having latest versions of everything might be good for our use case. At least that has been desirable in my lab's. :)
___
*[`Dockerfile` line 24 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NTEVwOO0rT0lVQEfHB1:-NZWDPHh5fpuZsZ_i227:br6i6xn) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L24)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, can we try that out here?

I'd much prefer to stick w/ just apt / Python / ROS ecosystem rather than using yet another package manager if we don't need to
</blockquote></details>

lmk if the new flow works better. 
___
*[`Dockerfile` line 30 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURxMMr2z4AT--E5B4O:-NWSw6eO1Nv5pxCAmbCC:b-896fja) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I do not believe these are necessary for bare bones image (which IMO is the ideal for this image).

Can you remove these lines and/or merge minimal set w/ above line?
Anything for development should be done as secondary layer by devs.
</blockquote></details>

Done!
___
*[`Dockerfile` line 38 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURywztBB5TDINYr5gP:-NWSvxTMA4IE9G4exarv:b6ptjp1) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why `dist-upgrade` is strict improvement.

Consider removing?
</blockquote></details>

Done. Yep, generally I prefer to do it since in the lab we've been using stuff and have had issues not having all the stuff up to date. But yeah it makes sense to drop it since I think definitely induces more entropy for no reason haha
___
*[`Dockerfile` line 40 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURw7i20bZJNBwgV1ya:-NWSyl9j5qf-TRK5eV1o:b-896fja) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L40)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Initially unclear why this option is needed, but I see it's for arm64 support.

Can you add comment to that effect?

</blockquote></details>

Done!
___
*[`Dockerfile` line 50 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURxxZJ9oYHUCSkmR6m:-NZWDF2N7ggRXI62pH2l:b-896fja) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L50)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Since we're in a Docker container, I would recommend just installing to `/opt/drake`.
</blockquote></details>

Done!
___
*[`Dockerfile` line 53 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURyfifAmqntug7XuqA:-NZWCWBo6S2kVceK9Qz5:b-896fix) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L53)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unclear why we need to untar, vs. just use `*.deb` installed Drake.

Can you use the Debian version, as illustrated in the example README?
https://github.com/RobotLocomotion/drake-ros/tree/main/drake_ros_examples
</blockquote></details>

Done.
___
*[`Dockerfile` line 77 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURy5Yj2Bn2I_ghuWdz:-NWSvr5nERnsl7vQUTa7:b-896fja) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/Dockerfile#L77)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I believe this forking may not be necessary.

Rather than explicitly using `CMAKE_PREFIX_PATH` via command-line, I would recommend using env vars, and solely use `/opt/drake/bin`.
</blockquote></details>

Done!
___
*[`docker-compose.yml` line 1 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NURxo2s0X-G3ogdvAID:-NWSvGb76P4D5zAmRjKR:bb6un1j) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/892fdd1207e95be40618ac1f39f6191fc4509458/docker-compose.yml#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you clarify that this is only necessary for machines w/o NVidia GPUs?
</blockquote></details>

Done
___
*[`docker-compose.yml` line 29 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-NUS-biJ0ZXUew3m2dhR:-NWSuvdO-9WxoZiBgWSq:brfpi15) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob [...]

2023-08-02 02:54 UTC, EricCousineau-TRI requested changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>, just gonna briefly try to get CI to be happy

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-:-Nao9afa13zWZLDo-e5h:bekm5c5)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-Nao9_Zv3SMMyfTQ4RAb:-Nao9_Zv3SMMyfTQ4RAc:b-mmd0jv) (no related file):*
Working: Pushing squashed + rebased to see if that makes CI happier.

___


<!-- Sent from Reviewable.io -->

2023-08-02 02:56 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272)* status: all files reviewed, 1 unresolved discussion (waiting on @adeeb10abbas)

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/272#-Nao9_Zv3SMMyfTQ4RAb:-Nao9oLc0fNyW5UDY30Z:bq43p1q) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Pushing squashed + rebased to see if that makes CI happier.
</blockquote></details>

Ah, I can't - it's `adeeb:main`.

Would you be able to squash / rebase? If you want, here's the branch I used:
https://github.com/RobotLocomotion/drake-ros/compare/main...EricCousineau-TRI:drake-ros:adeeb-pr272

___


<!-- Sent from Reviewable.io -->

2023-08-02 09:27 UTC, adeeb10abbas commented
@EricCousineau-TRI Sorry about that! hehe. Top notch security...
This should do it. Thanks!

2023-08-02 14:16 UTC, EricCousineau-TRI commented
Failure on CI appears to be flake (\cc @calderpg-tri @IanTheEngineer @adityapande-1995)
Will go ahead and merge for now

2023-08-02 14:17 UTC, merged