[WIP] Add drake_ros_bazel_installed Bazel package.
RobotLocomotion/drake-ros pull request #3
Opened 2021-05-07 20:07 UTC by hidmic

This PR addresses https://github.com/ToyotaResearchInstitute/osrc_drake_project/issues/22. It includes:

- Build infrastructure to pull a ROS 2 binary installation into the WORKSPACE as a local repository (adapted from https://github.com/ToyotaResearchInstitute/enabling-anzu/pull/91).
- ...

2021-05-07 20:09 UTC, hidmic commented
I have a few `CMakeLists.txt` files to fix upstream before I can setup that ROS 2 `local_repository`.

2021-05-12 18:54 UTC, hidmic commented
It took a few more fixes to get it to build, upstream in:

- [ ] [ros2/rviz#687](https://github.com/ros2/rviz/pull/687)
- [ ] [ros2/rviz#688](https://github.com/ros2/rviz/pull/688)

 and to the build infrastructure itself (a few more corner cases were introduced going from Eloquent to Rolling).

2021-06-04 15:47 UTC, hidmic commented
Alright, we're getting closer. Had to make some changes upstream (https://github.com/ros2/rosidl_python/pull/131, https://github.com/ros2/rosidl/pull/597) to help the process. But of course the basic build infrastructure wasn't enough, and it still isn't. Some dependencies within Rolling's binary underlay are not ROS packages but plain CMake packages (e.g. FastCDR) that the current tools miss. So I have to add support to scrap those as well.

2021-06-18 18:39 UTC, hidmic commented
Getting closer after a few more upstream fixes and major surgery to the build infrastructure. Interfaces now build in Bazel, composing interfaces in the overlay and in another package within the Bazel workspace. Need to write some examples next and make sure runfiles and environment are OK.

2021-06-24 22:55 UTC, hidmic commented
Alright, after some more upstream changes (see https://github.com/ros2/rosidl/pull/601 & co) we now have a pair of C++ publisher and subscription working :tada: Service and action come next. Then Python.

2021-06-30 14:44 UTC, hidmic commented
Alright, topics, services, and action interfaces built within Bazel are fully functional in C++.

2021-07-02 18:28 UTC, hidmic commented
Finally ! Both C++ and Python demos in the `//apps` packages are working.

@IanTheEngineer @EricCousineau-TRI this is not a small PR. The largest (and perhaps most controversial) bit remains to be the build infrastructure, which I'm sure can be further polished. How do you want to move forward with this? I'd like to settle on a review process so it doesn't rot.

2021-07-12 19:58 UTC, hidmic commented
Alright, now that this POC is feature complete, I would really appreciate every piece of feedback I can get before I start splitting and documenting it in full. To put things in context a bit:

- Demo interfaces are split across both [`//apps`](https://github.com/RobotLocomotion/drake-ros/tree/hidmic/drake_ros_bazel_installed/drake_ros_bazel_installed/apps) and [`//common`](https://github.com/RobotLocomotion/drake-ros/tree/hidmic/drake_ros_bazel_installed/drake_ros_bazel_installed/common) packages. This exercises interface dependencies between packages as well as between repositories.
- Demo executables in C++ and Python can be found in the [`//apps`](https://github.com/RobotLocomotion/drake-ros/tree/hidmic/drake_ros_bazel_installed/drake_ros_bazel_installed/apps) package:
  - Both `//apps:oracle_cc` and `//apps:oracle_py` executables publish `apps_msgs/msg/Status`, respond to `common_msgs/srv/Query` requests, and service `common_msgs/action/Do` actions.
  - Both `//apps:inquirer_cc` and `//apps:inquirer_py` executables subscribe to `apps_msgs/msg/Status`, send `common_msgs/srv/Query` requests, and request `common_msgs/action/Do` actions.
- Everything else, namely the [`//tools`](https://github.com/RobotLocomotion/drake-ros/tree/hidmic/drake_ros_bazel_installed/drake_ros_bazel_installed/tools) package, is build infrastructure:
  - The `//tools/skylark:dload*.bzl` files provide macros to associate runtime environment variables to different target types (mainly C++ and Python libraries and "binaries") and to run downstream executables in said runtime environments through shims.
  - The `//tools/skylark/ros2` package encapsulates all the machinery to pull a (subset of a) ROS 2 workspace installation (from binaries or from source) as a Bazel repository and into Bazel's sandbox. This includes libraries and tools (such as the `rosidl` pipeline). Specifically:
     - The `//tools/skylark/ros2/cmake_tools` Python package provides an idiomatic API to the CMake server, necessary to collect CMake packages' exported configuration.
     - The `//tools/skylark/ros2/ros2bzl` Python package is the backbone for the `//tools/skylark/ros2:generate_repository_files.py` executable. This executable crawls the target workspace, collects CMake packages' exported configuration, collects Python packages' egg metadata, symlinks all relevant directories and files, and generates a Bazel package that recreates the dependency graph in the workspace as close as it is possible. In order to do this:
        -  APIs in the `//tools/skylark/ros2/cmake_tools` Python package are leveraged to collect and cache CMake packages' exported configuration (in parallel, one job per CPU core, but this is optional).
        - C++ and Python libraries and binaries are described using macros built on top of `//tools/skylark:dload*.bzl` macros, as ROS 2 dependencies rely heavily on `LD_LIBRARY_PATH` (to overlay workspaces with RPATH stripped binaries) and `AMENT_PREFIX_PATH` (to locate package data of all kinds). These macros are made available in the resulting package thorough `cc_tools.bzl` and `py_tools.bzl` files for downstream consumption. These macros are bound to the corresponding ROS 2 workspace.
       - The entire `rosidl` pipeline is made accessible through rules and macros in the `rosidl_tools.bzl` file in resulting package. These tools are bound to the corresponding ROS 2 workspace.
     - The `//tools/skylark/ros2:ros2.bzl` file provides a repository rule that encapsulate all the logic described above.
  - The `//tools/workspace/python` package provides a repository rule that picks up CPython development libraries to support native extension builds.
   - The `//tools/workspace/ros2` package provides a repository rule with reasonable defaults to pick  up a subset of a system-installed ROS 2 Rolling binary distribution.  
   - The `//tools/skylark:execute.bzl` file contains an `execute_or_fail()` macro inspired in that of Drake.

There are a few more misc files with helper macros and to support `rmw_fastrtps_cpp`-specific network isolation.

@EricCousineau-TRI @IanTheEngineer (and perhaps @jwnimmer-tri), it'd be best if we can tackle major concerns before pursuing this path any further. WDYT?

2021-08-09 17:13 UTC, hidmic commented
I just updated this patch, mainly to deal with https://github.com/ros2/rosidl/pull/601 getting reverted. Some code simplification and fixes for corner cases when using symlink installed overlays also went in.

2021-09-21 20:00 UTC, EricCousineau-TRI requested changes
> Reviewed 1 of 44 files at r1, 1 of 33 files at r3, 1 of 42 files at r4, 2 of 13 files at r7, 2 of 20 files at r8.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 7 of 78 files reviewed, 7 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

___
*[drake_ros_bazel_installed/apps/BUILD.bazel, line 1 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8uV_O-srtJdYFfdni:-Mk8uV_O-srtJdYFfdnj:b-u8lm8f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/apps/BUILD.bazel#L1)):*
> ```Starlark
> load("@ros2//:rosidl_tools.bzl", "rosidl_interfaces_group")
> ```

(Once main review is done) Could you add README briefly describing this? (per your PR overview)
___
*[drake_ros_bazel_installed/apps/inquirer.py, line 19 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8u6bk87GFXGwdhGLf:-Mk8u6bk87GFXGwdhGLg:b-bhxfyi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/apps/inquirer.py#L19)):*
> ```Python
>         super().__init__('inquirer')
>         self._status_sub = self.create_subscription(
>             apps_msgs.msg.Status, 'status', self._on_status, 1)
> ```

nit Why does this not supply explicit QoS, while the C++ example does?

(if this is common practice, can you provide link to docs?)
___
*[drake_ros_bazel_installed/tools/skylark/dload.bzl, line 15 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8urNY4ZrqDD8eagf8:-Mk8urNY4ZrqDD8eagf9:b-qa57hs) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload.bzl#L15)):*
> ```Starlark
> }
> 
> def unique(input_list):
> ```

These are presently exposed as public API, though they don't seem to be in scope of this library.

Can you make them private, `_unique` / `_normpath`? (or move them to a separate library, ideally without the word `util`?)
___
*[drake_ros_bazel_installed/tools/skylark/dload.bzl, line 40 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8v6puB7ppEKKOvaJW:-Mk8v6puB7ppEKKOvaJX:b-tfnyl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload.bzl#L40)):*
> ```Starlark
>     return "/".join(normalized_path_parts)
> 
> def get_dload_shim_attributes():
> ```

nit Can this be private?
___
*[drake_ros_bazel_installed/tools/skylark/dload_cc.bzl, line 76 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8vgoq9-MLLUhUHS71:-Mk8vgoq9-MLLUhUHS72:bboosm1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload_cc.bzl#L76)):*
> ```Starlark
>   }}
>   other_argv[argc] = NULL;
>   int ret = execv(other_argv[0], other_argv);
> ```

BTW Perhaps there is a way to have this directly link in the intended code, e.g. `dload_shim_main(...)`, so that way there's less indirection.

However, not sure if there will be any real issues yet with just using `exec`
___
*[drake_ros_bazel_installed/tools/skylark/dload_py.bzl, line 22 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8wI-p1mMPmQgxXsEF:-Mk8wI-p1mMPmQgxXsEG:b-2yh1v5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload_py.bzl#L22)):*
> ```Starlark
> from bazel_tools.tools.python.runfiles import runfiles
> 
> r = runfiles.Create()
> ```

Having script logic outside of `main()` is OK, but should at least have `assert __name__ == "__main__"` to avoid confusion.

Can you either add this assert, or wrap all logic in `main()`, and use a `if __name__ == "__main__"` stanza?
___
*[drake_ros_bazel_installed/tools/skylark/dload_py.bzl, line 53 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8wUQ70grN1V10cqjW:-Mk8wUQ70grN1V10cqjX:b-zig5wp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload_py.bzl#L53)):*
> ```Starlark
> """
> 
> def to_py_list(collection):
> ```

Can this be made private?
___
*[drake_ros_bazel_installed/tools/workspace/BUILD.bazel, line 0 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8t6nD1kVKNRrKmJnb:-Mk8t6nEDGiNSmK3atNY:b-5j92fg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/239a70c6f98294a963d959262d971ef3a53800a6/drake_ros_bazel_installed/tools/workspace/BUILD.bazel#L0)):*
nit Empty files (here and elsewhere) should have a comment briefly describing why they're empty; otherwise, it's unclear if this was a mistake.

Can you add a small comment? e.g.
```
# Empty build file to mark package boundaries.
```


<!-- Sent from Reviewable.io -->

2021-09-22 15:29 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 3 of 80 files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_bazel_installed/apps/BUILD.bazel, line 1 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8uV_O-srtJdYFfdni:-MkCr0YODoznF68JFf0U:b-7u38ng) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/apps/BUILD.bazel#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(Once main review is done) Could you add README briefly describing this? (per your PR overview)
</blockquote></details>

Done in f0ecfe27840f89661ea8e91b3900f435498250c6
___
*[drake_ros_bazel_installed/apps/inquirer.py, line 19 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8u6bk87GFXGwdhGLf:-MkCr50yAz4ENUXn0xCT:b-9nr40k) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/apps/inquirer.py#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why does this not supply explicit QoS, while the C++ example does?

(if this is common practice, can you provide link to docs?)
</blockquote></details>

No reason. Habit combined with a slight preference over the explicit form. 

Made it consistent in 055193a4e2cc40f33a04d0562778df14f1a984e2. 
___
*[drake_ros_bazel_installed/tools/skylark/dload.bzl, line 15 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8urNY4ZrqDD8eagf8:-MkCs-IN6TvhrJG8tRm6:b2nq7xq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload.bzl#L15)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

These are presently exposed as public API, though they don't seem to be in scope of this library.

Can you make them private, `_unique` / `_normpath`? (or move them to a separate library, ideally without the word `util`?)
</blockquote></details>

Made them private in 701fd860104a331cf4fddafb8aa0eed680d25532
___
*[drake_ros_bazel_installed/tools/skylark/dload.bzl, line 40 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8v6puB7ppEKKOvaJW:-MkCsC_r9N5vzRCIKTvr:b-ujseez) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload.bzl#L40)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can this be private?
</blockquote></details>

Hmm, no, it is used by `dload_*.bzl` files for rule definition.
___
*[drake_ros_bazel_installed/tools/skylark/dload_cc.bzl, line 76 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8vgoq9-MLLUhUHS71:-MkCsbQR11LwYzetYDrn:b-s7cygw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload_cc.bzl#L76)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Perhaps there is a way to have this directly link in the intended code, e.g. `dload_shim_main(...)`, so that way there's less indirection.

However, not sure if there will be any real issues yet with just using `exec`
</blockquote></details>

Hmm, the intended code likely has a `main` already. I guess we could override the executable's entry point. We'd also have to find a way to invoke `_start` or otherwise ensure that any C/C++ runtime setup bits get done. 

What did you have in mind?
___
*[drake_ros_bazel_installed/tools/skylark/dload_py.bzl, line 22 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8wI-p1mMPmQgxXsEF:-MkCuhRZCCbQNNpmyxuL:b-wjz44k) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload_py.bzl#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Having script logic outside of `main()` is OK, but should at least have `assert __name__ == "__main__"` to avoid confusion.

Can you either add this assert, or wrap all logic in `main()`, and use a `if __name__ == "__main__"` stanza?
</blockquote></details>

For sure. I clearly didn't put much effort in cleaning this one up. See e567c106fb8d40ed5470208603721c5e300aad47 
___
*[drake_ros_bazel_installed/tools/skylark/dload_py.bzl, line 53 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8wUQ70grN1V10cqjW:-MkCvdbLDF3FSKpqskBU:bqwmn07) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload_py.bzl#L53)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can this be made private?
</blockquote></details>

Indeed. See 701fd860104a331cf4fddafb8aa0eed680d25532
___
*[drake_ros_bazel_installed/tools/workspace/BUILD.bazel, line  at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8t6nD1kVKNRrKmJnb:-MkCwVnf9mp8A7DHWE6e:b-l3lws8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/239a70c6f98294a963d959262d971ef3a53800a6/drake_ros_bazel_installed/tools/workspace/BUILD.bazel#L)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Empty files (here and elsewhere) should have a comment briefly describing why they're empty; otherwise, it's unclear if this was a mistake.

Can you add a small comment? e.g.
```
# Empty build file to mark package boundaries.
```
</blockquote></details>

Done in ed1bcab6b3e51977ebe085fe5e915789bd99dd7a


<!-- Sent from Reviewable.io -->

2021-09-28 19:57 UTC, EricCousineau-TRI requested changes
> Reviewed 1 of 33 files at r3, 4 of 11 files at r6, 2 of 20 files at r8, 11 of 20 files at r9.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 21 of 80 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/common/README.md, line 1 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mkhwb7E-UtiRmyo33CK:-Mkhwb7FDElYPYHPRhN5:bl5e05f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/common/README.md#L1)):*
> ```Markdown
> ## Common interfaces
> ```

nit I first thought that this was `common` in the sense of the ROS ecosystem; however, it seems like this is "common" to `drake_ros`.

Can this package name be further qualified? e.g. `drake_ros_common`?
___
*[drake_ros_bazel_installed/tools/skylark/dload.bzl, line 40 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8v6puB7ppEKKOvaJW:-MkhwqUiAqEtQCqqpHKO:b-65icqp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload.bzl#L40)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Hmm, no, it is used by `dload_*.bzl` files for rule definition.
</blockquote></details>

OK Gotcha.
___
*[drake_ros_bazel_installed/tools/skylark/dload_cc.bzl, line 76 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8vgoq9-MLLUhUHS71:-MkhwzWx1ilJ6vmflNbT:b-re6eer) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload_cc.bzl#L76)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Hmm, the intended code likely has a `main` already. I guess we could override the executable's entry point. We'd also have to find a way to invoke `_start` or otherwise ensure that any C/C++ runtime setup bits get done. 

What did you have in mind?
</blockquote></details>

I was thinking about having intended code just specify a separate, custom entry point, and we call that through our own `main()`, but perhaps that's not a great idea for now.

So yeah, let's stick w/ the `execv` shim for now - sorry for the distraction!
___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py, line 12 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mkhxa5N9gPxH0GXy6Is:-Mkhxa5N9gPxH0GXy6It:bk4yffo) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py#L12)):*
> ```Python
> import toposort
> 
> sys.path.insert(0, os.path.dirname(__file__))  # noqa
> ```

Inside a bazel runfiles directory, this shouldn't be necessary (as `imports = ...` should be defined)

Is it possible to remove this line?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py, line 142 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MkhxrmyADhh-unbw-cW:-MkhxrmyADhh-unbw-cX:b-nca961) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py#L142)):*
> ```Python
>                     configure_package_share_filegroup(name, metadata, sandbox)
>                 fd.write(interpolate(template, config) + '\n')
>                 
> ```

nit Trailing whitespace (here and elsewhere)
___
*[drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl, line 38 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mkhy6lGEnFLZjPWnKkZ:-Mkhy6lGEnFLZjPWnKk_:b-9mstkb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl#L38)):*
> ```Starlark
>     )
> 
> def use_fastrtps_profile(name):
> ```

Sorry that this has been so long in the tooth, but is there a reason to prefer FastRTPS (old default) over Eclipse Cyclone DDS (newer default)?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl, line 38 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MkhyGAi3My8-d2s0srn:-MkhyGAi3My8-d2s0sro:b9dji78) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl#L38)):*
> ```Starlark
>     )
> 
> def use_fastrtps_profile(name):
> ```

nit `use_fastrtps_profile()` sounds like it's acting upon something, but in fact is returning a dictionary.

Can you rename this to something a bit more indicative of what's going on? e.g. `get_fastrtps_profile`?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2.bzl, line 89 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MkhyvwkDMXgGxdTtZV0:-MkhyvwkDMXgGxdTtZV1:bpvt5jr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/ros2.bzl#L89)):*
> ```Starlark
>     attrs = dict(
>         # Workspaces
>         # - FHS install trees (incl. ABI compatible overlays).
> ```

nit Are overlays presently supported in ROS2?


<!-- Sent from Reviewable.io -->

2021-09-28 20:01 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 44 files at r1, 1 of 42 files at r4, 1 of 20 files at r9.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 24 of 80 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2021-09-30 19:00 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 12 of 80 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/dload_cc.bzl, line 76 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mk8vgoq9-MLLUhUHS71:-Mkrju9Z0XD7t3Y12yjz:bxgtfvi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/fd1e8e4ffd18648df1e2eb9175320bd621a8c842/drake_ros_bazel_installed/tools/skylark/dload_cc.bzl#L76)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I was thinking about having intended code just specify a separate, custom entry point, and we call that through our own `main()`, but perhaps that's not a great idea for now.

So yeah, let's stick w/ the `execv` shim for now - sorry for the distraction!
</blockquote></details>

Oh I see. Yeah, when I wrote this I felt that was a bit too disruptive of anyone's workflow. We can revisit it later though.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py, line 12 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mkhxa5N9gPxH0GXy6Is:-MkriFTc9ujg5xKBIIXH:b-r6uv8v) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py#L12)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Inside a bazel runfiles directory, this shouldn't be necessary (as `imports = ...` should be defined)

Is it possible to remove this line?
</blockquote></details>

The thing is that this script is invoked from the `ros2_local_repository()` rule. Repository rules are executed in the loading phase. It's too early for us to be able to use it as a `py_binary()`. Same goes for the `ros2bzl` and `cmake_tools` modules. Thus this hack.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py, line 142 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MkhxrmyADhh-unbw-cW:-MkriBJ_1aQMXdMOWn0g:b68l581) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py#L142)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Trailing whitespace (here and elsewhere)
</blockquote></details>

Argh, I missed it. Linted all sources in 5192b552add9663521e8e098bf210f874502d52f
___
*[drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl, line 38 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mkhy6lGEnFLZjPWnKkZ:-Mkrhshw38ovOcyLLT5y:bi4qwry) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry that this has been so long in the tooth, but is there a reason to prefer FastRTPS (old default) over Eclipse Cyclone DDS (newer default)?
</blockquote></details>

Back when we started with this `rmw_fastrtps_cpp` was the default RMW implementation. We can add support for both. 
___
*[drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl, line 38 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MkhyGAi3My8-d2s0srn:-Mkri5al3V3AHXPZwL2w:b-nm4nzj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `use_fastrtps_profile()` sounds like it's acting upon something, but in fact is returning a dictionary.

Can you rename this to something a bit more indicative of what's going on? e.g. `get_fastrtps_profile`?
</blockquote></details>

Fair point. Merged it with `incorporate_fastrtps_profile()` in 2ead16b972d0ce43aecf4698413b0e74f6a2ac84.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2.bzl, line 89 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MkhyvwkDMXgGxdTtZV0:-Mkrh61Y7cdwyzo_wto-:b-e79h70) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/ros2.bzl#L89)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Are overlays presently supported in ROS2?
</blockquote></details>

To some extent. So long as each package is found in only one overlay, it will work.
___
*[drake_ros_bazel_installed/common/README.md, line 1 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mkhwb7E-UtiRmyo33CK:-Mkrk21X7qV6g9hzv9_A:b-bpwvs1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/common/README.md#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I first thought that this was `common` in the sense of the ROS ecosystem; however, it seems like this is "common" to `drake_ros`.

Can this package name be further qualified? e.g. `drake_ros_common`?
</blockquote></details>

Sure. Did the same for the `apps` package. See 6f0f56619af9eea1efa36f0f1e5ad58791dc9ecb.


<!-- Sent from Reviewable.io -->

2021-10-04 18:53 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 9 of 81 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl, line 38 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mkhy6lGEnFLZjPWnKkZ:-MlBdS4oCY-jK7364sz6:bqjavjh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl#L38)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Back when we started with this `rmw_fastrtps_cpp` was the default RMW implementation. We can add support for both. 
</blockquote></details>

See 7381bb9 for network isolation when using a Cyclone DDS based RMW implementation.  


<!-- Sent from Reviewable.io -->

2021-10-04 18:55 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 9 of 81 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl, line 38 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mkhy6lGEnFLZjPWnKkZ:-MlBeF9mDP75M9EqvrUT:b-icq159) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl#L38)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

See 7381bb9 for network isolation when using a Cyclone DDS based RMW implementation.  
</blockquote></details>

Also see 7a87131f3939f5dcc58aaf6c7655ca5cd8d795d7 for typo fix :man_facepalming: 


<!-- Sent from Reviewable.io -->

2021-10-05 20:14 UTC, EricCousineau-TRI commented
Per f2f, other high-level comment is if we really need separate shims, or if we can use one or the other (C++ or Python).

A quick automated test for `gdb` to double-check the shim / fork-follow is good. Possibly testing `lldb` sounds good too.

2021-10-08 18:05 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 16 of 81 files reviewed, 10 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl, line 40 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlW3KU3Ar2UhgRiopuV:-MlW3KU3Ar2UhgRiopuW:b-29o21c) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a87131f3939f5dcc58aaf6c7655ca5cd8d795d7/drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl#L40)):*
> ```Starlark
> def generate_isolated_cyclonedds_profile(name):
>     tool = "//tools/skylark/ros2:generate_cyclonedds_profile"
>     label_name = "{}//{}:{}".format(
> ```

Hm... upon reading this again, this might fail when using sharding or having the test runner run a test multiple times; see:
https://docs.bazel.build/versions/4.1.0/test-encyclopedia.html#test-sharding
https://docs.bazel.build/versions/4.1.0/command-line-reference.html#flag--runs_per_test

Is it possible to defer profile env generation to when the process is invoked, where it could use something like a GUID or PWD to generate the hash? (as is done w/ `unique_lcm_url`?)


<!-- Sent from Reviewable.io -->

2021-10-15 21:51 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 10 of 94 files reviewed, 22 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_cyclonedds_profile.py, line 1 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlW2aNyCgCDXAnQRio-:-Mm4w-gT1HMq1jRjNTCc:b-yq284x) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a87131f3939f5dcc58aaf6c7655ca5cd8d795d7/drake_ros_bazel_installed/tools/skylark/ros2/generate_cyclonedds_profile.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should have brief overview docstring

(e.g. "Admits test environment isolation for bazel test runner (see Skylark macro x)").
</blockquote></details>

e83151db383d737f93db80d02a9c579c76e886d8 invalidated this.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl, line 15 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlW4O_tB_wzPIteSzLu:-Mm4vxv2DRQNW3aeUr1q:boqb3vi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a87131f3939f5dcc58aaf6c7655ca5cd8d795d7/drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl#L15)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Same comment as below - hashing based on label will not provide sufficient isolation / "chaos"
</blockquote></details>

Yeap. See e83151db383d737f93db80d02a9c579c76e886d8.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl, line 40 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlW3KU3Ar2UhgRiopuV:-Mm4vorqCFZd9pxVaJdW:b-it2ybs) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a87131f3939f5dcc58aaf6c7655ca5cd8d795d7/drake_ros_bazel_installed/tools/skylark/ros2/rmw.bzl#L40)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Ah, yeah, I didn't consider test sharding. As per f2f chat, I'll try to defer.
</blockquote></details>

Alright, finally got something working. See e83151db383d737f93db80d02a9c579c76e886d8. Unclear whether I can decouple these tools from the enclosing workspace for reuse or not.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_fastrtps_profile.py, line 1 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlW2vf80fT_iY5HUyLc:-Mm4w1BRBb7IhNRfofBa:b-yq284x) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a87131f3939f5dcc58aaf6c7655ca5cd8d795d7/drake_ros_bazel_installed/tools/skylark/ros2/generate_fastrtps_profile.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Same thing here (docstring, usage indicator)
</blockquote></details>

e83151db383d737f93db80d02a9c579c76e886d8 invalidated this.


<!-- Sent from Reviewable.io -->

2021-11-05 16:25 UTC, EricCousineau-TRI requested changes
> Reviewed 1 of 20 files at r13, 1 of 22 files at r15, 1 of 34 files at r17, 2 of 2 files at r19.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 13 of 99 files reviewed, 23 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlWBobW0vkOUxeYFdmo:-Mnkt9twE-BoDz6xx46G:b-w196av) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

"Internal" is accurate. Those macros are parametrized rule implementations and are not meant to be invoked from BUILD.bazel files. Updated documentation in cf5cc5b1f147d11ad66ce2ddd536c779b75f2d50.   
</blockquote></details>

OK Thanks!

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlWB_w_8BfqPwl5_Nq9:-Mnkti7N8WmzdEM9IXDv:b-25hsc3) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

https://github.com/RobotLocomotion/drake-ros/pull/3/commits/5f82eeec3fbb1a0f54af7144bf5cb83e575fc828 starts moving in this direction. It happily solves some of the shortcomings we had with paths.
</blockquote></details>

OK Sweet (per this and VC)

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MmdavUlD_JDT4kazsQg:-Mnkt43c-aLgs-eEXDJY:b-6mowch) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Basic CI workflow is up -- installing prerequisites on a container off of a ROS2 Rolling image to speed things up.

I wonder if this shouldn't be on its own repository though. There is a `drake-ros` CI workflow in the `develop` branch already.
</blockquote></details>

OK Gotcha. I think it's fine to have a separate workflow for now, but yeah, may be good rationale for separating out.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MmdbnDb0qR21TEe1naD:-MnksyZq9wbN_zzIwDqF:buf9gq) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Oops. Some `'manual'` shouldn't have been there in the first place. See 8c1c2ed12d28ef079396e4d9d5dc6010b51cf97f.
</blockquote></details>

Per VC, can you remove `manual` for the GDB / LLDB tests?

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mmy0pYu9lLYfmdMmhI5:-MnktRhl2apiErHgBhaA:b-7mhrk1) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

I stumbled with CMake server errors in my first CI setup attempt. Some day, we'll have to move away from it. Starting with CMake 3.20, the functionality is gone (https://cmake.org/cmake/help/v3.20/manual/cmake-server.7.html). That we knew about and it won't be a problem so long as we stay on Ubuntu 20.04. It will be a problem past that.
</blockquote></details>

Would you be able to put this into an issue?

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MnkuKKdCX0-WTvS2SNG:-MnkuKKe7FG5WbqFEIiu:b-3t7g30) (no related file):*
Seeing collisions on isolation tests. On a 48 core machine:
``
$ bazel test --runs_per_test=1000 -j 48 @ros2//rmw_isolation:rmw_isolation_cc_test
...
@ros2//rmw_isolation:rmw_isolation_cc_test                               FAILED in 11 out of 1000 in 4.6s
```

Failures mostly seem to be of the form:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  I heard 'Howdy'
```

Per VC:
- Possible to change tests to check for isolated traffic using UUID between talker and listener under isolation? Consider replacing glue shell w/ Python.
- Possible to do similar stress test for LCM using `unique_lcm_url` approach?
```


---
___
*[.github/workflows/bazelized.yml, line 32 at r19](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mnkhkd08ctm5UDiZSoO:-Mnkhkd1Cz6JxaEP_ppJ:bwzp06k) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/56d7962a19e0f48329bd4efbca65478af531d0bb/.github/workflows/bazelized.yml#L32)):*
> ```YAML
>       - name: Test Bazel workspace
>         run: |
>           bazel test //drake_ros_apps:gdb_oracle_cc_test
> ```

nit Unclear why you're running each of these in separate invocations. Consider joining them, and just letting Bazel resolve tests, e.g.

```
bazel test //... @ros2//...
```

Ideally, none of the useful tests are manual, so they should all run.
___
*[drake_ros_bazel_installed/README.md, line 25 at r19](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MnkjorK6JQoUlXmybJm:-MnkjorK6JQoUlXmybJn:b-iaoaej) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/56d7962a19e0f48329bd4efbca65478af531d0bb/drake_ros_bazel_installed/README.md#L25)):*
> ```Markdown
> ```
> 
> To run binaries directly: 
> ```

nit (here and elsewhere) Trailing whitespace.
___
*[drake_ros_bazel_installed/tools/skylark/dload_cc.bzl, line 7 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlW1PKw5RmfG58lcXyI:-MnktwN6CeyLN6wI_hTS:b7cvvoo) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a87131f3939f5dcc58aaf6c7655ca5cd8d795d7/drake_ros_bazel_installed/tools/skylark/dload_cc.bzl#L7)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

I ended up clarifying this in rules' documentation. See cf5cc5b1f147d11ad66ce2ddd536c779b75f2d50. Let me know what you think.
</blockquote></details>

OK Yup, better!
___
*[drake_ros_bazel_installed/tools/skylark/kwargs.bzl, line 17 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlW21E06ZWzjJ14BJ_F:-Mnku43k20WmZnBED1Uo:b-mq6amk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a87131f3939f5dcc58aaf6c7655ca5cd8d795d7/drake_ros_bazel_installed/tools/skylark/kwargs.bzl#L17)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Hmm, `ensure` suggests this function adds to `kwargs` when it is filtering it.

Now that I think of it again, the implementation makes no sense. See c74037c6bb74de3704685f1ef1a8da1ea977efd4.
</blockquote></details>

Ah, oops!
Perhaps `filter_to_only_common_kwargs()`?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py, line 12 at r9](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mkhxa5N9gPxH0GXy6Is:-MnkuFyuDrbWs6H5q4zS:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/91392b56311c769820aa1c33a40492f5fd03c0da/drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py#L12)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

See 5fbb60e403beb2c21a092455741f6cba884bc4ed
</blockquote></details>

OK Thanks!


<!-- Sent from Reviewable.io -->

2021-11-08 22:39 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 10 of 100 files reviewed, 22 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MmdbnDb0qR21TEe1naD:-Mo02NiXCtwpVYVqyKe4:bcbdngy) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per VC, can you remove `manual` for the GDB / LLDB tests?
</blockquote></details>

Done in 244adec733b6a7443b4ba6ca0462d780c55290ef

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mmy0pYu9lLYfmdMmhI5:-Mo02kAc4W7KUz88D6sn:b48aour) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Would you be able to put this into an issue?
</blockquote></details>

Done in https://github.com/RobotLocomotion/drake-ros/issues/29.

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MnkuKKdCX0-WTvS2SNG:-Mo06TRtB9rj48zVHDCF:b-zbe9at) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Seeing collisions on isolation tests. On a 48 core machine:
``
$ bazel test --runs_per_test=1000 -j 48 @ros2//rmw_isolation:rmw_isolation_cc_test
...
@ros2//rmw_isolation:rmw_isolation_cc_test                               FAILED in 11 out of 1000 in 4.6s
```

Failures mostly seem to be of the form:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  I heard 'Howdy'
```

Per VC:
- Possible to change tests to check for isolated traffic using UUID between talker and listener under isolation? Consider replacing glue shell w/ Python.
- Possible to do similar stress test for LCM using `unique_lcm_url` approach?
```

</blockquote></details>

Take a look at fa5ec0d0a6be353378c10458143240060bc93c26 and let me know what you think.  I haven't been able to reproduce failures again, yet I don't have a 48 core machine at hand :sweat_smile:  

---
___
*[.github/workflows/bazelized.yml, line 32 at r19](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mnkhkd08ctm5UDiZSoO:-Mo02tdRAYVMGHIIqgpy:b-slnfrd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/56d7962a19e0f48329bd4efbca65478af531d0bb/.github/workflows/bazelized.yml#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why you're running each of these in separate invocations. Consider joining them, and just letting Bazel resolve tests, e.g.

```
bazel test //... @ros2//...
```

Ideally, none of the useful tests are manual, so they should all run.
</blockquote></details>

Sounds good. Done in d0c020bdc5872e3c63d6b5c94dc01d6e3324876e.
___
*[drake_ros_bazel_installed/README.md, line 25 at r19](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MnkjorK6JQoUlXmybJm:-Mo03Wr140GLx_MdOHGB:b-fxsdik) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/56d7962a19e0f48329bd4efbca65478af531d0bb/drake_ros_bazel_installed/README.md#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (here and elsewhere) Trailing whitespace.
</blockquote></details>

Argh. Fixed in 7c998b8b4f6c8303aefe709ef8e7bb8143d1f392.
___
*[drake_ros_bazel_installed/tools/skylark/kwargs.bzl, line 17 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlW21E06ZWzjJ14BJ_F:-Mo06RGP2Zv1_AwwhxJ_:b-ub3sty) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a87131f3939f5dcc58aaf6c7655ca5cd8d795d7/drake_ros_bazel_installed/tools/skylark/kwargs.bzl#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, oops!
Perhaps `filter_to_only_common_kwargs()`?
</blockquote></details>

Renamed in 687f6180edbf38124920cc4dcfcd7adf5d6ba05c.


<!-- Sent from Reviewable.io -->

2021-11-08 22:46 UTC, hidmic commented
> bazel-out/k8-opt/bin/_solib_k8/_U@ros2_S_S_Crclcpp_Uaction_Ucc___U_Uopt_Uros_Urolling_Slib/librclcpp_action.so: error: undefined reference to 'rclcpp::exceptions::throw_from_rcl_error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcutils_error_state_s const*, void (*)())'

Hmm, something changed upstream. I'll look into it tomorrow.

2021-11-09 14:41 UTC, hidmic commented
Found it. It's a partial upgrade of the base Rolling installation that comes with the container image. Working on a fix.

2021-11-10 00:08 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 20 files at r9, 9 of 23 files at r10, 5 of 20 files at r13, 3 of 16 files at r14, 1 of 3 files at r16, 6 of 34 files at r17, 6 of 16 files at r20, 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 41 of 100 files reviewed, 14 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py, line 4 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo63U5fBh5aMTnRvHVN:-Mo63U5fBh5aMTnRvHVO:b-gdmfqc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py#L4)):*
> ```Python
> 
> """
> Scraps ROS 2 workspaces and exposes their artifacts through a Bazel local repository.
> ```

nit "Scraps" => "Scrapes"
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 3 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo63qOaCnQhcdL7WBcZ:-Mo63qOaCnQhcdL7WBc_:b-4199xl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L3)):*
> ```Markdown
> ## Infrastructure to use ROS 2 from a Bazel workspace
> 
> This package encapsulates all the machinery to pull a ROS 2 workspace install space or a subset thereof as a Bazel repository.
> ```

nit Is it possible to state reason why we forgo `cmake.bzl` from these tools?
https://github.com/bazelbuild/rules_foreign_cc/blob/main/foreign_cc/cmake.bzl

e.g. "they don't have cmake-server for speed", etc.?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 30 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo64GEFAdcr7Nsj7Uev:-Mo64GEFAdcr7Nsj7Uew:b3et7e4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L30)):*
> ```Markdown
> ```
> 
> Note that all files and subdirectories that are mere implementation details have been excluded from this layout. 
> ```

nit More trailing whitespace ;)
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 37 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo64P0t7bWR09y-dAuV:-Mo64P0t7bWR09y-dAuW:btgo385) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L37)):*
> ```Markdown
> 
> - A `<package_name>_share` filegroup for every package that installs artifacts under the share directory.
> - A `<package_name>_cc` C/C++ library for every CMake package that installs C++ binary artifacts (in addition to compiler/linker flags, includes, etc.).
> ```

nit "library for every CMake package that installs" => This phrase is ambiguous; I can't tell if it's filtering based on that criteria, or that's what the target does.

I know it's the former - any chance that could be disambiguated? My suggestion is to take the "filtering" part and hoist it to top-level:

```
For each package in [...], if the CMake build generates the relevant install artifacts, then the following Bazel targets (with declared immediate dependencies) are produced:
[...]
- `<package_name>_py` - package's Python libraries
- `<package_name>_cc` - package's C/C++ libraries
```
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 41 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo66DYP6YNhgReCvDwZ:-Mo66DYP6YNhgReCvDw_:b-6txocp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L41)):*
> ```Markdown
> - A `<package_name>_defs` filegroup for every package that installs ROS 2 interfaces (.msg, .srv, .action, and .idl files). 
> - A `<package_name>_c` C/C++ library for every CMake package that installs C binary artifacts. Typically an alias of the `<package>_cc` C/C++ library if C and C++ binary artifacts cannot be told apart.
> - A `<package_name>_transitively_py` Python library for every package that does not install a Python egg yet it depends and it is a dependency of packages that do. This helps maintain the dependency graph.
> ```

nit Grammar - "yet it depends and it is a"

Possible to fix?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 41 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo66ItW0NvJdcnwdnWq:-Mo66ItX7oqvyejhjbif:brdsjo0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L41)):*
> ```Markdown
> - A `<package_name>_defs` filegroup for every package that installs ROS 2 interfaces (.msg, .srv, .action, and .idl files). 
> - A `<package_name>_c` C/C++ library for every CMake package that installs C binary artifacts. Typically an alias of the `<package>_cc` C/C++ library if C and C++ binary artifacts cannot be told apart.
> - A `<package_name>_transitively_py` Python library for every package that does not install a Python egg yet it depends and it is a dependency of packages that do. This helps maintain the dependency graph.
> ```

nit "transitively" is an adverb, but our targets are generally nouns (plus adjectives).

Can you rename suffix to "transitive_py"?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 43 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo66XJ-0J_EQWLsmJOh:-Mo66XJ-0J_EQWLsmJOi:b-rdpzmf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L43)):*
> ```Markdown
> - A `<package_name>_transitively_py` Python library for every package that does not install a Python egg yet it depends and it is a dependency of packages that do. This helps maintain the dependency graph.
> - A `<package_name>_<executable_name>` for every executable installed at the package-level (i.e. under `lib/<package>`, where `ros2 run` can find them).
> - A `<executable_name>` for every executable installed under the `bin` directory (and thus in the `$PATH`).
> ```

nit "and thus in the `$PATH`" is confusing.

I assume it means "and thus is accessible in nominal install workspace via $PATH, but it doesn't impact Bazel at all."
Consider rewording a bit more succinctly, e.g.
```
for every executable installed under the `<install_root>/bin` directory
```
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 47 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo644eL6DzgXh2DSQMW:-Mo644eL6DzgXh2DSQMX:bp2gsz4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L47)):*
> ```Markdown
> #### Rules
> 
> To build C++ binaries and tests that depend on ROS 2, `ros_cc_binary` and `ros_cc_test` rules are available in the `ros_cc.bzl` file. These rules, equivalent to the native `cc_binary` and `cc_test` rules, ensure these binaries run in a environment that is tightly coupled with the underlying ROS 2 workspace install space.
> ```

nit Can you word-wrap these to 80 lines?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 51 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo641995VxwibtMviuw:-Mo641995VxwibtMviux:bbz6vad) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L51)):*
> ```Markdown
> To build Python binaries and tests that depend on ROS 2, `ros_py_binary` and `ros_pytest` rules are available in the `ros_py.bzl` file. These rules, equivalent to the native `py_binary` and `py_test` rules, ensure these binaries run in a envi [...]

2021-12-07 15:11 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 41 of 100 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py, line 4 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo63U5fBh5aMTnRvHVN:-MqKRLOF8d1_z6nK8uEL:bh8m59b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py#L4)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "Scraps" => "Scrapes"
</blockquote></details>

Done in e40de0161d099c0500b6edcc7bc2f937e147b031
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 3 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo63qOaCnQhcdL7WBcZ:-MqKLFRo1k94IPyBZs_j:b-qdwvwb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L3)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Is it possible to state reason why we forgo `cmake.bzl` from these tools?
https://github.com/bazelbuild/rules_foreign_cc/blob/main/foreign_cc/cmake.bzl

e.g. "they don't have cmake-server for speed", etc.?

</blockquote></details>

Hmm, I think mentioning `rules_foreign_cc` would be confusing.

IIUC, our use case is fundamentally different from that of `rules_foreign_cc`. We are not building CMake projects from Bazel, we are collecting CMake projects' exported configurations from Bazel. I guess we could've generated one dummy CMake project per system-installed ROS package as a proxy to get that information using `rules_foreign_cc`, but it would've been insufficient (think CMake-installed Python eggs) and somewhat icky.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 30 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo64GEFAdcr7Nsj7Uev:-MqKQtYV-V1ISqmOKsPx:b-smpe4q) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit More trailing whitespace ;)
</blockquote></details>

Argh, fixed in e40de0161d099c0500b6edcc7bc2f937e147b031. We need linters.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 37 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo64P0t7bWR09y-dAuV:-MqKR-QjAUd9YWMn6iHb:b-npj25w) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "library for every CMake package that installs" => This phrase is ambiguous; I can't tell if it's filtering based on that criteria, or that's what the target does.

I know it's the former - any chance that could be disambiguated? My suggestion is to take the "filtering" part and hoist it to top-level:

```
For each package in [...], if the CMake build generates the relevant install artifacts, then the following Bazel targets (with declared immediate dependencies) are produced:
[...]
- `<package_name>_py` - package's Python libraries
- `<package_name>_cc` - package's C/C++ libraries
```
</blockquote></details>

Rephrased in e40de0161d099c0500b6edcc7bc2f937e147b031. PTAL
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 41 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo66DYP6YNhgReCvDwZ:-MqKR2lb2jrLGBpIdErG:b-dztan1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Grammar - "yet it depends and it is a"

Possible to fix?
</blockquote></details>

Rephrased in e40de0161d099c0500b6edcc7bc2f937e147b031.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 41 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo66ItW0NvJdcnwdnWq:-MqKRB-76QNVAkUjgffA:b728xiz) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "transitively" is an adverb, but our targets are generally nouns (plus adjectives).

Can you rename suffix to "transitive_py"?
</blockquote></details>

Done in bb2ec9a4f4f840c85098aee33e9bbea098e086cf.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 43 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo66XJ-0J_EQWLsmJOh:-MqKR5WCBXR6Eh1ju4Ej:b-dztan1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L43)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "and thus in the `$PATH`" is confusing.

I assume it means "and thus is accessible in nominal install workspace via $PATH, but it doesn't impact Bazel at all."
Consider rewording a bit more succinctly, e.g.
```
for every executable installed under the `<install_root>/bin` directory
```
</blockquote></details>

Rephrased in e40de0161d099c0500b6edcc7bc2f937e147b031.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 47 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo644eL6DzgXh2DSQMW:-MqKR7CMCGPAUdOhWNID:bh8m59b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L47)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you word-wrap these to 80 lines?
</blockquote></details>

Done in e40de0161d099c0500b6edcc7bc2f937e147b031
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 51 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo641995VxwibtMviuw:-MqKR7q97pp7418If1tZ:b-bwotp1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L51)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Extra comma: "and builds them, off of" 
</blockquote></details>

Rephrased in e40de0161d099c0500b6edcc7bc2f937e147b031
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2.bzl, line 106 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo671N3DKWmttRpk6w0:-MqKREqYDbcGYJ0Qt0Ic:b-xttwr5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5f82eeec3fbb1a0f54af7144bf5cb83e575fc828/drake_ros_bazel_installed/tools/skylark/ros2/ros2.bzl#L106)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "included files" => "included packages"?
</blockquote></details>

Done in e40de0161d099c0500b6edcc7bc2f937e147b031.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2.bzl, line 101 at r19](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mnl2B7rCMLRP3nqinQS:-MqKRCe_1Kxy69a4s9aF:b-xttwr5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/56d7962a19e0f48329bd4efbca65478af531d0bb/drake_ros_bazel_installed/tools/skylark/ros2/ros2.bzl#L101)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "Scraps" => "Scrapes" ;)
</blockquote>< [...]

2021-12-08 18:14 UTC, hidmic commented
@EricCousineau-TRI @IanTheEngineer should we merge this into `develop`? And unify provisioning and CI (#27)?

2021-12-16 18:27 UTC, hidmic commented
@cottsay I could definitely use some :eyes: here.

2021-12-17 19:16 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 38 of 100 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/setup/install_prereqs.sh, line 5 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8odUdA79CIr4Hr6u0:-Mr8odUdA79CIr4Hr6u1:b-n3d2s9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/setup/install_prereqs.sh#L5)):*
> ```Shell
> set -eux pipefail
> 
> apt update && apt install -y apt-transport-https curl gnupg lsb-release cmake build-essential gettext-base
> ```

Can you remove usage of `-y` here?


<!-- Sent from Reviewable.io -->

2021-12-17 19:19 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 38 of 100 files reviewed, 10 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/setup/install_prereqs.sh, line 10 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8pCxo0pkWqycuUs2F:-Mr8pCxo0pkWqycuUs2G:b-altckj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/setup/install_prereqs.sh#L10)):*
> ```Shell
> curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
> mv bazel.gpg /etc/apt/trusted.gpg.d/
> echo "deb [arch=$(dpkg --print-architecture)] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
> ```

This diverges from usage in Drake; for consistency, could you install from `wget`, and keep the option say yes or no on upgrade?

https://github.com/RobotLocomotion/drake/blob/7f18c8a520b7fbc23a5f963320f2b3db90f4e04f/setup/ubuntu/source_distribution/install_prereqs.sh#L181-L184


<!-- Sent from Reviewable.io -->

2021-12-17 19:31 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 38 of 100 files reviewed, 11 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/build.bazel, line 82 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8rqPb8um2Gcj5tK7u:-Mr8rqPb8um2Gcj5tK7v:bmcwvxq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/build.bazel#L82)):*
> ```
>     ],
>     data = [":isolated_talker_py", ":isolated_listener_py"],
>     shard_count = 10,
> ```

Per VC, prefer to dispatch multiple runs w/in binary (e.g. Python / Bash job concurrency) to escape Bazel's conservative resource limitation.

Also, let user configure `--runs_per_test` for add'l stress test.


<!-- Sent from Reviewable.io -->

2021-12-17 19:31 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 38 of 100 files reviewed, 12 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/build.bazel, line 1 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8sCADDZvF-9sARjk3:-Mr8sCADDZvF-9sARjk4:bedmw51) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/build.bazel#L1)):*
> ```
> # -*- python -*-
> ```

nit File should be called `BUILD.bazel`, for consistency?


<!-- Sent from Reviewable.io -->

2021-12-17 19:34 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 5 files at r22.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 39 of 100 files reviewed, 13 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py, line 28 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8sNVn79rmfOYYi5GP:-Mr8sNVn79rmfOYYi5GQ:b-740hhg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py#L28)):*
> ```Python
> sys.path.insert(0, os.path.dirname(__file__))  # noqa
> 
> from ros2bzl.scrapping import load_distribution
> ```

nit "scrapping" => "scraping"?


<!-- Sent from Reviewable.io -->

2021-12-17 19:42 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 5 files at r22.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 40 of 100 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 3 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo63qOaCnQhcdL7WBcZ:-Mr8srvRAJsS2bDJux3O:bo62idi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L3)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Hmm, I think mentioning `rules_foreign_cc` would be confusing.

IIUC, our use case is fundamentally different from that of `rules_foreign_cc`. We are not building CMake projects from Bazel, we are collecting CMake projects' exported configurations from Bazel. I guess we could've generated one dummy CMake project per system-installed ROS package as a proxy to get that information using `rules_foreign_cc`, but it would've been insufficient (think CMake-installed Python eggs) and somewhat icky.
</blockquote></details>

I think it's still good to mention in terms of "alternatives considered", with your explanation.

Would you be able to add that in?


<!-- Sent from Reviewable.io -->

2021-12-17 19:46 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 40 of 100 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/build.bazel, line 1 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8sCADDZvF-9sARjk3:-Mr8v25G09R-sMJjlx8G:bbw633t) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/build.bazel#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit File should be called `BUILD.bazel`, for consistency?
</blockquote></details>

Per VC, this was done to defer to use in generated repository.

Consider using `package.BUILD.bazel`
https://github.com/RobotLocomotion/drake/blob/v0.37.0/tools/workspace/fmt/package.BUILD.bazel
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/build.bazel, line 32 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8uvXFBUwbkaViA7m4:-Mr8uvXFBUwbkaViA7m5:b-ebzckp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/build.bazel#L32)):*
> ```
>     outs = ["rmw_isolation.cc"],
>     cmd = (
>         "ISOLATED_RMW_ENV_PATH={}/rmw_isolation/isolated_rmw_env ".format(
> ```

Per VC, is it possible to remove the use of templating here, and simply require that the user pass in the runfile path spec for the binary?

(then users can wrap as they see fit)


<!-- Sent from Reviewable.io -->

2021-12-17 19:54 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 40 of 100 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/bazel/py_tools.bzl.tpl, line 27 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MlWAs_T2sa0IuZ3lnba:-Mr8wvay9OmLH2UgUTmW:b-82yrew) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7a87131f3939f5dcc58aaf6c7655ca5cd8d795d7/drake_ros_bazel_installed/tools/skylark/ros2/resources/bazel/py_tools.bzl.tpl#L27)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Not quite. It is akin to Bazel's builtin `cc_import` rule. It essentially builds a Python shim for an existing, pre-built executable.

Would `ros_exec_import` be a clearer name?
</blockquote></details>

Per VC, understood on relation to `cc_import`, but it's still for libs.

Better to say `ros_import_binary`, perhaps?
(and note that wrapped binary does not necessary need to be Python?)


<!-- Sent from Reviewable.io -->

2021-12-17 20:02 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 40 of 100 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MnkuKKdCX0-WTvS2SNG:-Mr8z7xHDhP_ILDLpo3D:b-svy54i) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Take a look at fa5ec0d0a6be353378c10458143240060bc93c26 and let me know what you think.  I haven't been able to reproduce failures again, yet I don't have a 48 core machine at hand :sweat_smile:  
</blockquote></details>

Looks like we have 9 / 10000 failures: https://gist.github.com/EricCousineau-TRI/538849ba7b9f4d67a9a9fe7697890d75

Not too bad!

Is it possible to document this issue in a README here, perhaps add an issue to fix?

---


<!-- Sent from Reviewable.io -->

2021-12-17 20:05 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 42 files at r4, 1 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 40 of 100 files reviewed, 10 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/dload_cc.bzl, line 83 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8zzFh7TzxTSFTbKUl:-Mr8zzFiA4V7dTOn3Lvt:b4ctcwi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/dload_cc.bzl#L83)):*
> ```Starlark
>   other_argv[argc] = NULL;
>   int ret = execv(other_argv[0], other_argv);
>   std::cout << "ERROR: " << strerror(errno) << std::endl;
> ```

nit For clarity, can you comment here that this would only return control here if `execv` itself fails (e.g. can't find the binary)?


<!-- Sent from Reviewable.io -->

2021-12-17 20:23 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 20 files at r13, 1 of 5 files at r22.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 41 of 100 files reviewed, 11 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/ros_py.bzl, line 85 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr92YZBBWzuBoHqF7Qb:-Mr92YZBBWzuBoHqF7Qc:b-qw5yy5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/ros_py.bzl#L85)):*
> ```Starlark
>     """
> 
>     binary_name = "_" + name
> ```

nit From looking at output, was confused concretely about `_{name}_{lang}` for both Python and C++.

Can we add add'l annotation about what the target is, e.g. `_{name}_{lang}_shimmed`, to parallel the generated source file?
e.g. `_inquirer_cc` will become `_inquirer_cc_shimmed`, which would be invoked by `_inquirer_cc_shim.cc`


<!-- Sent from Reviewable.io -->

2021-12-17 20:26 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 41 of 100 files reviewed, 11 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr93V5a4itG4w9NA9kj:-Mr93V5a4itG4w9NA9kk:b4f1glh) (no related file):*
BTW Inspected output of `bazel query //... @ros//... | sort`, and it looks good!

---


<!-- Sent from Reviewable.io -->

2021-12-17 20:28 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 41 of 100 files reviewed, 12 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr93qDq3o-N4WdXzroY:-Mr93qDq3o-N4WdXzroZ:b-jc3nzq) (no related file):*
nit Per VC, could any targets that are implementation details have a preceding `_`?

---


<!-- Sent from Reviewable.io -->

2021-12-17 20:29 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 41 of 100 files reviewed, 13 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rosidl.bzl, line 780 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr94L3a9q8-uVSmzkbt:-Mr94L3a9q8-uVSmzkbu:b-64trzq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/rosidl.bzl#L780)):*
> ```Starlark
>     )
> 
> def defs(name):
> ```

nit These naming functions appear to be implementation details.

Can you make them private?


<!-- Sent from Reviewable.io -->

2021-12-17 20:35 UTC, EricCousineau-TRI reviewed
> Reviewed 5 of 34 files at r17, 6 of 16 files at r20.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 52 of 100 files reviewed, 16 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/isolated_rmw_env.py, line 1 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr95I0dE2vOy9EpnFuV:-Mr95I0dE2vOy9EpnFuW:b-ytucur) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/isolated_rmw_env.py#L1)):*
> ```Python
> #!/usr/bin/env python3
> ```

nit Was unclear if this was library or binary.

For this binary, can you add an action name to it, e.g., `generate_isolated_rmw_env`?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/isolated_rmw_env.py, line 4 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr94gjlDfajLwciJ6n5:-Mr94gjlDfajLwciJ6n6:bk9d9i9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/isolated_rmw_env.py#L4)):*
> ```Python
> 
> """
> Generates a runtime environment for RMW isolation.
> ```

nit Can you mention how this is to be used? (e.g. the corresponding cc / py targets that allow users to leverage this?)
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py, line 23 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr95dsH0Hbs_cfwxn5C:-Mr95dsI1rgKwDRdvJVY:b1zrmpe) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py#L23)):*
> ```Python
> 
> if __name__ == '__main__':
>     if 'TEST_TMPDIR' in os.environ:
> ```

nit This should be declared in a `main()` function; otherwise, globals can leak out.


<!-- Sent from Reviewable.io -->

2021-12-17 20:52 UTC, EricCousineau-TRI requested changes
> Reviewed 1 of 44 files at r1, 5 of 33 files at r3, 12 of 42 files at r4, 2 of 11 files at r6, 1 of 13 files at r7, 2 of 20 files at r8, 3 of 20 files at r9, 4 of 23 files at r10, 1 of 20 files at r13, 3 of 16 files at r14, 1 of 22 files at r15, 12 of 34 files at r17, 2 of 16 files at r20, 2 of 5 files at r22.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: all files reviewed, 23 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/resources.py, line 13 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr96bwM0oEbwDxE22-y:-Mr96bwM0oEbwDxE22-z:b-jhpcpr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/resources.py#L13)):*
> ```Python
> 
> 
> @functools.lru_cache(maxsize=None)
> ```

nit Use of `lru_cache` here seems a bit premature.

Can this be removed for now?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py, line 1 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr96lXn58DvyVqgtDtC:-Mr96lXn58DvyVqgtDtD:bz5ikw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py#L1)):*
> ```Python
> import os
> ```

nit Unclear what the intent of this is.

Can you describe this briefly?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py, line 4 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr97OYX2MYK6zTE_jre:-Mr97OYY4i5L_WwMGRJm:b-w0q7jx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py#L4)):*
> ```Python
> 
> 
> def configure(name, mapping):
> ```

nit `configure` is a bit ambiguous.

Can you update the name to reflect the intent a bit more, if possible? e.g.
```
make_symlink_forest_mapping()
```
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py, line 16 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr97GDS5qfovfQn6no2:-Mr97GDTBX0P6FJXYUw2:bqa3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py#L16)):*
> ```Python
>                 return path
>         return path
>     sandbox.kwargs = dict(name=name, mapping=mapping)
> ```

nit This usage seems a bit odd.

Can you instead use `functools.partial(sandbox, name, mapping)`?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scrapping/system.py, line 6 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr98EkY2LeIv9oJq9bK:-Mr98EkY2LeIv9oJq9bL:bm251md) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scrapping/system.py#L6)):*
> ```Python
> import sys
> 
> DEFAULT_INCLUDE_DIRECTORIES = ['/usr/include', '/usr/local/include']
> ```

For usage w/ Bazel, we should avoid accidentally eating things that someone may have sprayed into `/usr/local`.

Can you remove usage of `/usr/local` here?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/rmw_isolation.py, line 181 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr95zWBBPWxegxx9TyC:-Mr95zWBBPWxegxx9TyD:blweaxz) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/rmw_isolation.py#L181)):*
> ```Python
>     if rmw_implementation is None:
>         rmw_implementation = rclpy.get_rmw_implementation_identifier()
>     target_function_name = f'isolated_{rmw_implementation}_env'
> ```

nit Rather than using pattern matching w/ `globals()`, can you instead make an explicit registry `dict`? e.g.
```
_RMW_ISOLATION_FUNC = {
  "rmw_cyclone_dds": ...,
   ...
}
```
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/templates/ament_cmake_CMakeLists.txt.in, line 1 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr96Kxn7Y4dQsSfAexS:-Mr96Kxn7Y4dQsSfAexT:batipql) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/resources/templates/ament_cmake_CMakeLists.txt.in#L1)):*
> ```
> # Generated by Bazel.
> ```

nit Usage of file is unclear, and is confusing w/ mention of `Generated by Bazel`.

Can you describe what this template / file is for?


<!-- Sent from Reviewable.io -->

2021-12-17 20:53 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> pending discussion items

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-:-Mr99toxDLTBqTm_AryF:bb1q8ps)* status: all files reviewed, 23 unresolved discussions (waiting on @hidmic and @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2021-12-21 20:17 UTC, hidmic reviewed
Thanks @ericcousineau-tri! 

@cottsay would you mind taking a final look before we merge?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-:-MrTcucWAWhv23EQi-DR:bf2datj)* status: all files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MnkuKKdCX0-WTvS2SNG:-MrTb7uC7ZDjsyfF-O9_:b9hws0n) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Looks like we have 9 / 10000 failures: https://gist.github.com/EricCousineau-TRI/538849ba7b9f4d67a9a9fe7697890d75

Not too bad!

Is it possible to document this issue in a README here, perhaps add an issue to fix?
</blockquote></details>

Done in 21718a9a07767d3fcba47a31e7c18db6288f455b. 

I gave it some thought to the idea of implementing a form of backoff mechanism to further reduce our collision rate. The main issue here is collision detection. There's no ROS 2 API we can use to tell in an application-agnostic way whether a collision has ensued or not. Thinking out loud, I think we need a system-wide hash map where processes can check if their IP/ports "slot" is occupied. But I'll defer that to another ticket. 

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr93qDq3o-N4WdXzroY:-MrOHgXc309TkN4OGI4I:b-jbi1j2) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Per VC, could any targets that are implementation details have a preceding `_`?
</blockquote></details>

Done in 24c5c7bc866908505acd34a84d875ce5f77874ab, but only to the extent that it is possible. Several binaries, namely those that are either CPython extensions or rosidl typesupport shared libraries, must have a specific name for dependent code to be able to dlopen them later. I have yet to find a linker-agnostic way to force a `cc_binary` output name to be anything but the target name. 

---
___
*[drake_ros_bazel_installed/setup/install_prereqs.sh, line 5 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8odUdA79CIr4Hr6u0:-MrNbDU7-jF5OYjVRNLw:b-prms89) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/setup/install_prereqs.sh#L5)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you remove usage of `-y` here?
</blockquote></details>

Done in 98042d4d332416a095b6640b8ee980b008ef667a
___
*[drake_ros_bazel_installed/setup/install_prereqs.sh, line 10 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8pCxo0pkWqycuUs2F:-MrNbENg8nMkLaViE8Vd:bualo6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/setup/install_prereqs.sh#L10)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This diverges from usage in Drake; for consistency, could you install from `wget`, and keep the option say yes or no on upgrade?

https://github.com/RobotLocomotion/drake/blob/7f18c8a520b7fbc23a5f963320f2b3db90f4e04f/setup/ubuntu/source_distribution/install_prereqs.sh#L181-L184
</blockquote></details>

Done in  98042d4d332416a095b6640b8ee980b008ef667a. I kept `curl` though (a bit more versatile than `wget`).
___
*[drake_ros_bazel_installed/tools/skylark/dload_cc.bzl, line 83 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8zzFh7TzxTSFTbKUl:-MrNjPEq-b-2r-MXs3_W:b2nh24g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/dload_cc.bzl#L83)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For clarity, can you comment here that this would only return control here if `execv` itself fails (e.g. can't find the binary)?
</blockquote></details>

Done in 0bffdc958b5986d58383de42b7606d4e52a1ff4f.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py, line 28 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr8sNVn79rmfOYYi5GP:-MrNkXvACKIpEOvECLpy:b-pr8wng) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/generate_repository_files.py#L28)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "scrapping" => "scraping"?
</blockquote></details>

Done in 84c8910c2794ee8f9b0046abe4387c38372625d6.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 3 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mo63qOaCnQhcdL7WBcZ:-MrNpG_Y3-04VlpSeUVk:b-qfdgxm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c9264db8b9cb3506a7e33a565d4267f28e22217c/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L3)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I think it's still good to mention in terms of "alternatives considered", with your explanation.

Would you be able to add that in?
</blockquote></details>

Done in ff444cc7c9ef0edad5eb08cd715a3c870b8e8d78
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/resources.py, line 13 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr96bwM0oEbwDxE22-y:-MrO0L3jCmLep74AAlEo:b-s0qfi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/resources.py#L13)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Use of `lru_cache` here seems a bit premature.

Can this be removed for now?
</blockquote></details>

Done in 78fb9397a8e007e571ac1e6731e6edd36acaece2
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py, line 1 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr96lXn58DvyVqgtDtC:-MrO1Iw48mgSwnaBCtCx:br3xnu4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear what the intent of this is.

Can you describe this briefly?
</blockquote></details>

Done in 3faa640f34df55cb351e815e71f564c9cb8de818
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py, line 4 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr97OYX2MYK6zTE_jre:-MrO1IJW-3dGZE6QJ3vS:br3xnu4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py#L4)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `configure` is a bit ambiguous.

Can you update the name to reflect the intent a bit more, if possible? e.g.
```
make_symlink_forest_mapping()
```
</blockquote></details>

Done in 3faa640f34df55cb351e815e71f564c9cb8de818
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py, line 16 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr97GDS5qfovfQn6no2:-MrO1BCi6NwgBYzy7HFF:bbq3nu3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/sandboxing.py#L16)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This usage seems a bit odd.

Can you instead use `functools.partial(sandbox, name, mapping)`?
</blockquote></details>

This is actually a leftover from an earlier version of the message generatio [...]

2021-12-21 20:27 UTC, EricCousineau-TRI requested changes
> Reviewed 1 of 34 files at r17, 29 of 29 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 100 of 101 files reviewed, 3 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr93qDq3o-N4WdXzroY:-MrTfHQ65t1EXFcRGLlq:b-w196av) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Done in 24c5c7bc866908505acd34a84d875ce5f77874ab, but only to the extent that it is possible. Several binaries, namely those that are either CPython extensions or rosidl typesupport shared libraries, must have a specific name for dependent code to be able to dlopen them later. I have yet to find a linker-agnostic way to force a `cc_binary` output name to be anything but the target name. 
</blockquote></details>

OK Thanks!

---
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/package.BUILD.bazel, line 33 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrTdpGtDREQwrRFzKvU:-MrTdpGtDREQwrRFzKvV:b-qkyekh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/package.BUILD.bazel#L33)):*
> ```
>     data = [":generate_isolated_rmw_env"],
>     local_defines = [
>         "RMW_ISOLATION_ROOTPATH={}/rmw_isolation".format(
> ```

TIL `local_defines` - nice!
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/package.BUILD.bazel, line 76 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrTduuB80I7Wkr1CaU9:-MrTduuB80I7Wkr1CaUA:b8rv05q) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/package.BUILD.bazel#L76)):*
> ```
>     data = [":isolated_talker_py", ":isolated_listener_py"],
>     size = "small",
>     flaky = True,
> ```

nit (Here and below) Can you mention why this is marked as flaky?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py, line 31 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrTeHSuAMvC0ipmrY0j:-MrTeHSv6aNfxZEWxEH3:b4kqmv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py#L31)):*
> ```Python
> 
>     uuid = os.environ.get('TEST_TMPDIR', 'none')
>     try:
> ```

BTW Why not `try ... finally: rclpy.shutdown()`?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py, line 41 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrTeMhA34dGUkg20fyr:-MrTeMhA34dGUkg20fys:b-hoepz8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py#L41)):*
> ```Python
>         raise
> ```

nit Extra lines?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scraping/ament_cmake.py, line 62 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrTelg_20sCdflrMXqz:-MrTelg_20sCdflrMXr-:bl2dad1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scraping/ament_cmake.py#L62)):*
> ```Python
>             ])
>         # Fail on any /usr/local libraries
>         local_link_libraries = [
> ```

BTW We may want to allow people to opt into this in the future, but I do like it being off by default - thanks!
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scrapping/system.py, line 6 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Mr98EkY2LeIv9oJq9bK:-MrTexfc6X4xU1dMo69_:bz69yrx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/bb2ec9a4f4f840c85098aee33e9bbea098e086cf/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scrapping/system.py#L6)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

We can't change an already linked binary nor the fact that compiler and linker will look under these directories after exhausting all user provided ones. 

What we can do is to fail when we detect it. See 93fa595feb5cc1edd56cdd0eb235be5865ef4a07.
</blockquote></details>

Gotcha; can you add a brief comment to that effect for `DEFAULT_*`?


<!-- Sent from Reviewable.io -->

2021-12-22 01:55 UTC, cottsay reviewed
> Reviewed 1 of 34 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: all files reviewed, 18 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 67 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUeiyR0cDt1wSrd-Gc:-MrUeiyR0cDt1wSrd-Gd:bu22e4x) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L67)):*
> ```Markdown
> - A `<package_name>_c` C/C++ library for C libraries. Typically an alias of the
>   `<package>_cc` target if C and C++ libraries cannot be told apart.
> - A `<package_name>_transitive_py` Python library if the package has does not
> ```

Nix the 'has'.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 74 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUf9oS2zKgO4U9i2iT:-MrUf9oS2zKgO4U9i2iU:b-j3t736) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L74)):*
> ```Markdown
>   installed at the package-level (i.e. under `lib/<package_name>`, where
>   `ros2 run` can find them).
> - A `<executable_name>` Python binary for each executable installed under the
> ```

What about non-Python executables installed to the global bin directory? I'm not sure there are any in `ros2.repos`, but it's certainly possible to do.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 83 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUfSaV0sELTiTMX4yK:-MrUfSaW373JPa13QTwR:bsl1wn2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L83)):*
> ```Markdown
> `ros_cc_test` rules are available in the `ros_cc.bzl` file. These rules,
> equivalent to the native `cc_binary` and `cc_test` rules, ensure these binaries
> run in a environment that is tightly coupled with the underlying ROS 2 workspace
> ```

...run in *an* environment...
Same in the next paragraph.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 99 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUfvuT3d9d2pXR2Hf5:-MrUfvuU6v-NRIi4Mhix:b-oiilj3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L99)):*
> ```Markdown
> following strict naming conventions (e.g. C++ and Python interface libraries
> carry `_cc` and `_py` suffixes, respectively), though finer-grained control over
> what is generated and built can be achieved through via other rules available in
> ```

Nix either through or via 
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 111 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUg8Rd-tS3z_n_z4Kj:-MrUg8Rd-tS3z_n_z4Kk:b-jvtg4a) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L111)):*
> ```Markdown
> 
> **DISCLAIMER**
> : Isolation relies on `rmw`-specific configuration. Support is available for 
> ```

nitpick: trailing whitespace
___
*[drake_ros_bazel_installed/tools/skylark/ros2/cmake_tools/__init__.py, line 6 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUgd1M9sdRMdk6z6F0:-MrUgd1M9sdRMdk6z6F1:b8tf3ch) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/cmake_tools/__init__.py#L6)):*
> ```Python
> 
> from .server_mode import server_mode
> from .packages import get_packages_with_prefixes
> ```

nitpick: alphabetize these imports

There are a lot of these later in the review. I'm going to stop calling them out.
___
*[drake_ros_bazel_installed/drake_ros_apps/inquirer.cc, line 10 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUZLTjEDxSMLpvQhfs:-MrUZLTjEDxSMLpvQhft:bicxtrq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/drake_ros_apps/inquirer.cc#L10)):*
> ```cpp
> #include "drake_ros_apps_msgs/msg/status.hpp"
> #include "drake_ros_common_msgs/srv/query.hpp"
> #include "drake_ros_common_msgs/action/do.hpp"
> ```

nitpick: Alphabetize these two includes
___
*[drake_ros_bazel_installed/drake_ros_apps/inquirer.cc, line 34 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUZrsoC4IWL88Q0inr:-MrUZrsoC4IWL88Q0ins:b-i5vf66) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/drake_ros_apps/inquirer.cc#L34)):*
> ```cpp
> private:
>   using QueryClient = rclcpp::Client<drake_ros_common_msgs::srv::Query>;
> ```

nitpick: this one has a blank line between, the next doesn't. I don't care which, but it would be nice to be consistent (same in `oracle.cc`)
___
*[drake_ros_bazel_installed/drake_ros_apps/inquirer.py, line 80 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUa0r0BlfhUolHh28V:-MrUa0r0BlfhUolHh28W:bwbo6dj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/drake_ros_apps/inquirer.py#L80)):*
> ```Python
>         else:
>             self.get_logger().warning('oracle not available for actions')
> ```

nitpick: I believe there should be a blank line here.
___
*[drake_ros_bazel_installed/drake_ros_apps/oracle.cc, line 41 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUaWkq6wsYYNBOJ8dZ:-MrUaWkq6wsYYNBOJ8d_:b-yylrre) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/drake_ros_apps/oracle.cc#L41)):*
> ```cpp
> 
> private:
> ```

nitpick: drop the extra blank line for consistency
___
*[drake_ros_bazel_installed/drake_ros_apps/README.md, line 10 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUYuIa84WrHqoKoc0n:-MrUYuIa84WrHqoKoc0o:b-j51m5a) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/drake_ros_apps/README.md#L10)):*
> ```Markdown
> - Equivalent `inquirer_(cc|py)` applications that subscribe to `drake_ros_apps_msgs/msg/Status` messages, make `drake_ros_common_msgs/srv/Query` service requests, and invoke the `drake_ros_common_msgs/action/Do` action.
> 
> You may run a C++ oracle against a Python inquirer, and viceversa:
> ```

sp: "vice versa"
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scraping/__init__.py, line 39 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUoiYO4jpIiphWnEPd:-MrUoiYO4jpIiphWnEPe:b-wv8pvk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scraping/__init__.py#L39)):*
> ```Python
> 
> 
> SKIPPED_GROUP_DEPENDENCIES = ('rmw_implementation_packages',)
> ```

What makes `rmw_implementation_packages` special? Did I miss a note somewhere?
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scraping/__init__.py, line 55 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUmlyb-G1Gq0KQ7lyd:-MrUmlyb-G1Gq0KQ7lye:btey866) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scraping/__init__.py#L55)):*
> ```Python
>         for group_name in metadata['groups']:
>             if group_name not in groups:
>                 groups[group_name] = []
> ```

Simplify these two lines:



_Code snippet:_
```Python
groups.setdefault(group_name, [])
```
___
*[drake_ros_bazel_installed/tools/skylark [...]

2021-12-23 22:43 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 79 of 101 files reviewed, 17 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 67 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUeiyR0cDt1wSrd-Gc:-MrdResU1fiwmzJ3DKD3:bb7c9pv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L67)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

Nix the 'has'.
</blockquote></details>

Fixed in d6dceeeab0f62834ff7245de4c77104ddb66c03d
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 74 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUf9oS2zKgO4U9i2iT:-MrcbmjsDq1uvOuIqHMH:b-ux772b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L74)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

What about non-Python executables installed to the global bin directory? I'm not sure there are any in `ros2.repos`, but it's certainly possible to do.
</blockquote></details>

Those are picked up as well. That's why I didn't qualify the noun. See d6dceeeab0f62834ff7245de4c77104ddb66c03d.  
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 83 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUfSaV0sELTiTMX4yK:-MrdRhw58wm8Sb5ZLx6j:b-7tzwkl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L83)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

...run in *an* environment...
Same in the next paragraph.
</blockquote></details>

Fixed in d6dceeeab0f62834ff7245de4c77104ddb66c03d.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 99 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUfvuT3d9d2pXR2Hf5:-MrdRjC2AmD5teeCPkpy:b-q0rwgg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L99)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

Nix either through or via 
</blockquote></details>

I was indecisive it seems :) Fixed in 674f8795e64ad56b014e2dd99488ac64e94a02c5
___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 111 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUg8Rd-tS3z_n_z4Kj:-MrdROr_AGHPjOAgp5Gb:b-2s7if0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L111)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

nitpick: trailing whitespace
</blockquote></details>

See 674f8795e64ad56b014e2dd99488ac64e94a02c5
___
*[drake_ros_bazel_installed/tools/skylark/ros2/cmake_tools/__init__.py, line 6 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUgd1M9sdRMdk6z6F0:-MrdRTRbEvkS_66EI_P9:b-s1qfkt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/cmake_tools/__init__.py#L6)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

nitpick: alphabetize these imports

There are a lot of these later in the review. I'm going to stop calling them out.
</blockquote></details>

Done in d6dceeeab0f62834ff7245de4c77104ddb66c03d.
___
*[drake_ros_bazel_installed/drake_ros_apps/inquirer.cc, line 10 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUZLTjEDxSMLpvQhfs:-MrdRUvm6yIBB_07KwC7:b-uowqvp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/drake_ros_apps/inquirer.cc#L10)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

nitpick: Alphabetize these two includes
</blockquote></details>

Done in d6dceeeab0f62834ff7245de4c77104ddb66c03d
___
*[drake_ros_bazel_installed/drake_ros_apps/inquirer.cc, line 34 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUZrsoC4IWL88Q0inr:-MrdRWBY17DroonHNcRn:b-7tzwkl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/drake_ros_apps/inquirer.cc#L34)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

nitpick: this one has a blank line between, the next doesn't. I don't care which, but it would be nice to be consistent (same in `oracle.cc`)
</blockquote></details>

Fixed in d6dceeeab0f62834ff7245de4c77104ddb66c03d.
___
*[drake_ros_bazel_installed/drake_ros_apps/inquirer.py, line 80 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUa0r0BlfhUolHh28V:-MrdRXzjCGqqn_C1IwSg:bb7c9pv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/drake_ros_apps/inquirer.py#L80)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

nitpick: I believe there should be a blank line here.
</blockquote></details>

Fixed in d6dceeeab0f62834ff7245de4c77104ddb66c03d
___
*[drake_ros_bazel_installed/drake_ros_apps/oracle.cc, line 41 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUaWkq6wsYYNBOJ8dZ:-MrdRZ-gA2Q_wxuyoL0P:bb7c9pv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/drake_ros_apps/oracle.cc#L41)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

nitpick: drop the extra blank line for consistency
</blockquote></details>

Fixed in d6dceeeab0f62834ff7245de4c77104ddb66c03d
___
*[drake_ros_bazel_installed/drake_ros_apps/README.md, line 10 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUYuIa84WrHqoKoc0n:-MrdR_7D1K8r5KCzg9-b:b20i7v8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/drake_ros_apps/README.md#L10)):*
<details><summary><i>Previously, cottsay (Scott K Logan) wrote…</i></summary><blockquote>

sp: "vice versa"
</blockquote></details>

Done in 674f8795e64ad56b014e2dd99488ac64e94a02c5
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/package.BUILD.bazel, line 76 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrTduuB80I7Wkr1CaU9:-MrccM027dmadflVNDpi:b-v1w7xa) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/package.BUILD.bazel#L76)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (Here and below) Can you mention why this is marked as flaky?
</blockquote></details>

Done in b159cbe211361d31afe47e3674b4b32886cdca49
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py, line 31 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrTeHSuAMvC0ipmrY0j:-MrcSWpK8fVTn4V_Oy6Y:b-7qkya2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py#L31)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Why not `try ... finally: rclpy.shutdown()`?
</blockquote></details>

In this case, if `rclp [...]

2022-01-03 21:08 UTC, hidmic reviewed
Had to manage another issue in 7e44de53b8310d47e67de9aea69faaf4a2e1767a that 700752a98653680b9402ebf6e47c9bc941e5c283 uncovered. @cottsay PTAL!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-:-MsWl8lX2JjJ3Ge5AlIH:b-qjkcu4)* status: 78 of 101 files reviewed, 17 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2022-01-05 15:24 UTC, EricCousineau-TRI reviewed
> Reviewed 5 of 23 files at r24.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 83 of 101 files reviewed, 17 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/cmake_tools/server_mode.py, line 22 at r24](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Msep5BXCXedcxnBU0Fq:-Msep5BXCXedcxnBU0Fr:b-x8nu0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7e44de53b8310d47e67de9aea69faaf4a2e1767a/drake_ros_bazel_installed/tools/skylark/ros2/cmake_tools/server_mode.py#L22)):*
> ```Python
>         if not address:
>             address = tempfile.mktemp()
>         self.__address = address
> ```

nit Use of double-under score not clearly merited (no inheritance here, so no need for mangling?).

Consider demoting / simplifying to single underscore.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/package.BUILD.bazel, line 76 at r24](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MsepLFT1d5DXUukMZOJ:-MsepLFU2MHd7lOnAQfy:b5w3ut) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7e44de53b8310d47e67de9aea69faaf4a2e1767a/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/package.BUILD.bazel#L76)):*
> ```
>     data = [":isolated_talker_py", ":isolated_listener_py"],
>     size = "small",
>     flaky = True,  # because collision rates are non-zero
> ```

nit For formatting / clearer context, consider hoisting comments to line above code, e.g.
```
# Set flaky because collision rates are non-zero. See [...]
flaky = True,
```
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py, line 31 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrTeHSuAMvC0ipmrY0j:-MsepdddA4xcitAYdULk:bb7ide1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py#L31)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

In this case, if `rclpy.executors.ExternalShutdownException` is raised that means `rclpy.shutdown` has been already invoked. Attempting to shut down twice raises. 

FWIW there's `rclpy.try_shutdown()` to circumvent that, but last time I checked it wasn't working properly. https://github.com/ros2/rclpy/pull/868 may have fixed it (got in yesterday). 
</blockquote></details>

OK Ah, gotcha. Consider linking to upstream issue (but I won't block on that).


<!-- Sent from Reviewable.io -->

2022-01-05 20:45 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 83 of 101 files reviewed, 15 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/cmake_tools/server_mode.py, line 22 at r24](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-Msep5BXCXedcxnBU0Fq:-MsfvEVvAOw8W5RLUlyc:bg9j93h) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7e44de53b8310d47e67de9aea69faaf4a2e1767a/drake_ros_bazel_installed/tools/skylark/ros2/cmake_tools/server_mode.py#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Use of double-under score not clearly merited (no inheritance here, so no need for mangling?).

Consider demoting / simplifying to single underscore.
</blockquote></details>

Done in 8d5a489964ef1af23c2b48a56efdcae17ec82e36.
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/package.BUILD.bazel, line 76 at r24](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MsepLFT1d5DXUukMZOJ:-MsfvNH04PorO344Wbkv:b-a5swau) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7e44de53b8310d47e67de9aea69faaf4a2e1767a/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/package.BUILD.bazel#L76)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For formatting / clearer context, consider hoisting comments to line above code, e.g.
```
# Set flaky because collision rates are non-zero. See [...]
flaky = True,
```
</blockquote></details>

Done in efb4d54d1d019123cea8cdb2877dc1132cc4137d
___
*[drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py, line 31 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrTeHSuAMvC0ipmrY0j:-Msfw-G7-QUYDvsVEDM5:bykecwp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/resources/rmw_isolation/test/isolated_talker.py#L31)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Ah, gotcha. Consider linking to upstream issue (but I won't block on that).
</blockquote></details>

Done in cae236a5ebd846fecb11d8aecdda755fded5f1df


<!-- Sent from Reviewable.io -->

2022-01-05 21:13 UTC, EricCousineau-TRI reviewed
> Reviewed 3 of 4 files at r25.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: 83 of 101 files reviewed, 15 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2022-01-07 15:47 UTC, hidmic commented
@EricCousineau-TRI @cottsay anything else?

2022-01-07 17:04 UTC, EricCousineau-TRI reviewed
Nothing on my side!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-:-MspUpHT3L9c3enE-9w0:bhlussf)* status: 83 of 101 files reviewed, 15 unresolved discussions (waiting on @cottsay, @EricCousineau-TRI, and @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2022-01-08 03:26 UTC, EricCousineau-TRI approved these changes
> Reviewed 17 of 23 files at r24, 1 of 4 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3)* status: all files reviewed, 15 unresolved discussions (waiting on @cottsay and @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2022-01-08 03:38 UTC, EricCousineau-TRI approved these changes
Per Slack DM w/ Miche, I'll provide additional approval for Scott's comments given that he's on vacation (hence dismissals / additional comments on discussion items).

For this, I'm fine w/ serving as sole LGTM'er

> Dismissed @cottsay and @hidmic from 15 discussions.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-:-MsrkcjFEehJ5FAGohOj:b-idylml)* status: all files reviewed, 2 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 74 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUf9oS2zKgO4U9i2iT:-Msrj0G06qtuCjkDTBzY:b7ms8y8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L74)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Those are picked up as well. That's why I didn't qualify the noun. See d6dceeeab0f62834ff7245de4c77104ddb66c03d.  
</blockquote></details>

nit Better, but I think "binary or not" can be confusing, esp. given that `binary` is a bit ambiguous - e.g. ASCII vs. binary (intended context?);  vs. `py_binary` vs. `py_library` (nearby context?).

Consider different qualifier, e.g:
```
A `<exectuable_name>` for *any* kind of executable (Python, shell script, compiled binary, etc.). For simplicity, this is exposed as a Python binary in Bazel.
```
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scraping/metadata.py, line 81 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUq5FF-3Ab29sHYsc1:-MsrkJkTBsD0O8ZaUlQC:byy8uyn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scraping/metadata.py#L81)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

It holds for symlink- and merge-installed workspaces.
</blockquote></details>

nit Consider providing this info as a comment for this function.

(As a non-ROS2 expert, I'm not sure if there are workspace types that aren't supported, and/if it'd be easy for me to determine how the workspace is or isn't compatible.)


<!-- Sent from Reviewable.io -->

2022-01-11 14:47 UTC, hidmic reviewed
Thank you @ericcousineau-tri !

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-:-Mt8av0cB0WO5M_CPI7x:bwsjn7i)* status: 99 of 101 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[drake_ros_bazel_installed/tools/skylark/ros2/README.md, line 74 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUf9oS2zKgO4U9i2iT:-Mt8asfW87nA_vyIRBar:bymu1om) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/README.md#L74)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Better, but I think "binary or not" can be confusing, esp. given that `binary` is a bit ambiguous - e.g. ASCII vs. binary (intended context?);  vs. `py_binary` vs. `py_library` (nearby context?).

Consider different qualifier, e.g:
```
A `<exectuable_name>` for *any* kind of executable (Python, shell script, compiled binary, etc.). For simplicity, this is exposed as a Python binary in Bazel.
```
</blockquote></details>

Done in 74e2e585b36cbf34bfa50096c44bcb41e7aa0712
___
*[drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scraping/metadata.py, line 81 at r23](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-MrUq5FF-3Ab29sHYsc1:-Mt8alQtDCzadWdVPG49:b-goo67y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/21718a9a07767d3fcba47a31e7c18db6288f455b/drake_ros_bazel_installed/tools/skylark/ros2/ros2bzl/scraping/metadata.py#L81)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider providing this info as a comment for this function.

(As a non-ROS2 expert, I'm not sure if there are workspace types that aren't supported, and/if it'd be easy for me to determine how the workspace is or isn't compatible.)
</blockquote></details>

Done in f068da47d1ab67a0670e2fdef098e81d97651330


<!-- Sent from Reviewable.io -->

2022-01-11 15:22 UTC, EricCousineau-TRI approved these changes
Welcome!

> Reviewed 2 of 2 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/3#-:-Mt8iuIN0iXQ0j2LE9Fn:bu692xw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)



<!-- Sent from Reviewable.io -->

2022-01-11 16:07 UTC, merged