Handle cmake failures in dependent packages
RobotLocomotion/drake-ros pull request #300
Opened 2023-09-17 15:28 UTC by abrandemuehl

CMake fails for many packages in the default ros2 humble install, leaving expected cmake api query results empty. This handles the failure and surfaces the name of the failing package for investigation.

In order to artificially generate errors, leave `include_packages` empty in a `ros2_local_repository` instance to pull in all installed packages. Many will have cmake failures.

To see the specific errors I encountered, apply the following change to the `//ros2_example_bazel_installed:WORKSPACE`  and run `bazel build //...` from `ros2_example_bazel_installed`

```
 ros2_local_repository(
     name = "ros2" if ROS2_DISTRO_PREFIX else "ros2_ignored",
-    include_packages = ROS2_PACKAGES,
+    # include_packages = ROS2_PACKAGES,
     workspaces = [ROS2_DISTRO_PREFIX],
 )
```

2023-09-18 15:41 UTC, jwnimmer-tri commented
See also https://github.com/RobotLocomotion/drake-ros/issues/281.

@EricCousineau-TRI could you assign a reviewer, please?

2023-09-21 21:49 UTC, EricCousineau-TRI requested changes
+@EricCousineau-TRI for review, thanks!
\cc @IanTheEngineer @calderpg-tri @adityapande-1995 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/300#-:-Neteejb0KnAC8yC1OnN:btz9y1z)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/300#-Netepuv7BlkeCYHz4yU:-Netepuv7BlkeCYHz4yV:b-fxaxwz) (no related file):*
I am able to reproduce this with a bit less than `ros-humble-desktop` installed:
https://gist.github.com/EricCousineau-TRI/a9a58071867c6ecc17ecedf3395e5a55

Will install `ros-humble-desktop`, and see what diff this PR produces.

___


<!-- Sent from Reviewable.io -->

2023-09-21 22:13 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/300#-:-NetnbeI-gT3EzC3jH1A:b-uwkowd)* status: 0 of 2 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/RobotLocomotion/drake-ros/300#-Netepuv7BlkeCYHz4yU:-NetnXJx5fbPm67yQPjL:b-xh39sk) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I am able to reproduce this with a bit less than `ros-humble-desktop` installed:
https://gist.github.com/EricCousineau-TRI/a9a58071867c6ecc17ecedf3395e5a55

Will install `ros-humble-desktop`, and see what diff this PR produces.
</blockquote></details>

Updated above gist with output, looks much better, thanks!

___


<!-- Sent from Reviewable.io -->

2023-09-25 09:57 UTC, abrandemuehl commented
What is the next step? Seems like the CI failed but I don't think I can restart it or see why it failed.

2023-09-25 15:53 UTC, EricCousineau-TRI commented
At present, the Bazel CI is still being a bit finicky (see #247) - should be fixed soon.
That being said, I will go ahead and merge this PR and fix any additional errors that may have cropped up from skipping that CI.

Thanks!

2023-09-25 15:54 UTC, EricCousineau-TRI approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/300)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @abrandemuehl)



<!-- Sent from Reviewable.io -->

2023-09-25 15:54 UTC, merged