Update bazelized_drake_ros.yml
RobotLocomotion/drake-ros pull request #301
Opened 2023-09-21 18:39 UTC by adityapande-1995

Fixes CI due to ubuntu version mismatch. Old libs require a restart after an upgrade which makes the CI jobs fail.

2023-09-21 19:45 UTC, EricCousineau-TRI approved these changes
Thanks!

> I'd personally prefer specifying the exact version of ubuntu to be used, but I'm open for suggestions.

I'd support that - let's switch both to point to ubuntu-22.04 for now?

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/301#-:-NetGYti0wPHi9n956Li:b-95kt1t)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @calderpg-tri and @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2023-09-21 19:45 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/301)* status: all files reviewed, 1 unresolved discussion (waiting on @adityapande-1995, @calderpg-tri, and @IanTheEngineer)

___
*[`.github/workflows/bazelized_drake_ros.yml` line 16 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/301#-NetGf-S538s-JkKur1w:-NetGf-S538s-JkKur1x:b-1ocsc) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/61a541c0519b48d323c41b1fd59db0154d0950d2/.github/workflows/bazelized_drake_ros.yml#L16)):*
> ```YAML
>   bazel_build_and_test:
>     if: "! contains(github.event.pull_request.labels.*.name, 'status: defer ci')"
>     runs-on: ubuntu-latest
> ```

Per above, can we switch both Bazel workflows to ubuntu-22.04?


<!-- Sent from Reviewable.io -->

2023-09-21 19:46 UTC, EricCousineau-TRI reviewed
> Old libs require a restart after an upgrade which makes the CI jobs fail.

Do you have example of this?

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/301#-:-NetGkky1GMu2-6_cypT:b-omk15f)* status: all files reviewed, 1 unresolved discussion (waiting on @adityapande-1995, @calderpg-tri, and @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2023-09-21 19:53 UTC, adityapande-1995 reviewed
Apologies, I meant it might require a restart of some daemons, as from the logs here : 

Just a guess for now, lets see if the CI passes in this PR.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/301#-:-NetI6NA8xWCTKFIeSG8:b-w5q6ar)* status: all files reviewed, 1 unresolved discussion (waiting on @calderpg-tri and @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2023-09-21 19:55 UTC, EricCousineau-TRI commented
I think there'd be a way to disable that stuff... Let me see if we've done something like for AWS EC2 stuff

2023-09-21 19:55 UTC, IanTheEngineer reviewed
I am on board with switching both to `ubuntu-22.04`. I am curious as to the source of the underlying failure. According to Github's https://github.com/actions/runner-images README, `ubuntu-22.04` and `ubuntu-latest` are different labels currently pointing to the same image.

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/301#-:-NetHrCu-NICQ8SG5jGM:b-n1v0q0)* status: all files reviewed, 1 unresolved discussion (waiting on @calderpg-tri and @EricCousineau-TRI)

___
*[`.github/workflows/bazelized_drake_ros.yml` line 16 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/301#-NetGf-S538s-JkKur1w:-NetHBMY5ODMiffpLaXx:bgzm61r) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/61a541c0519b48d323c41b1fd59db0154d0950d2/.github/workflows/bazelized_drake_ros.yml#L16)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per above, can we switch both Bazel workflows to ubuntu-22.04?
</blockquote></details>

Agreed on `ubuntu-22.04` for everything. `ubuntu-latest` could eventually point to a version not supported by`drake-ros`.


<!-- Sent from Reviewable.io -->

2023-09-22 17:17 UTC, adityapande-1995 commented
Green CI ! Turns out the job was running out of disk space.

2023-09-22 20:06 UTC, EricCousineau-TRI approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, thanks!

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/drake-ros/301#-:-NeyUz_MEEr0ooZNmvla:bpqxd5f)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @calderpg-tri)

___
*[`.github/workflows/bazelized_drake_ros.yml` line 16 at r1](https://reviewable.io/reviews/RobotLocomotion/drake-ros/301#-NetGf-S538s-JkKur1w:-NeyUrNSA_cCKeaYxRFT:bj0c8t8) ([raw file](https://github.com/RobotLocomotion/drake-ros/blob/61a541c0519b48d323c41b1fd59db0154d0950d2/.github/workflows/bazelized_drake_ros.yml#L16)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Agreed on `ubuntu-22.04` for everything. `ubuntu-latest` could eventually point to a version not supported by`drake-ros`.
</blockquote></details>

Aye, thanks!


<!-- Sent from Reviewable.io -->

2023-09-22 20:07 UTC, merged