[WIP] Add ros2_archive() Bazel rule
RobotLocomotion/drake-ros pull request #38
Opened 2022-02-04 23:01 UTC by hidmic

2022-02-04 23:21 UTC, hidmic commented
@EricCousineau-TRI Bazel keeps restarting the `ros2_archive()` repository rule invocation as if it were invalidating itself, but I don't see how. I tried several things, all to no avail:

- If I attempt to build, the repository gets invalidated midway symlinks creation _in most cases_. Sometimes, after many tries, it goes through.
- If I don't attempt to scrape the archive, the rule goes through (and downstream targets obviously fail to depend on the missing generated files).
- If I scrape workspaces elsewhere in the filesystem, it works just fine.
 
I'm frankly at a loss here. It looks a lot like a bug in Bazel's cache/build invalidation logic but I could definitely an extra pair of eyes. BTW debugging provisions in Bazel are awful. The best I was able to get from it was a very sparse (and thus useless) event log.

2022-02-04 23:27 UTC, hidmic commented
Hmm, or maybe `repo_ctx.path("archive")` is always outdated? :thinking:

2022-02-09 22:50 UTC, hidmic commented
I've now refactored our repository rules to make sure every new file goes through Bazel. It doesn't hang in a continuous restarting loop anymore, but building from a clean workspace, it looks like I get one restart per added file after downloading and extracting the tarball (!?).

I'll try with a newer Bazel version.

2022-02-10 18:42 UTC, hidmic commented
I knew it was an issue with Bazel... See https://github.com/bazelbuild/bazel/issues/4533. Hopefully I can fix use their little hack to workaround this in [`http.bzl`](https://github.com/bazelbuild/bazel/commit/ada0c370c2a3ea484925bc4e7d927b015bc4ad92) as a basis to fix ours.

2022-02-10 21:05 UTC, hidmic commented
Alright, it's finally working. I'll go check why CI is failing, but I don't expect things to change much.

+@EricCousineau-TRI for review please.

2022-02-16 23:44 UTC, EricCousineau-TRI requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with small nits

> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-:-Mw3v5srBSQoW5likAn-:bpne7ni)* status: all files reviewed, 15 unresolved discussions (waiting on @hidmic)

___
*[bazel_ros2_rules/ros2/compute_system_rosdeps.py, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3uBfK9vpaDDKYOIe_:-Mw3uBfK9vpaDDKYOIea:b-qry6s5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/compute_system_rosdeps.py#L40)):*
> ```Python
> # See https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Binary.html
> # for further reference.
> SKIPPED_ROSDEP_KEYS = {
> ```

nit A bit odd to see globals after first function declaration.

Consider hoisting this to top.
___
*[bazel_ros2_rules/ros2/defs.bzl, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3qmsR0xBH-W94SqhD:-Mw3qmsR0xBH-W94SqhE:b-baykot) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/defs.bzl#L32)):*
> ```Starlark
> ]
> 
> def symlink_common_files(repo_ctx):
> ```

nit This appears to be private, but is publicly accessible.

Can you make private? (`_symlink_common_files`?)
___
*[bazel_ros2_rules/ros2/defs.bzl, line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3qBip0WAgCKkqbZa9:-Mw3qBiq9Dzq4QEDTzo2:b1b2d3l) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/defs.bzl#L118)):*
> ```Starlark
>     # NOTE: all these labels are listed as private attributes
>     # to force prefetching, or else repository rules will be
>     # restarted on first hit. See cdc99afc1a03ff8fbbbae088d358b7c029e0d232
> ```

nit Consider compressing repo + commit as:
`https://github.com/bazelbuild/bazel/commit/cdc99afc1a03ff8fbbbae088d358b7c029e0d232`
___
*[bazel_ros2_rules/ros2/defs.bzl, line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3q7Zs8oK5uMjUioy4:-Mw3q7Zs8oK5uMjUioy5:b-my3qh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/defs.bzl#L119)):*
> ```Starlark
>     # to force prefetching, or else repository rules will be
>     # restarted on first hit. See cdc99afc1a03ff8fbbbae088d358b7c029e0d232
>     # at https://github.com/bazelbuild/bazel for further reference.
> ```

nit Can you also refer to the Bazel issue regarding repo invalidation?

(it's in the commit, but good for top-level traceability since it's just one line)
___
*[bazel_ros2_rules/ros2/generate_distro_file.py, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3r8Pj98qc0W83O0jG:-Mw3r8Pj98qc0W83O0jH:bb78jkk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/generate_distro_file.py#L22)):*
> ```Python
> # cannot be relied on to make modules such as `ros2bzl` and `cmake_tools`
> # reachable through PYTHONPATH. Thus, we force it here.
> sys.path.insert(0, os.path.dirname(__file__))  # noqa
> ```

nit `__file__` may not always be an absolute path, and not sure how bad relpaths are for `sys.path`
Can you use `dirname(abspath(__file__))` here?

https://github.com/EricCousineau-TRI/repro/commit/272961a34fc098dc04d014fa7e3ceb699d4181fa
___
*[bazel_ros2_rules/ros2/generate_distro_file.py, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3rzbxBZEHsSJTf_NQ:-Mw3rzbxBZEHsSJTf_NR:bioydtn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/generate_distro_file.py#L60)):*
> ```Python
>     args.sandbox = sandboxing.make_path_mapping(
>         name=args.repository_name, mapping=dict(
>             entry.partition(':')[0::2]
> ```

nit Why not just `entry.split(':')`?
___
*[bazel_ros2_rules/ros2/resources/templates/run.bash.in, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3thka4S3uB8v_QjBZ:-Mw3thka4S3uB8v_QjB_:b-5ch0ul) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/resources/templates/run.bash.in#L6)):*
> ```
> for workspace in @WORKSPACES@; do
>     COLCON_CURRENT_PREFIX=${workspace}
>     . ${workspace}/setup.sh
> ```

nit Can you add TODO for using `setup.bash`?
___
*[bazel_ros2_rules/ros2/resources/tools/package.BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3XF9X10OGKYovFSTE:-Mw3XF9Y-u6Gvji6DfPA:b-zd6pfj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4e25efcbae586a04e3249632518e589b5619a6bf/bazel_ros2_rules/ros2/resources/tools/package.BUILD.bazel#L1)):*
> ```
> # Empty build file to mark package boundaries.
> ```

nit I can't tell if this is deleted.

If this is empty, can you either delete the file or restore the comment?
___
*[ros2_example_bazel_installed/BUILD.bazel, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3tWWh51ZW1FkNqIEY:-Mw3tWWh51ZW1FkNqIEZ:bs5dwkm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/BUILD.bazel#L5)):*
> ```Starlark
> load("//tools:cmd_test.bzl", "cmd_test")
> 
> cmd_test(
> ```

nit Can you add TODO to make this more user-friendly?
___
*[ros2_example_bazel_installed/BUILD.bazel, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3tVfH3WfaUwrEAdy4:-Mw3tVfH3WfaUwrEAdy5:b3bchdx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/BUILD.bazel#L14)):*
> ```Starlark
>     data = [
>         "@ros2//:system-rosdep-keys.txt", 
> 	    "setup/prereq-rosdep-keys.txt",
> ```

nit Whitespace.
___
*[ros2_example_bazel_installed/WORKSPACE, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3usau1_w7h5mzelVx:-Mw3usavEdJOHCoxLz10:bfn6rk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/WORKSPACE#L13)):*
> ```Starlark
> load("@bazel_ros2_rules//ros2:defs.bzl", "ros2_archive")
> 
> ros2_archive(
> ```

Solely relying on `ros2_archive` may be a bit confusing.

Can you make this "configurable"? e.g. an environment variable, that `install_prereqs` could also leverage this.

And then perhaps CI could test both configurations.
___
*[ros2_example_bazel_installed/WORKSPACE, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3pkIk4iMpOWCy0jtN:-Mw3pkIk4iMpOWCy0jtO:b-41cra4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/WORKSPACE#L16)):*
> ```Starlark
>     name = "ros2",
>     url = "http://repo.ros2.org/ci_archives/rolling-on-focal/ros2-rolling-linux-focal-amd64-ci.tar.bz2",
>     sha256 = "5bd37168cd2b704eabee207145362ce38eb83431ac183f9a9b432121c9fb8015",
> ```

From our discussions, it seems like this sha256 will be quickly invalidated (every time it's rebuilt).

Can you add warning about this, and TODO to mirror this?
___
*[ros2_example_bazel_installed/setup/install_prereqs.sh, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3oqqV4BM83ETk4yQo:-Mw3oqqV4BM83ETk4yQp:b-ttqc7u) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/setup/install_prereqs.sh#L68)):*
> ```Shell
> rosdep update
> 
> ROS_PYTHON_VERSION=3 apt install \
> ```

Rather than still use `rosdep` here, is it possible to instead just delegate this to pure `apt` packages?

Then `rosdep` is purely  [...]

2022-02-18 21:01 UTC, hidmic reviewed
Thanks for the review! PTAL.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-:-MwDcmM37oDHPv0SL5kH:b25x2z4)* status: all files reviewed, 12 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bazel_ros2_rules/ros2/compute_system_rosdeps.py, line 40 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3uBfK9vpaDDKYOIe_:-MwCXCzH-qf4EQVNe18Q:b-m4a2tb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/compute_system_rosdeps.py#L40)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit A bit odd to see globals after first function declaration.

Consider hoisting this to top.
</blockquote></details>

Sure. I meant to keep it close to the `compute_system_rosdeps()` logic, but I don't mind either way. See fa5e5fcf851c41c8d5776b5b47139db965567426.
___
*[bazel_ros2_rules/ros2/defs.bzl, line 32 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3qmsR0xBH-W94SqhD:-MwCY-lSDR9u8X3WAi4w:b2ghxhg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/defs.bzl#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This appears to be private, but is publicly accessible.

Can you make private? (`_symlink_common_files`?)
</blockquote></details>

Sure. Done in 76783049e20e5e83bf790b74ccdbc599556e393e
___
*[bazel_ros2_rules/ros2/defs.bzl, line 118 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3qBip0WAgCKkqbZa9:-MwDbJHrCb8okngontaZ:brbinfd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/defs.bzl#L118)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider compressing repo + commit as:
`https://github.com/bazelbuild/bazel/commit/cdc99afc1a03ff8fbbbae088d358b7c029e0d232`
</blockquote></details>

Done in ca5ed36766b85b40bbcdf585152cd4b42089de0f
___
*[bazel_ros2_rules/ros2/defs.bzl, line 119 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3q7Zs8oK5uMjUioy4:-MwDbJuw5OYkUujk1eSc:b-5gahfv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/defs.bzl#L119)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you also refer to the Bazel issue regarding repo invalidation?

(it's in the commit, but good for top-level traceability since it's just one line)
</blockquote></details>

Done in ca5ed36766b85b40bbcdf585152cd4b42089de0f.
___
*[bazel_ros2_rules/ros2/generate_distro_file.py, line 22 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3r8Pj98qc0W83O0jG:-MwCZUGX80MKz41GVLWh:b-cq0nnq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/generate_distro_file.py#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `__file__` may not always be an absolute path, and not sure how bad relpaths are for `sys.path`
Can you use `dirname(abspath(__file__))` here?

https://github.com/EricCousineau-TRI/repro/commit/272961a34fc098dc04d014fa7e3ceb699d4181fa
</blockquote></details>

Ahh good catch. Should've been `dirname(abspath(__file__))` all along. See 0f75cd13cb5af027bd1a5ff83d7b8d67a7f04385.
___
*[bazel_ros2_rules/ros2/generate_distro_file.py, line 60 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3rzbxBZEHsSJTf_NQ:-MwC_T2YAo7UjMkIr0S5:byo0tr5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/generate_distro_file.py#L60)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why not just `entry.split(':')`?
</blockquote></details>

Habit? Switched to use `str.split` instead. It's actually better, it'll crash if an entry is ill-formed. See 454ada0dc6e2be5550abf86a7c75275470cb4115.
___
*[bazel_ros2_rules/ros2/resources/templates/run.bash.in, line 6 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3thka4S3uB8v_QjBZ:-MwDbRtf4nckvpnPDmW0:b-19x6wb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/bazel_ros2_rules/ros2/resources/templates/run.bash.in#L6)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you add TODO for using `setup.bash`?
</blockquote></details>

Done in cd67c15d9df0796815dd49ef4b5359d560478df1.
___
*[bazel_ros2_rules/ros2/resources/tools/package.BUILD.bazel, line 1 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3XF9X10OGKYovFSTE:-MwDbTxv00I3JBhk6zdW:b-eopi6m) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4e25efcbae586a04e3249632518e589b5619a6bf/bazel_ros2_rules/ros2/resources/tools/package.BUILD.bazel#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I can't tell if this is deleted.

If this is empty, can you either delete the file or restore the comment?
</blockquote></details>

Fixed in 66568af93138fe205878d7d7fe85726d8f39353c.
___
*[ros2_example_bazel_installed/BUILD.bazel, line 5 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3tWWh51ZW1FkNqIEY:-MwCbZNp9_bQz8DMYAds:b154o78) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/BUILD.bazel#L5)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you add TODO to make this more user-friendly?
</blockquote></details>

Sure. I actually like the `diff` + `patch` workflow best, but I also like Emacs so maybe I'm crazy :sweat_smile: 

Done in 23348db32213f9a6ebbaf2ccb840be8e3d05459a.
___
*[ros2_example_bazel_installed/BUILD.bazel, line 14 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3tVfH3WfaUwrEAdy4:-MwDbX9a9w3PP-XAc5Vd:b-4sh31q) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/BUILD.bazel#L14)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Whitespace.
</blockquote></details>

Fixed in 23348db32213f9a6ebbaf2ccb840be8e3d05459a.
___
*[ros2_example_bazel_installed/WORKSPACE, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3usau1_w7h5mzelVx:-MwDbZit-C8pyhf5eMBf:b-2cb32n) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/WORKSPACE#L13)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Solely relying on `ros2_archive` may be a bit confusing.

Can you make this "configurable"? e.g. an environment variable, that `install_prereqs` could also leverage this.

And then perhaps CI could test both configurations.
</blockquote></details>

Done in ba119e13a432d6e1649c35cc0abbe0e9b038025c, though I'm not sure I follow what kind of CI you have in mind. Installing the tarball before the build I presume (or in prereqs?).
___
*[ros2_example_bazel_installed/WORKSPACE, line 16 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3pkIk4iMpOWCy0jtN:-MwDc2Ci-2CAmMbjJBCh:bwmnxtq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/WORKSPACE#L16)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

From our discussions, it seems like this sha256 will be quickly [...]

2022-02-21 18:02 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/38)* status: 26 of 27 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bazel_ros2_rules/ros2/resources/templates/run.bash.in, line 2 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwDpDsu2P-WONnh4Pmc:-MwSKF8lA0qt38Sp4Xsp:bnv9svo) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/bazel_ros2_rules/ros2/resources/templates/run.bash.in#L2)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you add top-level comment for what this script is for?
</blockquote></details>

Done in 3540765332637aabe12f94b81e271c092f63f0c3
___
*[bazel_ros2_rules/ros2/resources/templates/run.bash.in, line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwE0XWj5J5zIggbQCDe:-MwSJtfv0jEI8RoOiNya:b9hh90k) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/bazel_ros2_rules/ros2/resources/templates/run.bash.in#L15)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Does this allow running an interactive shell session? e.g. `run.bash bash`?
Do bash aliases / functions still work?
If not, consider making this `source`-able. For example:
```
if [[ ${0} != ${BASH_SOURCE} ]]; then
   # Only source; perhaps assert than $# == 0
else
   # Source, then exec
fi
```

An example from side stuff:
https://github.com/EricCousineau-TRI/repro/blob/272961a34fc098dc04d014fa7e3ceb699d4181fa/python/manim_examples/setup.sh
</blockquote></details>

It is not meant to be used by users yet, but yes, it could become the entrypoint for an interactive shell session.

Do you want to try and add support for an interactive shell session here? I'd defer, but your call.
___
*[ros2_example_bazel_installed/WORKSPACE, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3usau1_w7h5mzelVx:-MwSRRv73r04gCwA9aWN:bye4hve) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/WORKSPACE#L13)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Ah, good point :facepalm:

Perhaps add a TODO to do rolling from 22.04 once Drake supports it?
</blockquote></details>

Done in 13eb65905e0e3b16e677608c90fcfb6ed9118613
___
*[ros2_example_bazel_installed/setup/install_prereqs.sh, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3oqqV4BM83ETk4yQo:-MwSRaMD80ReTaY9LluD:bp6kfo) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/setup/install_prereqs.sh#L68)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For Anzu, I'd prefer we not let `rosdep` do anything but emit the packages to install. I don't want it installing anything to stuff like `/usr/local` or `~/.local`, and without knowing what it does, there isn't an guarantee. (We have bugs crop up because of `/usr/local`, and I'd hate to depend on it implicitly)

However, we can defer that to Anzu for now (and upstream later).

Can you add TODO to that effect? `# TODO: Be very explicit about what installation mechanisms we allow.`
</blockquote></details>

Done in 13eb65905e0e3b16e677608c90fcfb6ed9118613.
___
*[ros2_example_bazel_installed/setup/install_prereqs.sh, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwDzKxbEIAr-XSHWmCN:-MwSRbQv0kqeCTtTIMxY:bp6kfo) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/ros2_example_bazel_installed/setup/install_prereqs.sh#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you add comment / reference to why `ROS_PYTHON_VERSION` is necessary for `apt install` here?
(it's a bit disturbing, TBH)
</blockquote></details>

Done in 13eb65905e0e3b16e677608c90fcfb6ed9118613.
___
*[ros2_example_bazel_installed/tools/ros2.bzl, line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwE08hUB01PUNlPso5X:-MwSLwpiBeVsw4cyO9m4:b-w9g038) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/ros2_example_bazel_installed/tools/ros2.bzl#L6)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Sorry for not being clearer, I was thinking something more like a top-level commented out portion, or perhaps something a bit more gymnastic like this mechanism:
https://github.com/RobotLocomotion/drake-external-examples/blob/f5e4dd1d8656d8ce620969b3406b7962786ea618/drake_bazel_external/WORKSPACE

</blockquote></details>

Switch to using `_ignored` suffixes in b793e751f2f14f261744f6e779efc7e2ed92eb3a
___
*[ros2_example_bazel_installed/tools/ros2.bzl, line 7 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwE-gnLB1bpi9TeKrLS:-MwSRPOBAk8pL1gIYa8j:b-y0lmgu) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/ros2_example_bazel_installed/tools/ros2.bzl#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `prefix == ""` is odd. Better would be to use `None`. Even better to use mutually exclusive arguments / choices.

Can you change this to reflect `github_archive`? e.g.
https://github.com/RobotLocomotion/drake/blob/c966e648e66b094b2fceef2d05ff7a448525ca30/tools/workspace/github.bzl#L9-L19
```
ros2_repository(name, local_repository_override=None, **kwargs)
```
</blockquote></details>

No longer necessary as of b793e751f2f14f261744f6e779efc7e2ed92eb3a


<!-- Sent from Reviewable.io -->

2022-02-21 19:35 UTC, EricCousineau-TRI approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

___
*[bazel_ros2_rules/ros2/resources/templates/run.bash.in, line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwE0XWj5J5zIggbQCDe:-MwSldhGAnPWyLFJ0Uk3:be7lplh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/bazel_ros2_rules/ros2/resources/templates/run.bash.in#L15)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

It is not meant to be used by users yet, but yes, it could become the entrypoint for an interactive shell session.

Do you want to try and add support for an interactive shell session here? I'd defer, but your call.
</blockquote></details>

OK Defering sounds good! Perhaps mention that? e.g. "Not yet ready for interactive shells ... TODO: Support source'ing"
___
*[ros2_example_bazel_installed/WORKSPACE, line 13 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3usau1_w7h5mzelVx:-MwSlnd_7JfZvBUOzSby:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/WORKSPACE#L13)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Done in 13eb65905e0e3b16e677608c90fcfb6ed9118613
</blockquote></details>

OK Thanks!
___
*[ros2_example_bazel_installed/setup/install_prereqs.sh, line 68 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-Mw3oqqV4BM83ETk4yQo:-MwSlyLP93KuMKxjKqPp:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7fd22f06e16478798ca72f32d81421035bd4e0a/ros2_example_bazel_installed/setup/install_prereqs.sh#L68)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Done in 13eb65905e0e3b16e677608c90fcfb6ed9118613.
</blockquote></details>

OK Thanks!
___
*[ros2_example_bazel_installed/setup/install_prereqs.sh, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwDzKxbEIAr-XSHWmCN:-MwSlruj-i_j-hrnvaA6:bcg8axm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/ros2_example_bazel_installed/setup/install_prereqs.sh#L69)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Done in 13eb65905e0e3b16e677608c90fcfb6ed9118613.
</blockquote></details>

OK Thanks! Still unclear why we shouldn't install `python-is-python3` first, but this is good for moving forward!
___
*[ros2_example_bazel_installed/tools/ros2.bzl, line 6 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwE08hUB01PUNlPso5X:-MwSm0VpCGj19OahdzUu:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/ros2_example_bazel_installed/tools/ros2.bzl#L6)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Switch to using `_ignored` suffixes in b793e751f2f14f261744f6e779efc7e2ed92eb3a
</blockquote></details>

OK Thanks!


<!-- Sent from Reviewable.io -->

2022-02-21 20:11 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/38)* status: 26 of 27 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[bazel_ros2_rules/ros2/resources/templates/run.bash.in, line 15 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwE0XWj5J5zIggbQCDe:-MwSu9PFBByFciYGAzZM:bsreaxs) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/bazel_ros2_rules/ros2/resources/templates/run.bash.in#L15)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Defering sounds good! Perhaps mention that? e.g. "Not yet ready for interactive shells ... TODO: Support source'ing"
</blockquote></details>

Done in 8d9cbe12b4fad7aec731c25de2d4ff4beac7661f
___
*[ros2_example_bazel_installed/setup/install_prereqs.sh, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwDzKxbEIAr-XSHWmCN:-MwSshak8aR314hO4pXz:bop3g1b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/ros2_example_bazel_installed/setup/install_prereqs.sh#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Thanks! Still unclear why we shouldn't install `python-is-python3` first, but this is good for moving forward!
</blockquote></details>

We can install `python-is-python3` first, but that won't have any effect in `rosdep` behavior. See https://github.com/ros-infrastructure/rosdep/blob/16e4b3a50f909dfff0f88e8b259cfe5ee308e7b1/src/rosdep2/main.py#L273-L298. To be fair, forcing a `ROS_PYTHON_VERSION` value only prevents an unnecessary warning.


<!-- Sent from Reviewable.io -->

2022-02-21 20:30 UTC, EricCousineau-TRI approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

___
*[ros2_example_bazel_installed/setup/install_prereqs.sh, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwDzKxbEIAr-XSHWmCN:-MwSyOH35poFzUWP4wiA:b-hzf101) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/ros2_example_bazel_installed/setup/install_prereqs.sh#L69)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

We can install `python-is-python3` first, but that won't have any effect in `rosdep` behavior. See https://github.com/ros-infrastructure/rosdep/blob/16e4b3a50f909dfff0f88e8b259cfe5ee308e7b1/src/rosdep2/main.py#L273-L298. To be fair, forcing a `ROS_PYTHON_VERSION` value only prevents an unnecessary warning.
</blockquote></details>

Is this just for `rosdep`? If so, can we downscope that env variable?
e.g. `apt install $(env ROS_PYTHON_VERSION=3 rosdep ...)`


<!-- Sent from Reviewable.io -->

2022-02-21 20:41 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/38)* status: 26 of 27 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

___
*[ros2_example_bazel_installed/setup/install_prereqs.sh, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwDzKxbEIAr-XSHWmCN:-MwT02lg5zldZBF0kYTn:b7hp1iz) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/ros2_example_bazel_installed/setup/install_prereqs.sh#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is this just for `rosdep`? If so, can we downscope that env variable?
e.g. `apt install $(env ROS_PYTHON_VERSION=3 rosdep ...)`
</blockquote></details>

Done in fbd21afed283be4aa0251a1a69b729714bc9ab7d. On a second look, I spotted a bug and fixed it.


<!-- Sent from Reviewable.io -->

2022-02-21 21:35 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/38)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @hidmic)

___
*[ros2_example_bazel_installed/setup/install_prereqs.sh, line 69 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/38#-MwDzKxbEIAr-XSHWmCN:-MwTCSVZ6hHuWlhZEbZ8:bcgzp9s) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3a55c0d2b4fa3708a7fa1802012d64dbfba63d54/ros2_example_bazel_installed/setup/install_prereqs.sh#L69)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Done in fbd21afed283be4aa0251a1a69b729714bc9ab7d. On a second look, I spotted a bug and fixed it.
</blockquote></details>

OK Sweet!


<!-- Sent from Reviewable.io -->

2022-02-21 22:48 UTC, EricCousineau-TRI approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)



<!-- Sent from Reviewable.io -->

2022-02-21 22:52 UTC, merged