Add Python bindings for drake_ros_core package.
RobotLocomotion/drake-ros pull request #6
Opened 2021-06-09 21:48 UTC by hidmic

Spin off from #2. Built on top of #5.

2021-06-09 21:48 UTC, hidmic commented
FYI @gbalke

2021-06-14 17:35 UTC, hidmic commented
@IanTheEngineer friendly ping (or should I bump someone else for review?)

2021-10-14 21:29 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 16 of 26 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI, @IanTheEngineer, and @sloretz)

___
*[drake_ros_core/src/python_bindings/module_drake_ros_core.cpp, line 50 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MlM_wVEC8mO73ennODT:-Mm-dcKB0V_A5XrBMM8o:b-eiu807) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9fe467b3eca4fcf3926abaad9fc8d90fb852ad7e/drake_ros_core/src/python_bindings/module_drake_ros_core.cpp#L50)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

My read on `DrakeRosInterface` is that it's similar in spirit to `DrakeLcmInterface`:
https://github.com/RobotLocomotion/drake/blob/v0.34.0/lcm/drake_lcm_interface.h

In this case, we use raw pointers to alias things, as this is more of a Drake-centric usage.

For consistency, `unique_ptr<>` and `T*` is ideal; it does require the use of `py::keep_alive<>`, but at least we don't depart from Drake-style usages.
</blockquote></details>

Fair enough. See 461561020119476c4d8870ceecf9837e41951b15.
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 33 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MlW65Hj3IkQ_h-I3DHF:-Mm-dRxI4yV_cWLZqZSC:b-7nsg41) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e696974368716901edaa4f1a9834b1a2e899b0c2/drake_ros_core/src/python_bindings/qos_type_caster.hpp#L33)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is this still necessary given newer `rclpy` Python bindings?
</blockquote></details>

It is. `QoSProfile` instances are still pure Python. See https://github.com/ros2/rclpy/blob/6f4e42cb4b409cbd79273dd9dd12cc35198ff138/rclpy/rclpy/qos.py#L57.


<!-- Sent from Reviewable.io -->

2021-11-01 20:07 UTC, EricCousineau-TRI requested changes
First pass done on my side, PTAL!

> Reviewed 2 of 7 files at r6, 1 of 1 files at r7, 6 of 7 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-:-MnS6Ah67qTI2MEJEgpL:b-li4uxc)* status: all files reviewed, 20 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS-hs38lvaneZhvKKg:-MnS-hs38lvaneZhvKKh:bj1b5pa) (no related file):*
nit Filenames here use `*.{hpp,cpp}`, whereas Drake uses `*.{h,cc}`.

Is there a strong reason why?
If not, can we more closely align with Drake?

Sorry for just now noticing this; can file an issue s.t. it could be handled outside of this PR.

---
___
*[drake_ros_core/CMakeLists.txt, line 67 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRyFOM2AzrI2Hx5QhA:-MnRyFOM2AzrI2Hx5QhB:b48zss8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/CMakeLists.txt#L67)):*
> ```CMake
> # Python bindings
> ###
> pybind11_add_module(py_drake_ros_core SHARED
> ```

nit Target naming convention unclear to me.

I would assume prefix to be package name, but this seems to indicate it's for Python components of `drake_ros_core`.

Is this an `ament` convention?
If not, would it be possible to pivot the ordering? e.g. `drake_ros_core_py`?
This is slightly closer to the conventions we use for Drake (and Anzu) Python targets:
https://drake.mit.edu/doxygen_cxx/group__python__bindings.html (see the "Target Conventions" documentation)
___
*[drake_ros_core/CMakeLists.txt, line 80 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRxw35ESoAwqYW4LP2:-MnRxw35ESoAwqYW4LP3:b-ulf53p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/CMakeLists.txt#L80)):*
> ```CMake
> 
> # Sets PYTHON_INSTALL_DIR
> _ament_cmake_python_get_python_install_dir()
> ```

nit This seems to dip into private implementation guts of `ament_cmake_python` without a TODO or rationale.

Can you provide rationale, perhaps upstream issue / PR?
___
*[drake_ros_core/pycodestyle.ini, line 2 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRynqiCe3vCaH0cN24:-MnRynqiCe3vCaH0cN25:b-75qu89) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/pycodestyle.ini#L2)):*
> ```INI
> [pycodestyle]
> ignore = 'E121,E123,E126,E226,E24,E704,W503'
> ```

nit Unclear why these ignores are selected.

Can a terse comment be provided (so that parity can be "tracked")?
e.g. "This is close to the ignore's that Drake uses, as of https://github.com/RobotLocomotion/drake/blob/v0.35.0/tools/lint/python_lint.bzl#L7"
___
*[drake_ros_core/src/python_bindings/module_drake_ros_core.cpp, line 60 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRzi0Q2bOi4gAKgAFS:-MnRzi0Q2bOi4gAKgAFT:boaye90) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/module_drake_ros_core.cpp#L60)):*
> ```cpp
>       .def(py::init([](pybind11::object type, const char* topic_name,
>                        drake_ros_core::QoS qos,
>                        DrakeRosInterface* ros_interface) {
> ```

This binding needs a `keep_alive` for `ros_interface`.

Related example:
https://github.com/RobotLocomotion/drake/blob/b026886f559c2cba1b450d65f53d123adf106ef5/bindings/pydrake/systems/analysis_py.cc#L113-L117
___
*[drake_ros_core/src/python_bindings/module_drake_ros_core.cpp, line 71 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRzjlO4gKTHuzGIoyL:-MnRzjlO4gKTHuzGIoyM:b-3ghwd7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/module_drake_ros_core.cpp#L71)):*
> ```cpp
>       .def(
>           py::init([](pybind11::object type, const char* topic_name,
>                       drake_ros_core::QoS qos, DrakeRosInterface* ros_interface,
> ```

This needs a `keep_alive`, same as above.
___
*[drake_ros_core/src/python_bindings/module_drake_ros_core.cpp, line 84 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRzlivDUmZqYnhiC0W:-MnRzlivDUmZqYnhiC0X:b-3ghwd7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/module_drake_ros_core.cpp#L84)):*
> ```cpp
>       .def(py::init([](pybind11::object type, const char* topic_name,
>                        drake_ros_core::QoS qos,
>                        DrakeRosInterface* ros_interface) {
> ```

This needs a `keep_alive`, same as above.
___
*[drake_ros_core/src/python_bindings/py_serializer.hpp, line 1 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS-aDSBr-rh5sxncSy:-MnS-aDSBr-rh5sxncSz:bvwv3y7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/py_serializer.hpp#L1)):*
> ```cpp
> // Copyright 2021 Open Source Robotics Foundation, Inc.
> ```

nit This appears to be a utility file for `pybind`. In Drake, we tend to suffix files like this with `_pybind.h`:
https://drake.mit.edu/doxygen_cxx/group__python__bindings.html

Can this be renamed accordingly?
___
*[drake_ros_core/src/python_bindings/py_serializer.hpp, line 14 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRzrJr9YA8SBQjliZI:-MnRzrJr9YA8SBQjliZJ:b-68ykjf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/py_serializer.hpp#L14)):*
> ```cpp
> // See the License for the specific language governing permissions and
> // limitations under the License.
> #ifndef PYTHON_BINDINGS__PY_SERIALIZER_HPP_
> ```

nit Unclear why we use `ifdef` header guards versus `#pragma once`.

Drake style guide uses `#pragma once`:
https://drake.mit.edu/styleguide/cppguide.html#The__pragma_once_Guard
___
*[drake_ros_core/src/python_bindings/py_serializer.hpp, line 29 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS0SM5-YeI2h98Vh6o:-MnS0SM5-YeI2h98Vh6p:bjhmwo0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/py_serializer.hpp#L29)):*
> ```cpp
> namespace drake_ros_core {
> // Serialize/Deserialize Python ROS types to rclcpp::SerializedMessage
> class PySerializer : public SerializerInterface {
> ```

nit A lot of this appears to be tightly linked to 
___
*[drake_ros_core/src/python_bindings/py_serializer.hpp, line 34 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS-3Tw-LP7lZSTcsy6:-MnS-3Tx8xHjvrUETO7k:b-ed6q31) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/py_serializer.hpp#L34)):*
> ```cpp
>     py::dict scope;
>     py::exec(
>         R"delim(
> ```

nit For multiline raw "heredoc" in Drake C++, we use strings of the form `R"""(text)"""`:
https://drake.mit.edu/styleguide/cppguide.html#Raw_String_Literals
___
*[drake_ros_core/src/python_bindings/py_serializer.hpp, line 160 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS0lL8-sQ2W10DfQm9:-MnS0lL8-sQ2W10DfQmA:bt1lvz4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/py_serializer.hpp#L160)):*
> ```cpp
>  private:
>   py::object message_type_;
>   rosidl_message_type_support_t* type_support_;
> ```

All of these values should be initialized to `nullptr`.

See: https://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 33 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MlW65Hj3IkQ_h-I3DH [...]

2021-11-02 16:40 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 3 of 28 files reviewed, 17 unresolved discussions (waiting on @EricCousineau-TRI, @IanTheEngineer, and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS-hs38lvaneZhvKKg:-MnWLgYH0BXqnzYJsq5F:bxqj067) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Filenames here use `*.{hpp,cpp}`, whereas Drake uses `*.{h,cc}`.

Is there a strong reason why?
If not, can we more closely align with Drake?

Sorry for just now noticing this; can file an issue s.t. it could be handled outside of this PR.
</blockquote></details>

We've already done non-Python binding changes in here. I'll make sure to curate commits so we can rebase instead of squashing when we merge. See 5f40fa16a9bda5ef4e3364491cb11d992913d784.

---
___
*[drake_ros_core/CMakeLists.txt, line 67 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRyFOM2AzrI2Hx5QhA:-MnVuUp78iTbnFHb79e_:b-blua15) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/CMakeLists.txt#L67)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Target naming convention unclear to me.

I would assume prefix to be package name, but this seems to indicate it's for Python components of `drake_ros_core`.

Is this an `ament` convention?
If not, would it be possible to pivot the ordering? e.g. `drake_ros_core_py`?
This is slightly closer to the conventions we use for Drake (and Anzu) Python targets:
https://drake.mit.edu/doxygen_cxx/group__python__bindings.html (see the "Target Conventions" documentation)
</blockquote></details>

I don't think there's any convention w.r.t CMake target names. Changed in 1d969ea9ee7bcf446798a180eaad6aa544de6b52
___
*[drake_ros_core/CMakeLists.txt, line 80 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRxw35ESoAwqYW4LP2:-MnVxfLR2Bzse3lEY31N:b-emkx7a) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/CMakeLists.txt#L80)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This seems to dip into private implementation guts of `ament_cmake_python` without a TODO or rationale.

Can you provide rationale, perhaps upstream issue / PR?
</blockquote></details>

There's a public function for us to use. Switched to it in 1d969ea9ee7bcf446798a180eaad6aa544de6b52
___
*[drake_ros_core/pycodestyle.ini, line 2 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRynqiCe3vCaH0cN24:-MnVxvRK3UIP1rfNZNUo:bcg1rsn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/pycodestyle.ini#L2)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why these ignores are selected.

Can a terse comment be provided (so that parity can be "tracked")?
e.g. "This is close to the ignore's that Drake uses, as of https://github.com/RobotLocomotion/drake/blob/v0.35.0/tools/lint/python_lint.bzl#L7"
</blockquote></details>

Done in aaf2a05d33300f475d84642e5eef835ae62fe2c2
___
*[drake_ros_core/test/test_pub_sub.py, line 15 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS4d9jDYfvBR5Yp-ON:-MnWH4mS1QqmYNwfT9Ot:b1dn4ow) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/test/test_pub_sub.py#L15)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit It's better to include first-party stuff after third party. Ideally, you have:
```
import pydrake
import rclpy
...
import drake_ros_core
```
</blockquote></details>

Sounds good. Done in c7417e78e944cbbb3943c6b902667439c564a6dc.
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 33 at r8](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MlW65Hj3IkQ_h-I3DHF:-MnW27qO-ajtxMJlwSMd:b-j3og5j) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/e696974368716901edaa4f1a9834b1a2e899b0c2/drake_ros_core/src/python_bindings/qos_type_caster.hpp#L33)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is it possible to mention as a TODO?
</blockquote></details>

Sure. Done in 91389be53fd6c921e7631406e3d7caf26e87278b
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 1 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS0WW65EhbXTmZqQ_0:-MnWLaa0-bM0kC-dnOFf:b5hrbml) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/qos_type_caster.hpp#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Same as above - this is a utility file for `pybind`.

Can this file have the suffix `_pybind.h` to align with Drake target conventions?
</blockquote></details>

Done in b743312b07a18c0df5e7835ab7c9b46a43614c9c
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 23 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS5S9-350y-K8sjXgd:-MnW14IvAnktqGLl8PTB:bmbzdvf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/qos_type_caster.hpp#L23)):*
> FWIW There is a way to write the `type_caster<>` to not need a shim type.

Hmm I bet we were not aware of that. https://github.com/pybind/pybind11/issues/864 & co suggest a default-constructible C++ type is required unless PYBIND11_TYPE_CASTER is written out manually? 

Yeap, that seems to be the case https://github.com/pybind/pybind11/blob/e7c9753f1d35061d137ac3ce561e94a7407e5583/include/pybind11/cast.h#L88.
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 33 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS5ihbB0kM4-Rp1UZZ:-MnW31jN2V2lPXL2pSrr:bnhqgm0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/qos_type_caster.hpp#L33)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit In Drake, when writing custom type casters, we typically write the main code in Drake, and then use thin specialization code in `pybind11::detail` namespace.

Example:
https://github.com/RobotLocomotion/drake/blob/b026886f559c2cba1b450d65f53d123adf106ef5/bindings/pydrake/common/cpp_param_pybind.h#L152-L155
</blockquote></details>

Thing is, `PYBIND11_TYPE_CASTER` assumes it is within `pybind11` namespaces. The example you mention relies on `drake::pydrake::internal::type_caster_wrapped` (https://github.com/RobotLocomotion/drake/blob/e59b7fc18dbe80b827d07e4a3283a0c87eda7021/bindings/pydrake/common/wrap_pybind.h#L61), which we don't have access to and apparently foregoes `PYBIND11_TYPE_CASTER` entirely.

Do you want to do the same here?
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 67 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS1VUz7-iZHROSYY8f:-MnW4fHmDcxZKmr092Ud:b-3dmj7q) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/qos_type_caster.hpp#L67)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

You should use `py::object` if you want reference counting to be cleaned up, rather than doing piecemeal cleanup?
</blockquote></details>

Fully agreed. Changed in 91389be53fd6c921e7631406e3d7caf26e87278b
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 94 at r10](https://reviewable.io/reviews/robotlocomotion/drak [...]

2021-11-02 22:57 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with just a few more nits

> Reviewed 24 of 25 files at r11.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-:-MnXrj9-4VSmrOKoLWS2:b-m8gr4b)* status: 27 of 28 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS-hs38lvaneZhvKKg:-MnXriC2E0lcKXSnIgCN:b-w196av) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

We've already done non-Python binding changes in here. I'll make sure to curate commits so we can rebase instead of squashing when we merge. See 5f40fa16a9bda5ef4e3364491cb11d992913d784.
</blockquote></details>

OK Thanks!

---
___
*[drake_ros_core/src/python_bindings/qos_type_caster_pybind.h, line 31 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXrQWpDHluA42xPsLh:-MnXrQWpDHluA42xPsLi:b-5p62lx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/qos_type_caster_pybind.h#L31)):*
> ```objc
> namespace pybind11 {
> namespace detail {
> // TODO(hidmic): rely on rclpy.qos.QoSProfile
> ```

nit Can you file an issue and reference it here?
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 23 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS5S9-350y-K8sjXgd:-MnXoCoKARCoM5rQsTCy:b-9oqiy4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/qos_type_caster.hpp#L23)):*
> Hmm I bet we were not aware of that.

That being said, can you add a comment to make it obvious why default constructor is desired? e.g. `... since rclcpp::QoS deletes its default constructor`?
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 33 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS5ihbB0kM4-Rp1UZZ:-MnXoxWnE1HvLPYyYq-W:b-4sfsu0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/qos_type_caster.hpp#L33)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Thing is, `PYBIND11_TYPE_CASTER` assumes it is within `pybind11` namespaces. The example you mention relies on `drake::pydrake::internal::type_caster_wrapped` (https://github.com/RobotLocomotion/drake/blob/e59b7fc18dbe80b827d07e4a3283a0c87eda7021/bindings/pydrake/common/wrap_pybind.h#L61), which we don't have access to and apparently foregoes `PYBIND11_TYPE_CASTER` entirely.

Do you want to do the same here?
</blockquote></details>

OK Yeah, forgot about how much of the weirdness is in there. Nah, it's fine to leave as-is for now.
___
*[drake_ros_core/src/python_bindings/module_drake_ros_core.cpp, line 60 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnRzi0Q2bOi4gAKgAFS:-MnXnjhQ2X5yjez74-FR:b-uytolt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/module_drake_ros_core.cpp#L60)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Actually, it doesn't. Neither `RosPublisherSystem` nor `RosSubscriberSystem` keep a reference to the `DrakeRosInterface` instance. That's because deep down the underlying `rcl` instances are shared (e.g. https://github.com/ros2/rclcpp/blob/94264320b4a2fde8999b895824d2c85cf0e4d2ac/rclcpp/include/rclcpp/publisher_base.hpp#L225).
</blockquote></details>

OK Ah, gotcha. Thanks for clarifying!
___
*[drake_ros_core/src/python_bindings/py_serializer.hpp, line 29 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS0SM5-YeI2h98Vh6o:-MnXpB3X4-cVmD7roSkE:b-hxuact) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/py_serializer.hpp#L29)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

... Python generated messages and their typesupport? Yes.
</blockquote></details>

Ah, sorry, incomplete thought.

But yeah, a lot of it smells like Python code written in `pybind11`.
Ideally, a lot of this should just happen in Python itself as is done in Drake:
https://github.com/RobotLocomotion/drake/blob/4696afeacbbd87cfc962f10404f74c03f2eea575/bindings/pydrake/systems/lcm_py.cc#L209
https://github.com/RobotLocomotion/drake/blob/4696afeacbbd87cfc962f10404f74c03f2eea575/bindings/pydrake/systems/_lcm_extra.py#L7-L30

Consider adding TODO to that effect?
___
*[drake_ros_core/src/python_bindings/py_serializer_pybind.h, line 87 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXpuehAX7oVvYbItrO:-MnXpuehAX7oVvYbItrP:b-jhgdku) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/py_serializer_pybind.h#L87)):*
> ```objc
>     py::dict scope;
>     scope["av"] = &abstract_value;
>     py::object message = py::eval("av.Clone().get_mutable_value()", scope);
> ```

nit `py::eval()` seems a little heavy-handed (requires parsing each time).

Instead, consider breaking it down (and using non-mutable version):
```
py::object abstract_value_py = py::cast(&abstract_value);
py::object message = abstract_value_py.attr("get_value")();
```

Alternatively, consider writing most of this code in Python itself (see above).
___
*[drake_ros_core/src/python_bindings/py_serializer_pybind.h, line 87 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXqChwAajZlfN91V7Z:-MnXqChwAajZlfN91V7_:b-u2qi2n) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/py_serializer_pybind.h#L87)):*
> ```objc
>     py::dict scope;
>     scope["av"] = &abstract_value;
>     py::object message = py::eval("av.Clone().get_mutable_value()", scope);
> ```

nit Unclear why this is mutable.

Can this just access `const` value of message?
___
*[drake_ros_core/src/python_bindings/py_serializer_pybind.h, line 112 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXrCWYCZY3ROvB_dUK:-MnXrCWYCZY3ROvB_dUL:b8bdl4h) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/py_serializer_pybind.h#L112)):*
> ```objc
>   bool deserialize(const rclcpp::SerializedMessage& serialized_message,
>                    drake::AbstractValue& abstract_value) const override {
>     // TODO(sloretz) it would be so much more convenient if I didn't have to
> ```

nit I'm not sure if fully understand this.

Is it more so "why doesn't RMW support to-and-from bytes?"
___
*[drake_ros_core/src/python_bindings/py_serializer_pybind.h, line 113 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXpIhaD_2d4xwXIe4w:-MnXpIhaD_2d4xwXIe4x:b-otj01g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/py_serializer_pybind.h#L113)):*
> ```objc
>                    drake::AbstractValue& abstract_value) const override {
>     // TODO(sloretz) it would be so much more convenient if I didn't have to
>     // care that the Python typesupport used the C type support internally.
> ```

nit Can this be filed as upstream issue?


<!-- Sent from Reviewable.io -->

2021-11-04 00:11 UTC, hidmic reviewed
All comments addresed, PTAL!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-:-MncHDor5iPtht3IEQqu:biwrw8o)* status: 17 of 31 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_core/src/python_bindings/qos_type_caster_pybind.h, line 31 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXrQWpDHluA42xPsLh:-MncGT8P8U0SQ8eFFsq5:b-ptwrea) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/qos_type_caster_pybind.h#L31)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you file an issue and reference it here?
</blockquote></details>

Done in 021f259d36a8f89f2dfda1a7aea38df03b921a2f
___
*[drake_ros_core/src/python_bindings/qos_type_caster.hpp, line 23 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS5S9-350y-K8sjXgd:-MncCEBBBs0G3OzZP2-A:b-ptwrea) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/qos_type_caster.hpp#L23)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> Hmm I bet we were not aware of that.

That being said, can you add a comment to make it obvious why default constructor is desired? e.g. `... since rclcpp::QoS deletes its default constructor`?
</blockquote></details>

Done in 021f259d36a8f89f2dfda1a7aea38df03b921a2f
___
*[drake_ros_core/src/python_bindings/py_serializer.hpp, line 29 at r10](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnS0SM5-YeI2h98Vh6o:-MncGuD54aqiYi4zbV5K:bj5csut) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/7f2fd0ad9d701b62bcd8339e978487a291b3487a/drake_ros_core/src/python_bindings/py_serializer.hpp#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, sorry, incomplete thought.

But yeah, a lot of it smells like Python code written in `pybind11`.
Ideally, a lot of this should just happen in Python itself as is done in Drake:
https://github.com/RobotLocomotion/drake/blob/4696afeacbbd87cfc962f10404f74c03f2eea575/bindings/pydrake/systems/lcm_py.cc#L209
https://github.com/RobotLocomotion/drake/blob/4696afeacbbd87cfc962f10404f74c03f2eea575/bindings/pydrake/systems/_lcm_extra.py#L7-L30

Consider adding TODO to that effect?
</blockquote></details>

I ended up carrying through with the refactor. See 7e1bea02825bae19e830bb4654f3143de0e3ac14.
___
*[drake_ros_core/src/python_bindings/py_serializer_pybind.h, line 87 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXpuehAX7oVvYbItrO:-MncH6H47OU72V_BASIF:b7j3czy) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/py_serializer_pybind.h#L87)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `py::eval()` seems a little heavy-handed (requires parsing each time).

Instead, consider breaking it down (and using non-mutable version):
```
py::object abstract_value_py = py::cast(&abstract_value);
py::object message = abstract_value_py.attr("get_value")();
```

Alternatively, consider writing most of this code in Python itself (see above).
</blockquote></details>

See 7e1bea02825bae19e830bb4654f3143de0e3ac14.
___
*[drake_ros_core/src/python_bindings/py_serializer_pybind.h, line 87 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXqChwAajZlfN91V7Z:-MncH7as-N0ipgMc17rd:b-ahxrq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/py_serializer_pybind.h#L87)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why this is mutable.

Can this just access `const` value of message?
</blockquote></details>

No longer applies. See 7e1bea02825bae19e830bb4654f3143de0e3ac14.
___
*[drake_ros_core/src/python_bindings/py_serializer_pybind.h, line 112 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXrCWYCZY3ROvB_dUK:-MncHBFF9caeCgvan34n:b-ahxrq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/py_serializer_pybind.h#L112)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I'm not sure if fully understand this.

Is it more so "why doesn't RMW support to-and-from bytes?"
</blockquote></details>

No longer applies. See 7e1bea02825bae19e830bb4654f3143de0e3ac14.
___
*[drake_ros_core/src/python_bindings/py_serializer_pybind.h, line 113 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXpIhaD_2d4xwXIe4w:-MncHCAt35C-GavYpv-S:b-ahxrq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/py_serializer_pybind.h#L113)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can this be filed as upstream issue?
</blockquote></details>

No longer applies. See 7e1bea02825bae19e830bb4654f3143de0e3ac14.


<!-- Sent from Reviewable.io -->

2021-11-04 02:43 UTC, EricCousineau-TRI requested changes
> Reviewed 14 of 14 files at r12.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 7 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-MncnURI9wr-JeRj8Ivj:b-xw60ns) (no related file):*
CI is currently failing:
https://github.com/RobotLocomotion/drake-ros/runs/4099649076?check_suite_focus=true

Seems like this might be the issue for `rolling`?
```
   CMake Error in CMakeLists.txt:
    Imported target "pybind11::module" includes non-existent path
  
      "/usr/include/python2.7"
  
    in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
```

Galactic seemed to have errors out for different reasons:
https://github.com/RobotLocomotion/drake-ros/runs/4099649032?check_suite_focus=true

---
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mncnw0z1tTNRIjRu9lr:-Mncnw1-8lBwOZfKYv0T:b-kk9nv2) (no related file):*
At present, some of the method names seem to diverge from what Drake normally uses; O(1) get `snake_case`, while all others get `CamelCase`:
https://drake.mit.edu/styleguide/cppguide.html#Function_Names

Many of these methods seem like they're more than O(1).

(In terms of what "unit" we're talking about, I'm not sure if I have a good answer; my gut says "small instructions" more-or-less, e.g. returning pointers / references, doing basic arithmetic, etc.)

---
___
*[drake_ros_core/CMakeLists.txt, line 73 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncjV1QBANmNAB7wrZW:-MncjV1R7RZgy-gQNe1x:b-fx8tu2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/021f259d36a8f89f2dfda1a7aea38df03b921a2f/drake_ros_core/CMakeLists.txt#L73)):*
> ```CMake
>   src/python_bindings/drake_ros_core_pybind.cc
> )
> target_link_libraries(_drake_ros_core_pybind PRIVATE drake_ros_core)
> ```

nit For libraries themselves incorporating symbols, we typically name them just `_module` or `_module_py` - sorry for the nit-picking.

Example:
https://github.com/RobotLocomotion/drake/pull/15409/files#diff-04ebb3e4ed781ce9e6058b186b4cc5c78e013db45506af90486095f1d400a48b
___
*[drake_ros_core/src/python_bindings/drake_ros_core_pybind.cc, line 41 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnckX6J2hu6yxY4mf5d:-MnckX6K5iYtr8gGsZvj:b-di7a0k) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/021f259d36a8f89f2dfda1a7aea38df03b921a2f/drake_ros_core/src/python_bindings/drake_ros_core_pybind.cc#L41)):*
> ```cpp
> using drake_ros_core::SerializerInterface;
> 
> PYBIND11_MODULE(_drake_ros_core_pybind, m) {
> ```

nit Written as-is, the docstrings for these symbols will refer to `_drake_ros_core_pybind`.
To work around it, you can hack it with `m.attr("__name__") = "drake_ros_core";`

For an example showing the issue and the fix:
https://github.com/RobotLocomotion/drake/pull/15457
___
*[drake_ros_core/src/python_bindings/py_serializer_interface_pybind.h, line 49 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mncmoje-CugpIUYWz3D:-Mncmoje-CugpIUYWz3E:b-sx5zel) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/021f259d36a8f89f2dfda1a7aea38df03b921a2f/drake_ros_core/src/python_bindings/py_serializer_interface_pybind.h#L49)):*
> ```objc
>   rclcpp::SerializedMessage serialize(
>       const drake::AbstractValue& abstract_value) const override {
>     std::string bytes = [&]() -> py::bytes {
> ```

nit Defining and calling a lambda doesn't have great readability.

Consider separating out:
```
auto overload = [&]() { ... };
std::string bytes = overload();
```
___
*[drake_ros_core/src/ros_publisher_system.cc, line 34 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnciXULDwml9n9sJuv3:-MnciXULDwml9n9sJuv4:buoiwow) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/ros_publisher_system.cc#L34)):*
> ```cpp
> 
> RosPublisherSystem::RosPublisherSystem(
>     std::unique_ptr<SerializerInterface>& serializer,
> ```

BTW Ooh, good catch! Sorry for missing that.
___
*[drake_ros_core/src/ros_subscriber_system.cc, line 105 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mncibga-ZimXgkZPqFY:-Mncibga-ZimXgkZPqFZ:b-m7gxzp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/021f259d36a8f89f2dfda1a7aea38df03b921a2f/drake_ros_core/src/ros_subscriber_system.cc#L105)):*
> ```cpp
>         try {
>           impl_->serializer_->deserialize(*serialized_message, &abstract_value);
>         } catch (const std::exception&) {
> ```

Sorry for not seeing this before; it's a nice usage of the systems setup!

However, it diverges from the LCM setup and other things; we typically don't intercept exceptions and translate them to failure messages. In this case, it may be hard to backtrace with `coredumpctl gdb` or what not.

Is it possible to just let the exception happen?
___
*[drake_ros_core/src/python_bindings/py_serializer_pybind.h, line 112 at r11](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnXrCWYCZY3ROvB_dUK:-MnclMBn-STG2LyDhz7l:b-ieyay5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c7417e78e944cbbb3943c6b902667439c564a6dc/drake_ros_core/src/python_bindings/py_serializer_pybind.h#L112)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

No longer applies. See 7e1bea02825bae19e830bb4654f3143de0e3ac14.
</blockquote></details>

OK Sweet, thanks!


<!-- Sent from Reviewable.io -->

2021-11-04 13:18 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 15 of 31 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mncnw0z1tTNRIjRu9lr:-Mnf55qKEhq3KgIzFmzt:b4ble0u) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

At present, some of the method names seem to diverge from what Drake normally uses; O(1) get `snake_case`, while all others get `CamelCase`:
https://drake.mit.edu/styleguide/cppguide.html#Function_Names

Many of these methods seem like they're more than O(1).

(In terms of what "unit" we're talking about, I'm not sure if I have a good answer; my gut says "small instructions" more-or-less, e.g. returning pointers / references, doing basic arithmetic, etc.)
</blockquote></details>

Done in 3011235fce10fcfead505c01ee0575ed4ba10025

---
___
*[drake_ros_core/CMakeLists.txt, line 73 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncjV1QBANmNAB7wrZW:-MneuynoCbPwQ2KJoraP:b39m7r4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/021f259d36a8f89f2dfda1a7aea38df03b921a2f/drake_ros_core/CMakeLists.txt#L73)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For libraries themselves incorporating symbols, we typically name them just `_module` or `_module_py` - sorry for the nit-picking.

Example:
https://github.com/RobotLocomotion/drake/pull/15409/files#diff-04ebb3e4ed781ce9e6058b186b4cc5c78e013db45506af90486095f1d400a48b
</blockquote></details>

Done in 15e56bbae3328d59cd0ebc9ef466c37ca0abc41e
___
*[drake_ros_core/src/python_bindings/py_serializer_interface_pybind.h, line 49 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mncmoje-CugpIUYWz3D:-MnexZ0gEDkJHTa9p8Xa:b5m6cak) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/021f259d36a8f89f2dfda1a7aea38df03b921a2f/drake_ros_core/src/python_bindings/py_serializer_interface_pybind.h#L49)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Defining and calling a lambda doesn't have great readability.

Consider separating out:
```
auto overload = [&]() { ... };
std::string bytes = overload();
```
</blockquote></details>

Done in 93b51b7281abc5c19807c6057212a20d93dd75d4
___
*[drake_ros_core/src/ros_subscriber_system.cc, line 105 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mncibga-ZimXgkZPqFY:-Mnev4AH5--rLWNwmCur:b5d8149) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/021f259d36a8f89f2dfda1a7aea38df03b921a2f/drake_ros_core/src/ros_subscriber_system.cc#L105)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry for not seeing this before; it's a nice usage of the systems setup!

However, it diverges from the LCM setup and other things; we typically don't intercept exceptions and translate them to failure messages. In this case, it may be hard to backtrace with `coredumpctl gdb` or what not.

Is it possible to just let the exception happen?
</blockquote></details>

Sure. Done in d68b656ee645528d0183c5280e8948ba33271967
___
*[drake_ros_core/src/python_bindings/drake_ros_core_pybind.cc, line 41 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnckX6J2hu6yxY4mf5d:-Mnevq4vD68PL6oKMbAC:b-7gqxl4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/021f259d36a8f89f2dfda1a7aea38df03b921a2f/drake_ros_core/src/python_bindings/drake_ros_core_pybind.cc#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Written as-is, the docstrings for these symbols will refer to `_drake_ros_core_pybind`.
To work around it, you can hack it with `m.attr("__name__") = "drake_ros_core";`

For an example showing the issue and the fix:
https://github.com/RobotLocomotion/drake/pull/15457
</blockquote></details>

Done in 8465976f7bae6d50e6331f307d547bbcfa1e8286. However, I will point out that this right here _is_ a separate module from the actual the actual `drake_ros_core` module that imports it. I did not replicate the `exec` magic that's being used in `pydrake` (not because we can't but because leaving broken Python modules in the install space seems a bit inappropriate).


<!-- Sent from Reviewable.io -->

2021-11-04 14:00 UTC, EricCousineau-TRI reviewed
> Reviewed 15 of 16 files at r13.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 30 of 31 files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mncnw0z1tTNRIjRu9lr:-MnfF3BeBEwnF9IELPYJ:b-w196av) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Done in 3011235fce10fcfead505c01ee0575ed4ba10025
</blockquote></details>

OK Thanks!

---
___
*[drake_ros_core/src/publisher.h, line 25 at r13](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfDrICBft15gc-xONr:-MnfDrICBft15gc-xONs:b-gdheua) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3011235fce10fcfead505c01ee0575ed4ba10025/drake_ros_core/src/publisher.h#L25)):*
> ```objc
> 
> namespace drake_ros_core {
> class Publisher final : public rclcpp::PublisherBase {
> ```

nit Unclear why this class exists.

Consider documenting. My guess?
`// Provides a publisher that is a type-erased version of rclcpp:::Publisher<Message>.`
___
*[drake_ros_core/src/publisher.h, line 25 at r13](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfDwTp6-v0bp0ItGlI:-MnfDwTp6-v0bp0ItGlJ:b-lvx89k) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3011235fce10fcfead505c01ee0575ed4ba10025/drake_ros_core/src/publisher.h#L25)):*
> ```objc
> 
> namespace drake_ros_core {
> class Publisher final : public rclcpp::PublisherBase {
> ```

nit `Publisher` is a bit of a 
___
*[drake_ros_core/src/publisher.h, line 34 at r13](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfCajd8ZD0mN_XnVFq:-MnfCajd8ZD0mN_XnVFr:b-49k2m9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3011235fce10fcfead505c01ee0575ed4ba10025/drake_ros_core/src/publisher.h#L34)):*
> ```objc
> 
>   // Using snake cased function names to not mix up Drake and ROS 2 C++ styles.
>   void publish(const rclcpp::SerializedMessage& serialized_msg);
> ```

nit It's unclear if you're preserving the name purely for consistency, or if you're you actually overriding a method / trying to obey a contract (e.g. `&Class::publish`).

My take is that it's for consistency, rather than any contract.

If so, two options:
- Consider just conforming to Drake, if you're not overriding anything?
- Hoist comment to top-level of class, stating that it's purely stylistic, not for contracts. (I guess "style" indicates that, but was still a tad ambiguous...
___
*[drake_ros_core/src/subscription.h, line 36 at r13](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfEEU-8PGuusnYR5MH:-MnfEEU0ESxUS0iSNjAu:bvunt8k) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3011235fce10fcfead505c01ee0575ed4ba10025/drake_ros_core/src/subscription.h#L36)):*
> ```objc
> 
>  protected:
>   // Using snake cased function names to not mix up Drake and ROS 2 C++ styles.
> ```

nit Same as above for `publisher`.
___
*[drake_ros_core/src/python_bindings/drake_ros_core_pybind.cc, line 41 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnckX6J2hu6yxY4mf5d:-MnfEKfn2WgKJxKApa7V:b-q1v9kv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/021f259d36a8f89f2dfda1a7aea38df03b921a2f/drake_ros_core/src/python_bindings/drake_ros_core_pybind.cc#L41)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Done in 8465976f7bae6d50e6331f307d547bbcfa1e8286. However, I will point out that this right here _is_ a separate module from the actual the actual `drake_ros_core` module that imports it. I did not replicate the `exec` magic that's being used in `pydrake` (not because we can't but because leaving broken Python modules in the install space seems a bit inappropriate).
</blockquote></details>

OK Yes, but to the user, they shouldn't care about a private module.

It is true that Drake's `_{module}_extra.py` are not "real" Python modules (given that they require C++ module's populated scope). However, they're private, so I don't think it's important what the user can see in this case.

(That being said, perhaps there's a better way to forward the symbols and import as you're doing here - I only just recently started using the `__name__` override trick hehe)


<!-- Sent from Reviewable.io -->

2021-11-04 16:00 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 28 of 31 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-MnffQgm7kF1gr8QZOyL:b1spik2) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

CI is currently failing:
https://github.com/RobotLocomotion/drake-ros/runs/4099649076?check_suite_focus=true

Seems like this might be the issue for `rolling`?
```
   CMake Error in CMakeLists.txt:
    Imported target "pybind11::module" includes non-existent path
  
      "/usr/include/python2.7"
  
    in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
```

Galactic seemed to have errors out for different reasons:
https://github.com/RobotLocomotion/drake-ros/runs/4099649032?check_suite_focus=true
</blockquote></details>

Hmm, I can't reproduce.

---
___
*[drake_ros_core/src/publisher.h, line 25 at r13](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfDrICBft15gc-xONr:-MnfW0Gs6tgwhDAnk-57:b-elahum) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3011235fce10fcfead505c01ee0575ed4ba10025/drake_ros_core/src/publisher.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why this class exists.

Consider documenting. My guess?
`// Provides a publisher that is a type-erased version of rclcpp:::Publisher<Message>.`
</blockquote></details>

Done in 
___
*[drake_ros_core/src/publisher.h, line 25 at r13](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfDwTp6-v0bp0ItGlI:-MnffGkGC3W874eppJCY:b-skcw9f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3011235fce10fcfead505c01ee0575ed4ba10025/drake_ros_core/src/publisher.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `Publisher` is a bit of a 
</blockquote></details>

Pending?
___
*[drake_ros_core/src/publisher.h, line 34 at r13](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfCajd8ZD0mN_XnVFq:-MnfUVszEJQgzIFgRuOX:beojbl5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3011235fce10fcfead505c01ee0575ed4ba10025/drake_ros_core/src/publisher.h#L34)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit It's unclear if you're preserving the name purely for consistency, or if you're you actually overriding a method / trying to obey a contract (e.g. `&Class::publish`).

My take is that it's for consistency, rather than any contract.

If so, two options:
- Consider just conforming to Drake, if you're not overriding anything?
- Hoist comment to top-level of class, stating that it's purely stylistic, not for contracts. (I guess "style" indicates that, but was still a tad ambiguous...
</blockquote></details>

As of today, consistency. If at some point `rclcpp` offers this API, it will conform to ROS 2's style.

Added comment in 
___
*[drake_ros_core/src/subscription.h, line 36 at r13](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfEEU-8PGuusnYR5MH:-MnfW1fKDFcK1shoisH9:b-elahum) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3011235fce10fcfead505c01ee0575ed4ba10025/drake_ros_core/src/subscription.h#L36)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Same as above for `publisher`.
</blockquote></details>

Done in 
___
*[drake_ros_core/src/python_bindings/drake_ros_core_pybind.cc, line 41 at r12](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnckX6J2hu6yxY4mf5d:-MnffIr_CxBLdwLPAjmg:b-gxztsp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/021f259d36a8f89f2dfda1a7aea38df03b921a2f/drake_ros_core/src/python_bindings/drake_ros_core_pybind.cc#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Yes, but to the user, they shouldn't care about a private module.

It is true that Drake's `_{module}_extra.py` are not "real" Python modules (given that they require C++ module's populated scope). However, they're private, so I don't think it's important what the user can see in this case.

(That being said, perhaps there's a better way to forward the symbols and import as you're doing here - I only just recently started using the `__name__` override trick hehe)
</blockquote></details>

Fair enough.


<!-- Sent from Reviewable.io -->

2021-11-04 16:12 UTC, EricCousineau-TRI requested changes
Just saw some tidbits about encapsulation that I think violate GSG (forward decl's, pimpl), and some confusion as to what's private / public API.

> Reviewed 1 of 16 files at r13, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-:-MnfiEj76qjyV7tpINMo:b-8h71oo)* status: all files reviewed, 11 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-Mnfh9gsAWUJWmbd_53O:b-7ohsxu) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Hmm, I can't reproduce.
</blockquote></details>

My guess is that there's some pollution, either from Drake Focal docker container that CI is using, or perhaps something from the ROS2 actions.

---
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 30 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhQr23jVpRTKXPHu3:-MnfhQr23jVpRTKXPHu4:b-8jc3p5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/drake_ros.h#L30)):*
> ```objc
> namespace drake_ros_core {
> /// PIMPL forward declarations
> class DrakeRosPrivate;
> ```

PIMPL detail should ideally be private within the class itself, e.g.
```
private:
  class Impl;
  unique_ptr<Impl> impl;
```
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 31 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhYVtBAXTIhQ0udjE:-MnfhYVu6gOsU2Y34Qs3:b-bj1oeh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/drake_ros.h#L31)):*
> ```objc
> /// PIMPL forward declarations
> class DrakeRosPrivate;
> class Publisher;
> ```

These forward decls don't seem warranted, and violated GSG.

Can they be removed? (at a minimum, from public API?)
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.h, line 26 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhmERBR2dVtYbc_Wf:-MnfhmES7zWSB8awIWUJ:b6eju8l) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/drake_ros_interface.h#L26)):*
> ```objc
> 
> namespace drake_ros_core {
> // Forward declarations for non-public-API classes
> ```

Same as above, not sure I understand why forward decl's are necessary, esp. in header.
___
*[drake_ros_core/include/drake_ros_core/ros_publisher_system.h, line 30 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhrhrE50MbNQM29Zo:-MnfhrhrE50MbNQM29Zp:b-1c3ew5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/ros_publisher_system.h#L30)):*
> ```objc
> namespace drake_ros_core {
> /// PIMPL forward declaration
> class RosPublisherSystemPrivate;
> ```

Same as above - PIMPL should contained private scope of class.
___
*[drake_ros_core/include/drake_ros_core/ros_subscriber_system.h, line 27 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhvYR0GZwB4EnZMPW:-MnfhvYR0GZwB4EnZMPX:b73eme1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/ros_subscriber_system.h#L27)):*
> ```objc
> 
> namespace drake_ros_core {
> // PIMPL forward declaration
> ```

Same as above - PIMPL should be encapsulated in private scope of class.
___
*[drake_ros_core/src/publisher.h, line 25 at r13](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfDwTp6-v0bp0ItGlI:-MnfgT_UBt8TyMB_dKVr:b-j7x4u6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3011235fce10fcfead505c01ee0575ed4ba10025/drake_ros_core/src/publisher.h#L25)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Pending?
</blockquote></details>

Ah, nuts, sorry. Meant to say, a bit of a confusing name w.r.t. `rclcpp::Publisher<>`, was going to suggest baking purpose into name.

That being said, class overview docs helps to clarify, so will mark myself satisfied.
___
*[drake_ros_core/src/publisher.h, line 34 at r13](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfCajd8ZD0mN_XnVFq:-MnfggM-D7VXjzp6_E4U:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3011235fce10fcfead505c01ee0575ed4ba10025/drake_ros_core/src/publisher.h#L34)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

As of today, consistency. If at some point `rclcpp` offers this API, it will conform to ROS 2's style.

Added comment in 
</blockquote></details>

OK Thanks!
___
*[drake_ros_core/src/publisher.h, line 25 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfgcjkClNwOLMtAWU4:-MnfgcjkClNwOLMtAWU5:b68h581) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/publisher.h#L25)):*
> ```objc
> 
> namespace drake_ros_core {
> // A type-erased version of rclcpp:::Publisher<Message>.
> ```

nit This should be a public "docstring", e.g. `/** A type-erased ... */`.
___
*[drake_ros_core/src/ros_interface_system.cc, line 45 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mnfgn3X-2nlyGnYE7wm:-Mnfgn3X-2nlyGnYE7wn:bpd40yp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/ros_interface_system.cc#L45)):*
> ```cpp
>   // Do work for at most 1ms so system doesn't get blocked if there's more work
>   // than it can handle
>   const int max_work_time_millis = 1;
> ```

Working: Will check to see if this matches LCM's semantics in Drake.
___
*[drake_ros_core/src/subscription.h, line 24 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mnfi1HUAIgMc_vzWUTY:-Mnfi1HUAIgMc_vzWUTZ:b-sdvnng) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/subscription.h#L24)):*
> ```objc
> #include <rosidl_runtime_c/message_type_support_struct.h>
> 
> namespace drake_ros_core {
> ```

It's not clear to me at all that this is private / internal.

If it is, can you place in `internal` namespace?

Consider also placing headers under `internal/` subdirectory.
___
*[drake_ros_core/src/subscription.h, line 25 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfgrPV-T-M2tfWgs7P:-MnfgrPV-T-M2tfWgs7Q:b-amyx5e) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/subscription.h#L25)):*
> ```objc
> 
> namespace drake_ros_core {
> // A type-erased version of rclcpp:::Subscription<Message>.
> ```

nit Should be public "docstring".


<!-- Sent from Reviewable.io -->

2021-11-04 16:36 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 11 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 31 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhYVtBAXTIhQ0udjE:-MnfmEL814jqj9mbAQrz:bz0sc7c) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/drake_ros.h#L31)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

These forward decls don't seem warranted, and violated GSG.

Can they be removed? (at a minimum, from public API?)
</blockquote></details>

Oof, I had overlooked this. Those forward declarations are necessary because, while both Publisher and Subscription are opaque to the caller, they are required by the `RosPublisherSystem` and `RosSubscriberSystem` implementations respectively :eyes: 

Judging by the code, I'm inclined to drop both `Create*`APIs and add  a `get_node` API for systems to fetch. WDYT?


<!-- Sent from Reviewable.io -->

2021-11-04 16:41 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 11 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 31 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhYVtBAXTIhQ0udjE:-MnfoDRz28a-zjwoFUq6:b35j4x6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/drake_ros.h#L31)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Oof, I had overlooked this. Those forward declarations are necessary because, while both Publisher and Subscription are opaque to the caller, they are required by the `RosPublisherSystem` and `RosSubscriberSystem` implementations respectively :eyes: 

Judging by the code, I'm inclined to drop both `Create*`APIs and add  a `get_node` API for systems to fetch. WDYT?

</blockquote></details>

Aye, that'd work for me!

Just thinking on alternatives:
- Ensure that this is cleared marked private (e.g. `internal::`), and have yer way within the `internal::` namespace.
- Do weird type erasure at this interface, e.g. return `rclcpp::PublishBase` and downcast inside system impls. (ew)


<!-- Sent from Reviewable.io -->

2021-11-04 17:59 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 18 of 31 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-Mng5DpxCcZuVVEYoEug:bxlybcr) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

My guess is that there's some pollution, either from Drake Focal docker container that CI is using, or perhaps something from the ROS2 actions.
</blockquote></details>

I did try using the Drake Focal docker image locally. No issues. That should indicate an issue in ROS 2 GH actions, but they have been the same for months.

---
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 30 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhQr23jVpRTKXPHu3:-Mng4tBq9DRJEzydWqGF:b7jifrd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/drake_ros.h#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

PIMPL detail should ideally be private within the class itself, e.g.
```
private:
  class Impl;
  unique_ptr<Impl> impl;
```
</blockquote></details>

Done in 4b2d2a6bf535ddc93e7763dc361edbe6ab26f2dd
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 31 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhYVtBAXTIhQ0udjE:-Mng4v99D3Rf1k7Z-paN:be1lvth) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/drake_ros.h#L31)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Aye, that'd work for me!

Just thinking on alternatives:
- Ensure that this is cleared marked private (e.g. `internal::`), and have yer way within the `internal::` namespace.
- Do weird type erasure at this interface, e.g. return `rclcpp::PublishBase` and downcast inside system impls. (ew)
</blockquote></details>

See 4b2d2a6bf535ddc93e7763dc361edbe6ab26f2dd.
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.h, line 26 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhmERBR2dVtYbc_Wf:-Mng51v31Se-N871jdUG:b4tlxod) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/drake_ros_interface.h#L26)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Same as above, not sure I understand why forward decl's are necessary, esp. in header.
</blockquote></details>

Removed in 4b2d2a6bf535ddc93e7763dc361edbe6ab26f2dd
___
*[drake_ros_core/include/drake_ros_core/ros_publisher_system.h, line 30 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhrhrE50MbNQM29Zo:-Mng54WP8nF-PndbIb1l:b7jifrd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/ros_publisher_system.h#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Same as above - PIMPL should contained private scope of class.
</blockquote></details>

Done in 4b2d2a6bf535ddc93e7763dc361edbe6ab26f2dd
___
*[drake_ros_core/include/drake_ros_core/ros_subscriber_system.h, line 27 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfhvYR0GZwB4EnZMPW:-Mng57VPBCmnlJsXtQMG:b7jifrd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/include/drake_ros_core/ros_subscriber_system.h#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Same as above - PIMPL should be encapsulated in private scope of class.
</blockquote></details>

Done in 4b2d2a6bf535ddc93e7763dc361edbe6ab26f2dd
___
*[drake_ros_core/src/publisher.h, line 25 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfgcjkClNwOLMtAWU4:-Mng58km22Y_5gCUzaip:b-v0ovul) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/publisher.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This should be a public "docstring", e.g. `/** A type-erased ... */`.
</blockquote></details>

Done in f434628708e3dd063e2883f2b9c343cdc22daf2a
___
*[drake_ros_core/src/subscription.h, line 24 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mnfi1HUAIgMc_vzWUTY:-Mng3sIo3xxgNFhJ_odr:b-tayzel) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/subscription.h#L24)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's not clear to me at all that this is private / internal.

If it is, can you place in `internal` namespace?

Consider also placing headers under `internal/` subdirectory.
</blockquote></details>

Done in cf92b8ee1b793b7d5a06fca28de966fa8b30b14c
___
*[drake_ros_core/src/subscription.h, line 25 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfgrPV-T-M2tfWgs7P:-Mng4pGA6SidCJ436AUF:b-v0ovul) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/subscription.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should be public "docstring".
</blockquote></details>

Done in f434628708e3dd063e2883f2b9c343cdc22daf2a


<!-- Sent from Reviewable.io -->

2021-11-04 18:19 UTC, EricCousineau-TRI reviewed
> Reviewed 13 of 13 files at r15.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 25 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mng9IO79lOrYvMqZ0-Y:-Mng9IO79lOrYvMqZ0-Z:b-gadjuu) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/include/drake_ros_core/drake_ros.h#L25)):*
> ```objc
> 
> namespace drake_ros_core {
> /// System that abstracts working with ROS
> ```

nit Unclear what "working with ROS" means.

Can you expand on documentation here? e.g. "manages a rclcpp::Node instance [...]"
___
*[drake_ros_core/src/publisher.h, line 25 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfgcjkClNwOLMtAWU4:-Mng9b342EcvxkhVCieX:bazspk7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/publisher.h#L25)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Done in f434628708e3dd063e2883f2b9c343cdc22daf2a
</blockquote></details>

Ah, now that it's internal, it should be demoted - sorry about that!
___
*[drake_ros_core/src/ros_publisher_system.cc, line 27 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mng9ry59zet5e4K68dX:-Mng9ry59zet5e4K68dY:b-sq5vkl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/src/ros_publisher_system.cc#L27)):*
> ```cpp
> 
> namespace drake_ros_core {
> class RosPublisherSystem::Impl {
> ```

nit (here and in subscriber) For implementation objects that expose members, I believe we should prefer a `struct` (where members do not end with trailing `_`), or provide mutable accessors.

(My pref is to do a `struct`)
___
*[drake_ros_core/src/ros_subscriber_system.cc, line 29 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngA67L48T1O7rBVkV0:-MngA67M0yKVZEd8OazA:b-uemhbm) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/src/ros_subscriber_system.cc#L29)):*
> ```cpp
> const int kStateIndexMessage = 0;
> 
> class RosSubscriberSystem::Impl {
> ```

nit Same as above: if you're expose all members as public, consider using `struct`.
___
*[drake_ros_core/src/subscription.h, line 25 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfgrPV-T-M2tfWgs7P:-MngAC0rDQpxzpIV7NPx:bsxfu05) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/subscription.h#L25)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Done in f434628708e3dd063e2883f2b9c343cdc22daf2a
</blockquote></details>

Same as above - now internal, should be private.


<!-- Sent from Reviewable.io -->

2021-11-04 18:32 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-MngDFo58o-IeR-mTLyI:b9dw88n) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

I did try using the Drake Focal docker image locally. No issues. That should indicate an issue in ROS 2 GH actions, but they have been the same for months.
</blockquote></details>

Hm... why did the CI results disappear? Can't seem now.

---


<!-- Sent from Reviewable.io -->

2021-11-04 18:48 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-MngGQb63pz98lHoonMZ:byv51aa) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... why did the CI results disappear? Can't seem now.
</blockquote></details>

Also, tracing the CI workflow results, why does it install what looks like vanilla ROS?
```
sudo bash -c echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list
```

---


<!-- Sent from Reviewable.io -->

2021-11-04 18:55 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-MngI6JyERhgv84iUFFw:bwvbrhz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Also, tracing the CI workflow results, why does it install what looks like vanilla ROS?
```
sudo bash -c echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list
```
</blockquote></details>

Aha, from link above, I think this is the offending line:
```
Invoking "sudo DEBIAN_FRONTEND=noninteractive RTI_NC_LICENSE_ACCEPTED=yes apt-get install --no-install-recommends --quiet --yes libssl-dev python3-dev build-essential clang cmake git lcov libc++-dev libc++abi-dev python python3-catkin-pkg-modules python3-pip python3-vcstool wget libasio-dev libtinyxml2-dev python3-rosdep"
```

Most notably, installation of the `python` package.

On my Focal setup:
```
$ sudo apt install python
...
Note, selecting 'python-is-python2' instead of 'python'
The following packages will be REMOVED:
  python-is-python3
The following NEW packages will be installed:
  python-is-python2
```

So yeah, I'm fairly certain you could repro by installing this package.

That being said, EWW. This seems like a bad thing for ros actions to do, esp. if you're wanting to use ROS2 on a system that defaults to Python 3?

Options:
- Somehow make it work with `python2` being `python`.
- Re-install `python-is-python3`

---


<!-- Sent from Reviewable.io -->

2021-11-04 19:04 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_core/src/ros_interface_system.cc, line 45 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mnfgn3X-2nlyGnYE7wm:-MngJ3VKDeEZd9YqHl-B:b-rqzynn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/ros_interface_system.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will check to see if this matches LCM's semantics in Drake.
</blockquote></details>

This deviates from LCM:
https://github.com/RobotLocomotion/drake/blob/v0.35.0/systems/lcm/lcm_interface_system.cc#L72-L73
https://github.com/RobotLocomotion/drake/blob/v0.35.0/lcm/drake_lcm_interface.h#L130-L137

In this case, it the timeout being zero means it does not wait at all if there are no new messages:
https://lcm-proj.github.io/group__LcmC__lcm__t.html#ga48b225668d5c08264af47c7dd2ffb70f

I don't believe it has anything to do with how much work can be executed.

Options:
- I'm misunderstanding?
- By default, set `max_work_time_millis=0`, but let it be tunable.


<!-- Sent from Reviewable.io -->

2021-11-04 19:04 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 6 unresolved discussions (waiting on @hidmic and @IanTheEngineer)



<!-- Sent from Reviewable.io -->

2021-11-04 19:11 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 6 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

___
*[drake_ros_core/src/ros_interface_system.cpp, line 49 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngL7A0D7oKhcyw95Dn:-MngL7A0D7oKhcyw95Do:bn33nkx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/581b156ce3444168c904c9383472410199beb5d1/drake_ros_core/src/ros_interface_system.cpp#L49)):*
> ```cpp
>   impl_->ros_->spin(max_work_time_millis);
>   // TODO(sloretz) Lcm system pauses time if some work was done, but ROS 2 API
>   // doesn't say if any work was done. How to reconcile that?
> ```

BTW Just now reading this, not sure if it's critical, given that subscriber also does this. A bit confused about interplay, but will review unittests.


<!-- Sent from Reviewable.io -->

2021-11-04 19:19 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 7 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

___
*[drake_ros_core/test/test_pub_sub.cc, line 81 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngNOg_52C9SQBHs2vC:-MngNOg_52C9SQBHs2vD:buzgsjj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/test/test_pub_sub.cc#L81)):*
> ```cpp
>       "out", qos, rx_callback);
> 
>   // Send messages into the drake system
> ```

nit (existing) Not sure if I see a check ensuring that `ros_subscriber_system` saw all of these messages.

Is it possible to address that? (either in this PR, or as a follow-up PR?)


<!-- Sent from Reviewable.io -->

2021-11-04 19:22 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 8 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

___
*[drake_ros_core/test/test_pub_sub.py, line 69 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngOYN00wsfaefIkfIQ:-MngOYN00wsfaefIkfIR:b-igzl07) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/test/test_pub_sub.py#L69)):*
> ```Python
>     # Send messages into the drake system
>     num_msgs = 5
>     for _ in range(num_msgs):
> ```

nit (same as above for C++) I'm not sure if I see anything that tests what `ros_subscriber_system` receives.


<!-- Sent from Reviewable.io -->

2021-11-04 19:27 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 9 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.h, line 24 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngP0Lp1zGaBdWesJ5m:-MngP0Lp1zGaBdWesJ5n:bts0m69) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/include/drake_ros_core/drake_ros_interface.h#L24)):*
> ```objc
> 
> namespace drake_ros_core {
> /// System that abstracts working with ROS
> ```

nit Not sure if I get the motivation for providing this `DrakeRosInterface`.

In Drake, we provide `DrakeLcmInterface` b/c all of the types are decoupled from the `lcm::LCM` class itself, so we can manage pub/sub.

For example, look at difference between `DrakeLcm` and `DrakeLcmLog`.

In this case, having the interface offer a `node` is a wee bit confusing, as I'm not sure how amenable it will be to similar implementations.

Consider removing, or add a TODO / issue about providing another implementation that motivates this base class?


<!-- Sent from Reviewable.io -->

2021-11-04 22:19 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-Mnh-pi2DiMN1EGuqM9r:b-no6t4c) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Aha, from link above, I think this is the offending line:
```
Invoking "sudo DEBIAN_FRONTEND=noninteractive RTI_NC_LICENSE_ACCEPTED=yes apt-get install --no-install-recommends --quiet --yes libssl-dev python3-dev build-essential clang cmake git lcov libc++-dev libc++abi-dev python python3-catkin-pkg-modules python3-pip python3-vcstool wget libasio-dev libtinyxml2-dev python3-rosdep"
```

Most notably, installation of the `python` package.

On my Focal setup:
```
$ sudo apt install python
...
Note, selecting 'python-is-python2' instead of 'python'
The following packages will be REMOVED:
  python-is-python3
The following NEW packages will be installed:
  python-is-python2
```

So yeah, I'm fairly certain you could repro by installing this package.

That being said, EWW. This seems like a bad thing for ros actions to do, esp. if you're wanting to use ROS2 on a system that defaults to Python 3?

Options:
- Somehow make it work with `python2` being `python`.
- Re-install `python-is-python3`
</blockquote></details>

That `python` dependency is hard-coded upstream https://github.com/ros-tooling/setup-ros/blob/45f6b7f943fe5b2902f51282f92ef14a678f7183/src/package_manager/apt.ts#L26 ...

 > Re-install python-is-python3

Let's go with that for now. I'll open a ticket upstream.

---
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.h, line 24 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngP0Lp1zGaBdWesJ5m:-Mnh0CWH8wFGHRCmQGmy:bn2n28j) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/include/drake_ros_core/drake_ros_interface.h#L24)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Not sure if I get the motivation for providing this `DrakeRosInterface`.

In Drake, we provide `DrakeLcmInterface` b/c all of the types are decoupled from the `lcm::LCM` class itself, so we can manage pub/sub.

For example, look at difference between `DrakeLcm` and `DrakeLcmLog`.

In this case, having the interface offer a `node` is a wee bit confusing, as I'm not sure how amenable it will be to similar implementations.

Consider removing, or add a TODO / issue about providing another implementation that motivates this base class?
</blockquote></details>

Hmm. I guess we could collapse it all into `DrakeRosInterface` to match `DrakeLcmInterface` too.

Do you foresee a need for a `DrakeRosLog`?
___
*[drake_ros_core/src/ros_interface_system.cpp, line 49 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngL7A0D7oKhcyw95Dn:-Mngupl3300y5OPjRdI5:b-xkmutc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/581b156ce3444168c904c9383472410199beb5d1/drake_ros_core/src/ros_interface_system.cpp#L49)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Just now reading this, not sure if it's critical, given that subscriber also does this. A bit confused about interplay, but will review unittests.
</blockquote></details>

IIUC this means that messages will not necessarily be made available through system ports "instantaneously" (in simulation time). If the node spins after a subscriber system attempts to take a message, it may have to wait till the next step.

It is still true that this information is not provided by ROS 2 APIs though.


<!-- Sent from Reviewable.io -->

2021-11-05 14:26 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 9 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-MnkU_O53TxOdZA1u3XB:b-ucfknh) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

That `python` dependency is hard-coded upstream https://github.com/ros-tooling/setup-ros/blob/45f6b7f943fe5b2902f51282f92ef14a678f7183/src/package_manager/apt.ts#L26 ...

 > Re-install python-is-python3

Let's go with that for now. I'll open a ticket upstream.
</blockquote></details>

Thanks!

---
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 25 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mng9IO79lOrYvMqZ0-Y:-MnkTLdi7TO8roRp9SIa:b-qf4ee1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/include/drake_ros_core/drake_ros.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear what "working with ROS" means.

Can you expand on documentation here? e.g. "manages a rclcpp::Node instance [...]"
</blockquote></details>

OK Redacting this comment based on Slack convo (no need for extensive docs in this PR)
https://drakedevelopers.slack.com/archives/C01B5B320QY/p1636053155014300
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.h, line 24 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngP0Lp1zGaBdWesJ5m:-MnkTSFOCbar4dM3pBTv:b-eyvytg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/include/drake_ros_core/drake_ros_interface.h#L24)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Hmm. I guess we could collapse it all into `DrakeRosInterface` to match `DrakeLcmInterface` too.

Do you foresee a need for a `DrakeRosLog`?
</blockquote></details>

Not yet; I was thinking of `DrakeRosLog` as a means to merit the interface.
(It would be helpful in the future, but let's keep that out-of-scope for this PR.)

Writing down backwards compat rationale (just to check):
If we merge this with `DrakeRos`, then we can always change type signatures here from `DrakeRos` to `DrakeRosInterface`, and be backwards-compatible where possible - so merging should be OK in terms of public API.
___
*[drake_ros_core/src/ros_interface_system.cpp, line 49 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngL7A0D7oKhcyw95Dn:-MnkUDqCEQRrCpzygL_U:b-5qngk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/581b156ce3444168c904c9383472410199beb5d1/drake_ros_core/src/ros_interface_system.cpp#L49)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

IIUC this means that messages will not necessarily be made available through system ports "instantaneously" (in simulation time). If the node spins after a subscriber system attempts to take a message, it may have to wait till the next step.

It is still true that this information is not provided by ROS 2 APIs though.
</blockquote></details>

Hm... at some point, it'd be nice to see what this actually means (e.g. writing a unittest / example that shows the difference in a minimal way).

Can you encode your more-concrete example here, and add that we should write a test exercising this difference? (raising to nit)


<!-- Sent from Reviewable.io -->

2021-11-05 22:24 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 15 of 32 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-MnmBPuT45opEr3TbPcx:b83vh2l) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Workaround added in 3781f5b18f2328137d11458e69c2bf76f2dfd636. Let's see how it fares. 

---
___
*[drake_ros_core/test/test_pub_sub.py, line 69 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngOYN00wsfaefIkfIQ:-Mnm9AkP-Mkv8rA0HMmm:b2nreh6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/test/test_pub_sub.py#L69)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (same as above for C++) I'm not sure if I see anything that tests what `ros_subscriber_system` receives.
</blockquote></details>

Same as above.
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 25 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mng9IO79lOrYvMqZ0-Y:-MnmBX5JD6kwMNfiwCii:bigj1nr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/include/drake_ros_core/drake_ros.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Redacting this comment based on Slack convo (no need for extensive docs in this PR)
https://drakedevelopers.slack.com/archives/C01B5B320QY/p1636053155014300
</blockquote></details>

I ended up adding some more documentation, just in case :sweat_smile: 

See 8cbd023a1f37b81a367b6eb6c2f2c49d2d232bb6.
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.h, line 24 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngP0Lp1zGaBdWesJ5m:-MnmBac-EYjd_RGzI_Am:bpl2r7x) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/include/drake_ros_core/drake_ros_interface.h#L24)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Not yet; I was thinking of `DrakeRosLog` as a means to merit the interface.
(It would be helpful in the future, but let's keep that out-of-scope for this PR.)

Writing down backwards compat rationale (just to check):
If we merge this with `DrakeRos`, then we can always change type signatures here from `DrakeRos` to `DrakeRosInterface`, and be backwards-compatible where possible - so merging should be OK in terms of public API.
</blockquote></details>

Removed `DrakeRosInterface` in 8cbd023a1f37b81a367b6eb6c2f2c49d2d232bb6.
___
*[drake_ros_core/src/publisher.h, line 25 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfgcjkClNwOLMtAWU4:-MnmBdMe1KWxABlgk9Jy:buelp49) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/publisher.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, now that it's internal, it should be demoted - sorry about that!
</blockquote></details>

Fixed in 8cbd023a1f37b81a367b6eb6c2f2c49d2d232bb6.
___
*[drake_ros_core/src/ros_interface_system.cc, line 45 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mnfgn3X-2nlyGnYE7wm:-MnlztRdC3gKDeKdTZ-H:bsgv1kp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/ros_interface_system.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This deviates from LCM:
https://github.com/RobotLocomotion/drake/blob/v0.35.0/systems/lcm/lcm_interface_system.cc#L72-L73
https://github.com/RobotLocomotion/drake/blob/v0.35.0/lcm/drake_lcm_interface.h#L130-L137

In this case, it the timeout being zero means it does not wait at all if there are no new messages:
https://lcm-proj.github.io/group__LcmC__lcm__t.html#ga48b225668d5c08264af47c7dd2ffb70f

I don't believe it has anything to do with how much work can be executed.

Options:
- I'm misunderstanding?
- By default, set `max_work_time_millis=0`, but let it be tunable.
</blockquote></details>

Hmm, API contracts differ here. 

For LCM, `HandleSubscriptions` waits up to a timeout for work, and then dispatches all available work in a non-blocking way (https://github.com/RobotLocomotion/drake/blob/2634b4c846945ead334752e13ca2087ccde77aec/lcm/drake_lcm.cc#L293-L297). 

For `rclcpp`, 

- `spin_some` dispatches all available work up to a timeout. It fetches work once and doesn't wait for more. A zero timeout means to dispatch them all.

- `spin_all` dispatches all available work up to a timeout. It fetches work repeatedly but doesn't wait for it. A zero timeout means to dispatch them all.

- `spin_once` waits up to a timeout for work. It dispatches once. A zero timeout means no wait.

So perhaps we can achieve behavior akin to LCM by combining `spin_once` and `spin_some`. See 8cbd023a1f37b81a367b6eb6c2f2c49d2d232bb6.
___
*[drake_ros_core/src/ros_interface_system.cpp, line 49 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngL7A0D7oKhcyw95Dn:-MnmBg-W8k58BK5Hhc_A:bvbcwys) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/581b156ce3444168c904c9383472410199beb5d1/drake_ros_core/src/ros_interface_system.cpp#L49)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... at some point, it'd be nice to see what this actually means (e.g. writing a unittest / example that shows the difference in a minimal way).

Can you encode your more-concrete example here, and add that we should write a test exercising this difference? (raising to nit)
</blockquote></details>

See 8cbd023a1f37b81a367b6eb6c2f2c49d2d232bb6. Not sure if this is exactly what you were expecting. I'll open a ticket to track it though.
___
*[drake_ros_core/src/ros_publisher_system.cc, line 27 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mng9ry59zet5e4K68dX:-MnmBl-n9UvTT5dG2Bcb:ba6v641) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/src/ros_publisher_system.cc#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit (here and in subscriber) For implementation objects that expose members, I believe we should prefer a `struct` (where members do not end with trailing `_`), or provide mutable accessors.

(My pref is to do a `struct`)

</blockquote></details>

Done in 8cbd023a1f37b81a367b6eb6c2f2c49d2d232bb6.
___
*[drake_ros_core/src/ros_subscriber_system.cc, line 29 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngA67L48T1O7rBVkV0:-MnmBllH0LSA5n7ma17S:ba6v641) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/src/ros_subscriber_system.cc#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Same as above: if you're expose all members as public, consider using `struct`.
</blockquote></details>

Done in 8cbd023a1f37b81a367b6eb6c2f2c49d2d232bb6.
___
*[drake_ros_core/src/subscription.h, line 25 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnfgrPV-T-M2tfWgs7P:-MnmBmSI90oP7wIIDuW6:ba6v641) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/subscription.h#L25)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Same as above - now internal, should be private.
</blockquote></details>

Done in 8cbd023a1f37b81a367b6eb6c2f [...]

2021-11-05 23:00 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 15 of 32 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-MnmK6oK73fsnyBmKyko:b9v0ypf) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Workaround added in 3781f5b18f2328137d11458e69c2bf76f2dfd636. Let's see how it fares. 
</blockquote></details>

Looks like CI is still unhappy :(

---


<!-- Sent from Reviewable.io -->

2021-11-05 23:20 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 15 of 32 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-MnmObto8UxNytnLnCeU:b-twrykm) (no related file):*
> Re-install `python-is-python3`

There we go. Good call.

---


<!-- Sent from Reviewable.io -->

2021-11-05 23:40 UTC, EricCousineau-TRI requested changes
> Reviewed 9 of 17 files at r16.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 24 of 32 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 32 at r16](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKDiv51V7L-KpYH5K:-MnmKDiv51V7L-KpYH5L:bl37q24) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3781f5b18f2328137d11458e69c2bf76f2dfd636/drake_ros_core/include/drake_ros_core/drake_ros.h#L32)):*
> ```objc
>   DrakeRos() : DrakeRos("drake_ros", rclcpp::NodeOptions{}) {}
> 
>   /// A constructor that wraps a `node_name` ROS2 node with `node_options`.
> ```

nit Mixture of docstring styles, `///` and `/** */`. Please prefer one.

(FTR, I prefer simply `/** */` without extra `*` for line prefixes - easier when using dumb text editors).
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.h, line 24 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngP0Lp1zGaBdWesJ5m:-MnmKaku9d_Up5N0JfEp:b-75bqi5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/include/drake_ros_core/drake_ros_interface.h#L24)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Removed `DrakeRosInterface` in 8cbd023a1f37b81a367b6eb6c2f2c49d2d232bb6.
</blockquote></details>





























+bug 






+
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-MnmKrXD8HlAhXvG-Ix8:b-ejbtfw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
> ```cpp
> 
> void DrakeRos::Spin(int timeout_millis) {
>   impl_->executor_->spin_once(std::chrono::milliseconds(timeout_millis));
> ```

Rationale for this is not immediately clear; can you add a comment explaining why you do this? (e.g. "Reflect functionality of what DrakeLcm does" or something like that?)

Also, does `timeout_millis` still make sense in this case?
___
*[drake_ros_core/src/ros_interface_system.cc, line 45 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mnfgn3X-2nlyGnYE7wm:-MnmLOgj7ttfDu5YO3tt:blxqwyc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/ros_interface_system.cc#L45)):*
> [...] in a non-blocking way [...]

I believe `lcm.handle()` should execute in the calling thread, so it will block based on callbacks?
___
*[drake_ros_core/src/ros_interface_system.cpp, line 49 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngL7A0D7oKhcyw95Dn:-MnmLCIWBeLOCrDH1-oz:b-tfxbsd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/581b156ce3444168c904c9383472410199beb5d1/drake_ros_core/src/ros_interface_system.cpp#L49)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

See 8cbd023a1f37b81a367b6eb6c2f2c49d2d232bb6. Not sure if this is exactly what you were expecting. I'll open a ticket to track it though.
</blockquote></details>

OK I think that about sums it up. We can always refine the goal in the issue.


<!-- Sent from Reviewable.io -->

2021-11-08 13:47 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 17 of 32 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 32 at r16](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKDiv51V7L-KpYH5K:-Mnzkca77hPRZpF_0NgB:b-2k5db9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/3781f5b18f2328137d11458e69c2bf76f2dfd636/drake_ros_core/include/drake_ros_core/drake_ros.h#L32)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Mixture of docstring styles, `///` and `/** */`. Please prefer one.

(FTR, I prefer simply `/** */` without extra `*` for line prefixes - easier when using dumb text editors).
</blockquote></details>

Argh, that's `rclcpp` style creeping in. Fixed in 1f577647ad1f02a7668883a63460811a3c4861da to match Drake's style.
___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.h, line 24 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngP0Lp1zGaBdWesJ5m:-Mnzn9OGBpnrRtkwyP23:bivb0jv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/include/drake_ros_core/drake_ros_interface.h#L24)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>





























+bug 






+
</blockquote></details>

Not sure I follow you here. Where did you spot a bug?
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-MnzlPhT0eWTtNMOBI10:b-wn8hiy) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
> can you add a comment explaining why you do this? 

Done in c919efdd42f174f805e6ab3ce7398021bb4db856.

> Also, does timeout_millis still make sense in this case?

To match `DrakeLcm::HandleSubscriptions`, for sure. For our particular use case, in which we provide a zero timeout, one can argue that it is redundant.
___
*[drake_ros_core/src/ros_interface_system.cc, line 45 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mnfgn3X-2nlyGnYE7wm:-MnzkFll4gpblMxpYRcb:bn8nthp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/ros_interface_system.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> [...] in a non-blocking way [...]

I believe `lcm.handle()` should execute in the calling thread, so it will block based on callbacks?


</blockquote></details>

Yeah. I meant that the executor/scheduler/dispatcher itself will not block waiting for subscriptions to handle. Whether subscriptions callbacks block or not is beyond its control.


<!-- Sent from Reviewable.io -->

2021-11-08 13:58 UTC, EricCousineau-TRI requested changes
> Reviewed 6 of 17 files at r16, 7 of 7 files at r18.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 30 of 32 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

___
*[drake_ros_core/include/drake_ros_core/drake_ros_interface.h, line 24 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngP0Lp1zGaBdWesJ5m:-Mnznyz65MQpOpIotwql:b-agjho2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/include/drake_ros_core/drake_ros_interface.h#L24)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Not sure I follow you here. Where did you spot a bug?
</blockquote></details>

Ah, jeepers, sorry :( I think that was me randomly middle clicking.
Resolving.
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-MnzoFuhAK2CWpEPwQ_t:bmo03pw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

> can you add a comment explaining why you do this? 

Done in c919efdd42f174f805e6ab3ce7398021bb4db856.

> Also, does timeout_millis still make sense in this case?

To match `DrakeLcm::HandleSubscriptions`, for sure. For our particular use case, in which we provide a zero timeout, one can argue that it is redundant.
</blockquote></details>

If it is redundant, can we remove it? (I'm not sure what it does if it is indeed redundant)
___
*[drake_ros_core/src/ros_publisher_system.cc, line 29 at r18](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnzoWIb32ah2-eZTrYT:-MnzoWIb32ah2-eZTrYU:bz6yzw9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c919efdd42f174f805e6ab3ce7398021bb4db856/drake_ros_core/src/ros_publisher_system.cc#L29)):*
> ```cpp
> struct RosPublisherSystem::Impl {
>   // Interface for message (de)serialization.
>   std::unique_ptr<SerializerInterface> serializer_;
> ```

(here and elsewhere) Members of `struct` should not end with `_`:
https://drake.mit.edu/styleguide/cppguide.html#Variable_Names
___
*[drake_ros_core/src/ros_subscriber_system.cc, line 51 at r18](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnzopQp0AWmdMxZTDHd:-MnzopQp0AWmdMxZTDHe:by88b41) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c919efdd42f174f805e6ab3ce7398021bb4db856/drake_ros_core/src/ros_subscriber_system.cc#L51)):*
> ```cpp
> struct RosSubscriberSystem::Impl {
>   // Interface for message (de)serialization.
>   std::unique_ptr<SerializerInterface> serializer_;
> ```

Struct members should not end with `_` (same as above)
___
*[drake_ros_core/src/python_bindings/drake_ros_core.cc, line 49 at r18](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnzozfpEnXj05hv7em1:-MnzozfpEnXj05hv7em2:box79w3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c919efdd42f174f805e6ab3ce7398021bb4db856/drake_ros_core/src/python_bindings/drake_ros_core.cc#L49)):*
> ```cpp
>   py::module::import("pydrake.multibody.plant");
> 
>   py::class_<DrakeRos>(m, "DrakeRos");
> ```

nit These Python objects are missing C++ docstrings.

It'd probably be way too much of a pain to manually sync, and too much work at this point to teach `mkdoc` how to function here.

Can you add a TODO to that effect?

FYI Regarding docstrings: https://drake.mit.edu/doxygen_cxx/group__python__bindings.html#PydrakeDoc
___
*[drake_ros_core/test/test_pub_sub.cc, line 81 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngNOg_52C9SQBHs2vC:-MnzpMCq5CnRnwUBBFAU:bneh0vf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/test/test_pub_sub.cc#L81)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

It has to, it's an end-to-end test. `publisher` publishes a message to the "in" topic, the subscriber system receives the message and sets its output port, the publisher system gets it from its input port and publishes it to the "out" topic for `subscription` to receive it. We're not testing the integrity of the data though.
</blockquote></details>

Ah, missed that part.

That being said, I think we should see the integrity. As it stands, I believe you'll only see the last-published message `num_msgs` of times.

We should at least encode that more explicitly (e.g. add an "index" field to whatever message type will be used here).


<!-- Sent from Reviewable.io -->

2021-11-08 13:58 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 30 of 32 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI, @hidmic, and @IanTheEngineer)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MncnURI9wr-JeRj8Ivi:-MnzpyFyENCwaX-FaLsc:b3dn7sy) (no related file):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

> Re-install `python-is-python3`

There we go. Good call.
</blockquote></details>

OK Sweet! Just saw that CI passed.

---


<!-- Sent from Reviewable.io -->

2021-11-08 16:07 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 30 of 32 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-Mnzsqi8EBMK-FTWSPKU:b-c66sx6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

If it is redundant, can we remove it? (I'm not sure what it does if it is indeed redundant)
</blockquote></details>

Looking at `RobotLocomotion/drake`, non-zero timeouts when handle LCM subscriptions seem to be there only to support https://github.com/RobotLocomotion/drake/blob/e59b7fc18dbe80b827d07e4a3283a0c87eda7021/lcm/drake_lcm_interface.cc#L21-L30. If we don't think we'll ever want that, we can remove the timeout and simply `spin_some(0)`.
___
*[drake_ros_core/src/ros_publisher_system.cc, line 29 at r18](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnzoWIb32ah2-eZTrYT:-Mnzse1411NKgCrEptGy:b4tlmtz) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c919efdd42f174f805e6ab3ce7398021bb4db856/drake_ros_core/src/ros_publisher_system.cc#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(here and elsewhere) Members of `struct` should not end with `_`:
https://drake.mit.edu/styleguide/cppguide.html#Variable_Names
</blockquote></details>

Done in 3b132ef365e6d0d6cbd514cc26f71c0ca6228af1
___
*[drake_ros_core/src/ros_subscriber_system.cc, line 51 at r18](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnzopQp0AWmdMxZTDHd:-Mnzsf3q9t7kCAlBxvqN:b4tlmtz) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c919efdd42f174f805e6ab3ce7398021bb4db856/drake_ros_core/src/ros_subscriber_system.cc#L51)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Struct members should not end with `_` (same as above)
</blockquote></details>

Done in 3b132ef365e6d0d6cbd514cc26f71c0ca6228af1
___
*[drake_ros_core/src/python_bindings/drake_ros_core.cc, line 49 at r18](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnzozfpEnXj05hv7em1:-MnzslPc0MfK7PzJ2bix:bjr0a77) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c919efdd42f174f805e6ab3ce7398021bb4db856/drake_ros_core/src/python_bindings/drake_ros_core.cc#L49)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit These Python objects are missing C++ docstrings.

It'd probably be way too much of a pain to manually sync, and too much work at this point to teach `mkdoc` how to function here.

Can you add a TODO to that effect?

FYI Regarding docstrings: https://drake.mit.edu/doxygen_cxx/group__python__bindings.html#PydrakeDoc
</blockquote></details>

Done in f4853a556d15288a8af32db97642c3d3894c9ce7
___
*[drake_ros_core/test/test_pub_sub.cc, line 81 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngNOg_52C9SQBHs2vC:-Mnzsn9jAI9eWFco5BAc:bfjvydb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/test/test_pub_sub.cc#L81)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, missed that part.

That being said, I think we should see the integrity. As it stands, I believe you'll only see the last-published message `num_msgs` of times.

We should at least encode that more explicitly (e.g. add an "index" field to whatever message type will be used here).
</blockquote></details>

Ahh, good point. This actually uncovered a little synchronization issue. Fixed in c20e2b5b8b103c6060bcae2c479611445cfda66d. 


<!-- Sent from Reviewable.io -->

2021-11-09 16:56 UTC, IanTheEngineer approved these changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Thanks for the updates, @hidmic . The API threshold between public and private seems much clearer. 

> Reviewed 1 of 1 files at r17, 7 of 7 files at r19.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-:-Mo4XuneDKcbqGSP2-Ph:b-p6vooz)* status: all files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[drake_ros_core/include/drake_ros_core/ros_publisher_system.h, line 37 at r19](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo4NzTDAfLwkqYEzNh9:-Mo4NzTDAfLwkqYEzNhA:bzgjmh5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c20e2b5b8b103c6060bcae2c479611445cfda66d/drake_ros_core/include/drake_ros_core/ros_publisher_system.h#L37)):*
> ```objc
>  public:
>   /** Instantiates a publisher system for a given ROS message type.
>    See `RosPublisherSystem::RosPublisherSystem` documentation for
> ```

FYI: This technique of pointing users to ROS2 documentation is a good one IMO. It shows how thin the interface is abstracting while giving useful info.
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-Mo4PS884MnLV2ZbWx86:bqkl1q5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Looking at `RobotLocomotion/drake`, non-zero timeouts when handle LCM subscriptions seem to be there only to support https://github.com/RobotLocomotion/drake/blob/e59b7fc18dbe80b827d07e4a3283a0c87eda7021/lcm/drake_lcm_interface.cc#L21-L30. If we don't think we'll ever want that, we can remove the timeout and simply `spin_some(0)`.
</blockquote></details>

FYI, I'm fine with leaving both spins at this point, assuming that `spin_once(0)` is a no-op?
___
*[drake_ros_core/test/test_pub_sub.cc, line 81 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngNOg_52C9SQBHs2vC:-Mo4SIcWCKA2g9bbR0a0:bs3hzhf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/test/test_pub_sub.cc#L81)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Ahh, good point. This actually uncovered a little synchronization issue. Fixed in c20e2b5b8b103c6060bcae2c479611445cfda66d. 
</blockquote></details>

Good find and fix. Thanks!


<!-- Sent from Reviewable.io -->

2021-11-09 17:30 UTC, hidmic reviewed
Thanks @iantheengineer. I'll go ahead and cleanup commits so we can get this rebase-merged.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-:-Mo4jvmI8tlMf00gPesp:bv92zbf)* status: all files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-Mo4jrTj9E7KnJa-CPnQ:b-t7s9lh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

FYI, I'm fine with leaving both spins at this point, assuming that `spin_once(0)` is a no-op?
</blockquote></details>

Not necessarily, it might dispatch one item.


<!-- Sent from Reviewable.io -->

2021-11-09 23:22 UTC, EricCousineau-TRI requested changes
> Reviewed 3 of 7 files at r19, 1 of 3 files at r20, 2 of 2 files at r21.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 11 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

___
*[drake_ros_core/test/test_pub_sub.py, line 63 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5wxYp5D5uGMf2vWuj:-Mo5wxYp5D5uGMf2vWuk:ba7ylvh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/test/test_pub_sub.py#L63)):*
> ```Python
> 
>     # Create subscription listening to publisher system
>     num_msgs = 5
> ```

(Same issues as above C++ code)
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 33 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5u-hx-0yvlidO9nQe:-Mo5u-hyCUYDUzoY861y:b-6dxdhl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/include/drake_ros_core/drake_ros.h#L33)):*
> ```objc
> 
>   /** A constructor that wraps a `node_name` ROS2 node with `node_options`.
>    See `rclcpp::Node` documentation for further reference on arguments.
> ```

nit `Node` doesn't seem very comprehensive in terms of its overview, esp. in terms of below nit ("what is work?").

Can you refer to Executor as well?
https://docs.ros2.org/galactic/api/rclcpp/classrclcpp_1_1Executor.html#details
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 45 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5rUzC1OGUeSR0wA3F:-Mo5rUzC1OGUeSR0wA3G:bezwszj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/include/drake_ros_core/drake_ros.h#L45)):*
> ```objc
>   rclcpp::Node* get_mutable_node() const;
> 
>   /** Spins the underlying ROS2 node, dispatching all available work.
> ```

nit Unclear what "available work" means exactly.

Can you add a brief inline of Executor's definition of "work"?
https://docs.ros2.org/galactic/api/rclcpp/classrclcpp_1_1Executor.html#details
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 48 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5uFpm1I-SbH8bNVXW:-Mo5uFpn65AuH7K-pDqR:bxirtn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/include/drake_ros_core/drake_ros.h#L48)):*
> ```objc
>    @param[in] timeout_millis Timeout, in milliseconds.
>      If timeout is less than 0, the call will block indefinitely
>      until some work has been dispatched. If timeout is 0, the call
> ```

"until some work has been dispatched"  is unclear; will this wait for work to queue up, or only for it to be executed?

Consider rewording a bit (assuming my mental model is correct):

```
If timeout is less than 0, this will wait indefinitely until work has been queued and executed.
If timeout is 0, the call will not wait for new work, and simply execute all available work.
If timeout is larger than zero, the call will wait for and execute new and available work up the given timeout.

@see rclcpp::spin_some and rclcpp::spin_once
```
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 48 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo6-PAr7aNVT6kaZnoG:-Mo6-PAr7aNVT6kaZnoH:b-mus2qv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/include/drake_ros_core/drake_ros.h#L48)):*
> ```objc
>    @param[in] timeout_millis Timeout, in milliseconds.
>      If timeout is less than 0, the call will block indefinitely
>      until some work has been dispatched. If timeout is 0, the call
> ```

In writing prior comment, I'm confused as to why `< 0` is allowed. I don't really see that in the docs.

Can we instead just require `timeout_millis >= 0`.
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-Mo5x8De3bV8cPP9BxaS:b-phf247) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Not necessarily, it might dispatch one item.
</blockquote></details>

Yeah, can we just reduce this to `executor->spin_some(timeout_thing)` or `spin_all`?
Multiple calls confuse me quite a bit.
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r18](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5xFOe5SFypPZtnfr-:-Mo5xFOf47zWLeWcNt7X:b-ct6iwv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c919efdd42f174f805e6ab3ce7398021bb4db856/drake_ros_core/src/drake_ros.cc#L72)):*
> ```cpp
> 
> void DrakeRos::Spin(int timeout_millis) {
>   // To match `DrakeLcm::HandleSubscriptions()`'s behavior, in the following
> ```

This seems like a contract; can you hoist this to public docstring?
___
*[drake_ros_core/src/ros_interface_system.cc, line 45 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mnfgn3X-2nlyGnYE7wm:-Mo5mXD45FFcQa68BSPj:b-43in0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/ros_interface_system.cc#L45)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Yeah. I meant that the executor/scheduler/dispatcher itself will not block waiting for subscriptions to handle. Whether subscriptions callbacks block or not is beyond its control.
</blockquote></details>

Thanks for explanation! That being said, I'm still very confused about nuance between `spin_once` vs. `spin_all`. My read on the docs haven't shed much light.

What's the difference between `spin_some(0)` and `spin_all(0)`?
My guess is `spin_some(0)` first blocks for new work, while `spin_all(0)` doesn't?
___
*[drake_ros_core/test/test_pub_sub.cc, line 81 at r15](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MngNOg_52C9SQBHs2vC:-Mo5kPNI5JKK1xZNGb0c:b1qxyzq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/cf92b8ee1b793b7d5a06fca28de966fa8b30b14c/drake_ros_core/test/test_pub_sub.cc#L81)):*
<details><summary><i>Previously, IanTheEngineer (Ian McMahon) wrote…</i></summary><blockquote>

Good find and fix. Thanks!
</blockquote></details>

OK Looks better!
___
*[drake_ros_core/test/test_pub_sub.cc, line 45 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5kf5s8PZZ06Jiwirb:-Mo5kf5s8PZZ06Jiwirc:buggpao) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/test/test_pub_sub.cc#L45)):*
> ```cpp
>   auto ros_interface_system =
>       builder.AddSystem<RosInterfaceSystem>(std::make_unique<DrakeRos>());
>   auto ros_subscriber_system =
> ```

nit Names here are a bit confusing to distinguish connections.

Can you qualify names a bit more? Suggestions:

- Drop `ros_` prefix, since you don't use `ros_publisher` and `ros_subscriber` for direct entities
- Denote what message it's connecting to in the variable, e.g. `direct_pub_in -> system_sub_in -> system_pub_out -> direct_sub_out`, renaming `rx_callback` to `rx_callback_direct_sub_in`,  `rx_msgs` to `rx_msgs_direct_sub_in`, etc.
___
*[drake_ros_core/test/test_pub_sub.cc, line 78 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5kUKm0NKPK76m_oIj:-Mo5kUKm0NKPK76m_oIk:b-runsp8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/test/test_pub_sub.cc#L78)):*
> ```cpp
>     // Cope with lack of synchronization between subscriber
>     // and publisher systems by ignoring duplicate messages.
>     if (rx_msgs.empty() || rx_msgs.back()->uint64_value != msg->uint64_value) {
> ```

It was initially unclear why this subscriber would see duplicate messages, then I realized it's from a publis [...]

2021-11-11 00:21 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 27 of 32 files reviewed, 11 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_core/test/test_pub_sub.py, line 63 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5wxYp5D5uGMf2vWuj:-MoAXcYwBtcsoMn_n8_c:btlgzoq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/test/test_pub_sub.py#L63)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(Same issues as above C++ code)
</blockquote></details>

See b56f0736c8ae36c2e969e20eaf670ddcf99de86d. Same word of caution as above.
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 33 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5u-hx-0yvlidO9nQe:-MoA_N0i1ZnAPyAKOSVG:b-q1zdkc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/include/drake_ros_core/drake_ros.h#L33)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `Node` doesn't seem very comprehensive in terms of its overview, esp. in terms of below nit ("what is work?").

Can you refer to Executor as well?
https://docs.ros2.org/galactic/api/rclcpp/classrclcpp_1_1Executor.html#details
</blockquote></details>

I can refer to the Executor class but it is disconnected from this particular constructor docs. How about adding it to the class docstring? See 81859093cbe2a16529b2690f19c122c3b3fb7fb4
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 45 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5rUzC1OGUeSR0wA3F:-MoAbqC62XhIekH1-5xE:b-ie35nq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/include/drake_ros_core/drake_ros.h#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear what "available work" means exactly.

Can you add a brief inline of Executor's definition of "work"?
https://docs.ros2.org/galactic/api/rclcpp/classrclcpp_1_1Executor.html#details
</blockquote></details>

Good idea. See 81859093cbe2a16529b2690f19c122c3b3fb7fb4
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 48 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo6-PAr7aNVT6kaZnoG:-MoAep7C4MLN_rPPkSlx:b-rtwb9u) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/include/drake_ros_core/drake_ros.h#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

In writing prior comment, I'm confused as to why `< 0` is allowed. I don't really see that in the docs.

Can we instead just require `timeout_millis >= 0`.
</blockquote></details>

`spin_once` allows it, but I see LCM does not. I'll mimic what LCM does when `timeout_millis < 0`. See 81859093cbe2a16529b2690f19c122c3b3fb7fb4.
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 48 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5uFpm1I-SbH8bNVXW:-MoBMQ-99gzt3b2gcQwB:biepf2g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/include/drake_ros_core/drake_ros.h#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

"until some work has been dispatched"  is unclear; will this wait for work to queue up, or only for it to be executed?

Consider rewording a bit (assuming my mental model is correct):

```
If timeout is less than 0, this will wait indefinitely until work has been queued and executed.
If timeout is 0, the call will not wait for new work, and simply execute all available work.
If timeout is larger than zero, the call will wait for and execute new and available work up the given timeout.

@see rclcpp::spin_some and rclcpp::spin_once
```
</blockquote></details>

Done in 81859093cbe2a16529b2690f19c122c3b3fb7fb4
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-MoAQ9sB4att2G77TaJU:b54l2z8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, can we just reduce this to `executor->spin_some(timeout_thing)` or `spin_all`?
Multiple calls confuse me quite a bit.
</blockquote></details>

Thing is, neither `spin_some(timeout)` nor `spin_all(timeout)` with `timeout > 0` will wait for work if there's none available. That deviates from `DrakeLcm::HandleSubscriptions()` behavior. If you guys are happy with that, I'll remove the `spin_once` invocation.
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r18](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5xFOe5SFypPZtnfr-:-MoAQ8Au--jAdPj8w8Fl:bkej4ud) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/c919efdd42f174f805e6ab3ce7398021bb4db856/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This seems like a contract; can you hoist this to public docstring?
</blockquote></details>

Sounds good. Done in 81859093cbe2a16529b2690f19c122c3b3fb7fb4.
___
*[drake_ros_core/src/ros_interface_system.cc, line 45 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mnfgn3X-2nlyGnYE7wm:-MoARlsO5ZiVMje0jEXh:b47iewf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/ros_interface_system.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Thanks for explanation! That being said, I'm still very confused about nuance between `spin_once` vs. `spin_all`. My read on the docs haven't shed much light.

What's the difference between `spin_some(0)` and `spin_all(0)`?
My guess is `spin_some(0)` first blocks for new work, while `spin_all(0)` doesn't?
</blockquote></details>

See https://github.com/ros2/rclcpp/blob/0781ea543cc523aa8ecae266847ab42900e2a1fd/rclcpp/src/rclcpp/executor.cpp#L423-L472.

In short,

- `spin_some(0)` fetches all available work and processes it. It does not wait.
- `spin_all(0)` fetches all available work and processes it. It then repeats that operation until fetching for work yields no work. It does not wait (and thus it will only fetch work more than once if more work arrives while it is processing the previous batch).

I agree docs could be better.
___
*[drake_ros_core/test/test_pub_sub.cc, line 45 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5kf5s8PZZ06Jiwirb:-MoATL--6CbMDdvEDp7A:b-367x3o) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/test/test_pub_sub.cc#L45)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Names here are a bit confusing to distinguish connections.

Can you qualify names a bit more? Suggestions:

- Drop `ros_` prefix, since you don't use `ros_publisher` and `ros_subscriber` for direct entities
- Denote what message it's connecting to in the variable, e.g. `direct_pub_in -> system_sub_in -> system_pub_out -> direct_sub_out`, renaming `rx_callback` to `rx_callback_direct_sub_in`,  `rx_msgs` to `rx_msgs_direct_sub_in`, etc.
</blockquote></details>

Sounds good. Done in b56f0736c8ae36c2e969e20eaf670ddcf99de86d
___
*[drake_ros_core/test/test_pub_sub.cc, line 78 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5kUKm0NKPK76m_oIj:-MoATMsE7s3wIv-94kQi:b-o5j4np) ([raw file](https://github.com/robotlocomotion/dr [...]

2021-11-11 15:41 UTC, EricCousineau-TRI requested changes
> Reviewed 4 of 5 files at r22.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 31 of 32 files reviewed, 8 unresolved discussions (waiting on @hidmic and @IanTheEngineer)

___
*[drake_ros_core/test/test_pub_sub.py, line 85 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEdUkM3k1OVkF1LNgC:-MoEdUkM3k1OVkF1LNgD:bjemo1p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/test/test_pub_sub.py#L85)):*
> ```Python
>         # subscriber system. The drake ros publisher system should not publish
>         # just yet.
>         rclpy.spin_once(node, timeout_sec=0.5)
> ```

nit Why do we want / need such a large timeout here? Can you make this match C++ above? (`timeout = 0`)
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 33 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5u-hx-0yvlidO9nQe:-MoEX9ir-87EbSqlSkeB:buan8po) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/include/drake_ros_core/drake_ros.h#L33)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

I can refer to the Executor class but it is disconnected from this particular constructor docs. How about adding it to the class docstring? See 81859093cbe2a16529b2690f19c122c3b3fb7fb4
</blockquote></details>

OK Looks good to me!
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 34 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEY4Yx3AoUfuUAwRZC:-MoEY4Yx3AoUfuUAwRZD:b960tke) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/include/drake_ros_core/drake_ros.h#L34)):*
> ```objc
>  public:
>   /** A constructor that wraps a "drake_ros" ROS node with default options. */
>   DrakeRos() : DrakeRos("drake_ros", rclcpp::NodeOptions{}) {}
> ```

Unclear why we want a default node name here.

Is it possible to remove this? (or was there a prior discussion motivating it?)
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-MoEUk1Z07qa63P146OD:b-x3jie8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Thing is, neither `spin_some(timeout)` nor `spin_all(timeout)` with `timeout > 0` will wait for work if there's none available. That deviates from `DrakeLcm::HandleSubscriptions()` behavior. If you guys are happy with that, I'll remove the `spin_once` invocation.
</blockquote></details>

Gotcha. Yeah, can you remove `spin_once`? And perhaps use `spin_all()` instead of `spin_once()`?

I believe LCM usages are more akin to `spin_all()`, in that more work could be queued up while the following loop can be running:
https://github.com/RobotLocomotion/drake/blob/bb3d0ffc1360123b4c9096274b6cbdc28c9335ef/lcm/drake_lcm.cc#L290-L297
___
*[drake_ros_core/src/drake_ros.cc, line 42 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXQ2w-DBP0RiDofUX:-MoEXQ2x0Wmxn4p4V9ZF:b-7d61bj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/src/drake_ros.cc#L42)):*
> ```cpp
>   impl_->context = node_options.context();
>   if (impl_->context->is_valid()) {
>     // Context is being init/shutdown outside of this system
> ```

nit "has been init'd and will be shutdown"

(or perhaps remove given below?)
___
*[drake_ros_core/src/drake_ros.cc, line 46 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXW5g5RCoN_B4_Je0:-MoEXW5g5RCoN_B4_Je1:b6hsgoc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/src/drake_ros.cc#L46)):*
> ```cpp
>   } else {
>     // This system will init/shutdown the context
>     impl_->externally_init = false;
> ```

While this feature ("auto-init") seems useful, it also seems like it'll cause confusing down the line.

Can we instead just require that `rcl*::init()` (or any valid invocation similar that) has already been called?
e.g. in class doc overview:
```
@pre Requires that rcl* context has been initialized.
```
___
*[drake_ros_core/src/drake_ros.cc, line 52 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXm9u4yUw3saofCO1:-MoEXm9u4yUw3saofCO2:b-6pjt4l) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/src/drake_ros.cc#L52)):*
> ```cpp
>   impl_->node.reset(new rclcpp::Node(node_name, node_options));
> 
>   // TODO(sloretz) allow passing in executor options
> ```

BTW It seems like the only need for sync for the executor is `context`. If that's the case, then we should just let users pass in an executor instance itself?
___
*[drake_ros_core/src/ros_interface_system.cc, line 45 at r14](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mnfgn3X-2nlyGnYE7wm:-MoEVTL47jNeDaxZhDSL:b-6meq50) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/9ea1e426005ab4ad684415e7bbd543126d2f33cc/drake_ros_core/src/ros_interface_system.cc#L45)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

See https://github.com/ros2/rclcpp/blob/0781ea543cc523aa8ecae266847ab42900e2a1fd/rclcpp/src/rclcpp/executor.cpp#L423-L472.

In short,

- `spin_some(0)` fetches all available work and processes it. It does not wait.
- `spin_all(0)` fetches all available work and processes it. It then repeats that operation until fetching for work yields no work. It does not wait (and thus it will only fetch work more than once if more work arrives while it is processing the previous batch).

I agree docs could be better.
</blockquote></details>

OK That's starting to make more sense.
___
*[drake_ros_core/test/test_pub_sub.cc, line 78 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5kUKm0NKPK76m_oIj:-MoEVb71By1tfEucflTJ:be3x3r0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/test/test_pub_sub.cc#L78)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Fair enough. See b56f0736c8ae36c2e969e20eaf670ddcf99de86d. 

As a word of caution, I'd generally avoid writing tests in ROS as if there was a deterministic, sequentially-consistent order of computation. There's not. Transport latency is not constant nor bound. There are reasonable expectations to be had, but those depend on multiple, varying factors (middleware impl., OS scheduler, netstack load, CPU load). A 1 sec publishing period will definitely make test flakes very unlikely (but not impossible e.g. think of some middleware  impl. thread not getting scheduled on time for whatever reason).
</blockquote></details>

OK Gotcha. In practice, though, I'm not sure if we've seen a huge issue of LCM pub/sub via local loopback when within the same process, at least not for small "toy" payloads.
___
*[drake_ros_core/test/test_pub_sub.cc, line 87 at r21](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-Mo5pdv18qcE3dJJCb5J:-MoEdG7fARQjU7n3w-9X:b-zfh9kw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/4842d7604a8403f66fe85d6f57ea0f69e62bccf6/drake_ros_core/test/test_pub_sub.cc#L87)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

No need to spin multiples times after b56f0736c8ae36c2e969e20eaf670ddcf99de86d
</blockquote></details>

OK Awesome, thanks!
___
*[drake_ros_core/test/test_pub_sub.cc, line 42 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXyRQ8KIXGsE_YBgc:-MoEXyRQ8KIXGsE_YBgd:bnzwftj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2 [...]

2021-11-11 17:17 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 26 of 32 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @IanTheEngineer)

___
*[drake_ros_core/test/test_pub_sub.py, line 85 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEdUkM3k1OVkF1LNgC:-MoEnsKRCWkrDx1MbpaC:b-2wkztx) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/test/test_pub_sub.py#L85)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Why do we want / need such a large timeout here? Can you make this match C++ above? (`timeout = 0`)
</blockquote></details>

Argh, that's a leftover of a debugging session. Removed in 8e23c115cf635f2c42f319b0c5f45bf6dba335a9.
___
*[drake_ros_core/include/drake_ros_core/drake_ros.h, line 34 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEY4Yx3AoUfuUAwRZC:-MoEo1gs5ImpsKb6hcU2:bf3ep2e) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/include/drake_ros_core/drake_ros.h#L34)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unclear why we want a default node name here.

Is it possible to remove this? (or was there a prior discussion motivating it?)
</blockquote></details>

No prior discussion. Done in 7db7f5808daaae8dba9e97cff4fc70587a19b8d7 
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-MoEoVBz5ftUYeaePee7:b-cxe65g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha. Yeah, can you remove `spin_once`? And perhaps use `spin_all()` instead of `spin_once()`?

I believe LCM usages are more akin to `spin_all()`, in that more work could be queued up while the following loop can be running:
https://github.com/RobotLocomotion/drake/blob/bb3d0ffc1360123b4c9096274b6cbdc28c9335ef/lcm/drake_lcm.cc#L290-L297
</blockquote></details>

`spin_all` does not currently support a zero timeout. Not entirely clear why. Changed in 8836bc42a60a586e9e9c319cad56fc55121de1fa to `spin_some` only. We can submit a ticket upstream and try fight that API contract.
___
*[drake_ros_core/src/drake_ros.cc, line 42 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXQ2w-DBP0RiDofUX:-MoEto5U716I-9NKCAqQ:b-k4bx87) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/src/drake_ros.cc#L42)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "has been init'd and will be shutdown"

(or perhaps remove given below?)
</blockquote></details>

Done in da5dcfbeb894d746e7beaa398d76808c14e5fb2e.
___
*[drake_ros_core/src/drake_ros.cc, line 46 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXW5g5RCoN_B4_Je0:-MoEslpABnNH9sRPQ2Fu:bpepe8o) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/src/drake_ros.cc#L46)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

While this feature ("auto-init") seems useful, it also seems like it'll cause confusing down the line.

Can we instead just require that `rcl*::init()` (or any valid invocation similar that) has already been called?
e.g. in class doc overview:
```
@pre Requires that rcl* context has been initialized.
```
</blockquote></details>

Hmm, I think that won't work for Python code. While both `rclpy` and `rclcpp` contexts eventually wrap `rcl`'s, they are not thin wrappers nor is `rclpy` a set of bindings for `rclcpp`. We could have a `drake_ros` specific function to perform the initialization though.
___
*[drake_ros_core/src/drake_ros.cc, line 52 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXm9u4yUw3saofCO1:-MoEucKY5yfoXFUKcZPn:b-8yqcha) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/src/drake_ros.cc#L52)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW It seems like the only need for sync for the executor is `context`. If that's the case, then we should just let users pass in an executor instance itself?
</blockquote></details>

There are no Python bindings for `rclcpp` executors. We could allow it in the C++ API though. Does that sound reasonable?
___
*[drake_ros_core/test/test_pub_sub.cc, line 42 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXyRQ8KIXGsE_YBgc:-MoEv1iV9EwZXnP4QGAj:b-lig11q) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/test/test_pub_sub.cc#L42)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Related to below - can you assign this an explicit node name?
</blockquote></details>

Done in 0309ad9316090941abbfc21955b17bb3f7584d19
___
*[drake_ros_core/test/test_pub_sub.cc, line 66 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEVuIDAsWA7ilta99n:-MoErvoO-xwduZwo-xzT:b719q1f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/test/test_pub_sub.cc#L66)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you rename this variable to `direct_ros` or `direct_node`?
</blockquote></details>

Done in 64f560a7aaf3af1af5087539fe762c5527efb75b
___
*[drake_ros_core/test/test_pub_sub.cc, line 66 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEWLon2gtyUsa9xfr9:-MoErwJe-lMYD5Vjm4qQ:b-raeul1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/test/test_pub_sub.cc#L66)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Unclear why this node has a name different than above.
</blockquote></details>

Hmm, not sure what you mean by the above. The one in the C++ test?


<!-- Sent from Reviewable.io -->

2021-11-11 17:46 UTC, EricCousineau-TRI requested changes
> Reviewed 1 of 7 files at r19, 6 of 6 files at r23.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 1 unresolved discussion (waiting on @hidmic)

___
*[drake_ros_core/test/test_pub_sub.py, line 85 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEdUkM3k1OVkF1LNgC:-MoF4XweDI8hGiQe3lCX:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/test/test_pub_sub.py#L85)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Argh, that's a leftover of a debugging session. Removed in 8e23c115cf635f2c42f319b0c5f45bf6dba335a9.
</blockquote></details>

OK Thanks!
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-MoF5GU24rw2tb6uCVDN:b-5r81wu) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

`spin_all` does not currently support a zero timeout. Not entirely clear why. Changed in 8836bc42a60a586e9e9c319cad56fc55121de1fa to `spin_some` only. We can submit a ticket upstream and try fight that API contract.
</blockquote></details>

OK Odd. Perhaps a TODO for now?
___
*[drake_ros_core/src/drake_ros.cc, line 46 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXW5g5RCoN_B4_Je0:-MoF3qyv1dfdMS4HXQJ8:b-x91m0f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/src/drake_ros.cc#L46)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Hmm, I think that won't work for Python code. While both `rclpy` and `rclcpp` contexts eventually wrap `rcl`'s, they are not thin wrappers nor is `rclpy` a set of bindings for `rclcpp`. We could have a `drake_ros` specific function to perform the initialization though.
</blockquote></details>

Yeah, I prefer explicit initialization over implicit initialization, at least to start.
___
*[drake_ros_core/src/drake_ros.cc, line 52 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXm9u4yUw3saofCO1:-MoF47Vm1dC20XLgOQdn:brwx71p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/src/drake_ros.cc#L52)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

There are no Python bindings for `rclcpp` executors. We could allow it in the C++ API though. Does that sound reasonable?
</blockquote></details>

OK Yup! I'd be fine with that living as a TODO, though.
___
*[drake_ros_core/test/test_pub_sub.cc, line 66 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEWLon2gtyUsa9xfr9:-MoF4Qg2DCW-gNQSU74c:bp2e795) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/test/test_pub_sub.cc#L66)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Hmm, not sure what you mean by the above. The one in the C++ test?
</blockquote></details>

OK Sorry, meant node name. But having it explicitly named makes it clearer.


<!-- Sent from Reviewable.io -->

2021-11-11 18:33 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: all files reviewed, 1 unresolved discussion (waiting on @hidmic)

___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-MoF9uIa-wO4HMY-su_B:btflaai) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Odd. Perhaps a TODO for now?
</blockquote></details>

Oh, right, `spin_all` doesn't allow zero timeouts because that could result in an indefinite wait (if work gets queued up faster or at the exact same pace it gets dequeued). Still, opened to a ticket to foster discussion https://github.com/ros2/rclcpp/issues/1825. See 74f4a80b05085531a0adfa975b434a8679c5c48a.


<!-- Sent from Reviewable.io -->

2021-11-11 20:42 UTC, hidmic reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6)* status: 25 of 32 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[drake_ros_core/src/drake_ros.cc, line 46 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXW5g5RCoN_B4_Je0:-MoFj6zcBzxhXL-5jgaG:b-5gfpyt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/src/drake_ros.cc#L46)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, I prefer explicit initialization over implicit initialization, at least to start.
</blockquote></details>

Done in 471c8c2cd9dbff8c0f7aee31a503ca6418b1b151.
___
*[drake_ros_core/src/drake_ros.cc, line 52 at r22](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoEXm9u4yUw3saofCO1:-MoFj7yN8CSN3hWDZ5RF:bkg1txf) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/b56f0736c8ae36c2e969e20eaf670ddcf99de86d/drake_ros_core/src/drake_ros.cc#L52)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Yup! I'd be fine with that living as a TODO, though.
</blockquote></details>

Done in 471c8c2cd9dbff8c0f7aee31a503ca6418b1b151


<!-- Sent from Reviewable.io -->

2021-11-11 20:55 UTC, EricCousineau-TRI approved these changes
Looks good! I think this is ready to merge - will leave it up to you or Ian.

> Reviewed 7 of 7 files at r25.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-:-MoFm2sH7d8Lx-MfT4Ua:boneryx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hidmic)

___
*[drake_ros_core/test/test_pub_sub.py, line 1 at r25](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MoFlv98Duevscl7DUfI:-MoFlv98Duevscl7DUfJ:bviqnhr) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/471c8c2cd9dbff8c0f7aee31a503ca6418b1b151/drake_ros_core/test/test_pub_sub.py#L1)):*
> ```Python
> # Copyright 2021 Open Source Robotics Foundation, Inc.
> ```

BTW Would be better to see this as `unittest`, but that could be handled in follow-up PR.

In that way, we can show how to write unittests.
___
*[drake_ros_core/src/drake_ros.cc, line 72 at r17](https://reviewable.io/reviews/robotlocomotion/drake-ros/6#-MnmKrXD8HlAhXvG-Ix7:-MoFlelU6i0HfJJf8JwY:b-w196av) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ee290f497abd8921a9f677ade2b6182613109cf0/drake_ros_core/src/drake_ros.cc#L72)):*
<details><summary><i>Previously, hidmic (Michel Hidalgo) wrote…</i></summary><blockquote>

Oh, right, `spin_all` doesn't allow zero timeouts because that could result in an indefinite wait (if work gets queued up faster or at the exact same pace it gets dequeued). Still, opened to a ticket to foster discussion https://github.com/ros2/rclcpp/issues/1825. See 74f4a80b05085531a0adfa975b434a8679c5c48a.
</blockquote></details>

OK Thanks!


<!-- Sent from Reviewable.io -->

2021-12-06 16:39 UTC, merged