BUILD.bazel for drake_ros_core
RobotLocomotion/drake-ros pull request #75
Opened 2022-04-28 00:36 UTC by sloretz

Here's a first pass adding `BUILD.bazel` files for `drake_ros_core`. I'm opening it for feedback. I only added the C++ libraries for now.

@IanTheEngineer @EricCousineau-TRI Please take a look.

`test_pub_sub` does not pass. It passes using `CMake` and a local ROS 2 workspace, so maybe the out-of-date ROS 2 archive has an issue. If so,  #71 might resolve it.

2022-04-28 01:16 UTC, EricCousineau-TRI requested changes
First pass done, PTAL!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-:-N0hjKTT7RCVW_Z53GJ5:b-v6scke)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgXaG3rfCvmRRcIyW:-N0hgXaG3rfCvmRRcIyX:btcxhpw) (no related file):*
When do you think it'd be appropriate to add this to CI?

And is there a tracking issue that describes this? If not, can you add that and add in when you think CI, Python targets, etc. would be provided?

---
___
*[`drake_ros_core/BUILD.bazel` line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgBHR3OG3V8xVUnDn:-N0hgBHR3OG3V8xVUnDo:bxnx4ga) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/BUILD.bazel#L17)):*
> ```Starlark
> load("@ros2//:ros_cc.bzl", "ros_cc_test")
> 
> cc_library(
> ```

nit We may want these more granular at some point.

Can you add TODO to that effect?
Let's hold off for now, b/c in Anzu we will want both static- and shared-library variants if we want to use Python bindings - which I *very* much do!!!
___
*[`drake_ros_core/BUILD.bazel` line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgOl8AS6JgRZdtxPh:-N0hgOl948vlCxTZPOT1:bvehmg3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/BUILD.bazel#L31)):*
> ```Starlark
> )
> 
> ros_cc_test(
> ```

Does this use `rmw_isolation`?
___
*[`drake_ros_core/BUILD.bazel` line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgQzE87RjggHFyhrE:-N0hgQzE87RjggHFyhrF:bvehmg3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/BUILD.bazel#L48)):*
> ```Starlark
> 
> ros_cc_test(
>   name = "test_drake_ros",
> ```

Does this use `rmw_isolation`?
___
*[`drake_ros_core/WORKSPACE` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgiqYBWhfuxf53Wi7:-N0hgiqYBWhfuxf53Wi8:brjgrv8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/WORKSPACE#L41)):*
> ```Starlark
> DRAKE_COMMIT = "master"
> DRAKE_CHECKSUM = ""
> http_archive(
> ```

Meep! This will build Drake from source!!! (Timing will be OK-ish for C++, but will be very slow for Python bindings)
Can you instead use `@drake//:drake_shared_library` for now?

And not only for build time, but this will cause ODR violations for Python bindings if we mix static- and dynamically-linked targets.
(Drake's granular targets in Bazel are generally meant for static linking.)

In Anzu, we have the notion of a `:shared_library` roll-up target that recompiles together various (static-by-default) targets into a shared library.
Unfortunately to recompile, but that's the easiest thing, as Bazel doesn't yet have great affordance for handling diamond dependency stuff.
See example extracted here:
https://github.com/EricCousineau-TRI/repro/tree/5bc0e37a371239c096b0130c0c2ef4eca48153d8/drake_stuff/drake_downstream_pybind

My suggested course of action:

- Can you PR a sample `cc_test` example using `//:drake_shared_library` here? https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_bazel_installed
  For example, you can use transcribe `find_resource_test.py` into C++.
- For the purpose of CI, can you use shared library target here, and use a binary version of Drake?
- Can you add a TODO to provide the option for granular static targets? (for source-and-static Drake targets)?

Does this make sense? I can explain it to you next meeting if you'd like.


<!-- Sent from Reviewable.io -->

2022-05-02 23:42 UTC, sloretz reviewed
@ericcousineau-tri I'm having some trouble getting the Eigen include dirs from `@drake//:drake_shared_library`. Is this a Drake bug?

With an up to date `drake` source checkout I installed the prereqs

```console
$ ./setup/install_prereqs.sh
```

I have libeigen3-dev installed

```console
$ apt list --installed | grep libeigen

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libeigen3-dev/focal,now 3.3.7-2 all [installed]
```

And it installs its headers to `/usr/include/eigen3`

```console
$ dpkg -L libeigen3-dev | grep Core$
/usr/include/eigen3/Eigen/Core
/usr/include/eigen3/Eigen/SparseCore
/usr/include/eigen3/Eigen/src/Core
/usr/include/eigen3/Eigen/src/SparseCore
```


I made this MRE

<details><summary>mre.cpp</summary>

```C++
#include <drake/common/default_scalars.h>
```
</details>

<details><summary>WORKSPACE</summary>

```python
workspace(name = "drake_eigen_mre")

# Drake artifacts requires rules_python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz",
    sha256 = "aa96a691d3a8177f3215b14b0edc9641787abaaa30363a080165d06ab65e1161",
)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

# Depend on pre-built Drake
DRAKE_RELEASE = "latest"
DRAKE_CHECKSUM = ""
OS_CODENAME = "focal"

http_archive(
    name = "drake_artifacts",
    url = "https://drake-packages.csail.mit.edu/drake/nightly/drake-{}-{}.tar.gz".format(DRAKE_RELEASE, OS_CODENAME),
    sha256 = DRAKE_CHECKSUM,
    strip_prefix = "drake/",
    build_file_content = "#",
)

load("@drake_artifacts//:share/drake/repo.bzl", "drake_repository")

drake_repository(name = "drake")
```
</details>

<details><summary>BUILD.bazel</summary>

```python
cc_library(
  name = "drake_eigen_mre",
  srcs = glob(["mre.cpp"]),
  deps = [
    "@drake//:drake_shared_library",
  ],
  visibility = ["//visibility:public"]
)
```
</details>

That include directory doesn't get passed to the compiler. Does bazel support transitive include directories? If so, is something saying to pass on that include directory missing from the `drake_shared_library` target?

```console
$ bazel build //... --verbose_failures
DEBUG: Rule 'drake_artifacts' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "af60d2332293f05ae61cac3cc6e27ed9b4801805968badc2d2268bf4018833dc"
DEBUG: Repository drake_artifacts instantiated at:
  /home/osrf/ws/drake/src/drake_eigen_mre/WORKSPACE:18:13: in <toplevel>
Repository rule http_archive defined at:
  /home/osrf/.cache/bazel/_bazel_osrf/f3883443eb54426941fb10f0ff357b1d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed target //:drake_eigen_mre (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/osrf/ws/drake/src/drake_eigen_mre/BUILD.bazel:1:11: Compiling mre.cpp failed: (Exit 1): gcc failed: error executing command 
  (cd /home/osrf/.cache/bazel/_bazel_osrf/f3883443eb54426941fb10f0ff357b1d/sandbox/linux-sandbox/2/execroot/drake_eigen_mre && \
  exec env - \
    LD_LIBRARY_PATH=/.singularity.d/libs \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/_objs/drake_eigen_mre/mre.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/_objs/drake_eigen_mre/mre.pic.o' -fPIC -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/drake -iquote bazel-out/k8-fastbuild/bin/external/drake -Ibazel-out/k8-fastbuild/bin/external/drake/_virtual_includes/.drake_headers -Ibazel-out/k8-fastbuild/bin/external/drake/_virtual_includes/.fmt_headers -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c mre.cpp -o bazel-out/k8-fastbuild/bin/_objs/drake_eigen_mre/mre.pic.o)
# Configuration: d762925729a1e18d6a8bccbddcd1576e4dff3530a38be61ea64828e89bea4b8e
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
In file included from bazel-out/k8-fastbuild/bin/external/drake/_virtual_includes/.drake_headers/drake/common/default_scalars.h:3,
                 from mre.cpp:1:
bazel-out/k8-fastbuild/bin/external/drake/_virtual_includes/.drake_headers/drake/common/autodiff.h:12:10: fatal error: Eigen/Core: No such file or directory
   12 | #include <Eigen/Core>
      |          ^~~~~~~~~~~~
compilation terminated.
Target //:drake_eigen_mre failed to build
INFO: Elapsed time: 0.154s, Critical Path: 0.04s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-:-N166lAS2EBbjoLhlJx1:bidmpae)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)



<!-- Sent from Reviewable.io -->

2022-05-03 01:20 UTC, EricCousineau-TRI reviewed
Ah, nuts. This mode (binary tarball + Bazel C++ targets) may have a couple of more edges than expected.
Posted to Drake Slack for advice.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-:-N16VC1mEGosVPSg9-rP:bfkn6zc)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)



<!-- Sent from Reviewable.io -->

2022-05-03 01:54 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros_core/WORKSPACE` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgiqYBWhfuxf53Wi7:-N16awYz87AGrGZzC9-F:bh7b32e) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/WORKSPACE#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Meep! This will build Drake from source!!! (Timing will be OK-ish for C++, but will be very slow for Python bindings)
Can you instead use `@drake//:drake_shared_library` for now?

And not only for build time, but this will cause ODR violations for Python bindings if we mix static- and dynamically-linked targets.
(Drake's granular targets in Bazel are generally meant for static linking.)

In Anzu, we have the notion of a `:shared_library` roll-up target that recompiles together various (static-by-default) targets into a shared library.
Unfortunately to recompile, but that's the easiest thing, as Bazel doesn't yet have great affordance for handling diamond dependency stuff.
See example extracted here:
https://github.com/EricCousineau-TRI/repro/tree/5bc0e37a371239c096b0130c0c2ef4eca48153d8/drake_stuff/drake_downstream_pybind

My suggested course of action:

- Can you PR a sample `cc_test` example using `//:drake_shared_library` here? https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_bazel_installed
  For example, you can use transcribe `find_resource_test.py` into C++.
- For the purpose of CI, can you use shared library target here, and use a binary version of Drake?
- Can you add a TODO to provide the option for granular static targets? (for source-and-static Drake targets)?

Does this make sense? I can explain it to you next meeting if you'd like.
</blockquote></details>

Thinking about this more:
- CMake from installed tarball
  - Is cheap for CI, works well(ish) for Python and C++
- Bazel from installed tarball
  - Is cheap, works well for Python, but not really for C++ (pending Drake Slack convos)
  - We can't do Python-only b/c we have bindings on C++ (which is a *good* thing)
- Bazel from source
  - Is *not* cheap, but works well for Python and C++ (and is closer to Anzu workflow)

Some options for testing Bazel:

(a) If using binary archive, perhaps we stay with only C++, and defer Python (as well as shared library) considerations, at least for this repo, until Drake has affordances for it. Note that we will need an alternative approach for Anzu to consume this.
(b) Use better CI resources (e.g. Jenkins per d-e-e) to build everything from source for now, as that enables C++ and Python.

I think (b) will probably be best for short-term, but we should wait until we hear back on Bazel-C++-via-binary on Drake Slack.

@sloretz / @iantheengineer What do y'all think?


<!-- Sent from Reviewable.io -->

2022-05-03 23:19 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @eigen, @EricCousineau-TRI, @IanTheEngineer, and @sloretz)

___
*[`drake_ros_core/BUILD.bazel` line 17 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgBHR3OG3V8xVUnDn:-N1BD8VN0RQOS1u47nu_:b-iw1i2d) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/BUILD.bazel#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit We may want these more granular at some point.

Can you add TODO to that effect?
Let's hold off for now, b/c in Anzu we will want both static- and shared-library variants if we want to use Python bindings - which I *very* much do!!!
</blockquote></details>

Added todo
___
*[`drake_ros_core/BUILD.bazel` line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgQzE87RjggHFyhrE:-N1BCl8jEKxJLEWnLD2r:b-k8rdfu) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/BUILD.bazel#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Does this use `rmw_isolation`?
</blockquote></details>

I'm not sure that it does. I didn't find an example, so I'll ask Michel about how to make these tests use the `rmw_isolation` feature.
___
*[`drake_ros_core/WORKSPACE` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgiqYBWhfuxf53Wi7:-N1BBk6CApZzqQcBd3uP:bjqgx2e) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/WORKSPACE#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Thinking about this more:
- CMake from installed tarball
  - Is cheap for CI, works well(ish) for Python and C++
- Bazel from installed tarball
  - Is cheap, works well for Python, but not really for C++ (pending Drake Slack convos)
  - We can't do Python-only b/c we have bindings on C++ (which is a *good* thing)
- Bazel from source
  - Is *not* cheap, but works well for Python and C++ (and is closer to Anzu workflow)

Some options for testing Bazel:

(a) If using binary archive, perhaps we stay with only C++, and defer Python (as well as shared library) considerations, at least for this repo, until Drake has affordances for it. Note that we will need an alternative approach for Anzu to consume this.
(b) Use better CI resources (e.g. Jenkins per d-e-e) to build everything from source for now, as that enables C++ and Python.

I think (b) will probably be best for short-term, but we should wait until we hear back on Bazel-C++-via-binary on Drake Slack.

@sloretz / @iantheengineer What do y'all think?
</blockquote></details>

(b) seems more bazelish. Do I understand correctly that (b) would allow Anzu to use these files?

It seems like Jeremy recommended to have this `WORKSPACE` define the Eigen repository. e85a88cd1051c2e89ce439b2b38df24ed179279d uses `:drake_shared_library` and adds the dependency on @eigen, though this still seems like something `drake_repository()` and `:drake_shared_library` should be handling for us.


<!-- Sent from Reviewable.io -->

2022-05-04 00:31 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @eigen, @EricCousineau-TRI, @IanTheEngineer, and @sloretz)

___
*[`drake_ros_core/BUILD.bazel` line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgQzE87RjggHFyhrE:-N1BQgHd6om0cWtc1UeL:b-bjbk3v) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/BUILD.bazel#L48)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

I'm not sure that it does. I didn't find an example, so I'll ask Michel about how to make these tests use the `rmw_isolation` feature.
</blockquote></details>

It's a wee bit odd (sorry I didn't notice this during review), but the tools and examples are embedded in `@ros2`. See #72
___
*[`drake_ros_core/WORKSPACE` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgiqYBWhfuxf53Wi7:-N1BT7QX4lrE5hThPUNx:b-pjsp8i) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/WORKSPACE#L41)):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

(b) seems more bazelish. Do I understand correctly that (b) would allow Anzu to use these files?

It seems like Jeremy recommended to have this `WORKSPACE` define the Eigen repository. e85a88cd1051c2e89ce439b2b38df24ed179279d uses `:drake_shared_library` and adds the dependency on @eigen, though this still seems like something `drake_repository()` and `:drake_shared_library` should be handling for us.
</blockquote></details>

Sorry for the extra terms, but from Slack convos in Drake `#bazel`, seems like we should def. build from source, and leverage the third-party stuff already there (`drake_bazel_external`).

Per his suggestion, we should first see if we can leverage GitHub action cache, and use pinned Drake releases to minimize churn as much as possible and fit w/in free budget.
Failing that, we'll need to get $$ to scale up / help optimize Drake build (but $$ may be fastest to boot).


<!-- Sent from Reviewable.io -->

2022-05-04 00:37 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @eigen, @EricCousineau-TRI, @IanTheEngineer, and @sloretz)

___
*[`drake_ros_core/WORKSPACE` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgiqYBWhfuxf53Wi7:-N1BUzMv--voEJPJo9OQ:b7zs0m5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/WORKSPACE#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry for the extra terms, but from Slack convos in Drake `#bazel`, seems like we should def. build from source, and leverage the third-party stuff already there (`drake_bazel_external`).

Per his suggestion, we should first see if we can leverage GitHub action cache, and use pinned Drake releases to minimize churn as much as possible and fit w/in free budget.
Failing that, we'll need to get $$ to scale up / help optimize Drake build (but $$ may be fastest to boot).
</blockquote></details>

--> #78


<!-- Sent from Reviewable.io -->

2022-05-06 00:49 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @eigen, @EricCousineau-TRI, @IanTheEngineer, and @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgXaG3rfCvmRRcIyW:-N1Lpew52nkVnMdgaZi0:boyy4fy) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

When do you think it'd be appropriate to add this to CI?

And is there a tracking issue that describes this? If not, can you add that and add in when you think CI, Python targets, etc. would be provided?
</blockquote></details>

Looks like you opened a tracking issue already: https://github.com/RobotLocomotion/drake-ros/issues/78

---
___
*[`drake_ros_core/WORKSPACE` line 41 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgiqYBWhfuxf53Wi7:-N1Lpopa4FwF8KNZzudh:bng8jie) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/WORKSPACE#L41)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

--> #78
</blockquote></details>

5636a71c0587f81d5e75dc964b2d6a77d3acddb0 builds from source, but does not yet add it to CI


<!-- Sent from Reviewable.io -->

2022-05-08 22:27 UTC, EricCousineau-TRI reviewed
This is 

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-:-N1_loWTBGITa_DvJNRO:b-dh65uv)* status: all files reviewed, 3 unresolved discussions (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgXaG3rfCvmRRcIyW:-N1_luxD6edRHSQ3vxE0:b1hv4h6) (no related file):*
<details><summary><i>Previously, sloretz (Shane Loretz) wrote…</i></summary><blockquote>

Looks like you opened a tracking issue already: https://github.com/RobotLocomotion/drake-ros/issues/78
</blockquote></details>

Yup! I'll keep this as unresolved pending addition of CI

Would you like this PR to be more bit-sized? (e.g. just C++, but with CI - and perhaps usage of caching per Jeremy's suggestions on Drake Slack?)

---


<!-- Sent from Reviewable.io -->

2022-05-08 22:28 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: all files reviewed, 3 unresolved discussions (waiting on @sloretz)

___
*[`drake_ros_core/WORKSPACE` line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N1_mAaF8Zgo_bddpGUH:-N1_mAaF8Zgo_bddpGUI:b-jedvh7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/5636a71c0587f81d5e75dc964b2d6a77d3acddb0/drake_ros_core/WORKSPACE#L39)):*
> ```Starlark
> 
> # Depend on Drake
> DRAKE_COMMIT = "master"
> ```

BTW Per Jeremy's suggestion, if we want to fully leverage caching (esp. for Python bindings), then we should perhaps pin to releases (and update them at an appropriate cadence)


<!-- Sent from Reviewable.io -->

2022-05-08 22:29 UTC, EricCousineau-TRI reviewed
> This is

Ah, sorry - ignore this.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-:-N1_mYGy7BHUNtPyrKU2:b-1bl0zs)* status: all files reviewed, 3 unresolved discussions (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2022-05-13 17:21 UTC, sloretz reviewed
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: all files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgXaG3rfCvmRRcIyW:-N1yQGt5ElXe8biCRpWM:b-phig3l) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yup! I'll keep this as unresolved pending addition of CI

Would you like this PR to be more bit-sized? (e.g. just C++, but with CI - and perhaps usage of caching per Jeremy's suggestions on Drake Slack?)
</blockquote></details>

I chose to add new steps to the existing Bazel build CI job. The advantage is the machine is already setup to use bazel and build, so it saves time.

The build step took only 6 minutes in the latest run: https://github.com/RobotLocomotion/drake-ros/runs/6426839695?check_suite_focus=true so I assume the part of it that builds Drake must be using the bazel cache.

___
___
*[`drake_ros_core/BUILD.bazel` line 31 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgOl8AS6JgRZdtxPh:-N1yPzKK8P54jeSfr8Jv:b-df191r) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/BUILD.bazel#L31)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Does this use `rmw_isolation`?
</blockquote></details>

It uses rmw_isolation now.
___
*[`drake_ros_core/BUILD.bazel` line 48 at r1](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N0hgQzE87RjggHFyhrE:-N1yQ-YwAXrJ5NJBNaLG:b-df191r) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6ea72e6ce9c6283a7d530452965169b1b36020b7/drake_ros_core/BUILD.bazel#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

It's a wee bit odd (sorry I didn't notice this during review), but the tools and examples are embedded in `@ros2`. See #72
</blockquote></details>

It uses rmw_isolation now.
___
*[`drake_ros_core/WORKSPACE` line 39 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N1_mAaF8Zgo_bddpGUH:-N1yQ6Vd9CjuemK2Mu-h:bkzodj6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/efba24ed92bccb80adc8b4c0429d99c4cd69fc09/drake_ros_core/WORKSPACE#L39)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW Per Jeremy's suggestion, if we want to fully leverage caching (esp. for Python bindings), then we should perhaps pin to releases (and update them at an appropriate cadence)
</blockquote></details>

Pinned to Drake 1.2.0


<!-- Sent from Reviewable.io -->

2022-05-13 17:28 UTC, jwnimmer-tri commented
*[`drake_ros_core/WORKSPACE` line 45 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N1yS3FpBvKLNxYq1BpE:-N1yS3FpBvKLNxYq1BpF:bx3jopp) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1adae8ee1fe809f13b80dcfa513837d89721b832/drake_ros_core/WORKSPACE#L45)):*
> ```Starlark
>     name = "drake",
>     urls = [x.format(DRAKE_COMMIT) for x in [
>         "https://github.com/RobotLocomotion/drake/archive/{}.tar.gz",
> ```

nit When fetching source code from a github tag (as opposed to git sha), the following URL pattern is guaranteed (by github) to maintain a consistent sha256sum forevermore:

`https://github.com/{repository}/archive/refs/tags/{release_tag}.tar.gz`

When you use `/archive/` URLs as here currently, the sha256sum will occasionally randomly change out from under you and your build (and your own releases) will nosedive if you don't have any dependency mirroring already set up.

If you don't expect to every switch away from using tags, it's probably worth using the tags-specific URL here.

Details:
https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1029861300


<!-- Sent from Reviewable.io -->

2022-05-13 19:42 UTC, sloretz reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @sloretz)

___
*[`drake_ros_core/WORKSPACE` line 45 at r4](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N1yS3FpBvKLNxYq1BpE:-N1ywL-431DxjdPGs0Cn:b-1i9vzw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/1adae8ee1fe809f13b80dcfa513837d89721b832/drake_ros_core/WORKSPACE#L45)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit When fetching source code from a github tag (as opposed to git sha), the following URL pattern is guaranteed (by github) to maintain a consistent sha256sum forevermore:

`https://github.com/{repository}/archive/refs/tags/{release_tag}.tar.gz`

When you use `/archive/` URLs as here currently, the sha256sum will occasionally randomly change out from under you and your build (and your own releases) will nosedive if you don't have any dependency mirroring already set up.

If you don't expect to every switch away from using tags, it's probably worth using the tags-specific URL here.

Details:
https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1029861300
</blockquote></details>

Using the tag URL in 2871ba7


<!-- Sent from Reviewable.io -->

2022-05-13 19:43 UTC, sloretz reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: all files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2022-05-23 14:24 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>, thanks!

I made some small changes on my side and pushed them here. I plan to merge after ROS2 meeting.

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-:-N2lIRlu4tAJekzL2u4i:bd6pebx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N2lHsJrEaw2LqUvoNHJ:-N2lIM9N2pjTVLqXjauh:b-xvi063) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Needs `.gitignore`
</blockquote></details>

Done. Hoisted.

___
___
*[`drake_ros_core/WORKSPACE` line 44 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N2lGj_F-0mH_yNoxybI:-N2lINAODokXPuaBGCiM:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2871ba7ff6d910ef358fa94eda81efe31b6675ad/drake_ros_core/WORKSPACE#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Since we only have 1 URL, let's simplify this.
</blockquote></details>

Done.
___
*[`drake_ros_core/test/test_drake_ros.cc` line 44 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N2lG94M1_v9GIo_CcK2:-N2lINlrDGfb4JRinnC8:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2871ba7ff6d910ef358fa94eda81efe31b6675ad/drake_ros_core/test/test_drake_ros.cc#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: We should make this explicitly required, not optional, as is done in `isolated_talker`, etc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-23 14:36 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)

___
*[`drake_ros_core/test/test_drake_ros.cc` line 44 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N2lG94M1_v9GIo_CcK2:-N2lLCAE4RiPgHOARQP3:bv8bej5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2871ba7ff6d910ef358fa94eda81efe31b6675ad/drake_ros_core/test/test_drake_ros.cc#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ah, derp. It's because we don't support `rmw_isolation` in CMake :facepalm: 


<!-- Sent from Reviewable.io -->

2022-05-23 14:36 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: all files reviewed, 1 unresolved discussion (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2022-05-23 14:39 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: all files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`drake_ros_core/test/test_drake_ros.cc` line 44 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N2lG94M1_v9GIo_CcK2:-N2lLwIl4uKu1rvsF2ht:bodxkrt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2871ba7ff6d910ef358fa94eda81efe31b6675ad/drake_ros_core/test/test_drake_ros.cc#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, derp. It's because we don't support `rmw_isolation` in CMake :facepalm: 
</blockquote></details>

Working: Flipping define bit, and focusing it in on CMake, as that is the facet *lacking* features.


<!-- Sent from Reviewable.io -->

2022-05-23 15:02 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[`drake_ros_core/test/test_drake_ros.cc` line 44 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/75#-N2lG94M1_v9GIo_CcK2:-N2lREiw-OyvftIZCSN_:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/2871ba7ff6d910ef358fa94eda81efe31b6675ad/drake_ros_core/test/test_drake_ros.cc#L44)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Flipping define bit, and focusing it in on CMake, as that is the facet *lacking* features.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-23 18:02 UTC, EricCousineau-TRI approved these changes
> Reviewed 1 of 5 files at r4, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sloretz)



<!-- Sent from Reviewable.io -->

2022-05-23 18:03 UTC, merged