Drake Model Interop tool scripts
RobotLocomotion/drake-ros pull request #83
Opened 2022-05-13 03:25 UTC by marcoag

This PR contains the first version of the Drake Model Interop tool. They are currently functional for `sdf` format and work for `ur` models on the `urdf` side. 

CI has also been updated to check on setup and transformation of modules. Models testing might still need some modifications to work on CI.

2022-05-13 14:55 UTC, EricCousineau-TRI requested changes
First pass done on `test_models.py`. I've put some nits / blocking comments about conventions and style. Can you push fixes for that file, and once I OK them, can you apply similar changes to remaining Python scripts?

> Reviewed 1 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-:-N1xue2cCwhDKI9AUnZE:b-q330uo)* status: 3 of 13 files reviewed, 19 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[`drake_model_interop/render_ur_urdfs.py` line 114 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xu7_AC27Vba7KW_33:-N1xu7_AC27Vba7KW_34:bqe7g8q) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/render_ur_urdfs.py#L114)):*
> ```Python
> def rotate_root_node(scene, rotation):
>     transformed = rotation.dot(scene.rootnode.transformation)
>     scene.mRootNode.contents.mTransformation.a1 = transformed.item(0)
> ```

nit This is a lot of boiler plate. Please instead use local alias to shorten, e.g.:
```
transformation = scene.mRootNode.contents.mTransformation
transformation.a1 = ....
```

Additionally, consider separating to another routine.

And are you sure this is the simplest way to go from np.array to transform?
___
*[`drake_model_interop/render_ur_urdfs.py` line 114 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xuJa43qG10J6BbpdB:-N1xuJa43qG10J6BbpdC:b9fw4o7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/render_ur_urdfs.py#L114)):*
> ```Python
> def rotate_root_node(scene, rotation):
>     transformed = rotation.dot(scene.rootnode.transformation)
>     scene.mRootNode.contents.mTransformation.a1 = transformed.item(0)
> ```

`.item()` for accessing elements in a matrix seems very odd.

Can you instead access the 2d indices? e.g. `[0, 0]`?
___
*[`drake_model_interop/requirements.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xrnt94KvnxNrj9hLW:-N1xrnt94KvnxNrj9hLX:bh1xa65) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/requirements.txt#L1)):*
> ```help
> dataclasses
> ```

This isn't necessary 
___
*[`drake_model_interop/requirements.txt` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xrr3PEmeTRQ6zSV9d:-N1xrr3PEmeTRQ6zSV9e:bqfqf5u) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/requirements.txt#L17)):*
> ```help
> # https://github.com/ipython/ipython/issues/12740
> jedi == 0.17.2
> drake == 1.1.0
> ```

nit Newer Drake is on `1.2.0`.
___
*[`drake_model_interop/test_models.py` line 48 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsGN-85oOh_lG7mAR:-N1xsGN-85oOh_lG7mAS:b-net2oi) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L48)):*
> ```Python
>     # Shorthand for defining a pose.
>     rpy_deg = np.asarray(rpy_deg)
>     return RigidTransform(RollPitchYaw(rpy_deg * np.pi / 180), xyz)
> ```

nit Can you change `x * np.pi / 180` to `np.deg2rad(x)`?
___
*[`drake_model_interop/test_models.py` line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsNe9Bixh78yUnOWp:-N1xsNe9Bixh78yUnOWq:b-mgscpa) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L68)):*
> ```Python
> def infer_mask(image, bg_pixel=[255, 255, 255]):
>     image_array = np.array(image)
>     mask_bg1 = np.all(image_array == np.full(image_array.shape, bg_pixel), axis=2)
> ```

nit `mask_bg1` is an odd name. Can you make that more general?
___
*[`drake_model_interop/test_models.py` line 105 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsVTC2OUIqxZChzSn:-N1xsVTC2OUIqxZChzSo:b-hdiqwb) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L105)):*
> ```Python
> 
> def generate_sdf(model, poses_file, random, file_name):
>     sdf_text = f"""<sdf version="1.6">
> ```

nit For formatting large strings, consider using `textwrap.dedent`, rather than morphing the content itself.
___
*[`drake_model_interop/test_models.py` line 105 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsiCj0lt4wnK5E2Wo:-N1xsiCj0lt4wnK5E2Wp:b-owizen) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L105)):*
> ```Python
> 
> def generate_sdf(model, poses_file, random, file_name):
>     sdf_text = f"""<sdf version="1.6">
> ```

Why SDFormat 1.6?
___
*[`drake_model_interop/test_models.py` line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xscvkD1E7Lz74-KoQ:-N1xscvkD1E7Lz74-KoR:b-m00dqz) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L106)):*
> ```Python
> def generate_sdf(model, poses_file, random, file_name):
>     sdf_text = f"""<sdf version="1.6">
>   <world name="default">
> ```

nit Indentations here are inconsistent.
___
*[`drake_model_interop/test_models.py` line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsvVn8X9GBIKMTJ7O:-N1xsvVn8X9GBIKMTJ7P:bazuqhh) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L135)):*
> ```Python
>       </include>
>       <model name="photo_shoot">
>       <pose>2.2 0 0 0 0 -3.14</pose>
> ```

Please don't use truncated radians.

Either use math+text formatting, or use degrees in SDFormat.
___
*[`drake_model_interop/test_models.py` line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xspH21w6qP8HOtJ0T:-N1xspH21w6qP8HOtJ0U:blz9b06) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L140)):*
> ```Python
>           <sensor name="camera" type="camera">
>           <camera>
>               <horizontal_fov>1.047</horizontal_fov>
> ```

(From prior PR) These magic numbers should come from `depth_camera` components.
___
*[`drake_model_interop/test_models.py` line 151 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xt0VfEIyog2DuIdO1:-N1xt0VfEIyog2DuIdO2:b-8021il) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L151)):*
> ```Python
>           </camera>
>           <always_on>1</always_on>
>           <update_rate>30</update_rate>
> ```

Unclear why an update rate is necessary.

Can you remove this / rely on default values?
___
*[`drake_model_interop/test_models.py` line 282 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xt9hi02vwOebJCwnL:-N1xt9hjEDNNcRIKWt44:bszra12) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L282)):*
> ```Python
>         )
> 
>     if pose_directory == "random_pose":
> ```

Implicit logic based on output seems sketchy.

Can you make this more explicit? e.g. add arg, `randomize_pose`, or pass a function in, etc.
___
*[`drake_model_interop/test_models.py` line 300 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xtKG866DPU-_xhdAX:-N1xtKG866DPU-_xhdAY:b4mvqsl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L300)):*
> ```Python
>         plant.SetPositions(sim_plant_context, model, joint_positions)
> 
>         simulator.AdvanceTo(1)
> ```

Why is this necessary? Why do we care about dynamics?
__ [...]

2022-05-22 07:13 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: 1 of 13 files reviewed, 17 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_model_interop/render_ur_urdfs.py` line 114 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xu7_AC27Vba7KW_33:-N2Rf3dH2HJZS6qQs2Il:b-4gtg63) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/render_ur_urdfs.py#L114)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This is a lot of boiler plate. Please instead use local alias to shorten, e.g.:
```
transformation = scene.mRootNode.contents.mTransformation
transformation.a1 = ....
```

Additionally, consider separating to another routine.

And are you sure this is the simplest way to go from np.array to transform?
</blockquote></details>

Moved to a specific function that makes the moves np_array to transform. Couldn't find a better way as pyassimp only seems to only expose the a1 a2 ... d4 variables of the matrix.
___
*[`drake_model_interop/render_ur_urdfs.py` line 114 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xuJa43qG10J6BbpdB:-N2RfQIPAwc_SL3BJBTe:bco4wnt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/render_ur_urdfs.py#L114)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

`.item()` for accessing elements in a matrix seems very odd.

Can you instead access the 2d indices? e.g. `[0, 0]`?
</blockquote></details>

Yes, done this way.
___
*[`drake_model_interop/requirements.txt` line 1 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xrnt94KvnxNrj9hLW:-N2RgBW35CF3VWVBgACl:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/requirements.txt#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This isn't necessary 
</blockquote></details>

Removed.
___
*[`drake_model_interop/requirements.txt` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xrr3PEmeTRQ6zSV9d:-N2Rg9qB5gwhZSLq5Nsm:b-cypxrc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/requirements.txt#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Newer Drake is on `1.2.0`.
</blockquote></details>

updated.
___
*[`drake_model_interop/test_models.py` line 48 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsGN-85oOh_lG7mAR:-N2USdmlC42wpOAzMP1v:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L48)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you change `x * np.pi / 180` to `np.deg2rad(x)`?
</blockquote></details>

Done.
___
*[`drake_model_interop/test_models.py` line 68 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsNe9Bixh78yUnOWp:-N2e9GxK24xEPIK14SSr:b7aet05) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L68)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `mask_bg1` is an odd name. Can you make that more general?
</blockquote></details>

made it `background_mask`, hope that's general enough.
___
*[`drake_model_interop/test_models.py` line 105 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsVTC2OUIqxZChzSn:-N2Uw8o60J6uJ4i5Ku4b:bm3yqt3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L105)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For formatting large strings, consider using `textwrap.dedent`, rather than morphing the content itself.
</blockquote></details>

OK, done.
___
*[`drake_model_interop/test_models.py` line 105 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsiCj0lt4wnK5E2Wo:-N2e7sOo75cNOunH4sw0:b-j4jyvl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L105)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Why SDFormat 1.6?
</blockquote></details>

Just left from copy-paste, moved to 1.9.
___
*[`drake_model_interop/test_models.py` line 106 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xscvkD1E7Lz74-KoQ:-N2dwNPO9FGq1jEmcg_b:bt2vr1b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L106)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Indentations here are inconsistent.
</blockquote></details>

Fixed.
___
*[`drake_model_interop/test_models.py` line 135 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsvVn8X9GBIKMTJ7O:-N2dzyvNEduaelf3PgMJ:b-b3jc39) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L135)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Please don't use truncated radians.

Either use math+text formatting, or use degrees in SDFormat.
</blockquote></details>

Using use math+text formatting.
___
*[`drake_model_interop/test_models.py` line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xspH21w6qP8HOtJ0T:-N2eRx4h0Xcw3zkJTxe8:bbwugcz) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L140)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(From prior PR) These magic numbers should come from `depth_camera` components.
</blockquote></details>

`depth_camera` gets created and used after this, I created a data structure containing the camera config and passed it around.
___
*[`drake_model_interop/test_models.py` line 151 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xt0VfEIyog2DuIdO1:-N2doEvB0eCJ6e826r6I:bss4a2b) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L151)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unclear why an update rate is necessary.

Can you remove this / rely on default values?
</blockquote></details>

Removed.
___
*[`drake_model_interop/test_models.py` line 282 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xt9hi02vwOebJCwnL:-N2eSaVeE9OCNOEs-R3k:bty4jug) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L282)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Implicit logic based on output seems sketchy.

Can you make this more explicit? e.g. add arg, `randomize_pose`, or pass a function in, etc.
</blockquote></details>

Made explicit with a `randomize_pose` and made changes accordingly.
___
*[`drake_model_interop/test_models.py` line 300 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xtKG866DPU-_xhdAX:-N2eUecMCKcILuCUCAXM:b-mgdcqs) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L300 [...]

2022-05-22 13:09 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: 1 of 13 files reviewed, 17 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_model_interop/test_models.py` line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xspH21w6qP8HOtJ0T:-N2fsTUj5ZOb6b8Mzr8i:b-y3mhmw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L140)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

`depth_camera` gets created and used after this, I created a data structure containing the camera config and passed it around.
</blockquote></details>

I just updated this, now I create a `camera_info` instance and pass it around so everyone gets the camera config data from the same source.


<!-- Sent from Reviewable.io -->

2022-05-23 13:25 UTC, marcoag reviewed
The CI currently doesn't run the test script. This is because when trying to run the `test_models.py` script on the GitHub CI the following error comes through:

```
2022-05-12 06:29:46.442 (   5.001s) [        9D068740]vtkTransformPolyDataFil:80     ERR| vtkTransformPolyDataFilter (0x3e141a0): No input data
2022-05-12 06:29:46.751 (   5.309s) [        9D068740]vtkXOpenGLRenderWindow.:465    ERR| vtkXOpenGLRenderWindow (0x3d204a0): bad X server connection. DISPLAY=
compare_model_via_drake_and_ingition_images.sh: line 13: 12733 Aborted                 (core dumped) ./test_models.py "$1" "$2" "$temp_directory"
```
Ref: https://github.com/marcoag/drake-ros/runs/6400833462?check_suite_focus=true

Since it seems that `vtk` complains about not having a connection to the X server, I assumed is a problem of drake not running in headless mode, is there a way to do this? any solution we can apply to this or shall we not run the test script for now?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-:-N2l525nCfdD5EBIXkRz:bai9mt3)* status: 1 of 13 files reviewed, 17 unresolved discussions (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2022-05-24 01:39 UTC, EricCousineau-TRI requested changes
> Reviewed 1 of 13 files at r1, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: 3 of 13 files reviewed, 16 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[`drake_model_interop/test_models.py` line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xspH21w6qP8HOtJ0T:-N2nePzz0gkkD_rTX8vG:b-ue4tep) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L140)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

I just updated this, now I create a `camera_info` instance and pass it around so everyone gets the camera config data from the same source.
</blockquote></details>

Thanks! And ah, I meant `RenderCameraCore`
___
*[`drake_model_interop/test_models.py` line 300 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xtKG866DPU-_xhdAX:-N2nf--Y5ScywTwrk8Za:bpm4sao) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L300)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

I believe this is needed for the random positions of the joints?
</blockquote></details>

Sorry, still not clear why. If you're not sure, can you try removing it, and show what goes wrong?
___
*[`drake_model_interop/test_models.py` line 79 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2nfa5p6vxMV41q6A2O:-N2nfa5p6vxMV41q6A2P:bufqdup) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L79)):*
> ```Python
>     intersection = np.logical_and(mask_a, mask_b).sum()
>     union = np.logical_or(mask_a, mask_b).sum()
>     print(intersection / union)
> ```

This should be tested against automatically.

Can you add something like `--iou_threshold`, and have the testing fail if the computed IoU is over that amount?
(and perhaps add a reasonable default value, like 0.95?)
___
*[`drake_model_interop/test_models.py` line 84 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2nh6LE6kNTdpwLdFDm:-N2nh6LE6kNTdpwLdFDn:b-4hqodq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L84)):*
> ```Python
> def generate_images_and_iou(simulator, sensor, temp_directory, poses_dir, num_image):
> 
>     context = simulator.get_context()
> ```

No need for `simulator`. Instead, just pass in `sensor_context` from top-level (see below).
___
*[`drake_model_interop/test_models.py` line 154 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2neVAKEuzdYHiddLt_:-N2neVAKEuzdYHiddLta:b-93g02g) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L154)):*
> ```Python
>                         </image>
>                         <clip>
>                             <near>0.01</near>
> ```

Per above - can you ensure that this function consumes a `RenderCameraCore` object (or a `ClippingRange` object), and use it here?
___
*[`drake_model_interop/test_models.py` line 264 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2nhEOP5OcbBFyyuzRL:-N2nhEOP5OcbBFyyuzRM:b-a68p15) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L264)):*
> ```Python
>     sensor_back = create_camera(builder, world_id, X_WB, depth_camera, scene_graph)
> 
>     DrakeVisualizer.AddToBuilder(builder, scene_graph)
> ```

nit Using DrakeVisualizer should be optional.

Consider making command-line argument?
___
*[`drake_model_interop/test_models.py` line 267 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2nfvYnBLkiJ192apuK:-N2nfvYo-WCvRmFfBhEV:b-xq8yu2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L267)):*
> ```Python
> 
>     # Remove gravity to avoid extra movements of the model when running the simulation
>     plant.gravity_field().set_gravity_vector(np.array([0, 0, 0], dtype=np.float64))
> ```

Per below, not sure why simulation is necessary?
___
*[`drake_model_interop/test_models.py` line 269 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2ng-WP6ityuEEUVxwj:-N2ng-WP6ityuEEUVxwk:bgfyms1) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L269)):*
> ```Python
>     plant.gravity_field().set_gravity_vector(np.array([0, 0, 0], dtype=np.float64))
> 
>     # Switch off collisions to avoid problems with random positions
> ```

Per below, not sure why collisions are a problem?
___
*[`drake_model_interop/test_models.py` line 280 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2ngyqj-0eP7IbnO74f:-N2ngyqj-0eP7IbnO74g:b-ho1i0s) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L280)):*
> ```Python
>     diagram = builder.Build()
> 
>     simulator = Simulator(diagram)
> ```

Unclear why `Simulator` is necessary.

Instead, you can do `diagram_context = diagram.CreateDefaultContext()`, and replace all references to context from simulator with this object.

Please consider briefly reviewing Drake tutorials. Specifically, see
https://nbviewer.org/github/RobotLocomotion/drake/blob/v1.3.0/tutorials/rendering_multibody_plant.ipynb#Create-context-and-get-subsystem-contexts.
___
*[`drake_model_interop/test_models.py` line 309 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2ng3XA2KhOCJhZaiHp:-N2ng3XA2KhOCJhZaiHq:bnsjd85) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L309)):*
> ```Python
>         simulator.AdvanceTo(1)
> 
>     generate_images_and_iou(
> ```

Should these live in a for-loop? e.g.
```
sensors = [sensor_perspetive, sensor_top, ...]
for i, sensor in enumerate(sensors):
    ...
```
___
*[`drake_model_interop/test_models.py` line 326 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2ngKAL2g4-2kQCh3e8:-N2ngKAL2g4-2kQCh3e9:b5qa54a) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L326)):*
> ```Python
> 
> 
> def setup_temporal_model_description_file(
> ```

nit "temporal" => "temporary"
___
*[`drake_model_interop/test_models.py` line 351 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2ngUZ9-QLMbFKHwV9O:-N2ngUZ9-QLMbFKHwV9P:bfqq7ms) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L351)):*
> ```Python
> 
>     data = etree.tostring(root, pretty_print=True).decode("utf-8")
>     text_file = open(model_file_path, "w")
> ```

Should use `with` statement.
___
*[`drake_model_interop/test_models.py` line 383 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2ng_EFD3tfRdi4qBKV:-N2ng_EFD3tfRdi4qBKW:b-aq70u) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L383)):*
> ```Python
>     )
> 
>     os.system(
> ```

nit `os.system` has a funny smell, and doesn't allow much more introspection.

Can you instead use `subprocess`?
In this case, I think `ign` should not fail, so `subprocess.run("ign gazebo ...", shell=True, check=True)`?
___
*[`drake_model_interop/test_models.py` line 396 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2nfDsu38h-bRh3Nxdz:-N2nfDsu38h-bRh3Nxe-:b30wm7o) ([raw file](https://github.com/robotlocomo [...]

2022-05-24 01:47 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: 3 of 13 files reviewed, 17 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2njTAwD4mU1weRaFHM:-N2njTAxBdrKOyFsWfez:b-hz09zv) (no related file):*
Per VC, we should test out using `xvfb`.

Primary source: https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml

From quick Googling for use w/ GitHub actions:
https://remarkablemark.org/blog/2020/12/12/headless-test-in-github-actions-workflow/

Usage inside Drake docker (more complex than what we need here)
https://github.com/RobotLocomotion/drake/blob/v1.3.0/setup/deepnote/install_xvfb

___
___
*[`drake_model_interop/requirements.txt` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xrr3PEmeTRQ6zSV9d:-N2njhat2oiPYV2SDyBC:b-j2r07j) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/requirements.txt#L17)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

updated.
</blockquote></details>

OK Thanks! FWIW, later version, 1.3.0, has been released.
___
*[`drake_model_interop/test_models.py` line 105 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsVTC2OUIqxZChzSn:-N2niANB7dtzucP0vFq0:bibvlzl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L105)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

OK, done.
</blockquote></details>

Sorry, I meant that you should use it inline with your literal, e.g.,
```
def my_func():
    my_text = dedent("""\
        <root>
            <sub/>
        </root>
    """)
```

It makes more sense to indicate intent there, rather than when writing contents.


<!-- Sent from Reviewable.io -->

2022-06-01 23:04 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: 3 of 13 files reviewed, 16 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[`drake_model_interop/requirements.txt` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xrr3PEmeTRQ6zSV9d:-N3TVAcO3epP_gJVYTq5:b-4byawt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/requirements.txt#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Thanks! FWIW, later version, 1.3.0, has been released.
</blockquote></details>

Updated again. 

This update seems to throw errors on malformed SDFs, the default [panda model](https://app.gazebosim.org/OpenRobotics/fuel/models/Panda%20with%20Ignition%20position%20controller%20model)  seems to fail with (seems to be an error in the model):

`error: At XML path /sdf/model[@name="Panda"]/link[@name="panda_leftfinger"]/visual[@name="panda_leftfinger_visual"]/material/pbr/metal/metallic_map: XML Element[metallic_map], child of element[metal], not defined in SDF. Copying[metallic_map] as children of [metal].`
___
*[`drake_model_interop/test_models.py` line 105 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xsVTC2OUIqxZChzSn:-N3U61Xs6nX-bTDkmim5:btpke0i) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L105)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry, I meant that you should use it inline with your literal, e.g.,
```
def my_func():
    my_text = dedent("""\
        <root>
            <sub/>
        </root>
    """)
```

It makes more sense to indicate intent there, rather than when writing contents.
</blockquote></details>

Sure, added there.
___
*[`drake_model_interop/test_models.py` line 140 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xspH21w6qP8HOtJ0T:-N3UNZEs0FvVV-owg_cF:b-vkwsxa) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L140)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Thanks! And ah, I meant `RenderCameraCore`
</blockquote></details>

True, much better.
___
*[`drake_model_interop/test_models.py` line 300 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xtKG866DPU-_xhdAX:-N3V1V_FDxu-tjNP01EE:b-szag2u) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/test_models.py#L300)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sorry, still not clear why. If you're not sure, can you try removing it, and show what goes wrong?
</blockquote></details>

Removed the simulator instance as per above and therefore this line.
___
*[`drake_model_interop/test_models.py` line 79 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2nfa5p6vxMV41q6A2O:-N3Tkdja2xQ_SZMBX_Z8:b7v5xe7) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L79)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This should be tested against automatically.

Can you add something like `--iou_threshold`, and have the testing fail if the computed IoU is over that amount?
(and perhaps add a reasonable default value, like 0.95?)
</blockquote></details>

Sometimes, some of the examples would, due to joint randomness, throw values slightly below 0.95, will leave the default to 0.9 so at least it passes the tests we currently have.

Added the `--iou_threshold` option.
___
*[`drake_model_interop/test_models.py` line 84 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2nh6LE6kNTdpwLdFDm:-N3U57hXBQ9kbK2mnVut:b4thyyn) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L84)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

No need for `simulator`. Instead, just pass in `sensor_context` from top-level (see below).
</blockquote></details>

Passing `sensor_context` from top level now.
___
*[`drake_model_interop/test_models.py` line 154 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2neVAKEuzdYHiddLt_:-N3UNTGE1ORskOuJ8PH3:b-jepp3h) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L154)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per above - can you ensure that this function consumes a `RenderCameraCore` object (or a `ClippingRange` object), and use it here?
</blockquote></details>

Using a `RenderCameraCore` for it, yes.
___
*[`drake_model_interop/test_models.py` line 264 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2nhEOP5OcbBFyyuzRL:-N3VYzdzAVXAnUeeCtT7:bkjg5kl) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L264)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Using DrakeVisualizer should be optional.

Consider making command-line argument?
</blockquote></details>

Made it a command-line argument.



_Code quote:_
```Python
DrakeVisualizer
```
___
*[`drake_model_interop/test_models.py` line 267 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2nfvYnBLkiJ192apuK:-N3V8bvM5g2ocL7Hevp-:b-g9zfe) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L267)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per below, not sure why simulation is necessary?
</blockquote></details>

No it's not, removed following the explanation bellow.
___
*[`drake_model_interop/test_models.py` line 269 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2ng-WP6ityuEEUVxwj:-N3V8iCKBD5V1Faq_L0J:b-6obol) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L269)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per below, not sure why collisions are a problem?
</blockquote></details>

I remember some problem with them long time ago. They don't seem to be a problem now, removing. 
___
*[`drake_model_interop/test_models.py` line 280 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2ngyqj-0eP7IbnO74f:-N3V1N9KDseLsCUm8Ujh:bu3lmh0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L280)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unclear why `Simulator` is necessary.

Instead, you can do `diagram_context = diagram.CreateDefaultContext()`, and replace all references to context from simulator with this object.

Please consider briefly reviewing Drake tutorials. Specifically, see
https://nbviewer.org/github/RobotLocomotion/drake/blob/v1.3.0/tutorials/rendering_multibody_plant.ipynb#Create-context-and-get-subsystem-contexts.
</blockquote></details>


Oh true, removed the need of `Simulator`.
___
*[`drake_model_interop/test_models.py` line 309 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2ng3XA2KhOCJhZaiHp:-N3UV_o15ohgwQwbji_d:b1z9rpd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9a [...]

2022-06-02 12:23 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: 3 of 13 files reviewed, 16 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2njTAwD4mU1weRaFHM:-N3ZMb--AAo2iI0hgeOF:b40y6nq) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per VC, we should test out using `xvfb`.

Primary source: https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml

From quick Googling for use w/ GitHub actions:
https://remarkablemark.org/blog/2020/12/12/headless-test-in-github-actions-workflow/

Usage inside Drake docker (more complex than what we need here)
https://github.com/RobotLocomotion/drake/blob/v1.3.0/setup/deepnote/install_xvfb

</blockquote></details>

Great, that seems to be working: https://github.com/RobotLocomotion/drake-ros/runs/6708073365?check_suite_focus=true

Thanks!

___


<!-- Sent from Reviewable.io -->

2022-06-06 23:05 UTC, EricCousineau-TRI requested changes
> Reviewed 3 of 13 files at r1, 1 of 4 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: all files reviewed, 7 unresolved discussions (waiting on @marcoag)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2njTAwD4mU1weRaFHM:-N3v4rqs9B0a8wURPP3L:bcgzp9s) (no related file):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Great, that seems to be working: https://github.com/RobotLocomotion/drake-ros/runs/6708073365?check_suite_focus=true

Thanks!
</blockquote></details>

OK Sweet!

___
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vEp2x4l_vUKEnxNhP:-N3vEp2y2BUTGc4kBoMV:b-svh6ez) (no related file):*
From file names, I'm having trouble disentangling what's UR specific and what's not.

Can you make it clearer from top-down, ideally CI script, of what reformatting happens for which model?

___
___
*[`.github/workflows/drake_model_interop.yml` line 33 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vE9XjAXaSwjU1gkd4:-N3vE9XjAXaSwjU1gkd5:b-12qks8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/.github/workflows/drake_model_interop.yml#L33)):*
> ```YAML
>           unzip NAO\ with\ Ignition\ position\ controller.zip -d NAO
>           source setup.sh
>           xvfb-run --auto-servernum bash setup_transform_test.sh NAO model.sdf
> ```

Unclear why we have download steps here and in separate scripts.

Can you defer this to something like `./setup/ci_tests.sh`, and run the script under xvfb?
Then the script can test NAO, anymal, UR arms, etc.
___
*[`drake_model_interop/format_model_and_generate_manifest.sh` line 1 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vF0gf9g6q_3Q2JzZx:-N3vF0gg-FLBF5uGgla2:b3umlz8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/format_model_and_generate_manifest.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

The odd logic of doing both venv, via script or what not, should ideally just be in one place, and as generic as possible.

I think that is handled by `setup.sh`.

For provisioning separate repos, can you either use `wget` and/or `vcstool` to use specific checkouts of given repos, and make that a fully separate script and step?
We can focus on CI, where the steps will be:

- cache
- sudo-required prereqs
- xvfb
- setup.sh to install venv
- download or clone sample models
- generate models via xacro if needed
- run rendering tests

Can you use Python for scripting, and only use shell when we need to inject shell variables (or the script is only a few lines long)?
Sorry about the prototype nature of this - perhaps we should have ditched my earlier prototype code and started from scratch when formulating this PR.
___
*[`drake_model_interop/multibody_extras.py` line 1 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vDAxr5GcaxJNYBHHN:-N3vDAxr5GcaxJNYBHHO:b-1sjjcc) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/multibody_extras.py#L1)):*
> ```Python
> from pydrake.multibody.tree import (
> ```

Are all of these methods used?

If not, can you pare this down to only what is used?
___
*[`drake_model_interop/requirements.txt` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xrr3PEmeTRQ6zSV9d:-N3vAjnN3dSmYCBj_3vC:b-3473al) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/requirements.txt#L17)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Updated again. 

This update seems to throw errors on malformed SDFs, the default [panda model](https://app.gazebosim.org/OpenRobotics/fuel/models/Panda%20with%20Ignition%20position%20controller%20model)  seems to fail with (seems to be an error in the model):

`error: At XML path /sdf/model[@name="Panda"]/link[@name="panda_leftfinger"]/visual[@name="panda_leftfinger_visual"]/material/pbr/metal/metallic_map: XML Element[metallic_map], child of element[metal], not defined in SDF. Copying[metallic_map] as children of [metal].`

</blockquote></details>

Thanks! And yes, more error / warnings have been added in Drake.

It seems like that is a bug in upstream model:
http://sdformat.org/spec?ver=1.9&elem=material

Is there an issue tracker of sorts of these models?
___
*[`drake_model_interop/test_models.py` line 79 at r3](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N2nfa5p6vxMV41q6A2O:-N3vA4jV-0exKfBjIW4Z:b-ieyay5) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/145cba31e4357f9adcfecf08326eae32268d3baf/drake_model_interop/test_models.py#L79)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Sometimes, some of the examples would, due to joint randomness, throw values slightly below 0.95, will leave the default to 0.9 so at least it passes the tests we currently have.

Added the `--iou_threshold` option.
</blockquote></details>

OK Sweet, thanks!
___
*[`drake_model_interop/test_models.py` line 14 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vDoIL7DpIOR2COY51:-N3vDoIM51vb6zyEi9CA:bqyoj3f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/test_models.py#L14)):*
> ```Python
> import math
> 
> from pydrake.all import (
> ```

For stability, we should avoid using `pydrake.all`

Can you instead use more direct imports?
___
*[`drake_model_interop/test_models.py` line 151 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3v9jQOCGcsr7ywLi97:-N3v9jQOCGcsr7ywLi98:b-c4gz9n) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/test_models.py#L151)):*
> ```Python
>                     <camera>
>                         <horizontal_fov>
>                                 {2*math.atan(render_camera_core.intrinsics().width()/
> ```

nit Instead of recomputing, can you instead use `.fov_x()` and `.fov_y()`?
___
*[`drake_model_interop/test_models.py` line 325 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vCVXM0b--qNyOva7W:-N3vCVXM0b--qNyOva7X:b-42a46p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/test_models.py#L325)):*
> ```Python
> 
>     if mesh_type == "collision":
>         collision_tags = root.findall(".//collision")
> ```

nit Rather than doing XML substitution, you should be able to use `AssignRole` and `RemoveRole`.
Then you won't need to massage the transformed tags.

As an example, see:
https://github.com/RobotLocomotion/drake/blob/1a6f2d93c/manipulation/util/show_model.py#L280-L292


<!-- Sent from Reviewable.io -->

2022-06-07 22:27 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: 7 of 14 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vEp2x4l_vUKEnxNhP:-N3xxLiGCimao6tTcpLZ:b-ldoak1) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

From file names, I'm having trouble disentangling what's UR specific and what's not.

Can you make it clearer from top-down, ideally CI script, of what reformatting happens for which model?
</blockquote></details>

True, legacy filenames are confusing. I just renamed and reduced the number of files. Hopefully it's clearer now. 

No files are UR specific, the tests are `sdf` specific though.

The `./setup/ci_tests.sh` file contains now the download, transform and test steps for UR and several `sdf` models.

___
___
*[`.github/workflows/drake_model_interop.yml` line 33 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vE9XjAXaSwjU1gkd4:-N3z4ozT9dcVmK4913mN:b-7slg8a) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/.github/workflows/drake_model_interop.yml#L33)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Unclear why we have download steps here and in separate scripts.

Can you defer this to something like `./setup/ci_tests.sh`, and run the script under xvfb?
Then the script can test NAO, anymal, UR arms, etc.
</blockquote></details>

All download steps happen now in `./setup/ci_tests.sh`. This script downloads, converts and tests all models we've considered during development so far.
___
*[`drake_model_interop/multibody_extras.py` line 1 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vDAxr5GcaxJNYBHHN:-N3zeM1I9CWg8JxtId1Z:b-gj32k8) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/multibody_extras.py#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Are all of these methods used?

If not, can you pare this down to only what is used?
</blockquote></details>

It comes down to just the `get_bodies` method, removed the rest.
___
*[`drake_model_interop/requirements.txt` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xrr3PEmeTRQ6zSV9d:-N3zeXUoC8kLvWi280L5:b-mvhmqk) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/requirements.txt#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Thanks! And yes, more error / warnings have been added in Drake.

It seems like that is a bug in upstream model:
http://sdformat.org/spec?ver=1.9&elem=material

Is there an issue tracker of sorts of these models?
</blockquote></details>

There was some effort in the past towards having some sort of issue tracker/PR kind of process but got dropped at some point.

Currently the only way is to contact the owner of the model, since this is an Open Robotics one I will find out who to ping and ask for correction. 
___
*[`drake_model_interop/format_model_and_generate_manifest.sh` line 1 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vF0gf9g6q_3Q2JzZx:-N3z57Zp12VmmGcHYgHP:b-ys43nt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/format_model_and_generate_manifest.sh#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

The odd logic of doing both venv, via script or what not, should ideally just be in one place, and as generic as possible.

I think that is handled by `setup.sh`.

For provisioning separate repos, can you either use `wget` and/or `vcstool` to use specific checkouts of given repos, and make that a fully separate script and step?
We can focus on CI, where the steps will be:

- cache
- sudo-required prereqs
- xvfb
- setup.sh to install venv
- download or clone sample models
- generate models via xacro if needed
- run rendering tests

Can you use Python for scripting, and only use shell when we need to inject shell variables (or the script is only a few lines long)?
Sorry about the prototype nature of this - perhaps we should have ditched my earlier prototype code and started from scratch when formulating this PR.
</blockquote></details>

I reduced the bash scripting to one main file. Generation and test scripts are only python now. 

Regarding the steps you suggested here is how they are currently distributed:

`.github/workflows/drake_model_interop.yml`:
- cache
- sudo-required prereqs
- xvfb
- setup.sh to install venv
- call `./setup/ci_tests.sh`
  - download or clone sample a model
  - call `setup_render_test.sh`
    - setup.sh to install venv
    - generate models via xacro if needed
    - run rendering tests if it's an `sdf` model

The steps in `setup_render_test.sh` can be called separately but this script exists to minimize the steps in the user workflow, that would look like this:

- sudo-required prereqs
- download or clone sample a certain model
- call `setup_render_test.sh`
___
*[`drake_model_interop/test_models.py` line 14 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vDoIL7DpIOR2COY51:-N3zlQGkCxb13Hx1QLse:bmw968w) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/test_models.py#L14)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For stability, we should avoid using `pydrake.all`

Can you instead use more direct imports?
</blockquote></details>

Done. I also removed unused ones.
___
*[`drake_model_interop/test_models.py` line 151 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3v9jQOCGcsr7ywLi97:-N3yyOlO7d7rMHZyeHaH:b-6rdz1y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/test_models.py#L151)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Instead of recomputing, can you instead use `.fov_x()` and `.fov_y()`?
</blockquote></details>

I looked for it but I couldn't find it exposed through the python bindings: https://drake.mit.edu/pydrake/pydrake.systems.sensors.html?highlight=camerainfo#pydrake.systems.sensors.CameraInfo
___
*[`drake_model_interop/test_models.py` line 325 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vCVXM0b--qNyOva7W:-N3zsxpL3aySrfbrogDy:b-2w4i6f) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/test_models.py#L325)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Rather than doing XML substitution, you should be able to use `AssignRole` and `RemoveRole`.
Then you won't need to massage the transformed tags.

As an example, see:
https://github.com/RobotLocomotion/drake/blob/1a6f2d93c/manipulation/util/show_model.py#L280-L292
</blockquote></details>

We still need to the substitution for gazebo sim side, shall we still use use `AssignRole` and `RemoveRole`and do the substitution afterwards?


<!-- Sent from Reviewable.io -->

2022-06-16 17:49 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[`drake_model_interop/setup/ci_tests.sh` line 7 at r6](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N4fqXhyDtgeLi1paA0e:-N4haFC38ZMYnFAFd4du:b-tuip6v) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/04bc7b96d35e9cfae3f23135207a01dfdebec223/drake_model_interop/setup/ci_tests.sh#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you add thresholds for all of these tests?
</blockquote></details>

Thresholds added. 

However tests don't work currently for the UR models, they might need some work to make them work with it. First question that comes to my mind is, how do we handle the fact that there are several models in this repo? do we test them all or ask the user to select one specifically? 
___
*[`drake_model_interop/format_model_and_generate_manifest.py` line 262 at r6](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N4fpr2L0lLg1ayTLbDp:-N4hUWwkARzluTgGZDKd:b-3jv9zt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/04bc7b96d35e9cfae3f23135207a01dfdebec223/drake_model_interop/format_model_and_generate_manifest.py#L262)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Purpose of print unclear. Consider removing?
</blockquote></details>

Probably leftover from debugging, removed.
___
*[`drake_model_interop/test_models.py` line 325 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3vCVXM0b--qNyOva7W:-N4hXScQBpaG02eZk9xR:bir0avq) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/test_models.py#L325)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, yeah! Can you add a comment to that effect?
</blockquote></details>

Comment added.


<!-- Sent from Reviewable.io -->

2022-06-21 15:42 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_model_interop/test_models.py` line 151 at r5](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N3v9jQOCGcsr7ywLi97:-N55vJY15WSg1Vt3Vytb:b-2k533w) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/6b9aa1d61d27e280fe13f8778dfe93afdde323d0/drake_model_interop/test_models.py#L151)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, gotcha. Can you add those bindings?
</blockquote></details>

Added in https://github.com/RobotLocomotion/drake/pull/17428. Shall we add a TODO here until those changes are released?


<!-- Sent from Reviewable.io -->

2022-06-30 00:26 UTC, marcoag reviewed
Just realized that I forgot to comment here, The `VTK` issue was fixed through the use of `xvfb-run`.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-:-N5lzksz1BBrWkRiiMRa:bf1u1s0)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2022-09-22 21:12 UTC, EricCousineau-TRI requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: all files reviewed, 13 unresolved discussions (waiting on @marcoag)

___
*[`drake_model_interop/requirements.txt` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xrr3PEmeTRQ6zSV9d:-NCb-3V1A8DQ0dMGCCxi:b-r6h116) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/requirements.txt#L17)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

There was some effort in the past towards having some sort of issue tracker/PR kind of process but got dropped at some point.

Currently the only way is to contact the owner of the model, since this is an Open Robotics one I will find out who to ping and ask for correction. 
</blockquote></details>

Any chance we can bump to latest Drake version (v1.8.0) and see if this still happens?
If so, can we add a transformation to remove the offending element?

Maybe we can use something like a non-strict `ign sdf` to read in the file then dump out what it could fully understand?
___
*[`drake_model_interop/requirements.txt` line 1 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb092f4inIrT3ryqNs:-NCb092f4inIrT3ryqNt:b-x8hzm0) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/requirements.txt#L1)):*
> ```help
> # Following adapted from a portion of TRI Anzu code.
> ```

nit Can you remove all of these deps, and perhaps just replcae them 
___
*[`drake_model_interop/setup/ci_tests.sh` line 7 at r6](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N4fqXhyDtgeLi1paA0e:-NCb-Q3HBjrC-cTbhnTQ:brkvho3) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/04bc7b96d35e9cfae3f23135207a01dfdebec223/drake_model_interop/setup/ci_tests.sh#L7)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Thresholds added. 

However tests don't work currently for the UR models, they might need some work to make them work with it. First question that comes to my mind is, how do we handle the fact that there are several models in this repo? do we test them all or ask the user to select one specifically? 
</blockquote></details>

Ideally, we should test all of them in CI; but we can add flags to let the user downselect.
(However, if we're parsing flags, I think this should then be in Python.)
___
*[`drake_model_interop/setup/ci_tests.sh` line 1 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb-ZaI9xKzKzUZFmjm:-NCb-ZaI9xKzKzUZFmjn:bm8oa2p) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/setup/ci_tests.sh#L1)):*
> ```Shell
> mkdir -p models
> ```

nit This should be named something more akin to `./tmp`?

Also, should this first `rm -rf ./tmp`, or perhaps fail fast if the directory already exists? (i.e., `mkdir` only, not `mkdir -p`)?
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 195 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb0i9d4QScN-wcVhKm:-NCb0i9d4QScN-wcVhKn:bfz73v2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L195)):*
> ```Python
>                 line_split = line.split(" ")
>                 scaling = float(line_split[1])
>             else:
> ```

What does this else cover? Rotation?
Can you make it more explicit here?
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 197 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb0e348f4CzOuoxNul:-NCb0e348f4CzOuoxNum:bi2u7v2) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L197)):*
> ```Python
>             else:
>                 line_split = line.split(" ")
>                 if line_split[1] == "nan":
> ```

Hm... Why convert `nan` to zero?
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 200 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb0l9t65n_3NI6KZAu:-NCb0l9t65n_3NI6KZAv:bh318rg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L200)):*
> ```Python
>                     random_poses[line_split[0][:-1]] = 0
>                 else:
>                     random_poses[line_split[0][:-1]] = float(line_split[1])
> ```

What does this case mean?
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 213 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb0oxK6jw24wKPgcRe:-NCb0oxK6jw24wKPgcRf:b-2vdqzv) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L213)):*
> ```Python
>     frame_W = plant.world_frame()
>     frame_B = model_bodies[0].body_frame()
>     if len(plant.GetBodiesWeldedTo(plant.world_body())) < 2:
> ```

Not sure if I know what this logic is doing, nor if it is still needed.

Can you remove and have this still work?
(our stuff is purely kinematic / perception based, so I don't think dynamics should matter?)
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 231 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb16NsACqCukk5-XuS:-NCb16NsACqCukk5-XuT:bjg9ybt) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L231)):*
> ```Python
>     world_id = plant.GetBodyFrameIdOrThrow(plant.world_body().index())
> 
>     # Creating perspective cam
> ```

Are these values that 
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 438 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb1HES7ivK1Ltm3jMr:-NCb1HETAumoX_2Wx4cS:b-xzeq01) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L438)):*
> ```Python
>         mesh_type,
>         "default_pose",
>         False,
> ```

What does this boolean value mean? Can you use kwargs to make it clearer?
___
*[`drake_model_interop/format_model_and_generate_manifest.py` line 226 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb1Uh_CG1wRWeR0jRy:-NCb1Uh_CG1wRWeR0jRz:b31y5f6) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/format_model_and_generate_manifest.py#L226)):*
> ```Python
> 
> 
> FLAVORS = [
> ```

This seems very specific to UR arms; is there a way to generalize this?
___
*[`drake_model_interop/format_model_and_generate_manifest.py` line 300 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb1_Z06n1UYKr2bPhw:-NCb1_Z06n1UYKr2bPhx:b-1kl63y) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/format_model_and_generate_manifest.py#L300)):*
> ```Python
>     cd(source_tree)
> 
>     print(pyassimp.__file__)
> ```

nit Unnecessary print statements?
___
*[`drake_model_interop/format_model_and_generate_manifest.py` line 351 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb1f2iCbsmYsMCVoVi:-NCb1f2iCbsmYsMCVoVj:b-bjqx5q) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/format_model_and_generate_manifest.py#L351)):*
> ```Python
>                 urdf_file = f"u [...]

2022-10-07 08:42 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-ros/83)* status: 5 of 15 files reviewed, 13 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[`drake_model_interop/requirements.txt` line 17 at r2](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N1xrr3PEmeTRQ6zSV9d:-NDbsuiA24pC_3qfYhyg:brbqzv9) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/ea4160518cb974793d057c8e300154c2f8d3250f/drake_model_interop/requirements.txt#L17)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Any chance we can bump to latest Drake version (v1.8.0) and see if this still happens?
If so, can we add a transformation to remove the offending element?

Maybe we can use something like a non-strict `ign sdf` to read in the file then dump out what it could fully understand?
</blockquote></details>

yup, bumped to `v1.8.0` also needed to use the updated bindings in `drake_model_interop/compare_model_via_drake_and_ingition_images.py:141`.

The conflicting model has been fixed upstream and updated in the ci script to the corect version.
___
*[`drake_model_interop/requirements.txt` line 1 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb092f4inIrT3ryqNs:-NDbtPk50i-jMUxIFvTu:b-ksa2fd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/requirements.txt#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you remove all of these deps, and perhaps just replcae them 
</blockquote></details>

Just leaving `drake and lxml` seems to suffice.
___
*[`drake_model_interop/setup/ci_tests.sh` line 7 at r6](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-N4fqXhyDtgeLi1paA0e:-NDhcfc20c-GOC6h3lgY:b8jn72k) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/04bc7b96d35e9cfae3f23135207a01dfdebec223/drake_model_interop/setup/ci_tests.sh#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ideally, we should test all of them in CI; but we can add flags to let the user downselect.
(However, if we're parsing flags, I think this should then be in Python.)
</blockquote></details>

Rewrote this into python with flags, now you can select any of the predefined models, test them all (without any parameters) or even pass a url as a parameter and the model will be downloaded and tested.
___
*[`drake_model_interop/setup/ci_tests.sh` line 1 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb-ZaI9xKzKzUZFmjm:-NDbuNpk-wJrBlYUgGCi:b9nubbj) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/setup/ci_tests.sh#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This should be named something more akin to `./tmp`?

Also, should this first `rm -rf ./tmp`, or perhaps fail fast if the directory already exists? (i.e., `mkdir` only, not `mkdir -p`)?
</blockquote></details>

Yup, modified to `rmf -rf ./tmp` and `mkdir ./tmp`.
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 195 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb0i9d4QScN-wcVhKm:-NDapCOW-pBdHD7zTA_5:bvyndu4) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L195)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

What does this else cover? Rotation?
Can you make it more explicit here?
</blockquote></details>

Yes, it will be in the for of: `JointName: rotationvalue`. I will add a comment to point it out.
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 197 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb0e348f4CzOuoxNul:-NDb8JyB8NDqykRkRU06:bhs4ovw) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L197)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... Why convert `nan` to zero?
</blockquote></details>

tbh I don't know why this is here at this point. Maybe a leftover from a corner case? Running it through all the test models we have seems to not need this line. Will remove for now. 
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 200 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb0l9t65n_3NI6KZAu:-NDbA24GDD6mWZ_6Br4y:b-nd7yrg) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L200)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

What does this case mean?
</blockquote></details>

This collects the random joint rotations, added a comment and changed the variable name to `random_joint_rotations` for clarity.
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 213 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb0oxK6jw24wKPgcRe:-NDbg_fBEIfJt0M86ZFR:b-zahaat) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L213)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Not sure if I know what this logic is doing, nor if it is still needed.

Can you remove and have this still work?
(our stuff is purely kinematic / perception based, so I don't think dynamics should matter?)
</blockquote></details>

Tbh I don't fully understand what this weld does in the background but It seems that for some models like the the [MPL right arm](https://app.gazebosim.org/OpenRobotics/fuel/models/MPL%20right%20arm) or the [Cerberus Anymal](https://app.gazebosim.org/OpenRobotics/fuel/models/CERBERUS_ANYMAL_C_SENSOR_CONFIG_2) removing it would make `plant.num_actuated_dofs() !=  plant.num_positions()` and [this line](https://github.com/RobotLocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L268) will fail. Also, without this weld, `joint.position_start()` returns different numbers, making the [joint_positions](https://github.com/RobotLocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L284) vector contain a bunch of 0 positions plus the random ones, I'm not sure if this is correct but if this happens I still get this weird error (dunno how it is related) down the line:

```
  File "./compare_model_via_drake_and_ingition_images.py", line 81, in generate_images_and_iou
    color = sensor.color_image_output_port().Eval(sensor_context).data
RuntimeError: QuaternionToRotationMatrix(): All the elements in a quaternion are zero.
```
___
*[`drake_model_interop/compare_model_via_drake_and_ingition_images.py` line 231 at r7](https://reviewable.io/reviews/robotlocomotion/drake-ros/83#-NCb16NsACqCukk5-XuS:-NDboBIL98m3Js_EgIqv:b-o8wjhd) ([raw file](https://github.com/robotlocomotion/drake-ros/blob/a61a5985670b5853941b32f6bcc669ecc869caa9/drake_model_interop/compare_model_via_drake_and_ingition_images.py#L231)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Are these values that 
</blockquote></details>

These are fixed values also used by the `model_photo_shoot` plugin [here](https://github.com/gazebosim/gz-sim/blob/3592c201094b94b36a3edbd1f03f89d959f4e578/src/systems/model_photo_shoot/ModelPhotoShoot.cc [...]

2023-02-17 01:07 UTC, EricCousineau-TRI commented
Closing this as "paused" for now. Will reopen once we have the chance to focus on it once we've landed the model directives conversion scripts.

Tracked via https://github.com/RobotLocomotion/drake/issues/15024 (on SDFormat board as well)

2023-02-17 01:07 UTC, closed without merging